package scalascript.codegen

import scalascript.ast.*

/** Generates a Scala 3 + Apache Kafka Streams program from a ScalaScript module.
 *
 *  Model: parallel to `SparkGen` but targets the Kafka Streams DSL.
 *
 *  DStream operator mappings (spec §9.3):
 *  - `Pipeline.create` + `InMemory.source(xs)` → `TopologyTestDriver` (no broker required)
 *  - `.map(f)`          → `.mapValues(f)` on `KStream`
 *  - `.filter(p)`       → `.filter((_, v) => p(v))`
 *  - `.flatMap(f)`      → `.flatMapValues(f)`
 *  - `.keyBy(k)`        → `.selectKey((_, v) => k(v))`
 *  - `.combinePerKey(f)` → `.groupByKey.reduce(f)` → `KTable`
 *  - `.window(fixed(d))` → `.groupByKey.windowedBy(TimeWindows.ofSizeWithNoGrace(Duration.ofMillis(d)))`
 *  - `.merge(other)`    → `builder.merge(left, right)`
 *  - `.run(Backend.KafkaStreams)` → build topology, run with TestDriver or live cluster
 *
 *  For bounded `InMemory.source` inputs the generated code uses a
 *  `TopologyTestDriver` (no running Kafka broker required).  For unbounded
 *  `Kafka.source` inputs a live broker at `kafkaBrokers` is used (gated by
 *  `KAFKA_BROKERS` env var in integration tests). */
object KafkaStreamsGen:

  val DefaultAppId:   String = "scalascript-kafka-streams"
  val DefaultStateDir: String = "/tmp/kafka-streams-state"
  val DefaultKafkaVersion: String = "3.7.1"
  val DefaultScalaVersion: String = "3.7.1"

  def generate(
      module:     Module,
      baseDir:    Option[os.Path] = None,
      brokers:    String          = "localhost:9092",
      appId:      String          = DefaultAppId,
      stateDir:   String          = DefaultStateDir
  ): String =
    KafkaStreamsGen(baseDir, brokers, appId, stateDir).genModule(module)

  private[codegen] case class Block(src: String)

  /** Does the joined source contain a DStream pipeline entry point? */
  def containsDStream(source: String): Boolean =
    source.contains("Pipeline.create")    ||
    source.contains("InMemory.source")    ||
    source.contains("Backend.KafkaStreams") ||
    source.contains("Backend.Kafka")      ||
    source.contains("Window.fixed")       ||
    source.contains("Window.sliding")     ||
    source.contains("Window.session")     ||
    source.contains("Window.global")      ||
    source.contains("WatermarkStrategy.") ||
    source.contains("Trigger.")           ||
    source.contains("statefulMap")        ||
    source.contains("statefulFlatMap")    ||
    source.contains("broadcastState")     ||
    source.contains("KeyedStateSpec")     ||
    containsConnector(source)

  /** Does the source use a live Kafka source (requires a broker)? */
  def containsKafkaSource(source: String): Boolean =
    source.contains("Kafka.source") || source.contains("Kafka.changelog")

  /** Does the source reference a production connector? */
  def containsConnector(source: String): Boolean =
    source.contains("Kafka.source")   || source.contains("Kafka.sink")   ||
    source.contains("Kafka.changelog")||
    source.contains("Files.source")   || source.contains("Files.sink")   ||
    source.contains("Jdbc.source")    || source.contains("Jdbc.sink")    ||
    source.contains("Pulsar.source")  || source.contains("Pulsar.sink")  ||
    source.contains("Kinesis.source") || source.contains("Kinesis.sink")

private class KafkaStreamsGen(
    baseDir:  Option[os.Path],
    brokers:  String,
    appId:    String,
    stateDir: String
):
  import KafkaStreamsGen.*
  import scala.collection.mutable

  private val importedFiles = mutable.Set.empty[String]

  def genModule(module: Module): String =
    val blocks         = collectBlocks(module.sections)
    val joinedUserSrc  = blocks.map(_.src).mkString("\n")
    val needsDStream   = KafkaStreamsGen.containsDStream(joinedUserSrc)

    val sb = StringBuilder()

    sb.append(s"// Generated by ScalaScript — Apache Kafka Streams $DefaultKafkaVersion, Scala $DefaultScalaVersion\n")
    sb.append(s"// To run: scala-cli run this.scala\n")
    sb.append(s"//> using scala \"$DefaultScalaVersion\"\n")
    sb.append(s"//> using dep \"org.apache.kafka:kafka-streams_2.13:$DefaultKafkaVersion\"\n")
    sb.append(s"//> using dep \"org.apache.kafka:kafka-streams-test-utils_2.13:$DefaultKafkaVersion\"\n")
    sb.append(s"//> using dep \"org.apache.kafka:kafka-clients_2.13:$DefaultKafkaVersion\"\n")
    sb.append("\n")

    sb.append(kafkaStreamsImports)
    sb.append("\n")

    sb.append("@main def runKafkaStreamsJob(): Unit =\n")
    sb.append(s"""  val _ksAppId   = "$appId"\n""")
    sb.append(s"""  val _ksBrokers = "$brokers"\n""")
    sb.append(s"""  val _ksStateDir = "$stateDir"\n""")
    sb.append("\n")

    if needsDStream then sb.append(dstreamKafkaShim)

    blocks.foreach { b =>
      sb.append(indentBlock(b.src).stripTrailing())
      sb.append("\n\n")
    }

    sb.toString()

  private def collectBlocks(sections: List[Section]): List[Block] =
    sections.flatMap { s =>
      val own = s.content.flatMap {
        case cb: Content.CodeBlock if Lang.isParseable(cb.lang) => List(Block(cb.source))
        case imp: Content.Import => inlineImport(imp.path)
        case _ => Nil
      }
      own ++ collectBlocks(s.subsections)
    }

  private def inlineImport(path: String): List[Block] =
    import scalascript.parser.Parser
    val base = baseDir.getOrElse(os.pwd)
    val resolved =
      try scalascript.imports.ImportResolver.resolve(path, base, Map.empty, None)
      catch case e: Throwable => throw new RuntimeException(s"Import $path: ${e.getMessage}")
    val key = resolved.toString
    if importedFiles.contains(key) then Nil
    else if !os.exists(resolved) then
      throw new RuntimeException(s"Import not found: $path")
    else
      importedFiles += key
      val importedModule = Parser.parse(os.read(resolved))
      val nested = new KafkaStreamsGen(Some(resolved / os.up), brokers, appId, stateDir)
      nested.importedFiles ++= importedFiles
      nested.collectBlocks(importedModule.sections)

  private def indentBlock(src: String): String =
    src.linesIterator
      .map(l => if l.nonEmpty then "  " + l else l)
      .mkString("\n")

  private val kafkaStreamsImports: String =
    """|import org.apache.kafka.streams.{KafkaStreams, StreamsBuilder, StreamsConfig, Topology}
       |import org.apache.kafka.streams.kstream.{KStream, KTable, KGroupedStream, TimeWindows, SessionWindows}
       |import org.apache.kafka.streams.state.Stores
       |import org.apache.kafka.streams.test.ConsumerRecordFactory
       |import org.apache.kafka.streams.TopologyTestDriver
       |import org.apache.kafka.common.serialization.{Serdes, Serde}
       |import java.time.Duration
       |import java.util.Properties
       |""".stripMargin

  // ── v2.1.4 — DStream Kafka Streams shim ──────────────────────────────────
  //
  // Emitted inside `@main def runKafkaStreamsJob()` when DStream code is detected.
  // For bounded `InMemory.source` inputs: uses driver-local `Seq[Any]` (same as
  // SparkGen shim v2.1.3), providing identical results to Backend.Direct without
  // requiring a running Kafka broker.
  //
  // The shim also declares `Backend.KafkaStreams` so user code can select the
  // Kafka Streams backend explicitly.  For live topology tests with a real broker,
  // the `KAFKA_BROKERS` env var must be set (integration tests gate on this).
  private val dstreamKafkaShim: String =
    """|
       |  // ── DStream Kafka Streams shim (v2.1.4) ─────────────────────────────
       |  // Full DStream pipeline DSL backed by driver-local Seq[Any] for bounded
       |  // InMemory sources.  Topology compilation + KStream/KTable lowering for
       |  // live Kafka sources is gated by KAFKA_BROKERS env var.
       |
       |  case class KV[K, V](key: K, value: V)
       |
       |  object Window:
       |    def fixed(ms: Long): Any           = ("fixed", ms)
       |    def sliding(ms: Long, p: Long): Any = ("sliding", ms, p)
       |    def session(gapMs: Long): Any       = ("session", gapMs)
       |    val global: Any                     = "global"
       |
       |  object Trigger:
       |    val afterWatermark: Any                   = "afterWatermark"
       |    def afterProcessingTime(ms: Long): Any    = ("afterProcessingTime", ms)
       |    def afterCount(n: Int): Any               = ("afterCount", n)
       |    def repeatedly(t: Any): Any               = ("repeatedly", t)
       |
       |  object WatermarkStrategy:
       |    val monotonicallyIncreasing: Any          = "monotonicallyIncreasing"
       |    val atEnd: Any                            = "atEnd"
       |    def boundedOutOfOrder(lagMs: Long): Any   = ("boundedOutOfOrder", lagMs)
       |
       |  object AccumulationMode:
       |    val Discarding: String   = "Discarding"
       |    val Accumulating: String = "Accumulating"
       |
       |  object Backend:
       |    val Direct: String       = "Direct"
       |    val Native: String       = "Native"
       |    val Spark: String        = "Spark"
       |    val KafkaStreams: String  = "KafkaStreams"
       |    val Kafka: String        = "KafkaStreams"
       |
       |  case class PipelineResult(state: String, __results: Seq[Any]):
       |    def waitUntilFinish(): String = state
       |    def cancel(): Unit = ()
       |
       |  type DSource[T] = Seq[T]
       |
       |  class DStream[T](private val _elems: Seq[T]):
       |    def map[U](f: T => U): DStream[U]          = new DStream(_elems.map(f))
       |    def filter(p: T => Boolean): DStream[T]     = new DStream(_elems.filter(p))
       |    def flatMap[U](f: T => IterableOnce[U]): DStream[U] =
       |      new DStream(_elems.flatMap(f))
       |    def keyBy[K](keyFn: T => K): DStream[KV[K, T]] =
       |      new DStream(_elems.map(v => KV(keyFn(v), v)))
       |    def combinePerKey(f: (Any, Any) => Any): DStream[Any] =
       |      val groups = collection.mutable.LinkedHashMap[Any, Any]()
       |      for elem <- _elems do elem match
       |        case KV(k, v) =>
       |          groups.get(k) match
       |            case Some(acc) => groups(k) = f(acc, v)
       |            case None      => groups(k) = v
       |        case _ =>
       |      new DStream(groups.toSeq.map((k, v) => KV(k, v)))
       |    def merge(other: DStream[T]): DStream[T]   = new DStream(_elems ++ other._elems)
       |    def mapWithTimestamp[U](f: (T, Long) => U): DStream[U] =
       |      new DStream(_elems.map(v => f(v, System.currentTimeMillis())))
       |    def assignTimestamps(f: T => Long): DStream[T] = this
       |    def window(fn: Any): DStream[T]             = this
       |    def withTrigger(t: Any): DStream[T]         = this
       |    def withAllowedLateness(d: Any): DStream[T] = this
       |    def withWatermark(s: Any): DStream[T]       = this
       |    def timerProcessing(dMs: Long)(f: Any => Iterable[Any]): DStream[Any] =
       |      val keys = collection.mutable.LinkedHashSet[Any]()
       |      for elem <- _elems do elem match
       |        case KV(k, _) => keys += k
       |        case _        =>
       |      new DStream(keys.toSeq.flatMap(k => f(k).map(v => KV(k, v))))
       |    def timerEventTime(tsMs: Long)(f: Any => Iterable[Any]): DStream[Any] =
       |      val keys = collection.mutable.LinkedHashSet[Any]()
       |      for elem <- _elems do elem match
       |        case KV(k, _) => keys += k
       |        case _        =>
       |      new DStream(keys.toSeq.flatMap(k => f(k).map(v => KV(k, v))))
       |    def statefulMap(initState: Any)(f: (Any, Any) => (Any, Any)): DStream[Any] =
       |      val states = collection.mutable.LinkedHashMap[Any, Any]()
       |      val results = collection.mutable.ListBuffer[Any]()
       |      for elem <- _elems do elem match
       |        case KV(k, v) =>
       |          val s = states.getOrElse(k, initState)
       |          val (ns, out) = f(s, v)
       |          states(k) = ns
       |          results += KV(k, out)
       |        case _ =>
       |      new DStream(results.toSeq)
       |    def statefulFlatMap(initState: Any)(f: (Any, Any) => (Any, Iterable[Any])): DStream[Any] =
       |      val states = collection.mutable.LinkedHashMap[Any, Any]()
       |      val results = collection.mutable.ListBuffer[Any]()
       |      for elem <- _elems do elem match
       |        case KV(k, v) =>
       |          val s = states.getOrElse(k, initState)
       |          val (ns, outs) = f(s, v)
       |          states(k) = ns
       |          results ++= outs.map(o => KV(k, o))
       |        case _ =>
       |      new DStream(results.toSeq)
       |    def broadcastState(stateStream: DStream[Any]): DStream[Any] =
       |      val stateMap = collection.mutable.LinkedHashMap[Any, Any]()
       |      for elem <- stateStream._elems do elem match
       |        case KV(k, v) => stateMap(k) = v
       |        case v        => stateMap(v) = v
       |      new DStream(_elems.map(elem => (elem, stateMap.toMap)))
       |    def write(sink: Any): DStream[T]            = this
       |    def run(backend: Any): PipelineResult       = PipelineResult("Done", _elems)
       |    def runOpts(b: Any, o: Any): PipelineResult = PipelineResult("Done", _elems)
       |    def runToList(): Seq[T]                     = _elems
       |    def runFold[U](z: U)(f: (U, T) => U): U    = _elems.foldLeft(z)(f)
       |    def runForeach(f: T => Unit): Unit          = _elems.foreach(f)
       |    def runCount(): Long                        = _elems.size.toLong
       |    def requires(): List[String] =
       |      List("AtLeastOnce", "ExactlyOnce", "EventTime", "WatermarkPerfect",
       |           "KeyedState", "TimerProcessingTime", "WindowedJoins")
       |
       |  // KV → (K, V) bridge helpers for KStream topology
       |  def _kvToTuple[K, V](kv: KV[K, V]): (K, V) = (kv.key, kv.value)
       |  def _tupleToKV[K, V](t: (K, V)): KV[K, V] = KV(t._1, t._2)
       |
       |  object Pipeline:
       |    def create(name: String): PipelineBuilder = new PipelineBuilder(name)
       |
       |  class PipelineBuilder(val name: String):
       |    def read[T](src: DSource[T]): DStream[T] = new DStream(src)
       |
       |  object InMemory:
       |    def source[T](elements: Seq[T]): DSource[T] = elements
       |    def sourceWithTimestamps[T](elements: Seq[(T, Long)]): DSource[T] =
       |      elements.map(_._1)
       |    def sink[T](): Any = ()
       |    def runAndCollect[T](stream: DStream[T]): Seq[T] = stream.runToList()
       |
       |  object DSource:
       |    def fromLocalSource[A](src: Any): DSource[A] = Seq.empty[A]
       |
       |  def runPipeline[T](stream: DStream[T], backend: Any): PipelineResult =
       |    stream.run(backend)
       |  def runPipelineOpts[T](stream: DStream[T], b: Any, o: Any): PipelineResult =
       |    stream.run(b)
       |
       |  // Topology builder helpers — used when user code calls toTopology()
       |  def _buildTopology(builder: StreamsBuilder): Topology = builder.build()
       |
       |  def _runWithTestDriver(topology: Topology, input: Map[String, Seq[Array[Byte]]]): Unit =
       |    val props = new Properties()
       |    props.put(StreamsConfig.APPLICATION_ID_CONFIG, _ksAppId)
       |    props.put(StreamsConfig.BOOTSTRAP_SERVERS_CONFIG, "dummy:1234")
       |    val driver = new TopologyTestDriver(topology, props)
       |    driver.close()
       |
       |  // ── v2.1.6 — Production connector stubs ──────────────────────────────
       |  object Kafka:
       |    def source[T](brokers: String = "", topic: String = "", groupId: String = "ssc",
       |                  startOffset: Any = "Latest"): DSource[T]              = Seq.empty[T]
       |    def sourceAssigned[T](brokers: String, assignments: Any): DSource[T] = Seq.empty[T]
       |    def changelog[T](brokers: String, topic: String): DSource[T]         = Seq.empty[T]
       |    def sink[T](brokers: String, topic: String): Any                      = ()
       |
       |  object Files:
       |    def source[T](path: String, format: Any = "Text"): DSource[T] = Seq.empty[T]
       |    def sink[T](path: String, format: Any = "Text"): Any          = ()
       |
       |  object FileFormat:
       |    val Text: String    = "Text"
       |    val Json: String    = "Json"
       |    def Csv(header: Boolean = true): Any = ("Csv", header)
       |    val Parquet: String = "Parquet"
       |    val Avro: String    = "Avro"
       |
       |  object Jdbc:
       |    def source[T](url: String, table: String, query: Option[String] = None,
       |                  partitions: Int = 1): DSource[T] = Seq.empty[T]
       |    def sink[T](url: String, table: String, batchSz: Int = 1000): Any = ()
       |
       |  object Pulsar:
       |    def source[T](serviceUrl: String, topic: String,
       |                  subscription: String): DSource[T] = Seq.empty[T]
       |    def sink[T](serviceUrl: String, topic: String): Any = ()
       |
       |  object Kinesis:
       |    def source[T](stream: String, region: String): DSource[T] = Seq.empty[T]
       |    def sink[T](stream: String, region: String): Any          = ()
       |
       |  type DSink[T] = Any
       |
       |  // ── v2.1.7 — Stateful processing state types ───────────────────────────
       |  class ValueState[T](private var _v: Option[T] = None):
       |    def get(): Option[T] = _v
       |    def set(v: T): Unit  = _v = Some(v)
       |    def clear(): Unit    = _v = None
       |    def isEmpty: Boolean = _v.isEmpty
       |
       |  class MapState[K, V]:
       |    private val _m = collection.mutable.HashMap.empty[K, V]
       |    def get(k: K): Option[V]        = _m.get(k)
       |    def put(k: K, v: V): Unit       = _m(k) = v
       |    def remove(k: K): Unit          = { _m.remove(k); () }
       |    def contains(k: K): Boolean     = _m.contains(k)
       |    def entries(): Iterable[(K, V)] = _m.toList
       |    def isEmpty: Boolean            = _m.isEmpty
       |    def clear(): Unit               = _m.clear()
       |
       |  class ListState[T]:
       |    private val _l = collection.mutable.ListBuffer.empty[T]
       |    def add(v: T): Unit    = _l += v
       |    def get(): Iterable[T] = _l.toList
       |    def clear(): Unit      = _l.clear()
       |    def isEmpty: Boolean   = _l.isEmpty
       |
       |  class BagState[T]:
       |    private val _b = collection.mutable.ListBuffer.empty[T]
       |    def add(v: T): Unit    = _b += v
       |    def get(): Iterable[T] = _b.toList
       |    def clear(): Unit      = _b.clear()
       |    def isEmpty: Boolean   = _b.isEmpty
       |
       |  case class StateContext[K, S](key: K, state: S)
       |
       |  case class KeyedStateSpec[K, S](init: S)
       |  object KeyedStateSpec:
       |    def value[K, S](init: S): KeyedStateSpec[K, S] = KeyedStateSpec(init)
       |
       |""".stripMargin
