package scalascript.frontend.vue

import scalascript.frontend.*

/** Two-pass emit (same shape as React / Solid):
 *
 *    1. Collect every `ReactiveSignal` referenced anywhere in
 *       the View tree.  Each becomes a `ref(init)` in `setup()`.
 *
 *    2. Emit a Vue 3 component with `setup` + `render`.  `setup`
 *       creates the refs and returns them on the proxy; `render`
 *       reads `this.x` (auto-unwrapped) and writes via
 *       `this.x = ...`.
 *
 *  Pattern produced:
 *  {{{
 *  import { ref, h, Fragment, createApp } from 'vue';
 *  const App = {
 *    setup() {
 *      const count = ref(0);
 *      return { count };
 *    },
 *    render() {
 *      return h('div', null, [
 *        h('button', { 'onClick': () => { this.count = this.count + 1; } }, '+'),
 *        h('span',   null, this.count)
 *      ]);
 *    }
 *  };
 *  createApp(App).mount('#app');
 *  }}}
 *  Note `this.count` not `count.value` — Vue's component proxy
 *  unwraps refs exposed from `setup`. */
private[vue] object VueEmitter:

  def emit(root: View): String =
    val signals = collectSignals(root)
    val sb = new StringBuilder
    sb ++= "// Generated by ScalaScript v1.18 — frontend-vue Phase A5.\n"
    sb ++= "// Signals lowered to ref(); same .ssc IR as Custom + React + Solid.\n"
    sb ++= "import { ref, h, Fragment, createApp } from 'vue';\n"
    sb ++= "const App = {\n"
    sb ++= "  setup() {\n"
    signals.foreach { (name, initial) =>
      sb ++= s"    const $name = ref($initial);\n"
    }
    val returned =
      if signals.isEmpty then "{}"
      else "{ " + signals.keys.mkString(", ") + " }"
    sb ++= s"    return $returned;\n"
    sb ++= "  },\n"
    sb ++= "  render() {\n"
    sb ++= "    return "
    sb ++= renderView(root)
    sb ++= ";\n"
    sb ++= "  }\n"
    sb ++= "};\n"
    sb ++= "createApp(App).mount('#app');\n"
    sb.toString

  private def collectSignals(view: View): scala.collection.mutable.LinkedHashMap[String, String] =
    val acc = scala.collection.mutable.LinkedHashMap.empty[String, String]
    def register(signal: ReactiveSignal[?]): Unit =
      val name = signal.jsName
      if !name.matches("[A-Za-z_][A-Za-z0-9_]*") then
        throw new IllegalArgumentException(
          s"ReactiveSignal jsName '$name' must match [A-Za-z_][A-Za-z0-9_]*."
        )
      val initJs = jsLiteral(signal())
      acc.get(name) match
        case Some(existing) if existing != initJs =>
          throw new IllegalArgumentException(
            s"ReactiveSignal jsName '$name' registered twice with different " +
            s"initial values ($existing vs $initJs)."
          )
        case _ => acc.update(name, initJs)
    def walk(v: View): Unit = v match
      case View.SignalText(signal) =>
        register(signal)
      case View.Element(_, _, events, children) =>
        events.foreach { (_, handler) =>
          handler match
            case EventHandler.SetSignalLiteral(signal, _) => register(signal)
            case EventHandler.IncrementSignal(signal, _)  => register(signal)
            case _ => ()
        }
        children.foreach(walk)
      case View.Fragment(children) => children.foreach(walk)
      case View.ComponentInstance(component, props) =>
        walk(component.render(props.asInstanceOf[Nothing]))
      case View.Show(_, whenTrue, whenFalse) =>
        walk(whenTrue())
        walk(whenFalse())
      case View.For(items, render) =>
        items().foreach(item => walk(render(item)))
      case _: View.TextNode => ()
    walk(view)
    acc

  private def renderView(view: View): String = view match
    case View.Element(tag, attrs, events, children) =>
      val propsJs = renderProps(attrs, events)
      val childrenJs =
        if children.isEmpty then ""
        else ", [" + children.map(renderView).mkString(", ") + "]"
      s"h(${jsString(tag)}, $propsJs$childrenJs)"

    case View.TextNode(thunk) =>
      jsString(thunk())

    case View.SignalText(signal) =>
      // `this.x` — Vue's component proxy auto-unwraps the ref.
      "this." + signal.jsName

    case View.Fragment(children) =>
      if children.isEmpty then "null"
      else s"h(Fragment, null, [${children.map(renderView).mkString(", ")}])"

    case View.ComponentInstance(component, props) =>
      renderView(component.render(props.asInstanceOf[Nothing]))

    case View.Show(cond, whenTrue, whenFalse) =>
      val branch = if cond() then whenTrue() else whenFalse()
      renderView(branch)

    case View.For(items, render) =>
      val realised = items().toList
      if realised.isEmpty then "null"
      else
        val parts = realised.map(item => renderView(render(item)))
        s"[${parts.mkString(", ")}]"

  private def renderProps(attrs: Map[String, AttrValue], events: Map[String, EventHandler]): String =
    val attrFields = attrs.flatMap { (k, v) =>
      attrValueJs(v).map { value =>
        // Vue accepts `class` natively (same as Solid; unlike React).
        s"${jsString(k)}: $value"
      }
    }
    val eventFields = events.flatMap { (eventName, handler) =>
      eventHandlerJs(eventName, handler)
    }
    val all = attrFields ++ eventFields
    if all.isEmpty then "null" else s"{ ${all.mkString(", ")} }"

  private def attrValueJs(av: AttrValue): Option[String] = av match
    case AttrValue.Str(value)    => Some(jsString(value))
    case AttrValue.Bool(value)   => Some(value.toString)
    case AttrValue.Num(value)    => Some(formatNumber(value))
    case AttrValue.Dynamic(read) => Some(jsLiteral(read()))
    case AttrValue.Absent        => None

  private def eventHandlerJs(eventName: String, handler: EventHandler): Option[String] =
    val onKey = onProp(eventName)
    // Arrow functions defined INSIDE render() lexically capture
    // render()'s `this` — which IS the Vue component proxy.  A
    // function expression instead would lose `this` because Vue's
    // DOM-listener invoker calls it with `this === null`.
    handler match
      case EventHandler.SetSignalLiteral(signal, value) =>
        val v = jsLiteral(value)
        Some(s"${jsString(onKey)}: () => { this.${signal.jsName} = $v; }")
      case EventHandler.IncrementSignal(signal, by) =>
        Some(s"${jsString(onKey)}: () => { this.${signal.jsName} = this.${signal.jsName} + $by; }")
      case EventHandler.Simple(_) | EventHandler.WithEvent(_) =>
        Some(s"/* '$eventName' is a JVM closure — A5 can't translate (richer IR coming later) */")

  /** Vue uses camelCase event props: 'click' → 'onClick'. */
  private def onProp(eventName: String): String =
    "on" + eventName.headOption.fold("")(_.toUpper.toString) + eventName.drop(1)

  private def jsLiteral(value: Any): String = value match
    case s: String  => jsString(s)
    case i: Int     => i.toString
    case l: Long    => l.toString
    case d: Double  => formatNumber(d)
    case f: Float   => formatNumber(f.toDouble)
    case b: Boolean => b.toString
    case null       => "null"
    case other      => throw new IllegalArgumentException(
      s"jsLiteral: unsupported value type ${other.getClass.getName} ($other).  " +
      "Supported: String / Int / Long / Double / Float / Boolean / null."
    )

  private def formatNumber(d: Double): String =
    if d == d.toLong.toDouble then d.toLong.toString else d.toString

  private def jsString(s: String): String =
    val sb = new StringBuilder
    sb += '\''
    s.foreach {
      case '\\' => sb ++= "\\\\"
      case '\'' => sb ++= "\\'"
      case '\n' => sb ++= "\\n"
      case '\r' => sb ++= "\\r"
      case '<'  => sb ++= "\\u003c"
      case c    => sb += c
    }
    sb += '\''
    sb.toString
