package scalascript.frontend.swiftui

import scalascript.frontend.*

/** Generates Swift/SwiftUI source from the framework-agnostic View IR.
 *
 *  Output layout:
 *   - Package.swift                    — Swift Package manifest
 *   - Sources/<App>/<App>App.swift     — @main entry
 *   - Sources/<App>/ContentView.swift  — generated UI
 *   - Sources/<App>/AppModel.swift     — @Observable model (only when list signals exist)
 *
 *  Signal state (`ReactiveSignal[T]`) lowers to `@State private var`.
 *  `ReactiveSignalList[T]` lowers to `@State private var` in ContentView and also
 *  appears as a property on the generated `@Observable AppModel` (Phase 3).
 *  `@Binding` is used where the child view needs to mutate a signal owned
 *  by the parent (TextInput, Toggle, Picker). */
object SwiftUIEmitter:

  /** Context injected when emitting inside a `ForSignal` loop body.
   *  Enables index-based operations such as `RemoveSelfFromList`. */
  private final case class ForCtx(listId: String, indexVar: String)

  // ── Package.swift ─────────────────────────────────────────────────────────

  def packageSwift(
    appName:      String,
    minIos:       String,
    minMacos:     String,
    includeIos:   Boolean,
    includeMacos: Boolean
  ): String =
    val platforms = List(
      if includeIos    then Some(s".iOS(.v${minIos.replace(".", "_")})")   else None,
      if includeMacos  then Some(s".macOS(.v${minMacos.replace(".", "_")})") else None
    ).flatten.mkString(", ")
    s"""// swift-tools-version:5.9
       |import PackageDescription
       |
       |let package = Package(
       |    name: "${swiftString(appName)}",
       |    platforms: [$platforms],
       |    targets: [
       |        .executableTarget(
       |            name: "${swiftString(appName)}",
       |            path: "Sources/${swiftString(appName)}"
       |        )
       |    ]
       |)
       |""".stripMargin

  // ── App entry ─────────────────────────────────────────────────────────────

  def appSwift(appName: String): String =
    s"""import SwiftUI
       |
       |@main
       |struct ${appName}App: App {
       |    var body: some Scene {
       |        WindowGroup {
       |            ContentView()
       |        }
       |    }
       |}
       |""".stripMargin

  // ── AppModel (Phase 3 — @Observable for list signals) ────────────────────

  /** Generates an `@Observable` model class containing all list signals.
   *  Returns `None` when the module has no `ReactiveSignalList` signals.
   *  When `Some`, the caller should emit this as `AppModel.swift` alongside
   *  `ContentView.swift` so that cross-component state sharing is available. */
  def appModelSwift(appName: String, module: FrontendModule): Option[String] =
    val entry = module.components.find(_.name == module.entryPoint).getOrElse(
      throw new IllegalArgumentException(
        s"FrontendModule.entryPoint='${module.entryPoint}' not found"
      )
    )
    val signals  = collectSignals(entry.body(()))
    val listSigs = signals.filter(_.isList)
    if listSigs.isEmpty then return None
    val props = listSigs.map { s =>
      val (typeName, defaultExpr) = swiftTypeAndDefault(s.value)
      s"    var ${s.id}: $typeName = $defaultExpr"
    }.mkString("\n")
    Some(
      s"""// Generated by ScalaScript — AppModel for ${swiftString(appName)}
         |import Foundation
         |import Observation
         |
         |/// Shared observable model.  Instantiate as `@State var model = AppModel()`
         |/// in any SwiftUI view that needs cross-component access to these lists.
         |@Observable final class AppModel {
         |$props
         |}
         |""".stripMargin
    )

  // ── ContentView ───────────────────────────────────────────────────────────

  def contentView(appName: String, module: FrontendModule, manifest: AppManifest): String =
    val entry = module.components.find(_.name == module.entryPoint).getOrElse(
      throw new IllegalArgumentException(
        s"FrontendModule.entryPoint='${module.entryPoint}' not found among " +
        s"[${module.components.map(_.name).mkString(", ")}]."
      )
    )
    val root       = entry.body(())
    val signals    = collectSignals(root)
    val stateDecls = emitStateDecls(signals, indent = 4)
    val body       = emitView(root, indent = 8)
    s"""// Generated by ScalaScript — ${swiftString(manifest.displayName)} ${swiftString(manifest.version)}
       |// App: ${swiftString(appName)}
       |import SwiftUI
       |
       |struct ContentView: View {
       |$stateDecls
       |    var body: some View {
       |$body
       |    }
       |}
       |
       |#Preview {
       |    ContentView()
       |}
       |""".stripMargin

  // ── View emission ─────────────────────────────────────────────────────────

  private def emitView(view: View[?], indent: Int, ctx: Option[ForCtx] = None): String =
    val pad = " " * indent
    view match

      case View.Text(content, style) =>
        emitMods(s"""${pad}Text(${swiftStringLit(content())})""", style, indent)

      case View.TextNode(value) =>
        emitMods(s"""${pad}Text(${swiftStringLit(value())})""", Style(), indent)

      case View.SignalText(signal, style) =>
        emitMods(s"""${pad}Text("\\(${signal.id})")""", style, indent)

      case View.Button(label, action, enabled, style) =>
        val labelStr   = textOf(label)
        val actionBody = emitAction(action, indent + 8, ctx)
        val base = s"""${pad}Button(${swiftStringLit(labelStr)}) {
                      |${actionBody}
                      |${pad}}""".stripMargin
        val withDisabled = if !enabled() then s"$base\n${pad}    .disabled(true)" else base
        emitMods(withDisabled, style, indent)

      case View.TextInput(value, placeholder, multiline, secure, style) =>
        val base =
          if secure then
            s"""${pad}SecureField(${swiftStringLit(placeholder)}, text: $$${value.id})"""
          else if multiline then
            s"""${pad}TextEditor(text: $$${value.id})
               |${pad}    .overlay(alignment: .topLeading) {
               |${pad}        if ${value.id}.isEmpty { Text(${swiftStringLit(placeholder)}).foregroundStyle(.secondary).padding(4) }
               |${pad}    }""".stripMargin
          else
            s"""${pad}TextField(${swiftStringLit(placeholder)}, text: $$${value.id})"""
        emitMods(base, style, indent)

      case View.Toggle(checked, label, style) =>
        emitMods(s"""${pad}Toggle(${swiftStringLit(label)}, isOn: $$${checked.id})""", style, indent)

      case View.Slider(value, min, max, step, style) =>
        val stepPart = if step > 0 then s", step: $step" else ""
        emitMods(s"""${pad}Slider(value: $$${value.id}, in: $min...$max$stepPart)""", style, indent)

      case View.Image(source, style) =>
        val img = source match
          case ImageSource.Asset(name)     => s"""${pad}Image(${swiftStringLit(name)})"""
          case ImageSource.Url(href)       => s"""${pad}AsyncImage(url: URL(string: ${swiftStringLit(href)})!)"""
          case ImageSource.Base64(_, data) => s"""${pad}Image(${swiftStringLit(data.take(20) + "…")})"""
        emitMods(img, style, indent)

      case View.Icon(name, style) =>
        emitMods(s"""${pad}Image(systemName: ${swiftStringLit(name)})""", style, indent)

      case View.Column(children, spacing, align, style) =>
        val spacingArg = s"alignment: ${hAlignToSwift(align)}, spacing: ${spacing.toInt}"
        emitContainer(s"VStack($spacingArg)", children, style, indent, ctx)

      case View.Row(children, spacing, align, style) =>
        val spacingArg = s"alignment: ${vAlignToSwift(align)}, spacing: ${spacing.toInt}"
        emitContainer(s"HStack($spacingArg)", children, style, indent, ctx)

      case View.Stack(children, style) =>
        emitContainer("ZStack", children, style, indent, ctx)

      case View.ScrollView(child, axis, style) =>
        val axisStr = axis match
          case Axis.Horizontal => ".horizontal"
          case Axis.Both       => "[.horizontal, .vertical]"
          case _               => ".vertical"
        val childBody = emitView(child, indent + 4, ctx)
        emitMods(s"${pad}ScrollView($axisStr) {\n$childBody\n${pad}}", style, indent)

      case View.LazyList(items, render, _, style) =>
        val rows = items().map(item => emitView(render(item), indent + 4, ctx)).mkString("\n")
        emitMods(s"${pad}List {\n$rows\n${pad}}", style, indent)

      case View.LazyGrid(items, render, columns, _, style) =>
        val colExpr = columns match
          case GridColumns.Fixed(n) => s"[GridItem(.adaptive(minimum: ${(320 / n.max(1)).toInt}))]"
          case _                    => "[GridItem(.flexible())]"
        val cells = items().map(item => emitView(render(item), indent + 4, ctx)).mkString("\n")
        emitMods(s"${pad}LazyVGrid(columns: $colExpr) {\n$cells\n${pad}}", style, indent)

      case View.TabBar(tabs, current, style) =>
        val tabItems = tabs.zipWithIndex.map { (tab, idx) =>
          val contentBody = emitView(tab.content, indent + 4, ctx)
          val iconPart = tab.icon.map(i => s", systemImage: ${swiftStringLit(i)}").getOrElse("")
          s"""$contentBody
             |${" " * (indent + 4)}.tabItem { Label(${swiftStringLit(tab.label)}$iconPart) }
             |${" " * (indent + 4)}.tag($idx)""".stripMargin
        }.mkString("\n")
        emitMods(s"${pad}TabView(selection: $$${current.id}) {\n$tabItems\n${pad}}", style, indent)

      case View.NavigationStack(routes, current, style) =>
        val firstRoute = routes.headOption.map(_._2()).getOrElse(View.Text(() => "", Style()))
        val childBody  = emitView(firstRoute, indent + 4, ctx)
        emitMods(s"${pad}NavigationStack {\n$childBody\n${pad}}", style, indent)

      case View.Sheet(content, isPresented) =>
        val contentBody = emitView(content, indent + 8, ctx)
        s"""${pad}Color.clear
           |${pad}    .sheet(isPresented: $$${isPresented.id}) {
           |$contentBody
           |${pad}    }""".stripMargin

      case View.AlertDialog(title, message, buttons, isPresented) =>
        val actionBodies = buttons.map { b =>
          val inner = s"${" " * (indent + 8)}// ${b.label} action"
          s"""${" " * (indent + 8)}Button(${swiftStringLit(b.label)}) {
             |$inner
             |${" " * (indent + 8)}}""".stripMargin
        }.mkString("\n")
        s"""${pad}Color.clear
           |${pad}    .alert(${swiftStringLit(title)}, isPresented: $$${isPresented.id}) {
           |$actionBodies
           |${pad}    } message: {
           |${pad}        Text(${swiftStringLit(message)})
           |${pad}    }""".stripMargin

      case View.Form(child, _, style) =>
        emitMods(s"${pad}Form {\n${emitView(child, indent + 4, ctx)}\n${pad}}", style, indent)

      case View.FormField(label, value, _, style) =>
        emitMods(s"""${pad}TextField(${swiftStringLit(label.toString)}, text: $$${value.id})""", style, indent)

      case View.Picker(options, selected, placeholder, style) =>
        val opts = options.map { case (label, _) =>
          s"""${" " * (indent + 4)}Text(${swiftStringLit(label)})"""
        }.mkString("\n")
        val pickerLabel = if placeholder.isEmpty then "\"\"" else swiftStringLit(placeholder)
        emitMods(s"${pad}Picker($pickerLabel, selection: $$${selected.id}) {\n$opts\n${pad}}", style, indent)

      case View.SafeArea(child, _) =>
        emitView(child, indent, ctx)

      case View.KeyboardAvoiding(child) =>
        emitView(child, indent, ctx)

      case View.Animated(child, _, style) =>
        val childStr = emitView(child, indent, ctx)
        emitMods(s"$childStr", style, indent) + s"\n${" " * indent}    .animation(.default, value: UUID())"

      case View.Spacer(size) =>
        size match
          case Some(px) => s"${pad}Spacer(minLength: ${px.toInt})"
          case None     => s"${pad}Spacer()"

      case View.Divider(_, style) =>
        emitMods(s"${pad}Divider()", style, indent)

      case View.Fragment(children) =>
        children.map(emitView(_, indent, ctx)).mkString("\n")

      case View.Show(cond, whenTrue, whenFalse) =>
        emitView(if cond() then whenTrue() else whenFalse(), indent, ctx)

      case View.ShowSignal(cond, whenTrue, whenFalse) =>
        emitView(if cond.apply() then whenTrue else whenFalse, indent, ctx)

      case View.For(items, render) =>
        items().map(item => emitView(render(item), indent, ctx)).mkString("\n")

      case View.ForSignal(list, _, _, itemTemplate) =>
        val idxVar   = s"__idx_${list.id}"
        val innerCtx = Some(ForCtx(list.id, idxVar))
        itemTemplate match
          case Some(tmpl) =>
            val body = emitView(tmpl, indent + 4, innerCtx)
            s"${pad}ForEach(${list.id}.indices, id: \\.self) { $idxVar in\n$body\n${pad}}"
          case None =>
            s"${pad}ForEach(${list.id}, id: \\.self) { item in\n${" " * (indent + 4)}Text(item)\n${pad}}"

      case View.Styled(child, style) =>
        val base  = emitView(child, indent, ctx)
        val extra = emitStyleModifiers(style, indent)
        if extra.isEmpty then base else s"$base\n$extra"

      case View.Adaptive(_, desktop, mobile, fallback) =>
        emitView(mobile.orElse(desktop).getOrElse(fallback), indent, ctx)

      case other =>
        s"""${pad}Text("[unsupported: ${other.productPrefix}]")"""

  // ── Container helper ──────────────────────────────────────────────────────

  private def emitContainer(
    swiftType: String, children: Seq[View[?]], style: Style,
    indent: Int, ctx: Option[ForCtx]
  ): String =
    val pad       = " " * indent
    val childBody = children.map(emitView(_, indent + 4, ctx)).mkString("\n")
    emitMods(s"${pad}$swiftType {\n$childBody\n${pad}}", style, indent)

  // ── Modifier helpers ──────────────────────────────────────────────────────

  private def emitMods(base: String, style: Style, indent: Int): String =
    val mods = emitStyleModifiers(style, indent)
    if mods.isEmpty then base else s"$base\n$mods"

  private def emitStyleModifiers(style: Style, indent: Int): String =
    val pad = " " * indent + "    "
    List(
      emitPadding(style.layout.padding, pad),
      emitFrame(style.layout, pad),
      emitBackground(style.decoration.background, pad),
      emitForeground(style.text.foreground, pad),
      emitFont(style.text, pad),
      emitCornerRadius(style.decoration.borderRadius, pad),
      emitOpacity(style.effects.opacity, pad),
      style.a11y.label.map(l => s"${pad}.accessibilityLabel(${swiftStringLit(l)})")
    ).flatten.mkString("\n")

  private def emitPadding(edges: EdgeInsets, pad: String): Option[String] =
    if edges == EdgeInsets.zero then None
    else if edges.top == edges.right && edges.right == edges.bottom && edges.bottom == edges.left then
      Some(s"${pad}.padding(${edges.top.toInt})")
    else
      Some(s"${pad}.padding(EdgeInsets(top: ${edges.top.toInt}, leading: ${edges.left.toInt}, bottom: ${edges.bottom.toInt}, trailing: ${edges.right.toInt}))")

  private def emitFrame(layout: LayoutStyle, pad: String): Option[String] =
    (layout.width, layout.height) match
      case (Dimension.Fixed(w), Dimension.Fixed(h)) => Some(s"${pad}.frame(width: ${w.toInt}, height: ${h.toInt})")
      case (Dimension.Fixed(w), _)                  => Some(s"${pad}.frame(width: ${w.toInt})")
      case (_, Dimension.Fixed(h))                  => Some(s"${pad}.frame(height: ${h.toInt})")
      case (Dimension.Fill, _) | (_, Dimension.Fill) => Some(s"${pad}.frame(maxWidth: .infinity)")
      case _                                         => None

  private def emitBackground(color: Option[Color], pad: String): Option[String] =
    color.flatMap(toSwiftColor).map(c => s"${pad}.background($c)")

  private def emitForeground(color: Option[Color], pad: String): Option[String] =
    color.flatMap(toSwiftColor).map(c => s"${pad}.foregroundStyle($c)")

  private def emitFont(text: TextStyle, pad: String): Option[String] =
    (text.fontSize, text.fontWeight, text.fontStyle) match
      case (None, None, FontStyle.Normal) => None
      case _ =>
        val size   = text.fontSize.map(s => s".system(size: ${s.toInt})").getOrElse(".body")
        val weight = text.fontWeight.map(weightToSwift).map(w => s"\n${pad}.fontWeight($w)")
        val italic = if text.fontStyle == FontStyle.Italic then Some(s"\n${pad}.italic()") else None
        Some(s"${pad}.font($size)${weight.getOrElse("")}${italic.getOrElse("")}")

  private def emitCornerRadius(radius: BorderRadius, pad: String): Option[String] =
    if radius == BorderRadius.zero then None
    else if radius.topLeft == radius.topRight && radius.topRight == radius.bottomRight && radius.bottomRight == radius.bottomLeft then
      Some(s"${pad}.cornerRadius(${radius.topLeft.toInt})")
    else
      Some(s"${pad}.cornerRadius(${radius.topLeft.toInt})")

  private def emitOpacity(opacity: Double, pad: String): Option[String] =
    if opacity >= 1.0 then None else Some(s"${pad}.opacity($opacity)")

  // ── Action emission ───────────────────────────────────────────────────────

  private def emitAction(action: EventHandler, indent: Int, ctx: Option[ForCtx]): String =
    val pad = " " * indent
    action match
      case EventHandler.SetSignalLiteral(signal, value) =>
        s"${pad}${signal.id} = ${swiftLiteral(value)}"
      case EventHandler.IncrementSignal(signal, by) =>
        s"${pad}${signal.id} += $by"
      case EventHandler.ToggleSignal(signal) =>
        s"${pad}${signal.id}.toggle()"
      case EventHandler.PushSignalLiteral(list, value) =>
        s"${pad}${list.id}.append(${swiftLiteral(value)})"
      case EventHandler.ClearSignalList(list) =>
        s"${pad}${list.id}.removeAll()"
      case EventHandler.RemoveSelfFromList(list) =>
        ctx match
          case Some(fc) if fc.listId == list.id =>
            s"${pad}${list.id}.remove(at: ${fc.indexVar})"
          case _ =>
            s"${pad}// RemoveSelfFromList: use inside ForSignal for index-based removal on ${list.id}"
      case EventHandler.InputChange(signal) =>
        s"${pad}// InputChange handled by TextField binding on $$${signal.id}"
      case EventHandler.FetchAction(method, url, _, _, _, _) =>
        s"""${pad}// FetchAction ${method.toUpperCase}: ${swiftString(url)}"""
      case EventHandler.Simple(_) | EventHandler.WithEvent(_) =>
        s"${pad}// closure action (not serializable into generated Swift source)"

  // ── State declarations ────────────────────────────────────────────────────

  private def emitStateDecls(signals: List[SignalInitial], indent: Int): String =
    if signals.isEmpty then ""
    else
      val pad = " " * indent
      signals.map { s =>
        val (typeName, defaultExpr) = swiftTypeAndDefault(s.value)
        s"${pad}@State private var ${s.id}: $typeName = $defaultExpr"
      }.mkString("\n")

  // ── Signal collection ─────────────────────────────────────────────────────

  private[swiftui] final case class SignalInitial(id: String, value: Any, isList: Boolean = false)

  private[swiftui] def collectSignals(view: View[?]): List[SignalInitial] =
    def add(acc: Map[String, SignalInitial], sig: ReactiveSignal[?]): Map[String, SignalInitial] =
      acc.updatedWith(sig.id) { case e @ Some(_) => e; case None => Some(SignalInitial(sig.id, sig.apply())) }
    def addList(acc: Map[String, SignalInitial], sig: ReactiveSignalList[?]): Map[String, SignalInitial] =
      acc.updatedWith(sig.id) { case e @ Some(_) => e; case None => Some(SignalInitial(sig.id, sig.initial, isList = true)) }
    def fromAction(acc: Map[String, SignalInitial], a: EventHandler): Map[String, SignalInitial] =
      a match
        case EventHandler.SetSignalLiteral(s, _)  => add(acc, s)
        case EventHandler.IncrementSignal(s, _)   => add(acc, s)
        case EventHandler.ToggleSignal(s)         => add(acc, s)
        case EventHandler.InputChange(s)          => add(acc, s)
        case EventHandler.PushSignalLiteral(l, _) => addList(acc, l)
        case EventHandler.ClearSignalList(l)      => addList(acc, l)
        case EventHandler.RemoveSelfFromList(l)   => addList(acc, l)
        case _                                    => acc
    def loop(acc: Map[String, SignalInitial], v: View[?]): Map[String, SignalInitial] =
      v match
        case View.SignalText(s, _)               => add(acc, s)
        case View.Button(_, a, _, _)             => fromAction(acc, a)
        case View.TextInput(s, _, _, _, _)       => add(acc, s)
        case View.Toggle(s, _, _)                => add(acc, s)
        case View.Slider(s, _, _, _, _)          => add(acc, s)
        case View.Picker(_, s, _, _)             => add(acc, s)
        case View.Sheet(ch, s)                   => loop(add(acc, s), ch)
        case View.AlertDialog(_, _, _, s)        => add(acc, s)
        case View.TabBar(tabs, cur, _)           => tabs.foldLeft(add(acc, cur))((a, t) => loop(a, t.content))
        case View.NavigationStack(routes, cur, _) => routes.values.foldLeft(add(acc, cur))((a, f) => loop(a, f()))
        case View.FormField(_, s, _, _)          => add(acc, s)
        case View.Column(ch, _, _, _)            => ch.foldLeft(acc)(loop)
        case View.Row(ch, _, _, _)               => ch.foldLeft(acc)(loop)
        case View.Stack(ch, _)                   => ch.foldLeft(acc)(loop)
        case View.ScrollView(ch, _, _)           => loop(acc, ch)
        case View.Fragment(ch)                   => ch.foldLeft(acc)(loop)
        case View.Show(_, t, f)                  => loop(loop(acc, t()), f())
        case View.ShowSignal(s, t, f)            => loop(loop(add(acc, s), t), f)
        case View.For(items, r)                  => items().foldLeft(acc)((a, i) => loop(a, r(i)))
        case View.ForSignal(l, _, _, tmpl)       =>
          val withList = addList(acc, l)
          tmpl.map(loop(withList, _)).getOrElse(withList)
        case View.Form(ch, a, _)                 => loop(fromAction(acc, a), ch)
        case View.Styled(ch, _)                  => loop(acc, ch)
        case View.Animated(ch, _, _)             => loop(acc, ch)
        case View.Adaptive(web, desk, mob, fb)   =>
          List(web, desk, mob).flatten.foldLeft(loop(acc, fb))(loop)
        case _ => acc
    loop(Map.empty, view).values.toList.sortBy(_.id)

  // ── Helpers ───────────────────────────────────────────────────────────────

  private def textOf(view: View[?]): String =
    view match
      case View.Text(c, _)      => c()
      case View.TextNode(v)     => v()
      case View.SignalText(s,_) => String.valueOf(s.apply())
      case View.Fragment(ch)    => ch.map(textOf).mkString
      case View.Styled(ch, _)   => textOf(ch)
      case View.Icon(n, _)      => n
      case _                    => "Button"

  def swiftIdent(name: String): String =
    name.filter(c => c.isLetterOrDigit || c == '_').capitalize match
      case ""  => "App"
      case str => if str.head.isDigit then s"App$str" else str

  private def swiftStringLit(value: String): String =
    "\"" + swiftString(value) + "\""

  def swiftString(value: String): String =
    value.flatMap {
      case '\\' => "\\\\"
      case '"'  => "\\\""
      case '\n' => "\\n"
      case '\r' => "\\r"
      case '\t' => "\\t"
      case c if c.isControl => f"\\u{${c.toInt}%04X}"
      case c    => c.toString
    }

  private def swiftLiteral(value: Any): String =
    value match
      case null       => "nil"
      case s: String  => swiftStringLit(s)
      case b: Boolean => if b then "true" else "false"
      case n: Int     => n.toString
      case n: Long    => n.toString
      case n: Float   => n.toString
      case n: Double  => n.toString
      case other      => swiftStringLit(other.toString)

  private def swiftTypeAndDefault(value: Any): (String, String) =
    value match
      case b: Boolean  => ("Bool",   if b then "true" else "false")
      case _: Int      => ("Int",    value.toString)
      case _: Long     => ("Int",    value.toString)
      case _: Double   => ("Double", value.toString)
      case _: Float    => ("Double", value.toString)
      case s: String   => ("String", swiftStringLit(s))
      case _: Seq[?]   => ("[String]", "[]")
      case _           => ("String", "\"\"")

  private def toSwiftColor(color: Color): Option[String] =
    color match
      case Color.Hex(v) =>
        val hex = v.stripPrefix("#")
        if hex.length == 6 then
          val r = Integer.parseInt(hex.substring(0, 2), 16) / 255.0
          val g = Integer.parseInt(hex.substring(2, 4), 16) / 255.0
          val b = Integer.parseInt(hex.substring(4, 6), 16) / 255.0
          Some(f"Color(red: $r%.3f, green: $g%.3f, blue: $b%.3f)")
        else None
      case Color.Rgb(r, g, b)     => Some(f"Color(red: ${r/255.0}%.3f, green: ${g/255.0}%.3f, blue: ${b/255.0}%.3f)")
      case Color.Rgba(r, g, b, a) => Some(f"Color(red: ${r/255.0}%.3f, green: ${g/255.0}%.3f, blue: ${b/255.0}%.3f, opacity: $a%.3f)")
      case Color.Named("red")     => Some("Color.red")
      case Color.Named("blue")    => Some("Color.blue")
      case Color.Named("green")   => Some("Color.green")
      case Color.Named("black")   => Some("Color.black")
      case Color.Named("white")   => Some("Color.white")
      case Color.Named("gray") | Color.Named("grey") => Some("Color.gray")
      case Color.Named("orange")  => Some("Color.orange")
      case Color.Named("yellow")  => Some("Color.yellow")
      case Color.Named("purple")  => Some("Color.purple")
      case Color.Named("pink")    => Some("Color.pink")
      case Color.System(token)    => Some(systemColorToken(token))
      case _                      => None

  private def systemColorToken(token: String): String =
    token match
      case "background"      => "Color(UIColor.systemBackground)"
      case "surface"         => "Color(UIColor.secondarySystemBackground)"
      case "primary"         => "Color.primary"
      case "secondary"       => "Color.secondary"
      case "accent"          => "Color.accentColor"
      case "error"           => "Color.red"
      case "on-background"   => "Color.primary"
      case "on-surface"      => "Color.primary"
      case "on-primary"      => "Color.white"
      case "on-secondary"    => "Color.white"
      case "outline"         => "Color(UIColor.separator)"
      case "outline-variant" => "Color(UIColor.opaqueSeparator)"
      case _                 => "Color.primary"

  private def weightToSwift(weight: FontWeight): String =
    weight match
      case FontWeight.Thin       => ".ultraLight"
      case FontWeight.ExtraLight => ".light"
      case FontWeight.Light      => ".light"
      case FontWeight.Regular    => ".regular"
      case FontWeight.Medium     => ".medium"
      case FontWeight.SemiBold   => ".semibold"
      case FontWeight.Bold       => ".bold"
      case FontWeight.ExtraBold  => ".heavy"
      case FontWeight.Black      => ".black"
      case FontWeight.Custom(v)  => if v >= 700 then ".bold" else if v >= 600 then ".semibold" else ".regular"

  private def hAlignToSwift(align: HAlign): String =
    align match
      case HAlign.Start   => ".leading"
      case HAlign.Center  => ".center"
      case HAlign.End     => ".trailing"
      case HAlign.Stretch => ".center"

  private def vAlignToSwift(align: VAlign): String =
    align match
      case VAlign.Top     => ".top"
      case VAlign.Center  => ".center"
      case VAlign.Bottom  => ".bottom"
      case VAlign.Stretch => ".center"


  // ── Signal bridge (v1.51.5c) ──────────────────────────────────────────────

  /** Generates `SignalBridge.swift` — a Combine-backed `ObservableSignal<T>` class
   *  providing platform-native equivalents of `Source.signal(sig)` and
   *  `sig.bind(source)` for generated SwiftUI apps. */
  def signalBridgeSwift(appName: String): String =
    s"""// Generated by ScalaScript — SignalBridge for ${swiftString(appName)} (v1.51.5c)
       |// Platform-native stream/signal bridge matching interpreter Source.signal + sig.bind.
       |import Combine
       |import Foundation
       |
       |// ObservableSignal: Combine-backed reactive signal for ScalaScript SwiftUI apps.
       |// Usage:
       |//   @StateObject var count = ObservableSignal(id: "count", 0)
       |//   count.value          // read
       |//   count.value = 42     // write
       |//   count.asStream       // Source.signal(count) equivalent
       |//   count.bind(src)      // sig.bind(source) equivalent
       |@MainActor
       |public final class ObservableSignal<T: Sendable>: ObservableObject {
       |    @Published public var value: T
       |    public let id: String
       |    private var bindTask: Task<Void, Never>?
       |
       |    public init(id: String, _ initial: T) {
       |        self.id = id
       |        self.value = initial
       |    }
       |
       |    /// Emits the current value and each subsequent update as an `AsyncStream`.
       |    /// Platform-native equivalent of `Source.signal(sig)`.
       |    public var asStream: AsyncStream<T> {
       |        AsyncStream { continuation in
       |            continuation.yield(self.value)
       |            let sub = self.$$value.sink { continuation.yield($$0) }
       |            continuation.onTermination = { _ in sub.cancel() }
       |        }
       |    }
       |
       |    /// Subscribes to `source` and writes each emitted value into this signal.
       |    /// Platform-native equivalent of `sig.bind(source)`. Last-value-wins.
       |    public func bind(source: AsyncStream<T>) {
       |        bindTask?.cancel()
       |        bindTask = Task { @MainActor [weak self] in
       |            for await v in source { self?.value = v }
       |        }
       |    }
       |
       |    deinit { bindTask?.cancel() }
       |}
       |""".stripMargin
