package scalascript.frontend.swiftui

import scalascript.frontend.*
import scalascript.ast.{ModelDef, ModelFieldType}

/** Generates Swift/SwiftUI source from the framework-agnostic View IR.
 *
 *  Output layout:
 *   - Package.swift                    — Swift Package manifest
 *   - Sources/<App>/<App>App.swift     — @main entry
 *   - Sources/<App>/ContentView.swift  — generated UI
 *   - Sources/<App>/AppModel.swift     — @Observable model (only when list signals exist)
 *
 *  Signal state (`ReactiveSignal[T]`) lowers to `@State private var`.
 *  `ReactiveSignalList[T]` lowers to `@State private var` in ContentView and also
 *  appears as a property on the generated `@Observable AppModel` (Phase 3).
 *  `@Binding` is used where the child view needs to mutate a signal owned
 *  by the parent (TextInput, Toggle, Picker). */
object SwiftUIEmitter:

  /** Context injected when emitting inside a `ForSignal` or `ForModel` loop body.
   *  `listId`/`indexVar` support `RemoveSelfFromList`; `modelItemVar` carries the
   *  Swift item variable name from a surrounding `ForModel` for `DeleteItem`. */
  private final case class ForCtx(
    listId:       String,
    indexVar:     String,
    modelItemVar: Option[String] = None
  )

  // ── Package.swift ─────────────────────────────────────────────────────────

  def packageSwift(
    appName:      String,
    minIos:       String,
    minMacos:     String,
    includeIos:   Boolean,
    includeMacos: Boolean
  ): String =
    val platforms = List(
      if includeIos    then Some(s".iOS(.v${minIos.replace(".", "_")})")   else None,
      if includeMacos  then Some(s".macOS(.v${minMacos.replace(".", "_")})") else None
    ).flatten.mkString(", ")
    s"""// swift-tools-version:5.9
       |import PackageDescription
       |
       |let package = Package(
       |    name: "${swiftString(appName)}",
       |    platforms: [$platforms],
       |    targets: [
       |        .executableTarget(
       |            name: "${swiftString(appName)}",
       |            path: "Sources/${swiftString(appName)}"
       |        )
       |    ]
       |)
       |""".stripMargin

  // ── App entry ─────────────────────────────────────────────────────────────

  def appSwift(appName: String): String =
    s"""import SwiftUI
       |
       |@main
       |struct ${appName}App: App {
       |    var body: some Scene {
       |        WindowGroup {
       |            ContentView()
       |        }
       |    }
       |}
       |""".stripMargin

  // ── AppModel (Phase 3 — @Observable for list signals) ────────────────────

  /** Generates an `@Observable` model class containing all list signals.
   *  Returns `None` when the module has no `ReactiveSignalList` signals.
   *  When `Some`, the caller should emit this as `AppModel.swift` alongside
   *  `ContentView.swift` so that cross-component state sharing is available. */
  def appModelSwift(appName: String, module: FrontendModule): Option[String] =
    val entry = module.components.find(_.name == module.entryPoint).getOrElse(
      throw new IllegalArgumentException(
        s"FrontendModule.entryPoint='${module.entryPoint}' not found"
      )
    )
    val signals  = collectSignals(entry.body(()))
    val listSigs = signals.filter(_.isList)
    if listSigs.isEmpty then return None
    val props = listSigs.map { s =>
      val (typeName, defaultExpr) = swiftTypeAndDefault(s.value)
      s"    var ${s.id}: $typeName = $defaultExpr"
    }.mkString("\n")
    Some(
      s"""// Generated by ScalaScript — AppModel for ${swiftString(appName)}
         |import Foundation
         |import Observation
         |
         |/// Shared observable model.  Instantiate as `@State var model = AppModel()`
         |/// in any SwiftUI view that needs cross-component access to these lists.
         |@Observable final class AppModel {
         |$props
         |}
         |""".stripMargin
    )

  // ── Model structs (typed models) ─────────────────────────────────────────

  def emitModelStructs(models: List[ModelDef]): String =
    if models.isEmpty then ""
    else models.map { m =>
      val hasId     = m.identifyingField.isDefined
      val idField   = m.identifyingField.getOrElse("")
      val idType    = if hasId then
        m.fields.find(_.name == idField).map(f => modelFieldTypeToSwift(f.tpe)).getOrElse("String")
      else ""
      val conformances = if hasId then ": Decodable, Identifiable" else ": Decodable"
      val fields = m.fields.map { f =>
        s"    let ${f.name}: ${modelFieldTypeToSwift(f.tpe)}"
      }.mkString("\n")
      val idComputed = if hasId && idField != "id" then
        s"\n    var id: $idType { $idField }"
      else ""
      s"struct ${m.name}$conformances {\n$fields$idComputed\n}"
    }.mkString("\n\n") + "\n"

  private def modelFieldTypeToSwift(tpe: ModelFieldType): String = tpe match
    case ModelFieldType.Str             => "String"
    case ModelFieldType.IntF            => "Int"
    case ModelFieldType.DblF            => "Double"
    case ModelFieldType.BoolF           => "Bool"
    case ModelFieldType.Nested(name)    => name
    case ModelFieldType.ListOf(inner)   => s"[${modelFieldTypeToSwift(inner)}]"
    case ModelFieldType.Optional(inner) => s"${modelFieldTypeToSwift(inner)}?"

  // ── ContentView ───────────────────────────────────────────────────────────

  def contentView(appName: String, module: FrontendModule, manifest: AppManifest): String =
    val entry = module.components.find(_.name == module.entryPoint).getOrElse(
      throw new IllegalArgumentException(
        s"FrontendModule.entryPoint='${module.entryPoint}' not found among " +
        s"[${module.components.map(_.name).mkString(", ")}]."
      )
    )
    val root          = entry.body(())
    val signals       = collectSignals(root)
    val fetchSigs     = collectFetchSignals(root)
    val dtSigs        = collectDataTableSignals(root)
    val fetchOwnedIds = fetchSigs.flatMap { fs =>
      List(fs.id, fs.id + "_loading", fs.id + "_loaded", fs.id + "_error")
    }.toSet
    val signalIds      = signals.map(_.id).toSet
    val fetchTickIds   = fetchSigs.map(_.tickId).distinct.filterNot(signalIds)
    val fetchTickDecls = fetchTickIds.map(id => s"    @State private var $id: Int = 0").mkString("\n")
    val stateDecls    = emitStateDecls(signals.filterNot(s => fetchOwnedIds(s.id)), indent = 4)
    val fetchState    = emitFetchStateDecls(fetchSigs, indent = 4)
    val dtState       = emitDataTableStateDecls(dtSigs, indent = 4)
    val allState      = List(stateDecls, fetchTickDecls, fetchState, dtState).filter(_.nonEmpty).mkString("\n")
    val body          = emitView(root, indent = 8)
    val fetchMods     = emitFetchModifiers(fetchSigs, indent = 8)
    val dtMods        = emitDataTableModifiers(dtSigs, indent = 8)
    val allMods       = List(fetchMods, dtMods).filter(_.nonEmpty).mkString("\n")
    val fetchMethods  = emitFetchMethods(fetchSigs, indent = 4)
    val dtMethods     = emitDataTableMethods(dtSigs, indent = 4)
    val bodyWithMods  = if allMods.isEmpty then body else s"$body\n$allMods"
    val modelStructs  = emitModelStructs(module.models)
    val structsBlock  = if modelStructs.nonEmpty then s"$modelStructs\n" else ""
    val allMethods = List(fetchMethods, dtMethods).filter(_.nonEmpty).mkString("\n")
    s"""// Generated by ScalaScript — ${swiftString(manifest.displayName)} ${swiftString(manifest.version)}
       |// App: ${swiftString(appName)}
       |import SwiftUI
       |
       |${structsBlock}struct ContentView: View {
       |$allState
       |    var body: some View {
       |$bodyWithMods
       |    }
       |$allMethods}
       |
       |""".stripMargin

  // ── View emission ─────────────────────────────────────────────────────────

  private def emitView(view: View[?], indent: Int, ctx: Option[ForCtx] = None): String =
    val pad = " " * indent
    view match

      case View.Text(content, style) =>
        emitMods(s"""${pad}Text(${swiftStringLit(content())})""", style, indent)

      case View.TextNode(value) =>
        emitMods(s"""${pad}Text(${swiftStringLit(value())})""", Style(), indent)

      case View.SignalText(signal, style) =>
        emitMods(s"""${pad}Text("\\(${signal.id})")""", style, indent)

      case View.Button(label, action, enabled, style) =>
        val labelStr   = textOf(label)
        val actionBody = emitAction(action, indent + 8, ctx)
        val base = s"""${pad}Button(${swiftStringLit(labelStr)}) {
                      |${actionBody}
                      |${pad}}""".stripMargin
        val withDisabled = if !enabled() then s"$base\n${pad}    .disabled(true)" else base
        emitMods(withDisabled, style, indent)

      case View.TextInput(value, placeholder, multiline, secure, style) =>
        val base =
          if secure then
            s"""${pad}SecureField(${swiftStringLit(placeholder)}, text: $$${value.id})"""
          else if multiline then
            s"""${pad}TextEditor(text: $$${value.id})
               |${pad}    .overlay(alignment: .topLeading) {
               |${pad}        if ${value.id}.isEmpty { Text(${swiftStringLit(placeholder)}).foregroundStyle(.secondary).padding(4) }
               |${pad}    }""".stripMargin
          else
            s"""${pad}TextField(${swiftStringLit(placeholder)}, text: $$${value.id})"""
        emitMods(base, style, indent)

      case View.Toggle(checked, label, style) =>
        emitMods(s"""${pad}Toggle(${swiftStringLit(label)}, isOn: $$${checked.id})""", style, indent)

      case View.Slider(value, min, max, step, style) =>
        val stepPart = if step > 0 then s", step: $step" else ""
        emitMods(s"""${pad}Slider(value: $$${value.id}, in: $min...$max$stepPart)""", style, indent)

      case View.Image(source, style) =>
        val img = source match
          case ImageSource.Asset(name)     => s"""${pad}Image(${swiftStringLit(name)})"""
          case ImageSource.Url(href)       => s"""${pad}AsyncImage(url: URL(string: ${swiftStringLit(href)})!)"""
          case ImageSource.Base64(_, data) => s"""${pad}Image(${swiftStringLit(data.take(20) + "…")})"""
        emitMods(img, style, indent)

      case View.Icon(name, style) =>
        emitMods(s"""${pad}Image(systemName: ${swiftStringLit(name)})""", style, indent)

      case View.Column(children, spacing, align, style) =>
        val spacingArg = s"alignment: ${hAlignToSwift(align)}, spacing: ${spacing.toInt}"
        emitContainer(s"VStack($spacingArg)", children, style, indent, ctx)

      case View.Row(children, spacing, align, style) =>
        val spacingArg = s"alignment: ${vAlignToSwift(align)}, spacing: ${spacing.toInt}"
        emitContainer(s"HStack($spacingArg)", children, style, indent, ctx)

      case View.Stack(children, style) =>
        emitContainer("ZStack", children, style, indent, ctx)

      case View.ScrollView(child, axis, style) =>
        val axisStr = axis match
          case Axis.Horizontal => ".horizontal"
          case Axis.Both       => "[.horizontal, .vertical]"
          case _               => ".vertical"
        val childBody = emitView(child, indent + 4, ctx)
        emitMods(s"${pad}ScrollView($axisStr) {\n$childBody\n${pad}}", style, indent)

      case View.LazyList(items, render, _, style) =>
        val rows = items().map(item => emitView(render(item), indent + 4, ctx)).mkString("\n")
        emitMods(s"${pad}List {\n$rows\n${pad}}", style, indent)

      case View.LazyGrid(items, render, columns, _, style) =>
        val colExpr = columns match
          case GridColumns.Fixed(n) => s"[GridItem(.adaptive(minimum: ${(320 / n.max(1)).toInt}))]"
          case _                    => "[GridItem(.flexible())]"
        val cells = items().map(item => emitView(render(item), indent + 4, ctx)).mkString("\n")
        emitMods(s"${pad}LazyVGrid(columns: $colExpr) {\n$cells\n${pad}}", style, indent)

      case View.TabBar(tabs, current, style) =>
        val tabItems = tabs.zipWithIndex.map { (tab, idx) =>
          val contentBody = emitView(tab.content, indent + 4, ctx)
          val iconPart = tab.icon.map(i => s", systemImage: ${swiftStringLit(i)}").getOrElse("")
          s"""$contentBody
             |${" " * (indent + 4)}.tabItem { Label(${swiftStringLit(tab.label)}$iconPart) }
             |${" " * (indent + 4)}.tag($idx)""".stripMargin
        }.mkString("\n")
        emitMods(s"${pad}TabView(selection: $$${current.id}) {\n$tabItems\n${pad}}", style, indent)

      case View.NavigationStack(routes, current, style) =>
        val firstRoute = routes.headOption.map(_._2()).getOrElse(View.Text(() => "", Style()))
        val childBody  = emitView(firstRoute, indent + 4, ctx)
        emitMods(s"${pad}NavigationStack {\n$childBody\n${pad}}", style, indent)

      case View.Sheet(content, isPresented) =>
        val contentBody = emitView(content, indent + 8, ctx)
        s"""${pad}Color.clear
           |${pad}    .sheet(isPresented: $$${isPresented.id}) {
           |$contentBody
           |${pad}    }""".stripMargin

      case View.AlertDialog(title, message, buttons, isPresented) =>
        val actionBodies = buttons.map { b =>
          val inner = s"${" " * (indent + 8)}// ${b.label} action"
          s"""${" " * (indent + 8)}Button(${swiftStringLit(b.label)}) {
             |$inner
             |${" " * (indent + 8)}}""".stripMargin
        }.mkString("\n")
        s"""${pad}Color.clear
           |${pad}    .alert(${swiftStringLit(title)}, isPresented: $$${isPresented.id}) {
           |$actionBodies
           |${pad}    } message: {
           |${pad}        Text(${swiftStringLit(message)})
           |${pad}    }""".stripMargin

      case View.Form(child, _, style) =>
        emitMods(s"${pad}Form {\n${emitView(child, indent + 4, ctx)}\n${pad}}", style, indent)

      case View.FormField(label, value, _, style) =>
        emitMods(s"""${pad}TextField(${swiftStringLit(label.toString)}, text: $$${value.id})""", style, indent)

      case View.Picker(options, selected, placeholder, style) =>
        val opts = options.map { case (label, _) =>
          s"""${" " * (indent + 4)}Text(${swiftStringLit(label)})"""
        }.mkString("\n")
        val pickerLabel = if placeholder.isEmpty then "\"\"" else swiftStringLit(placeholder)
        emitMods(s"${pad}Picker($pickerLabel, selection: $$${selected.id}) {\n$opts\n${pad}}", style, indent)

      case View.SafeArea(child, _) =>
        emitView(child, indent, ctx)

      case View.KeyboardAvoiding(child) =>
        emitView(child, indent, ctx)

      case View.Animated(child, _, style) =>
        val childStr = emitView(child, indent, ctx)
        emitMods(s"$childStr", style, indent) + s"\n${" " * indent}    .animation(.default, value: UUID())"

      case View.Spacer(size) =>
        size match
          case Some(px) => s"${pad}Spacer(minLength: ${px.toInt})"
          case None     => s"${pad}Spacer()"

      case View.Divider(_, style) =>
        emitMods(s"${pad}Divider()", style, indent)

      case View.Fragment(children) =>
        children.map(emitView(_, indent, ctx)).mkString("\n")

      case View.Show(cond, whenTrue, whenFalse) =>
        emitView(if cond() then whenTrue() else whenFalse(), indent, ctx)

      case View.ShowSignal(cond, whenTrue, whenFalse) =>
        val truePart  = emitView(whenTrue, indent + 4, ctx)
        val falsePart = emitView(whenFalse, indent + 4, ctx)
        val elseClause = if falsePart.trim.isEmpty then "" else s"\n${pad}} else {\n$falsePart"
        s"${pad}if ${cond.id} {\n$truePart\n$pad}$elseClause"

      case View.For(items, render) =>
        items().map(item => emitView(render(item), indent, ctx)).mkString("\n")

      case View.ForSignal(list, _, _, itemTemplate) =>
        val idxVar   = s"__idx_${list.id}"
        val innerCtx = Some(ForCtx(list.id, idxVar))
        itemTemplate match
          case Some(tmpl) =>
            val body = emitView(tmpl, indent + 4, innerCtx)
            s"${pad}ForEach(${list.id}.indices, id: \\.self) { $idxVar in\n$body\n${pad}}"
          case None =>
            s"${pad}ForEach(${list.id}, id: \\.self) { item in\n${" " * (indent + 4)}Text(item)\n${pad}}"

      case View.Styled(child, style) =>
        val base  = emitView(child, indent, ctx)
        val extra = emitStyleModifiers(style, indent)
        if extra.isEmpty then base else s"$base\n$extra"

      case View.Adaptive(_, desktop, mobile, fallback) =>
        emitView(mobile.orElse(desktop).getOrElse(fallback), indent, ctx)

      case View.ModelView(signal, bindingVar, template, style) =>
        val bv = escapeSwiftIdent(bindingVar)
        val innerBody = emitView(template, indent + 4, ctx)
        emitMods(
          s"${pad}if let $bv = ${signal.id} {\n$innerBody\n${pad}}",
          style, indent)

      case View.ForModel(bindingVar, fieldPath, itemVar, template, style) =>
        val bv       = escapeSwiftIdent(bindingVar)
        val iv       = escapeSwiftIdent(itemVar)
        val dotPath  = fieldPath.replace('.', '.')
        val fmCtx    = ctx.map(_.copy(modelItemVar = Some(iv)))
                          .orElse(Some(ForCtx("", "", Some(iv))))
        val innerBody = emitView(template, indent + 4, fmCtx)
        emitMods(
          s"${pad}ForEach(Array($bv.$dotPath.enumerated()), id: \\.offset) { _, $iv in\n$innerBody\n${pad}}",
          style, indent)

      case View.ModelText(varName, fieldPath, style) =>
        val dotPath = fieldPath.replace('.', '.')
        emitMods(s"""${pad}Text("\\(${escapeSwiftIdent(varName)}.$dotPath)")""", style, indent)

      case View.FormattedField(varName, fieldPath, _, style) =>
        // TODO(datatable-p3): kind-aware rendering for SwiftUI (Date/Money/StatusBadge/Link)
        val dotPath = fieldPath.replace('.', '.')
        emitMods(s"""${pad}Text("\\(${escapeSwiftIdent(varName)}.$dotPath)")""", style, indent)

      case dt: View.DataTable =>
        dt.source match
          case TableDataSource.Remote(sig) =>
            val pad2 = " " * (indent + 4)
            val pad3 = " " * (indent + 8)
            val pad4 = " " * (indent + 12)
            val headerCols = dt.columns.map(c => s"""${pad3}Text(${swiftStringLit(c.title)}).bold()""").mkString("\n")
            val editBuf  = s"_edit_${sig.id}"
            val dataCols = dt.columns.map { c =>
              val key = c.fieldPath.split("\\.").head
              c.editAction match
                case None =>
                  s"""${pad4}Text((_row[${swiftStringLit(key)}] as? String) ?? String(describing: _row[${swiftStringLit(key)}] ?? ""))"""
                case Some(ea) =>
                  val editKey    = swiftStringLit(key)
                  val idKey      = swiftStringLit(ea.idField.split("\\.").head)
                  val urlLit     = swiftStringLit(ea.url)
                  val methodLit  = swiftStringLit(ea.method.toUpperCase)
                  val fieldLit   = swiftStringLit(c.fieldPath.split("\\.").last)
                  val idFieldLit = swiftStringLit(ea.idField.split("\\.").last)
                  val bufKey     = s"\\(_idx)_${key}"
                  val rawVal     = s"""(_row[$editKey] as? String) ?? String(describing: _row[$editKey] ?? "")"""
                  val hApply     = sig.headersId.map { hid =>
                    s"""${pad4}        if let _hData = $hid.data(using: .utf8),
                       |${pad4}           let _hDict = try? JSONSerialization.jsonObject(with: _hData) as? [String: String] {
                       |${pad4}            for (k, v) in _hDict { _req.setValue(v, forHTTPHeaderField: k) }
                       |${pad4}        }""".stripMargin
                  }.getOrElse("")
                  val hSep = if hApply.nonEmpty then s"\n$hApply" else ""
                  s"""${pad4}TextField("", text: Binding(
                     |${pad4}    get: { $editBuf["$bufKey"] ?? ($rawVal) },
                     |${pad4}    set: { $editBuf["$bufKey"] = $$0 }
                     |${pad4}))
                     |${pad4}.textFieldStyle(.plain)
                     |${pad4}.frame(maxWidth: .infinity)
                     |${pad4}.onSubmit {
                     |${pad4}    let _val = $editBuf["$bufKey"] ?? ($rawVal)
                     |${pad4}    let _id  = (_row[$idKey] as? String) ?? String(describing: _row[$idKey] ?? "")
                     |${pad4}    Task { @MainActor in
                     |${pad4}        guard let _url = URL(string: $urlLit) else { return }
                     |${pad4}        var _req = URLRequest(url: _url)
                     |${pad4}        _req.httpMethod = $methodLit
                     |${pad4}        _req.setValue("application/json", forHTTPHeaderField: "Content-Type")$hSep
                     |${pad4}        _req.httpBody = try? JSONSerialization.data(withJSONObject: [$idFieldLit: _id, $fieldLit: _val])
                     |${pad4}        let _ = try? await URLSession.shared.data(for: _req)
                     |${pad4}        ${ea.onSuccessTick.id} += 1
                     |${pad4}    }
                     |${pad4}}""".stripMargin
            }.mkString("\n")
            val actionBtns = dt.actions.map {
              case RowActionDef.RowDelete(url, idField, tick, _) =>
                val key = idField.split("\\.").head
                s"""${pad4}Button("Delete") { Task { @MainActor in
                   |${pad4}  guard let _url = URL(string: ${swiftStringLit(url)}) else { return }
                   |${pad4}  var _req = URLRequest(url: _url)
                   |${pad4}  _req.httpMethod = "POST"
                   |${pad4}  _req.httpBody = ((_row[${swiftStringLit(key)}] as? String) ?? "").data(using: .utf8)
                   |${pad4}  let _ = try? await URLSession.shared.data(for: _req)
                   |${pad4}  ${tick.id} += 1
                   |${pad4}} }""".stripMargin
              case RowActionDef.RowPost(label, method, url, payload, tick, _) =>
                val bodyExpr = payload match
                  case RowPayload.Field(name) =>
                    val key = name.split("\\.").head
                    s"((_row[${swiftStringLit(key)}] as? String) ?? \"\").data(using: .utf8)"
                  case RowPayload.WholeRow =>
                    "(try? JSONSerialization.data(withJSONObject: _row)) ?? Data()"
                  case RowPayload.Fields(names) =>
                    val entries = names.map(n => s"${swiftStringLit(n)}: _row[${swiftStringLit(n)}] ?? \"\"").mkString(", ")
                    s"(try? JSONSerialization.data(withJSONObject: [$entries])) ?? Data()"
                s"""${pad4}Button(${swiftStringLit(label)}) { Task { @MainActor in
                   |${pad4}  guard let _url = URL(string: ${swiftStringLit(url)}) else { return }
                   |${pad4}  var _req = URLRequest(url: _url)
                   |${pad4}  _req.httpMethod = ${swiftStringLit(method.toUpperCase)}
                   |${pad4}  _req.httpBody = $bodyExpr
                   |${pad4}  let _ = try? await URLSession.shared.data(for: _req)
                   |${pad4}  ${tick.id} += 1
                   |${pad4}} }""".stripMargin
              case RowActionDef.RowLink(label, signal, fieldPath) =>
                val key = fieldPath.split("\\.").head
                s"""${pad4}Button(${swiftStringLit(label)}) {
                   |${pad4}  ${signal.id} = (_row[${swiftStringLit(key)}] as? String) ?? ""
                   |${pad4}}""".stripMargin
              case RowActionDef.RowInlineEdit(_, _, _, _, _) => ""
            }.filter(_.nonEmpty).mkString("\n")
            val rowBody = if actionBtns.nonEmpty then
              s"${pad3}HStack {\n$dataCols\n$actionBtns\n${pad3}}"
            else
              s"${pad3}HStack {\n$dataCols\n${pad3}}"
            s"""${pad}List {
               |${pad2}HStack {
               |$headerCols
               |${pad2}}
               |${pad2}ForEach(Array(${sig.id}.enumerated()), id: \\.offset) { _idx, _row in
               |$rowBody
               |${pad2}}
               |${pad}}""".stripMargin
          case _ =>
            // StaticRows / SignalRows: stub — emit a comment placeholder; full rendering in Phase 3
            s"${" " * indent}// DataTable: non-remote source not yet rendered\n${" " * indent}EmptyView()"

      case other =>
        s"${pad}// TODO: unsupported IR node: ${other.productPrefix}\n${pad}EmptyView()"

  // ── Container helper ──────────────────────────────────────────────────────

  private def emitContainer(
    swiftType: String, children: Seq[View[?]], style: Style,
    indent: Int, ctx: Option[ForCtx]
  ): String =
    val pad       = " " * indent
    val childBody = children.map(emitView(_, indent + 4, ctx)).mkString("\n")
    emitMods(s"${pad}$swiftType {\n$childBody\n${pad}}", style, indent)

  // ── Modifier helpers ──────────────────────────────────────────────────────

  private def emitMods(base: String, style: Style, indent: Int): String =
    val mods = emitStyleModifiers(style, indent)
    if mods.isEmpty then base else s"$base\n$mods"

  private def emitStyleModifiers(style: Style, indent: Int): String =
    val pad = " " * indent + "    "
    List(
      emitPadding(style.layout.padding, pad),
      emitFrame(style.layout, pad),
      emitBackground(style.decoration.background, pad),
      emitForeground(style.text.foreground, pad),
      emitFont(style.text, pad),
      emitCornerRadius(style.decoration.borderRadius, pad),
      emitOpacity(style.effects.opacity, pad),
      style.a11y.label.map(l => s"${pad}.accessibilityLabel(${swiftStringLit(l)})")
    ).flatten.mkString("\n")

  private def emitPadding(edges: EdgeInsets, pad: String): Option[String] =
    if edges == EdgeInsets.zero then None
    else if edges.top == edges.right && edges.right == edges.bottom && edges.bottom == edges.left then
      Some(s"${pad}.padding(${edges.top.toInt})")
    else
      Some(s"${pad}.padding(EdgeInsets(top: ${edges.top.toInt}, leading: ${edges.left.toInt}, bottom: ${edges.bottom.toInt}, trailing: ${edges.right.toInt}))")

  private def emitFrame(layout: LayoutStyle, pad: String): Option[String] =
    (layout.width, layout.height) match
      case (Dimension.Fixed(w), Dimension.Fixed(h)) => Some(s"${pad}.frame(width: ${w.toInt}, height: ${h.toInt})")
      case (Dimension.Fixed(w), _)                  => Some(s"${pad}.frame(width: ${w.toInt})")
      case (_, Dimension.Fixed(h))                  => Some(s"${pad}.frame(height: ${h.toInt})")
      case (Dimension.Fill, _) | (_, Dimension.Fill) => Some(s"${pad}.frame(maxWidth: .infinity)")
      case _                                         => None

  private def emitBackground(color: Option[Color], pad: String): Option[String] =
    color.flatMap(toSwiftColor).map(c => s"${pad}.background($c)")

  private def emitForeground(color: Option[Color], pad: String): Option[String] =
    color.flatMap(toSwiftColor).map(c => s"${pad}.foregroundStyle($c)")

  private def emitFont(text: TextStyle, pad: String): Option[String] =
    (text.fontSize, text.fontWeight, text.fontStyle) match
      case (None, None, FontStyle.Normal) => None
      case _ =>
        val size   = text.fontSize.map(s => s".system(size: ${s.toInt})").getOrElse(".body")
        val weight = text.fontWeight.map(weightToSwift).map(w => s"\n${pad}.fontWeight($w)")
        val italic = if text.fontStyle == FontStyle.Italic then Some(s"\n${pad}.italic()") else None
        Some(s"${pad}.font($size)${weight.getOrElse("")}${italic.getOrElse("")}")

  private def emitCornerRadius(radius: BorderRadius, pad: String): Option[String] =
    if radius == BorderRadius.zero then None
    else if radius.topLeft == radius.topRight && radius.topRight == radius.bottomRight && radius.bottomRight == radius.bottomLeft then
      Some(s"${pad}.cornerRadius(${radius.topLeft.toInt})")
    else
      Some(s"${pad}.cornerRadius(${radius.topLeft.toInt})")

  private def emitOpacity(opacity: Double, pad: String): Option[String] =
    if opacity >= 1.0 then None else Some(s"${pad}.opacity($opacity)")

  // ── Action emission ───────────────────────────────────────────────────────

  private def emitAction(action: EventHandler, indent: Int, ctx: Option[ForCtx]): String =
    val pad = " " * indent
    action match
      case EventHandler.SetSignalLiteral(signal, value) =>
        s"${pad}${signal.id} = ${swiftLiteral(value)}"
      case EventHandler.IncrementSignal(signal, by) =>
        s"${pad}${signal.id} += $by"
      case EventHandler.ToggleSignal(signal) =>
        s"${pad}${signal.id}.toggle()"
      case EventHandler.PushSignalLiteral(list, value) =>
        s"${pad}${list.id}.append(${swiftLiteral(value)})"
      case EventHandler.ClearSignalList(list) =>
        s"${pad}${list.id}.removeAll()"
      case EventHandler.RemoveSelfFromList(list) =>
        ctx match
          case Some(fc) if fc.listId == list.id =>
            s"${pad}${list.id}.remove(at: ${fc.indexVar})"
          case _ =>
            s"${pad}// RemoveSelfFromList: use inside ForSignal for index-based removal on ${list.id}"
      case EventHandler.InputChange(signal) =>
        s"${pad}// InputChange handled by TextField binding on $$${signal.id}"
      case EventHandler.FetchAction(method, url, body, onSuccessTick, clearBody, _) =>
        emitFetchTask(method, url, body.id, onSuccessTick.id, clearBody, indent)
      case EventHandler.DeleteItem(idField, deleteUrl, onSuccessTick, _) =>
        val pad2 = " " * (indent + 4)
        val pad3 = " " * (indent + 8)
        val bodyLine = ctx.flatMap(_.modelItemVar) match
          case Some(iv) =>
            s"""${pad2}_req.httpBody = "\\($iv.${escapeSwiftIdent(idField)})".data(using: .utf8)"""
          case None =>
            s"""${pad2}// DeleteItem: no ForModel context — $idField unresolved"""
        s"""${pad}Task { @MainActor in
           |${pad2}guard let _url = URL(string: ${swiftStringLit(deleteUrl)}) else { return }
           |${pad2}var _req = URLRequest(url: _url)
           |${pad2}_req.httpMethod = "POST"
           |${pad2}_req.setValue("application/json", forHTTPHeaderField: "Content-Type")
           |$bodyLine
           |${pad2}do {
           |${pad3}let (_, _) = try await URLSession.shared.data(for: _req)
           |${pad3}${onSuccessTick.id} += 1
           |${pad2}} catch {}
           |${pad}}""".stripMargin
      case EventHandler.ItemAction(method, url, payload, onSuccessTick, _) =>
        val pad2 = " " * (indent + 4)
        val pad3 = " " * (indent + 8)
        val bodyExpr = payload match
          case RowPayload.Field(name)    => s"(String($name)).data(using: .utf8)"
          case RowPayload.WholeRow       => "(try? JSONSerialization.data(withJSONObject: _row)) ?? Data()"
          case RowPayload.Fields(names)  =>
            val entries = names.map(n => s"${swiftStringLit(n)}: $n").mkString(", ")
            s"(try? JSONSerialization.data(withJSONObject: [$entries])) ?? Data()"
        s"""${pad}Task { @MainActor in
           |${pad2}guard let _url = URL(string: ${swiftStringLit(url)}) else { return }
           |${pad2}var _req = URLRequest(url: _url)
           |${pad2}_req.httpMethod = ${swiftStringLit(method.toUpperCase)}
           |${pad2}_req.httpBody = $bodyExpr
           |${pad2}do {
           |${pad3}let (_, _) = try await URLSession.shared.data(for: _req)
           |${pad3}${onSuccessTick.id} += 1
           |${pad2}} catch {}
           |${pad}}""".stripMargin
      case EventHandler.SetFieldToSignal(signal, fieldPath) =>
        s"${pad}${signal.id} = $fieldPath"
      case EventHandler.Simple(_) | EventHandler.WithEvent(_) =>
        s"${pad}// closure action (not serializable into generated Swift source)"

  // ── State declarations ────────────────────────────────────────────────────

  private def emitStateDecls(signals: List[SignalInitial], indent: Int): String =
    if signals.isEmpty then ""
    else
      val pad = " " * indent
      signals.map { s =>
        val (typeName, defaultExpr) = swiftTypeAndDefault(s.value)
        s"${pad}@State private var ${s.id}: $typeName = $defaultExpr"
      }.mkString("\n")

  private def emitFetchStateDecls(fetchSigs: List[FetchUrlSignal], indent: Int): String =
    if fetchSigs.isEmpty then ""
    else
      val pad = " " * indent
      fetchSigs.map {
        case fjs: FetchJsonSignal =>
          List(
            s"${pad}@State private var ${fjs.id}: ${fjs.modelTypeName}? = nil",
            s"${pad}@State private var ${fjs.id}_loading: Bool = false",
            s"${pad}@State private var ${fjs.id}_loaded: Bool = false",
            s"${pad}@State private var ${fjs.id}_error: String = \"\"",
          ).mkString("\n")
        case fs =>
          s"${pad}@State private var ${fs.id}: String = \"\""
      }.mkString("\n")

  // ── Signal collection ─────────────────────────────────────────────────────

  private[swiftui] final case class SignalInitial(id: String, value: Any, isList: Boolean = false)

  private[swiftui] def collectSignals(view: View[?]): List[SignalInitial] =
    def add(acc: Map[String, SignalInitial], sig: ReactiveSignal[?]): Map[String, SignalInitial] =
      acc.updatedWith(sig.id) { case e @ Some(_) => e; case None => Some(SignalInitial(sig.id, sig.apply())) }
    def addList(acc: Map[String, SignalInitial], sig: ReactiveSignalList[?]): Map[String, SignalInitial] =
      acc.updatedWith(sig.id) { case e @ Some(_) => e; case None => Some(SignalInitial(sig.id, sig.initial, isList = true)) }
    def fromAction(acc: Map[String, SignalInitial], a: EventHandler): Map[String, SignalInitial] =
      a match
        case EventHandler.SetSignalLiteral(s, _)  => add(acc, s)
        case EventHandler.IncrementSignal(s, _)   => add(acc, s)
        case EventHandler.ToggleSignal(s)         => add(acc, s)
        case EventHandler.InputChange(s)          => add(acc, s)
        case EventHandler.PushSignalLiteral(l, _) => addList(acc, l)
        case EventHandler.ClearSignalList(l)      => addList(acc, l)
        case EventHandler.RemoveSelfFromList(l)    => addList(acc, l)
        case EventHandler.DeleteItem(_, _, s, _)  => add(acc, s)
        case _                                    => acc
    def loop(acc: Map[String, SignalInitial], v: View[?]): Map[String, SignalInitial] =
      v match
        case View.SignalText(s, _)               => add(acc, s)
        case View.Button(_, a, _, _)             => fromAction(acc, a)
        case View.TextInput(s, _, _, _, _)       => add(acc, s)
        case View.Toggle(s, _, _)                => add(acc, s)
        case View.Slider(s, _, _, _, _)          => add(acc, s)
        case View.Picker(_, s, _, _)             => add(acc, s)
        case View.Sheet(ch, s)                   => loop(add(acc, s), ch)
        case View.AlertDialog(_, _, _, s)        => add(acc, s)
        case View.TabBar(tabs, cur, _)           => tabs.foldLeft(add(acc, cur))((a, t) => loop(a, t.content))
        case View.NavigationStack(routes, cur, _) => routes.values.foldLeft(add(acc, cur))((a, f) => loop(a, f()))
        case View.FormField(_, s, _, _)          => add(acc, s)
        case View.Column(ch, _, _, _)            => ch.foldLeft(acc)(loop)
        case View.Row(ch, _, _, _)               => ch.foldLeft(acc)(loop)
        case View.Stack(ch, _)                   => ch.foldLeft(acc)(loop)
        case View.ScrollView(ch, _, _)           => loop(acc, ch)
        case View.Fragment(ch)                   => ch.foldLeft(acc)(loop)
        case View.Show(_, t, f)                  => loop(loop(acc, t()), f())
        case View.ShowSignal(s, t, f)            => loop(loop(add(acc, s), t), f)
        case View.For(items, r)                  => items().foldLeft(acc)((a, i) => loop(a, r(i)))
        case View.ForSignal(l, _, _, tmpl)       =>
          val withList = addList(acc, l)
          tmpl.map(loop(withList, _)).getOrElse(withList)
        case View.Form(ch, a, _)                 => loop(fromAction(acc, a), ch)
        case View.Styled(ch, _)                  => loop(acc, ch)
        case View.Animated(ch, _, _)             => loop(acc, ch)
        case View.Adaptive(web, desk, mob, fb)   =>
          List(web, desk, mob).flatten.foldLeft(loop(acc, fb))(loop)
        case View.ModelView(_, _, tmpl, _)       => loop(acc, tmpl)
        case View.ForModel(_, _, _, tmpl, _)     => loop(acc, tmpl)
        case dt: View.DataTable =>
          dt.actions.foldLeft(acc) {
            case (a, RowActionDef.RowDelete(_, _, tick, _))        => add(a, tick)
            case (a, RowActionDef.RowPost(_, _, _, _, tick, _))    => add(a, tick)
            case (a, RowActionDef.RowLink(_, sig, _))              => add(a, sig)
            case (a, RowActionDef.RowInlineEdit(_, _, _, tick, _)) => add(a, tick)
          }
        case _ => acc
    loop(Map.empty, view).values.toList.sortBy(_.id)

  // ── FetchUrlSignal collection ─────────────────────────────────────────────

  private[swiftui] def collectFetchSignals(view: View[?]): List[FetchUrlSignal] =
    val seen = scala.collection.mutable.LinkedHashMap.empty[String, FetchUrlSignal]
    def walk(v: View[?]): Unit = v match
      case View.SignalText(fs: FetchUrlSignal, _)          => seen(fs.id) = fs
      case View.TextInput(fs: FetchUrlSignal, _, _, _, _)  => seen(fs.id) = fs
      case View.Column(ch, _, _, _)                        => ch.foreach(walk)
      case View.Row(ch, _, _, _)                           => ch.foreach(walk)
      case View.Stack(ch, _)                               => ch.foreach(walk)
      case View.ScrollView(ch, _, _)                       => walk(ch)
      case View.Fragment(ch)                               => ch.foreach(walk)
      case View.Show(_, t, f)                              => walk(t()); walk(f())
      case View.ShowSignal(_, t, f)                        => walk(t); walk(f)
      case View.For(items, r)                              => items().foreach(i => walk(r(i)))
      case View.ForSignal(_, _, _, tmpl)                   => tmpl.foreach(walk)
      case View.Form(ch, _, _)                             => walk(ch)
      case View.Styled(ch, _)                              => walk(ch)
      case View.Animated(ch, _, _)                         => walk(ch)
      case View.Sheet(ch, _)                               => walk(ch)
      case View.SafeArea(ch, _)                            => walk(ch)
      case View.KeyboardAvoiding(ch)                       => walk(ch)
      case View.TabBar(tabs, _, _)                         => tabs.foreach(t => walk(t.content))
      case View.NavigationStack(routes, _, _)              => routes.values.foreach(f => walk(f()))
      case View.LazyList(items, render, _, _)              => items().foreach(i => walk(render(i)))
      case View.LazyGrid(items, render, _, _, _)           => items().foreach(i => walk(render(i)))
      case View.Adaptive(web, desk, mob, fb)               =>
        List(web, desk, mob).flatten.foreach(walk); walk(fb)
      case View.ModelView(signal, _, template, _)          =>
        seen(signal.id) = signal; walk(template)
      case View.ForModel(_, _, _, template, _)             => walk(template)
      case _ => ()
    walk(view)
    seen.values.toList

  // ── FetchAction Task emit ────────────────────────────────────────────────

  private def emitFetchTask(
    method:         String,
    url:            String,
    bodyId:         String,
    onSuccessTickId: String,
    clearBody:      Boolean,
    indent:         Int
  ): String =
    val pad  = " " * indent
    val pad2 = " " * (indent + 4)
    val pad3 = " " * (indent + 8)
    val urlLine    = s"""${pad2}guard let _url = URL(string: ${swiftStringLit(url)}) else { return }"""
    val successLine = s"${pad3}$onSuccessTickId += 1"
    val clearLine   = if clearBody then s"\n${pad3}$bodyId = \"\"" else ""
    val httpMethod  = method.toUpperCase
    if httpMethod == "GET" || httpMethod == "DELETE" then
      s"""${pad}Task { @MainActor in
         |$urlLine
         |${pad2}do {
         |${pad3}let (_, _) = try await URLSession.shared.data(from: _url)
         |$successLine$clearLine
         |${pad2}} catch {}
         |${pad}}""".stripMargin
    else
      s"""${pad}Task { @MainActor in
         |$urlLine
         |${pad2}var _req = URLRequest(url: _url)
         |${pad2}_req.httpMethod = ${swiftStringLit(httpMethod)}
         |${pad2}_req.setValue("application/json", forHTTPHeaderField: "Content-Type")
         |${pad2}_req.httpBody = $bodyId.data(using: .utf8)
         |${pad2}do {
         |${pad3}let (_, _) = try await URLSession.shared.data(for: _req)
         |$successLine$clearLine
         |${pad2}} catch {}
         |${pad}}""".stripMargin

  // ── FetchUrlSignal modifiers + methods ───────────────────────────────────

  private def emitFetchModifiers(fetchSigs: List[FetchUrlSignal], indent: Int): String =
    if fetchSigs.isEmpty then ""
    else
      val pad = " " * indent
      val mods = fetchSigs.flatMap { fs =>
        val fnName = s"_load_${fs.id}"
        List(
          s"${pad}.task { await $fnName() }",
          s"${pad}.onChange(of: ${fs.tickId}) { _, _ in Task { @MainActor in await $fnName() } }"
        )
      }
      mods.mkString("\n")

  private def headersBlock(headersId: Option[String], reqVar: String, indent: Int): String =
    headersId match
      case None => ""
      case Some(hid) =>
        val pad = " " * indent
        s"""${pad}var $reqVar = URLRequest(url: _url)
           |${pad}if let _hData = $hid.data(using: .utf8),
           |${pad}   let _hDict = try? JSONSerialization.jsonObject(with: _hData) as? [String: String] {
           |${pad}    for (k, v) in _hDict { $reqVar.setValue(v, forHTTPHeaderField: k) }
           |${pad}}""".stripMargin

  private def fetchDataLine(headersId: Option[String], reqVar: String, indent: Int): String =
    val pad = " " * indent
    if headersId.isDefined then s"${pad}let (data, _) = try await URLSession.shared.data(for: $reqVar)"
    else                        s"${pad}let (data, _) = try await URLSession.shared.data(from: _url)"

  private def emitFetchMethods(fetchSigs: List[FetchUrlSignal], indent: Int): String =
    if fetchSigs.isEmpty then ""
    else
      val pad  = " " * indent
      val pad2 = " " * (indent + 4)
      val pad3 = " " * (indent + 8)
      fetchSigs.map {
        case fjs: FetchJsonSignal =>
          val hBlock = headersBlock(fjs.headersId, "_req", indent + 4)
          val hSep   = if hBlock.nonEmpty then "\n" + hBlock + "\n" else ""
          val fetch  = fetchDataLine(fjs.headersId, "_req", indent + 8)
          s"""${pad}private func _load_${fjs.id}() async {
             |${pad2}guard let _url = URL(string: ${swiftStringLit(fjs.fetchUrl)}) else { return }
             |${pad2}${fjs.id}_loading = true
             |${pad2}${fjs.id}_error = ""$hSep
             |${pad2}do {
             |$fetch
             |${pad3}${fjs.id} = try JSONDecoder().decode(${fjs.modelTypeName}.self, from: data)
             |${pad3}${fjs.id}_loaded = true
             |${pad2}} catch {
             |${pad3}${fjs.id}_error = error.localizedDescription
             |${pad2}}
             |${pad2}${fjs.id}_loading = false
             |${pad}}
             |""".stripMargin
        case fs =>
          val hBlock = headersBlock(fs.headersId, "_req", indent + 4)
          val hSep   = if hBlock.nonEmpty then "\n" + hBlock + "\n" else ""
          val fetch  = fetchDataLine(fs.headersId, "_req", indent + 8)
          s"""${pad}private func _load_${fs.id}() async {
             |${pad2}guard let _url = URL(string: ${swiftStringLit(fs.fetchUrl)}) else { return }$hSep
             |${pad2}do {
             |$fetch
             |${pad3}${fs.id} = String(data: data, encoding: .utf8) ?? ""
             |${pad2}} catch {}
             |${pad}}
             |""".stripMargin
      }.mkString("\n")

  // ── DataTable signal collection + state/modifier/method emit ────────────

  private[swiftui] def collectDataTableSignals(view: View[?]): List[View.DataTable] =
    val seen = scala.collection.mutable.LinkedHashMap.empty[String, View.DataTable]
    def walk(v: View[?]): Unit = v match
      case dt: View.DataTable =>
        dt.source match
          case TableDataSource.Remote(sig) => seen(sig.id) = dt
          case _ => ()
      case View.Column(ch, _, _, _)                     => ch.foreach(walk)
      case View.Row(ch, _, _, _)                        => ch.foreach(walk)
      case View.Stack(ch, _)                            => ch.foreach(walk)
      case View.ScrollView(ch, _, _)                    => walk(ch)
      case View.Fragment(ch)                            => ch.foreach(walk)
      case View.Show(_, t, f)                           => walk(t()); walk(f())
      case View.ShowSignal(_, t, f)                     => walk(t); walk(f)
      case View.For(items, r)                           => items().foreach(i => walk(r(i)))
      case View.ForSignal(_, _, _, tmpl)                => tmpl.foreach(walk)
      case View.Form(ch, _, _)                          => walk(ch)
      case View.Styled(ch, _)                           => walk(ch)
      case View.Animated(ch, _, _)                      => walk(ch)
      case View.Sheet(ch, _)                            => walk(ch)
      case View.SafeArea(ch, _)                         => walk(ch)
      case View.KeyboardAvoiding(ch)                    => walk(ch)
      case View.TabBar(tabs, _, _)                      => tabs.foreach(t => walk(t.content))
      case View.NavigationStack(routes, _, _)           => routes.values.foreach(f => walk(f()))
      case View.LazyList(items, render, _, _)           => items().foreach(i => walk(render(i)))
      case View.LazyGrid(items, render, _, _, _)        => items().foreach(i => walk(render(i)))
      case View.Adaptive(web, desk, mob, fb)            =>
        List(web, desk, mob).flatten.foreach(walk); walk(fb)
      case View.ModelView(_, _, template, _)            => walk(template)
      case View.ForModel(_, _, _, template, _)          => walk(template)
      case _                                            => ()
    walk(view)
    seen.values.toList

  private def emitDataTableStateDecls(dts: List[View.DataTable], indent: Int): String =
    if dts.isEmpty then ""
    else
      val pad = " " * indent
      dts.flatMap { dt =>
        dt.source match
          case TableDataSource.Remote(sig) =>
            val rowState  = s"${pad}@State private var ${sig.id}: [[String: Any]] = []"
            val editState = if dt.columns.exists(_.editAction.isDefined) then
              Some(s"${pad}@State private var _edit_${sig.id}: [String: String] = [:]")
            else None
            rowState :: editState.toList
          case _ => Nil
      }.mkString("\n")

  private def emitDataTableModifiers(dts: List[View.DataTable], indent: Int): String =
    if dts.isEmpty then ""
    else
      val pad = " " * indent
      dts.flatMap { dt =>
        dt.source match
          case TableDataSource.Remote(sig) =>
            val fn      = s"_load_dt_${sig.id}"
            val tickIds = scala.collection.mutable.LinkedHashSet(sig.tickId)
            dt.actions.foreach {
              case RowActionDef.RowDelete(_, _, tick, _)        => tickIds += tick.id
              case RowActionDef.RowPost(_, _, _, _, tick, _)    => tickIds += tick.id
              case RowActionDef.RowInlineEdit(_, _, _, tick, _) => tickIds += tick.id
              case _                                            => ()
            }
            dt.columns.foreach(c => c.editAction.foreach(ea => tickIds += ea.onSuccessTick.id))
            (s"${pad}.task { await $fn() }" ::
              tickIds.map(tid => s"${pad}.onChange(of: $tid) { _, _ in Task { @MainActor in await $fn() } }").toList)
          case _ => Nil
      }.mkString("\n")

  private def emitDataTableMethods(dts: List[View.DataTable], indent: Int): String =
    if dts.isEmpty then ""
    else
      val pad  = " " * indent
      val pad2 = " " * (indent + 4)
      val pad3 = " " * (indent + 8)
      dts.flatMap { dt =>
        dt.source match
          case TableDataSource.Remote(sig) =>
            val hBlock    = headersBlock(sig.headersId, "_req", indent + 4)
            val hSep      = if hBlock.nonEmpty then "\n" + hBlock + "\n" else ""
            val fetch     = fetchDataLine(sig.headersId, "_req", indent + 8)
            val hasEditable = dt.columns.exists(_.editAction.isDefined)
            val clearBuf  = if hasEditable then s"\n${pad3}_edit_${sig.id} = [:]" else ""
            Some(s"""${pad}private func _load_dt_${sig.id}() async {
               |${pad2}guard let _url = URL(string: ${swiftStringLit(sig.fetchUrl)}) else { return }$hSep
               |${pad2}do {
               |$fetch
               |${pad3}if let json = try JSONSerialization.jsonObject(with: data) as? [[String: Any]] {$clearBuf
               |${pad3}    ${sig.id} = json
               |${pad3}}
               |${pad2}} catch {}
               |${pad}}
               |""".stripMargin)
          case _ => None
      }.mkString("\n")

  // ── Helpers ───────────────────────────────────────────────────────────────

  private def textOf(view: View[?]): String =
    view match
      case View.Text(c, _)      => c()
      case View.TextNode(v)     => v()
      case View.SignalText(s,_) => String.valueOf(s.apply())
      case View.Fragment(ch)    => ch.map(textOf).mkString
      case View.Styled(ch, _)   => textOf(ch)
      case View.Icon(n, _)      => n
      case _                    => "Button"

  def swiftIdent(name: String): String =
    name.filter(c => c.isLetterOrDigit || c == '_').capitalize match
      case ""  => "App"
      case str => if str.head.isDigit then s"App$str" else str

  private val swiftKeywords = Set(
    "as","associatedtype","break","case","catch","class","continue","default","defer",
    "deinit","do","else","enum","extension","fallthrough","false","fileprivate","for",
    "func","guard","if","import","in","init","inout","internal","is","lazy","let",
    "mutating","nil","nonmutating","open","operator","override","package","precedencegroup",
    "private","protocol","public","repeat","rethrows","return","self","Self","static",
    "struct","subscript","super","switch","throw","throws","true","try","type","typealias",
    "var","where","while"
  )

  private def escapeSwiftIdent(name: String): String =
    if swiftKeywords.contains(name) then s"`$name`" else name

  private def swiftStringLit(value: String): String =
    "\"" + swiftString(value) + "\""

  def swiftString(value: String): String =
    value.flatMap {
      case '\\' => "\\\\"
      case '"'  => "\\\""
      case '\n' => "\\n"
      case '\r' => "\\r"
      case '\t' => "\\t"
      case c if c.isControl => f"\\u{${c.toInt}%04X}"
      case c    => c.toString
    }

  private def swiftLiteral(value: Any): String =
    value match
      case null       => "nil"
      case s: String  => swiftStringLit(s)
      case b: Boolean => if b then "true" else "false"
      case n: Int     => n.toString
      case n: Long    => n.toString
      case n: Float   => n.toString
      case n: Double  => n.toString
      case other      => swiftStringLit(other.toString)

  private def swiftTypeAndDefault(value: Any): (String, String) =
    value match
      case b: Boolean  => ("Bool",   if b then "true" else "false")
      case _: Int      => ("Int",    value.toString)
      case _: Long     => ("Int",    value.toString)
      case _: Double   => ("Double", value.toString)
      case _: Float    => ("Double", value.toString)
      case s: String   => ("String", swiftStringLit(s))
      case _: Seq[?]   => ("[String]", "[]")
      case _           => ("String", "\"\"")

  private def toSwiftColor(color: Color): Option[String] =
    color match
      case Color.Hex(v) =>
        val hex = v.stripPrefix("#")
        if hex.length == 6 then
          val r = Integer.parseInt(hex.substring(0, 2), 16) / 255.0
          val g = Integer.parseInt(hex.substring(2, 4), 16) / 255.0
          val b = Integer.parseInt(hex.substring(4, 6), 16) / 255.0
          Some(f"Color(red: $r%.3f, green: $g%.3f, blue: $b%.3f)")
        else None
      case Color.Rgb(r, g, b)     => Some(f"Color(red: ${r/255.0}%.3f, green: ${g/255.0}%.3f, blue: ${b/255.0}%.3f)")
      case Color.Rgba(r, g, b, a) => Some(f"Color(red: ${r/255.0}%.3f, green: ${g/255.0}%.3f, blue: ${b/255.0}%.3f, opacity: $a%.3f)")
      case Color.Named("red")     => Some("Color.red")
      case Color.Named("blue")    => Some("Color.blue")
      case Color.Named("green")   => Some("Color.green")
      case Color.Named("black")   => Some("Color.black")
      case Color.Named("white")   => Some("Color.white")
      case Color.Named("gray") | Color.Named("grey") => Some("Color.gray")
      case Color.Named("orange")  => Some("Color.orange")
      case Color.Named("yellow")  => Some("Color.yellow")
      case Color.Named("purple")  => Some("Color.purple")
      case Color.Named("pink")    => Some("Color.pink")
      case Color.System(token)    => Some(systemColorToken(token))
      case _                      => None

  private def systemColorToken(token: String): String =
    token match
      case "background"      => "Color(UIColor.systemBackground)"
      case "surface"         => "Color(UIColor.secondarySystemBackground)"
      case "primary"         => "Color.primary"
      case "secondary"       => "Color.secondary"
      case "accent"          => "Color.accentColor"
      case "error"           => "Color.red"
      case "on-background"   => "Color.primary"
      case "on-surface"      => "Color.primary"
      case "on-primary"      => "Color.white"
      case "on-secondary"    => "Color.white"
      case "outline"         => "Color(UIColor.separator)"
      case "outline-variant" => "Color(UIColor.opaqueSeparator)"
      case _                 => "Color.primary"

  private def weightToSwift(weight: FontWeight): String =
    weight match
      case FontWeight.Thin       => ".ultraLight"
      case FontWeight.ExtraLight => ".light"
      case FontWeight.Light      => ".light"
      case FontWeight.Regular    => ".regular"
      case FontWeight.Medium     => ".medium"
      case FontWeight.SemiBold   => ".semibold"
      case FontWeight.Bold       => ".bold"
      case FontWeight.ExtraBold  => ".heavy"
      case FontWeight.Black      => ".black"
      case FontWeight.Custom(v)  => if v >= 700 then ".bold" else if v >= 600 then ".semibold" else ".regular"

  private def hAlignToSwift(align: HAlign): String =
    align match
      case HAlign.Start   => ".leading"
      case HAlign.Center  => ".center"
      case HAlign.End     => ".trailing"
      case HAlign.Stretch => ".center"

  private def vAlignToSwift(align: VAlign): String =
    align match
      case VAlign.Top     => ".top"
      case VAlign.Center  => ".center"
      case VAlign.Bottom  => ".bottom"
      case VAlign.Stretch => ".center"


  // ── Signal bridge (v1.51.5c) ──────────────────────────────────────────────

  /** Generates `SignalBridge.swift` — a Combine-backed `ObservableSignal<T>` class
   *  providing platform-native equivalents of `Source.signal(sig)` and
   *  `sig.bind(source)` for generated SwiftUI apps. */
  def signalBridgeSwift(appName: String): String =
    s"""// Generated by ScalaScript — SignalBridge for ${swiftString(appName)} (v1.51.5c)
       |// Platform-native stream/signal bridge matching interpreter Source.signal + sig.bind.
       |import Combine
       |import Foundation
       |
       |// ObservableSignal: Combine-backed reactive signal for ScalaScript SwiftUI apps.
       |// Usage:
       |//   @StateObject var count = ObservableSignal(id: "count", 0)
       |//   count.value          // read
       |//   count.value = 42     // write
       |//   count.asStream       // Source.signal(count) equivalent
       |//   count.bind(src)      // sig.bind(source) equivalent
       |@MainActor
       |public final class ObservableSignal<T: Sendable>: ObservableObject {
       |    @Published public var value: T
       |    public let id: String
       |    private var bindTask: Task<Void, Never>?
       |
       |    public init(id: String, _ initial: T) {
       |        self.id = id
       |        self.value = initial
       |    }
       |
       |    /// Emits the current value and each subsequent update as an `AsyncStream`.
       |    /// Platform-native equivalent of `Source.signal(sig)`.
       |    public var asStream: AsyncStream<T> {
       |        AsyncStream { continuation in
       |            continuation.yield(self.value)
       |            let sub = self.$$value.sink { continuation.yield($$0) }
       |            continuation.onTermination = { _ in sub.cancel() }
       |        }
       |    }
       |
       |    /// Subscribes to `source` and writes each emitted value into this signal.
       |    /// Platform-native equivalent of `sig.bind(source)`. Last-value-wins.
       |    public func bind(source: AsyncStream<T>) {
       |        bindTask?.cancel()
       |        bindTask = Task { @MainActor [weak self] in
       |            for await v in source { self?.value = v }
       |        }
       |    }
       |
       |    deinit { bindTask?.cancel() }
       |}
       |""".stripMargin
