package ssc.swift

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Path}

import ssc.{Arm, Const, Def, Program, Term}

final case class SwiftPackage(files: Vector[(String, String)]):
  def writeTo(root: Path): Unit =
    files.foreach { (relative, content) =>
      val path = root.resolve(relative)
      Files.createDirectories(path.getParent)
      Files.writeString(path, content, StandardCharsets.UTF_8)
    }

object SwiftBackend:
  private val builtinGlobals = Set("print", "println")

  // This first executable slice intentionally freezes the structural runtime
  // vocabulary. Portable Decimal/effect primitives are added to this same
  // table/runtime in the next green sub-slice; generation fails honestly until
  // then instead of emitting a latent no-op.
  private val supportedPrimitives = Set(
    "i.add", "i.sub", "i.mul", "i.div", "i.mod", "i.neg",
    "i.and", "i.or", "i.xor", "i.not", "i.shl", "i.shr", "i.ushr",
    "i.eq", "i.lt", "i.le", "i.gt", "i.ge", "not",
    "f.add", "f.sub", "f.mul", "f.div", "f.neg",
    "f.sqrt", "f.floor", "f.ceil", "f.round", "f.trunc",
    "f.eq", "f.lt", "f.le", "f.gt", "f.ge", "f.isNaN", "f.isInf",
    "i->f", "f->i", "i->str", "f->str",
    "slen", "sconcat", "sslice", "scodeAt", "sfromCodes",
    "seq", "scmp", "sindexOf", "str.trim", "str.replace", "str.lines",
    "blen", "bget", "bslice", "bconcat", "str->utf8", "utf8->str",
    "tagOf", "arity", "fieldAt", "__isTag__",
    "cell.new", "cell.get", "cell.set", "lcell.new", "lcell.get", "lcell.set",
    "map.new", "map.get", "map.put", "map.has", "map.del", "map.keys", "map.size",
    "arr.new", "arr.len", "arr.get", "arr.set", "arr.push", "arr.pop", "arr.slice",
    "__mk_arr__", "__mk_map__", "__arith__", "__unary__",
    "io.print", "io.println",
  )

  def generate(program: Program, packageName: String = "SscApp"): SwiftPackage =
    validate(program)
    val product = safeProductName(packageName)
    SwiftPackage(Vector(
      "Package.swift" -> packageManifest(product),
      "Sources/AppCore/SscRuntime.swift" -> SwiftRuntime.source,
      "Sources/AppCore/GeneratedProgram.swift" -> generatedProgram(program),
      s"Sources/$product/main.swift" ->
        "import AppCore\n\nSscGeneratedProgram.run()\n",
    ))

  private def safeProductName(raw: String): String =
    val cleaned = raw.replaceAll("[^A-Za-z0-9_]", "_")
    val nonEmpty = if cleaned.isEmpty then "SscApp" else cleaned
    if nonEmpty.head.isDigit then s"Ssc_$nonEmpty" else nonEmpty

  private def packageManifest(product: String): String =
    s"""// swift-tools-version: 6.0
       |import PackageDescription
       |
       |let package = Package(
       |    name: ${swiftString(product)},
       |    platforms: [.macOS(.v13)],
       |    products: [
       |        .library(name: "AppCore", targets: ["AppCore"]),
       |        .executable(name: ${swiftString(product)}, targets: [${swiftString(product)}])
       |    ],
       |    targets: [
       |        .target(name: "AppCore"),
       |        .executableTarget(name: ${swiftString(product)}, dependencies: ["AppCore"])
       |    ]
       |)
       |""".stripMargin

  private def generatedProgram(program: Program): String =
    s"""// Generated by ScalaScript v2 SwiftBackend. DO NOT EDIT.
       |import Foundation
       |
       |public enum SscGeneratedProgram {
       |    public static func run() {
       |        let program = ${emitProgram(program)}
       |        SscRuntime.execute(program)
       |    }
       |}
       |""".stripMargin

  private def emitProgram(program: Program): String =
    val defs = program.defs.map(emitDef).mkString("[", ", ", "]")
    s"SscProgram(definitions: $defs, entry: ${emitTerm(program.entry)})"

  private def emitDef(d: Def): String =
    s"SscDefinition(name: ${swiftString(d.name)}, body: ${emitTerm(d.body)})"

  private def emitArm(a: Arm): String =
    s"SscArm(tag: ${swiftString(a.tag)}, arity: ${a.arity}, body: ${emitTerm(a.body)})"

  private def emitTerm(term: Term): String = term match
    case Term.Lit(c) => s".literal(${emitConst(c)})"
    case Term.Local(i) => s".local($i)"
    case Term.Global(name) => s".global(${swiftString(name)})"
    case Term.Lam(arity, body) => s".lambda($arity, ${emitTerm(body)})"
    case Term.App(fn, args) => s".apply(${emitTerm(fn)}, ${emitTerms(args)})"
    case Term.Let(rhs, body) => s".letBindings(${emitTerms(rhs)}, ${emitTerm(body)})"
    case Term.LetRec(lams, body) => s".letRecursive(${emitTerms(lams)}, ${emitTerm(body)})"
    case Term.If(cond, ifTrue, ifFalse) =>
      s".ifThenElse(${emitTerm(cond)}, ${emitTerm(ifTrue)}, ${emitTerm(ifFalse)})"
    case Term.Ctor(tag, fields) => s".constructor(${swiftString(tag)}, ${emitTerms(fields)})"
    case Term.Match(scrutinee, arms, default) =>
      val as = arms.map(emitArm).mkString("[", ", ", "]")
      val d = default.map(emitTerm).map(t => s"Optional.some($t)").getOrElse("Optional.none")
      s".matchValue(${emitTerm(scrutinee)}, $as, $d)"
    case Term.Prim(op, args) => s".primitive(${swiftString(op)}, ${emitTerms(args)})"
    case Term.While(cond, body) => s".whileLoop(${emitTerm(cond)}, ${emitTerm(body)})"
    case Term.Seq(terms) => s".sequence(${emitTerms(terms)})"

  private def emitTerms(terms: List[Term]): String =
    terms.map(emitTerm).mkString("[", ", ", "]")

  private def emitConst(c: Const): String = c match
    case Const.CUnit => ".unit"
    case Const.CBool(value) => s".bool($value)"
    case Const.CInt(value) => s".int($value)"
    case Const.CBig(value) => s".big(${swiftString(value.toString)})"
    case Const.CFloat(value) if value.isNaN => ".float(Double.nan)"
    case Const.CFloat(value) if value == Double.PositiveInfinity => ".float(Double.infinity)"
    case Const.CFloat(value) if value == Double.NegativeInfinity => ".float(-Double.infinity)"
    case Const.CFloat(value) => s".float(${java.lang.Double.toString(value)})"
    case Const.CStr(value) => s".string(${swiftString(value)})"
    case Const.CBytes(value) => s".bytes(${value.map(_ & 0xff).mkString("[", ", ", "]")})"

  private def swiftString(value: String): String =
    val out = new StringBuilder("\"")
    value.foreach {
      case '"' => out ++= "\\\""
      case '\\' => out ++= "\\\\"
      case '\n' => out ++= "\\n"
      case '\r' => out ++= "\\r"
      case '\t' => out ++= "\\t"
      case c if c.isControl => out ++= f"\\u{${c.toInt}%x}"
      case c => out += c
    }
    out += '"'
    out.toString

  private def validate(program: Program): Unit =
    val definitions = program.defs.map(_.name).toSet
    program.defs.foreach(d => validateTerm(d.body, definitions))
    validateTerm(program.entry, definitions)

  private def validateTerm(term: Term, definitions: Set[String]): Unit = term match
    case Term.Lit(_) | Term.Local(_) => ()
    case Term.Global(name) if definitions(name) || builtinGlobals(name) => ()
    case Term.Global(name) => fail(s"unsupported global '$name'")
    case Term.Lam(_, body) => validateTerm(body, definitions)
    case Term.App(fn, args) => validateTerm(fn, definitions); args.foreach(validateTerm(_, definitions))
    case Term.Let(rhs, body) => rhs.foreach(validateTerm(_, definitions)); validateTerm(body, definitions)
    case Term.LetRec(lams, body) =>
      lams.foreach {
        case lam @ Term.Lam(_, _) => validateTerm(lam, definitions)
        case _ => fail("letrec binding must be a lambda")
      }
      validateTerm(body, definitions)
    case Term.If(c, t, e) => List(c, t, e).foreach(validateTerm(_, definitions))
    case Term.Ctor(_, fields) => fields.foreach(validateTerm(_, definitions))
    case Term.Match(scrut, arms, default) =>
      validateTerm(scrut, definitions)
      arms.foreach(a => validateTerm(a.body, definitions))
      default.foreach(validateTerm(_, definitions))
    case Term.Prim(op, args) =>
      if !supportedPrimitives(op) then fail(s"unsupported primitive '$op'")
      args.foreach(validateTerm(_, definitions))
    case Term.While(c, body) => validateTerm(c, definitions); validateTerm(body, definitions)
    case Term.Seq(terms) => terms.foreach(validateTerm(_, definitions))

  private def fail(message: String): Nothing =
    throw new IllegalArgumentException(s"swift backend: $message")
