package scalascript.codegen

import scalascript.ast.*

/** Generates a Scala 3 + Apache Beam program from a ScalaScript module.
 *
 *  Model: parallel to `FlinkGen` but targets the Apache Beam Java SDK.
 *
 *  DStream operator mappings (spec §9.5):
 *  - `Pipeline.create` + `InMemory.source(xs)` → driver-local shim (no runner required)
 *  - `.map(f)`          → `MapElements.via(SerializableFunction { ... })`
 *  - `.filter(p)`       → `Filter.by(...)`
 *  - `.keyBy(k)` + `.combinePerKey(f)` → `WithKeys.of(k)` → `Combine.perKey(f)`
 *  - `.window(fn)`      → `.apply(Window.into(fn))`
 *  - `.run(Backend.Beam, opts)` → `pipeline.run()` via runner from `extraProperties`
 *
 *  For bounded `InMemory.source` inputs the generated code falls back to
 *  driver-local `Seq[Any]` shim (same as Spark/Kafka/Flink shims).
 *  For live Beam pipelines the `beamRunner` option selects the runner
 *  (`DirectRunner` is the default; `FlinkRunner` requires a running cluster). */
object BeamGen:

  val DefaultBeamVersion:  String = "2.62.0"
  val DefaultScalaVersion: String = "3.7.1"
  val DefaultRunner:       String = "DirectRunner"

  def generate(
      module:   Module,
      baseDir:  Option[os.Path] = None,
      runner:   String          = DefaultRunner,
      flinkMaster: Option[String] = None,
      checkpointDir: Option[String] = None
  ): String =
    BeamGen(baseDir, runner, flinkMaster, checkpointDir).genModule(module)

  private[codegen] case class Block(src: String)

  def containsDStream(source: String): Boolean =
    source.contains("Pipeline.create")    ||
    source.contains("InMemory.source")    ||
    source.contains("Backend.Beam")       ||
    source.contains("Window.fixed")       ||
    source.contains("Window.sliding")     ||
    source.contains("Window.session")     ||
    source.contains("Window.global")      ||
    source.contains("WatermarkStrategy.") ||
    source.contains("Trigger.")

private class BeamGen(
    baseDir:      Option[os.Path],
    runner:       String,
    flinkMaster:  Option[String],
    checkpointDir: Option[String]
):
  import BeamGen.*
  import scala.collection.mutable

  private val importedFiles = mutable.Set.empty[String]

  def genModule(module: Module): String =
    val blocks        = collectBlocks(module.sections)
    val joinedUserSrc = blocks.map(_.src).mkString("\n")
    val needsDStream  = BeamGen.containsDStream(joinedUserSrc)

    val sb = StringBuilder()

    sb.append(s"// Generated by ScalaScript — Apache Beam $DefaultBeamVersion ($runner), Scala $DefaultScalaVersion\n")
    sb.append(s"// To run: scala-cli run this.scala\n")
    sb.append(s"//> using scala \"$DefaultScalaVersion\"\n")
    sb.append(s"//> using dep \"org.apache.beam:beam-sdks-java-core:$DefaultBeamVersion\"\n")
    runner match
      case r if r.contains("Flink") =>
        sb.append(s"//> using dep \"org.apache.beam:beam-runners-flink-1.20:$DefaultBeamVersion\"\n")
      case r if r.contains("Spark") =>
        sb.append(s"//> using dep \"org.apache.beam:beam-runners-spark-3:$DefaultBeamVersion\"\n")
      case _ =>
        sb.append(s"//> using dep \"org.apache.beam:beam-runners-direct-java:$DefaultBeamVersion\"\n")
    sb.append("\n")

    sb.append(beamImports)
    sb.append("\n")

    sb.append("@main def runBeamJob(): Unit =\n")
    sb.append(s"""  val _beamRunner     = "$runner"\n""")
    flinkMaster.foreach { m =>
      sb.append(s"""  val _beamFlinkMaster = "$m"\n""")
    }
    checkpointDir.foreach { d =>
      sb.append(s"""  val _beamCheckpointDir = "$d"\n""")
    }
    sb.append("\n")

    if needsDStream then sb.append(dstreamBeamShim)

    blocks.foreach { b =>
      sb.append(indentBlock(b.src).stripTrailing())
      sb.append("\n\n")
    }

    sb.toString()

  private def collectBlocks(sections: List[Section]): List[Block] =
    sections.flatMap { s =>
      val own = s.content.flatMap {
        case cb: Content.CodeBlock if Lang.isParseable(cb.lang) => List(Block(cb.source))
        case imp: Content.Import => inlineImport(imp.path)
        case _ => Nil
      }
      own ++ collectBlocks(s.subsections)
    }

  private def inlineImport(path: String): List[Block] =
    import scalascript.parser.Parser
    val base = baseDir.getOrElse(os.pwd)
    val resolved =
      try scalascript.imports.ImportResolver.resolve(path, base, Map.empty, None)
      catch case e: Throwable => throw new RuntimeException(s"Import $path: ${e.getMessage}")
    val key = resolved.toString
    if importedFiles.contains(key) then Nil
    else if !os.exists(resolved) then
      throw new RuntimeException(s"Import not found: $path")
    else
      importedFiles += key
      val importedModule = Parser.parse(os.read(resolved))
      val nested = new BeamGen(Some(resolved / os.up), runner, flinkMaster, checkpointDir)
      nested.importedFiles ++= importedFiles
      nested.collectBlocks(importedModule.sections)

  private def indentBlock(src: String): String =
    src.linesIterator
      .map(l => if l.nonEmpty then "  " + l else l)
      .mkString("\n")

  private val beamImports: String =
    """|import org.apache.beam.sdk.Pipeline as BeamPipeline
       |import org.apache.beam.sdk.options.PipelineOptionsFactory
       |import org.apache.beam.sdk.transforms.{MapElements, Filter, Combine, WithKeys, ParDo, DoFn}
       |import org.apache.beam.sdk.transforms.windowing.{Window as BeamWindow, FixedWindows, SlidingWindows, Sessions, GlobalWindows as BeamGlobalWindows}
       |import org.apache.beam.sdk.values.{PCollection, KV as BeamKV, TypeDescriptors}
       |import org.joda.time.Duration as JodaDuration
       |""".stripMargin

  // ── v2.1.5 — DStream Beam shim ───────────────────────────────────────────
  //
  // Emitted inside `@main def runBeamJob()` when DStream code is detected.
  // For bounded `InMemory.source` inputs: uses driver-local `Seq[Any]` (same as
  // Spark/Kafka/Flink shims).
  //
  // `Backend.Beam` and `Backend.Flink` are declared.  For live Beam pipelines,
  // `_beamRunner` is used to configure the PipelineOptions.
  private val dstreamBeamShim: String =
    """|
       |  // ── DStream Beam shim (v2.1.5) ──────────────────────────────────────
       |  // Full DStream pipeline DSL backed by driver-local Seq[Any] for bounded
       |  // InMemory sources.  Beam PCollection transforms for live sources are
       |  // configured via _beamRunner.
       |
       |  case class KV[K, V](key: K, value: V)
       |
       |  object Window:
       |    def fixed(ms: Long): Any           = ("fixed", ms)
       |    def sliding(ms: Long, p: Long): Any = ("sliding", ms, p)
       |    def session(gapMs: Long): Any       = ("session", gapMs)
       |    val global: Any                     = "global"
       |
       |  object Trigger:
       |    val afterWatermark: Any                   = "afterWatermark"
       |    def afterProcessingTime(ms: Long): Any    = ("afterProcessingTime", ms)
       |    def afterCount(n: Int): Any               = ("afterCount", n)
       |    def repeatedly(t: Any): Any               = ("repeatedly", t)
       |
       |  object WatermarkStrategy:
       |    val monotonicallyIncreasing: Any          = "monotonicallyIncreasing"
       |    val atEnd: Any                            = "atEnd"
       |    def boundedOutOfOrder(lagMs: Long): Any   = ("boundedOutOfOrder", lagMs)
       |
       |  object AccumulationMode:
       |    val Discarding: String   = "Discarding"
       |    val Accumulating: String = "Accumulating"
       |
       |  object Backend:
       |    val Direct: String       = "Direct"
       |    val Native: String       = "Native"
       |    val Spark: String        = "Spark"
       |    val KafkaStreams: String  = "KafkaStreams"
       |    val Flink: String        = "Flink"
       |    val Beam: String         = "Beam"
       |
       |  case class PipelineOptions(
       |    extraProperties: Map[String, String] = Map.empty,
       |    checkpointDir:   Option[String]      = None,
       |    parallelism:     Int                 = 1
       |  )
       |
       |  case class PipelineResult(state: String, __results: Seq[Any]):
       |    def waitUntilFinish(): String = state
       |    def cancel(): Unit = ()
       |
       |  type DSource[T] = Seq[T]
       |
       |  class DStream[T](private val _elems: Seq[T]):
       |    def map[U](f: T => U): DStream[U]          = new DStream(_elems.map(f))
       |    def filter(p: T => Boolean): DStream[T]     = new DStream(_elems.filter(p))
       |    def flatMap[U](f: T => IterableOnce[U]): DStream[U] =
       |      new DStream(_elems.flatMap(f))
       |    def keyBy[K](keyFn: T => K): DStream[KV[K, T]] =
       |      new DStream(_elems.map(v => KV(keyFn(v), v)))
       |    def combinePerKey(f: (Any, Any) => Any): DStream[Any] =
       |      val groups = collection.mutable.LinkedHashMap[Any, Any]()
       |      for elem <- _elems do elem match
       |        case KV(k, v) =>
       |          groups.get(k) match
       |            case Some(acc) => groups(k) = f(acc, v)
       |            case None      => groups(k) = v
       |        case _ =>
       |      new DStream(groups.toSeq.map((k, v) => KV(k, v)))
       |    def merge(other: DStream[T]): DStream[T]   = new DStream(_elems ++ other._elems)
       |    def mapWithTimestamp[U](f: (T, Long) => U): DStream[U] =
       |      new DStream(_elems.map(v => f(v, System.currentTimeMillis())))
       |    def assignTimestamps(f: T => Long): DStream[T] = this
       |    def window(fn: Any): DStream[T]             = this
       |    def withTrigger(t: Any): DStream[T]         = this
       |    def withAllowedLateness(d: Any): DStream[T] = this
       |    def withWatermark(s: Any): DStream[T]       = this
       |    def timerProcessing(dMs: Long)(f: Any => Iterable[Any]): DStream[Any] =
       |      val keys = collection.mutable.LinkedHashSet[Any]()
       |      for elem <- _elems do elem match
       |        case KV(k, _) => keys += k
       |        case _        =>
       |      new DStream(keys.toSeq.flatMap(k => f(k).map(v => KV(k, v))))
       |    def write(sink: Any): DStream[T]            = this
       |    def run(backend: Any): PipelineResult       = PipelineResult("Done", _elems)
       |    def runOpts(b: Any, o: Any): PipelineResult = PipelineResult("Done", _elems)
       |    def runToList(): Seq[T]                     = _elems
       |    def runFold[U](z: U)(f: (U, T) => U): U    = _elems.foldLeft(z)(f)
       |    def runForeach(f: T => Unit): Unit          = _elems.foreach(f)
       |    def runCount(): Long                        = _elems.size.toLong
       |    def requires(): List[String] =
       |      List("AtLeastOnce", "ExactlyOnce", "EventTime", "WatermarkPerfect",
       |           "KeyedState", "TimerProcessingTime", "WindowedJoins")
       |
       |  object Pipeline:
       |    def create(name: String): PipelineBuilder = new PipelineBuilder(name)
       |
       |  class PipelineBuilder(val name: String):
       |    def read[T](src: DSource[T]): DStream[T] = new DStream(src)
       |
       |  object InMemory:
       |    def source[T](elements: Seq[T]): DSource[T] = elements
       |    def sourceWithTimestamps[T](elements: Seq[(T, Long)]): DSource[T] =
       |      elements.map(_._1)
       |    def sink[T](): Any = ()
       |    def runAndCollect[T](stream: DStream[T]): Seq[T] = stream.runToList()
       |
       |  object DSource:
       |    def fromLocalSource[A](src: Any): DSource[A] = Seq.empty[A]
       |
       |  def runPipeline[T](stream: DStream[T], backend: Any): PipelineResult =
       |    stream.run(backend)
       |  def runPipelineOpts[T](stream: DStream[T], b: Any, o: Any): PipelineResult =
       |    stream.run(b)
       |
       |  // Beam pipeline factory — used when user code calls toBeamPipeline()
       |  def _createBeamPipeline(): BeamPipeline =
       |    val opts = PipelineOptionsFactory.fromArgs(s"--runner=$$_beamRunner").create()
       |    BeamPipeline.create(opts)
       |
       |""".stripMargin
