package scalascript.frontend.react

import scala.annotation.nowarn
import scalascript.frontend.*
import scalascript.frontend.FetchJsonSignal

/** Two-pass emit:
 *
 *    1. **Collect signals.**  Walk the entire View tree, gathering
 *       every `ReactiveSignal` referenced by `SignalText`, by
 *       `IncrementSignal`, or by `SetSignalLiteral`.  These become
 *       `useState` calls hoisted to the top of the App function.
 *
 *    2. **Emit expression tree.**  Walk again, this time producing
 *       a single nested `React.createElement(...)` expression that
 *       returns the View.  No imperative DOM ops — React handles
 *       reconciliation.
 *
 *  Naming convention for hoisted state: signal with `jsName="count"`
 *  becomes `[count, setCount]` (camelCase setter).  Duplicate
 *  names with different initial values is a hard error (same
 *  contract as the custom backend).
 *
 *  Pure-expression output is on purpose — React's mental model
 *  is "component is a function from props to a tree."  Imperative
 *  side-effects would be wrong (they'd run during render). */
@nowarn("cat=deprecation")
private[react] object ReactEmitter:

  def emit(root: View[?]): String =
    val signals      = collectSignals(root)
    val lists           = collectLists(root)
    val refs            = collectRefs(root)
    val fetchSignals    = collectFetchSignals(root)
    val dataTableSigs   = collectDataTableSignals(root)
    val sb = new StringBuilder
    sb ++= "// Generated by ScalaScript v1.18 — frontend-react Phase A3 / A2e / A6.\n"
    sb ++= "// Signals + lists + DomRefs + Portals lower to useState / useRef / createPortal.\n"
    sb ++= "(function() {\n"
    sb ++= "  const { useState, useRef, useEffect, createElement: h, Fragment } = React;\n"
    sb ++= "  function App() {\n"
    signals.foreach { (name, initial) =>
      val setter = setterName(name)
      sb ++= s"    const [$name, $setter] = useState($initial);\n"
    }
    lists.foreach { (name, initial) =>
      val setter = setterName(name)
      sb ++= s"    const [$name, $setter] = useState($initial);\n"
    }
    // DataTable array state — useState([]) per DataTable signal.
    dataTableSigs.foreach { sig =>
      val setter = setterName(sig.id)
      sb ++= s"    const [${sig.id}, $setter] = useState([]);\n"
    }
    // A6 — each DomRef gets a useRef(null) hoisted at the top of App.
    // Expose on window so imperative user JS can read <name>.current.
    refs.foreach { name =>
      sb ++= s"    const $name = useRef(null);\n"
      sb ++= s"    if (typeof window !== 'undefined') window[${jsString(name)}] = $name;\n"
    }
    // FetchJsonSignal typed state: null + companion loading/loaded/error vars.
    fetchSignals.collect { case fjs: FetchJsonSignal => fjs }.foreach { fjs =>
      sb ++= s"    const [${fjs.id}, ${setterName(fjs.id)}] = useState(null);\n"
      sb ++= s"    const [${fjs.id}_loading, ${setterName(s"${fjs.id}_loading")}] = useState(false);\n"
      sb ++= s"    const [${fjs.id}_loaded, ${setterName(s"${fjs.id}_loaded")}] = useState(false);\n"
      sb ++= s"    const [${fjs.id}_error, ${setterName(s"${fjs.id}_error")}] = useState(\"\");\n"
    }
    // Fetch signals: mount-fetch + tick-driven re-fetch via useEffect.
    fetchSignals.foreach { fs =>
      val setter = setterName(fs.id)
      val urlJs  = jsString(fs.fetchUrl)
      fs match
        case fjs: FetchJsonSignal =>
          sb ++= s"    useEffect(() => { fetch($urlJs).then(r => r.json()).then(t => $setter(t)); }, []);\n"
          sb ++= s"    useEffect(() => { if (${fjs.tickId} > 0) fetch($urlJs).then(r => r.json()).then(t => $setter(t)); }, [${fjs.tickId}]);\n"
        case _ =>
          sb ++= s"    useEffect(() => { fetch($urlJs).then(r => r.text()).then(t => $setter(t)); }, []);\n"
          sb ++= s"    useEffect(() => { if (${fs.tickId} > 0) fetch($urlJs).then(r => r.text()).then(t => $setter(t)); }, [${fs.tickId}]);\n"
    }
    // DataTable: mount-fetch + tick-driven re-fetch, parsed as JSON array.
    dataTableSigs.foreach { sig =>
      val setter   = setterName(sig.id)
      val urlJs    = jsString(sig.fetchUrl)
      val tickName = sig.tickId
      sb ++= s"    useEffect(() => { fetch($urlJs).then(r => r.json()).then(data => $setter(data)); }, []);\n"
      sb ++= s"    useEffect(() => { if ($tickName > 0) fetch($urlJs).then(r => r.json()).then(data => $setter(data)); }, [$tickName]);\n"
    }
    sb ++= "    return "
    sb ++= renderView(root)
    sb ++= ";\n"
    sb ++= "  }\n"
    sb ++= "  const root = ReactDOM.createRoot(document.getElementById('app'));\n"
    sb ++= "  root.render(h(App));\n"
    sb ++= "})();\n"
    sb.toString

  /** First pass — DFS over the View tree harvesting reactive
   *  signals.  Returns a LinkedHashMap so emit order is stable
   *  (first occurrence wins for ordering; duplicate names with
   *  different initial values throw). */
  private def collectSignals(view: View[?]): scala.collection.mutable.LinkedHashMap[String, String] =
    val acc = scala.collection.mutable.LinkedHashMap.empty[String, String]
    def register(signal: ReactiveSignal[?]): Unit =
      val name = signal.id
      if !name.matches("[A-Za-z_][A-Za-z0-9_]*") then
        throw new IllegalArgumentException(
          s"ReactiveSignal id '$name' must match [A-Za-z_][A-Za-z0-9_]*."
        )
      val initJs = jsLiteral(signal())
      acc.get(name) match
        case Some(existing) if existing != initJs =>
          throw new IllegalArgumentException(
            s"ReactiveSignal id '$name' registered twice with different " +
            s"initial values ($existing vs $initJs)."
          )
        case _ => acc.update(name, initJs)
    def walk(v: View[?]): Unit = v match
      case View.SignalText(signal, _) =>
        register(signal)
      case View.Element(_, attrs, events, children) =>
        attrs.values.foreach {
          case AttrValue.Reactive(signal) => register(signal)
          case _ => ()
        }
        events.foreach { (_, handler) =>
          handler match
            case EventHandler.SetSignalLiteral(signal, _)      => register(signal)
            case EventHandler.IncrementSignal(signal, _)       => register(signal)
            case EventHandler.ToggleSignal(signal)             => register(signal)
            case EventHandler.InputChange(signal)              => register(signal)
            case EventHandler.FetchAction(_, _, body, tick, _, hOpt) => register(body); register(tick); hOpt.foreach(register)
            case _ => ()
        }
        children.foreach(walk)
      case View.Fragment(children) => children.foreach(walk)
      case View.ComponentInstance(component, props) =>
        walk(component.render(props.asInstanceOf[Nothing]))
      case View.Show(cond, whenTrue, whenFalse) =>
        // Walk both branches because either could end up rendered;
        // ALL signals they reference need state in the parent.
        walk(whenTrue())
        walk(whenFalse())
        val _ = cond  // cond is just a JVM thunk
      case View.ShowSignal(cond, whenTrue, whenFalse) =>
        register(cond)
        walk(whenTrue)
        walk(whenFalse)
      case View.For(items, render) =>
        // Render once with the realised items to discover signals
        // referenced inside.  If the list is empty no signals get
        // collected — Phase A3 limitation: empty initial lists with
        // signals declared inside won't get useState hoisting.  Caller
        // can work around by referencing the signal somewhere else.
        items().foreach(item => walk(render(item)))
      case View.ForSignal(_, _, _, itemTemplate) =>
        // A2e.2 — walk the item template so signals it references
        // still get useState hoisted in the parent component scope.
        // (Simple form has no nested signals; itemTemplate may.)
        itemTemplate.foreach(walk)
      case View.Portal(_, children) =>
        // A6 — portals lift children into a foreign DOM node but the
        // signals they reference still live in the parent component's
        // state.  Walk into them for useState hoisting.
        children.foreach(walk)
      case dt: View.DataTable =>
        dt.actions.foreach {
          case RowActionDef.RowDelete(_, _, tick, hOpt) => register(tick); hOpt.foreach(register)
          case RowActionDef.RowPost(_, _, _, _, tick, hOpt) => register(tick); hOpt.foreach(register)
          case RowActionDef.RowLink(_, sig, _)           => register(sig)
          case _                                         => ()
        }
        dt.columns.foreach {
          case FieldColumnDef(_, _, _, Some(RowActionDef.RowInlineEdit(_, _, _, tick, hOpt))) =>
            register(tick); hOpt.foreach(register)
          case _ => ()
        }
      case View.EditableCell(_, _, action) =>
        register(action.onSuccessTick); action.headers.foreach(register)
      // P2 — new semantic View cases
      case View.Column(children, _, _, _)     => children.foreach(walk)
      case View.Row(children, _, _, _)        => children.foreach(walk)
      case View.Stack(children, _)            => children.foreach(walk)
      case View.ScrollView(child, _, _)       => walk(child)
      case View.SafeArea(child, _)            => walk(child)
      case View.KeyboardAvoiding(child)       => walk(child)
      case View.Animated(child, _, _)         => walk(child)
      case View.Styled(child, _)              => walk(child)
      case View.Adaptive(web, _, _, fallback) =>
        web.foreach(walk); walk(fallback)
      case View.LazyList(items, render, _, _) => items().foreach(item => walk(render(item)))
      case View.LazyGrid(items, render, _, _, _) => items().foreach(item => walk(render(item)))
      case View.ModelView(_, _, template, _)    => walk(template)
      case View.ForModel(_, _, _, template, _)  => walk(template)
      case View.Button(label, action, _, _) =>
        walkHandler(action); walk(label)
      case View.TextInput(value, _, _, _, _)  => register(value)
      case View.Toggle(checked, _, _)         => register(checked)
      case View.Slider(value, _, _, _, _)     => register(value)
      case View.Picker(_, selected, _, _)     => register(selected)
      case View.TabBar(tabs, current, _) =>
        register(current); tabs.foreach(t => walk(t.content))
      case View.NavigationStack(routes, current, _) =>
        register(current); routes.values.foreach(fn => walk(fn()))
      case View.Sheet(content, isPresented) =>
        register(isPresented); walk(content)
      case View.AlertDialog(_, _, _, isPresented) => register(isPresented)
      case View.Form(child, onSubmit, _)  => walkHandler(onSubmit); walk(child)
      case View.FormField(_, value, _, _) => register(value)
      case _ => ()
    def walkHandler(h: EventHandler): Unit = h match
      case EventHandler.SetSignalLiteral(sig, _)         => register(sig)
      case EventHandler.IncrementSignal(sig, _)          => register(sig)
      case EventHandler.ToggleSignal(sig)                => register(sig)
      case EventHandler.InputChange(sig)                 => register(sig)
      case EventHandler.FetchAction(_, _, body, tick, _, hOpt) => register(body); register(tick); hOpt.foreach(register)
      case EventHandler.DeleteItem(_, _, tick, hOpt) => register(tick); hOpt.foreach(register)
      case EventHandler.ItemAction(_, _, _, tick, hOpt) => register(tick); hOpt.foreach(register)
      case EventHandler.SetFieldToSignal(sig, _)         => register(sig)
      case _ => ()
    walk(view)
    acc

  /** A2e — second collection pass for list signals, indexed under
   *  the same name → JS-array-literal shape that fuels per-list
   *  `useState`.  Visits the same View kinds that can carry a list
   *  reference: `ForSignal` itself + the list-mutation events
   *  (Push / Clear) attached to any Element. */
  private def collectLists(view: View[?]): scala.collection.mutable.LinkedHashMap[String, String] =
    val acc = scala.collection.mutable.LinkedHashMap.empty[String, String]
    def register(list: ReactiveSignalList[?]): Unit =
      val name = list.id
      if !name.matches("[A-Za-z_][A-Za-z0-9_]*") then
        throw new IllegalArgumentException(
          s"ReactiveSignalList id '$name' must match [A-Za-z_][A-Za-z0-9_]*."
        )
      val initJs = jsArrayLiteral(list.initial)
      acc.get(name) match
        case Some(existing) if existing != initJs =>
          throw new IllegalArgumentException(
            s"ReactiveSignalList id '$name' registered twice with different " +
            s"initial values ($existing vs $initJs)."
          )
        case _ => acc.update(name, initJs)
    def walk(v: View[?]): Unit = v match
      case View.ForSignal(list, _, _, itemTemplate) =>
        register(list)
        // Walk the template so RemoveSelfFromList → useState is set up
        // and any nested ForSignal inside has its list collected too.
        itemTemplate.foreach(walk)
      case View.Element(_, _, events, children) =>
        events.foreach { (_, handler) =>
          handler match
            case EventHandler.PushSignalLiteral(list, _) => register(list)
            case EventHandler.ClearSignalList(list)      => register(list)
            case EventHandler.RemoveSelfFromList(list)   => register(list)
            case _ => ()
        }
        children.foreach(walk)
      case View.Fragment(children) => children.foreach(walk)
      case View.ComponentInstance(component, props) =>
        walk(component.render(props.asInstanceOf[Nothing]))
      case View.Show(_, whenTrue, whenFalse) =>
        walk(whenTrue()); walk(whenFalse())
      case View.ShowSignal(_, whenTrue, whenFalse) =>
        walk(whenTrue); walk(whenFalse)
      case View.For(items, render) =>
        items().foreach(item => walk(render(item)))
      case View.Portal(_, children) =>
        children.foreach(walk)
      // P2 — walk new containers for list signals inside them
      case View.Column(children, _, _, _)     => children.foreach(walk)
      case View.Row(children, _, _, _)        => children.foreach(walk)
      case View.Stack(children, _)            => children.foreach(walk)
      case View.ScrollView(child, _, _)       => walk(child)
      case View.SafeArea(child, _)            => walk(child)
      case View.KeyboardAvoiding(child)       => walk(child)
      case View.Animated(child, _, _)         => walk(child)
      case View.Styled(child, _)              => walk(child)
      case View.Adaptive(web, _, _, fallback) => web.foreach(walk); walk(fallback)
      case View.LazyList(items, render, _, _)    => items().foreach(item => walk(render(item)))
      case View.LazyGrid(items, render, _, _, _) => items().foreach(item => walk(render(item)))
      case View.Button(label, _, _, _)        => walk(label)
      case View.TabBar(tabs, _, _)            => tabs.foreach(t => walk(t.content))
      case View.NavigationStack(routes, _, _) => routes.values.foreach(fn => walk(fn()))
      case View.Sheet(content, _)             => walk(content)
      case View.Form(child, _, _)             => walk(child)
      case _ => ()
    walk(view)
    acc

  /** A6 — DomRef collection.  Walks the View tree harvesting the
   *  `jsName` of every `AttrValue.RefBinding` so each becomes a
   *  `useRef(null)` hoisted at the top of App().  LinkedHashSet
   *  preserves first-seen order for deterministic output. */
  private def collectRefs(view: View[?]): scala.collection.mutable.LinkedHashSet[String] =
    val acc = scala.collection.mutable.LinkedHashSet.empty[String]
    def register(ref: WidgetRef): Unit =
      val name = ref.id
      if !name.matches("[A-Za-z_][A-Za-z0-9_]*") then
        throw new IllegalArgumentException(
          s"WidgetRef id '$name' must match [A-Za-z_][A-Za-z0-9_]*."
        )
      acc += name
    def walk(v: View[?]): Unit = v match
      case View.Element(_, attrs, _, children) =>
        attrs.values.foreach {
          case AttrValue.RefBinding(ref) => register(ref)
          case _ => ()
        }
        children.foreach(walk)
      case View.Fragment(children) => children.foreach(walk)
      case View.ComponentInstance(component, props) =>
        walk(component.render(props.asInstanceOf[Nothing]))
      case View.Show(_, whenTrue, whenFalse) =>
        walk(whenTrue()); walk(whenFalse())
      case View.ShowSignal(_, whenTrue, whenFalse) =>
        walk(whenTrue); walk(whenFalse)
      case View.For(items, render) =>
        items().foreach(item => walk(render(item)))
      case View.Portal(_, children) =>
        children.foreach(walk)
      case View.ForSignal(_, _, _, itemTemplate) => itemTemplate.foreach(walk)
      case _ => ()
    walk(view)
    acc

  /** Collect all FetchUrlSignal instances reachable from the view tree (stable order). */
  private def collectFetchSignals(view: View[?]): Seq[FetchUrlSignal] =
    val seen = scala.collection.mutable.LinkedHashMap.empty[String, FetchUrlSignal]
    def checkSig(sig: ReactiveSignal[?]): Unit = sig match
      case fs: FetchUrlSignal if !seen.contains(fs.id) => seen(fs.id) = fs
      case _ => ()
    def checkHandler(handler: EventHandler): Unit = handler match
      case EventHandler.FetchAction(_, _, body, tick, _, hOpt) => checkSig(body); checkSig(tick); hOpt.foreach(checkSig)
      case EventHandler.SetSignalLiteral(sig, _)               => checkSig(sig)
      case EventHandler.IncrementSignal(sig, _)                => checkSig(sig)
      case EventHandler.ToggleSignal(sig)                      => checkSig(sig)
      case EventHandler.InputChange(sig)                       => checkSig(sig)
      case _                                                   => ()
    ViewTraversal.foreachDepthFirst(view, ViewTraversal.Options.Web) {
      case View.SignalText(sig, _) => checkSig(sig)
      case View.Element(_, attrs, events, _) =>
        attrs.values.foreach { case AttrValue.Reactive(sig) => checkSig(sig); case _ => () }
        events.values.foreach(checkHandler)
      case View.ShowSignal(cond, _, _)                    => checkSig(cond)
      case View.ModelView(signal, _, _, _)                => checkSig(signal)
      case View.Button(_, action, _, _)                   => checkHandler(action)
      case View.TextInput(value, _, _, _, _)              => checkSig(value)
      case View.Toggle(checked, _, _)                     => checkSig(checked)
      case View.Slider(value, _, _, _, _)                 => checkSig(value)
      case View.Picker(_, selected, _, _)                 => checkSig(selected)
      case View.TabBar(_, current, _)                     => checkSig(current)
      case View.NavigationStack(_, current, _)            => checkSig(current)
      case View.Sheet(_, isPresented)                     => checkSig(isPresented)
      case View.AlertDialog(_, _, _, isPresented)         => checkSig(isPresented)
      case View.Form(_, onSubmit, _)                      => checkHandler(onSubmit)
      case View.FormField(_, value, _, _)                 => checkSig(value)
      case _ => ()
    }
    seen.values.toSeq

  /** Collect all DataTable fetch signals (as array state, useState([])). */
  private def collectDataTableSignals(view: View[?]): Seq[FetchUrlSignal] =
    val seen = scala.collection.mutable.LinkedHashMap.empty[String, FetchUrlSignal]
    ViewTraversal.foreachDepthFirst(view, ViewTraversal.Options.Web) {
      case dt: View.DataTable if !seen.contains(dt.signal.id) => seen(dt.signal.id) = dt.signal
      case _ => ()
    }
    seen.values.toSeq

  /** Second pass — emit a React.createElement expression tree.  No
   *  side-effects; pure expression.
   *
   *  `itemCtx` is `Some(list)` while rendering the body of a
   *  `ForSignal.itemTemplate` so `View.ItemText` and
   *  `EventHandler.RemoveSelfFromList` know they're inside an
   *  iteration and can emit code that references the `item` /
   *  `index` map-callback parameters. */
  private def renderView(view: View[?], itemCtx: Option[ReactiveSignalList[?]] = None, modelItemVar: String = ""): String = view match
    case View.Element(tag, attrs, events, children) =>
      val propsJs    = renderProps(attrs, events, itemCtx, modelItemVar = modelItemVar)
      val childrenJs = children.map(c => renderView(c, itemCtx, modelItemVar)).mkString(", ")
      val tail       = if children.isEmpty then "" else ", " + childrenJs
      s"h(${jsString(tag)}, $propsJs$tail)"

    case View.TextNode(thunk) =>
      jsString(thunk())

    case View.SignalText(signal, _) =>
      // Direct interpolation — React stringifies numbers / booleans.
      signal.id

    case View.ItemText =>
      // A2e.2 — inside an item template, reference the map-callback
      // `item` argument; outside, emit empty string (graceful no-op).
      if itemCtx.isDefined then "String(item)" else "''"

    case View.Fragment(children) =>
      if children.isEmpty then "null"
      else
        val childrenJs = children.map(c => renderView(c, itemCtx, modelItemVar)).mkString(", ")
        s"h(Fragment, null, $childrenJs)"

    case View.ComponentInstance(component, props) =>
      renderView(component.render(props.asInstanceOf[Nothing]), itemCtx, modelItemVar)

    case View.Show(cond, whenTrue, whenFalse) =>
      // Snapshot the condition AT EMIT TIME — `Show` is the
      // non-reactive variant.  Use `ShowSignal` for live swap.
      val branch = if cond() then whenTrue() else whenFalse()
      renderView(branch, itemCtx, modelItemVar)

    case View.ShowSignal(cond, whenTrue, whenFalse) =>
      // Ternary inside render — React re-runs render on useState
      // change, the ternary re-evaluates, reconciliation handles
      // the DOM swap.  Idiomatic React conditional rendering.
      s"(${cond.id} ? ${renderView(whenTrue, itemCtx, modelItemVar)} : ${renderView(whenFalse, itemCtx, modelItemVar)})"

    case View.For(items, render) =>
      // Emit a literal array; React handles list rendering.
      val realised = items().toList
      if realised.isEmpty then "null"
      else
        val parts = realised.map(item => renderView(render(item), itemCtx, modelItemVar))
        s"[${parts.mkString(", ")}]"

    case View.ForSignal(list, tag, attrs, itemTemplate) =>
      // A2e / A2e.2 — lower to `<jsName>.map((item, index) => ...)`.
      // React's keyed reconciliation handles add / remove / reorder
      // when the list state changes.  Two flavours:
      //
      //  - `itemTemplate = None`: simple `<tag>String(item)</tag>` per item.
      //  - `itemTemplate = Some(t)`: emit `t` recursively with
      //    `itemCtx = Some(list)` so item-hole leaves resolve to the
      //    iteration variables.
      itemTemplate match
        case None =>
          val tagJs = jsString(tag)
          val attrFields = attrs.flatMap { (k, av) =>
            attrValueJs(av).map { value =>
              val key = if k == "class" then "className" else k
              s"${jsString(key)}: $value"
            }
          }
          val propsParts = "'key': String(item)" :: attrFields.toList
          val propsJs    = s"{ ${propsParts.mkString(", ")} }"
          s"${list.id}.map((item, index) => h($tagJs, $propsJs, String(item)))"
        case Some(template) =>
          // Inject a `key: String(item)` on the template's root
          // element so React's keyed reconciliation can reuse DOM
          // nodes across re-renders.  Non-Element roots (Fragment,
          // bare TextNode) skip the key injection — same behaviour
          // as if the user wrote the map callback by hand.
          val body = template match
            case View.Element(tag, attrs, events, children) =>
              val propsJs    = renderProps(attrs, events, Some(list), injectKey = true)
              val childrenJs = children.map(c => renderView(c, Some(list))).mkString(", ")
              val tail       = if children.isEmpty then "" else ", " + childrenJs
              s"h(${jsString(tag)}, $propsJs$tail)"
            case other =>
              renderView(other, Some(list))
          s"${list.id}.map((item, index) => $body)"

    case View.Portal(target, children) =>
      // A6 — ReactDOM.createPortal(child, document.querySelector(target)).
      // When there's more than one child wrap them in a Fragment so the
      // createPortal call gets a single React node to render.
      val targetJs = jsString(target)
      val childJs  =
        if children.isEmpty then "null"
        else if children.size == 1 then renderView(children.head, itemCtx, modelItemVar)
        else s"h(Fragment, null, ${children.map(c => renderView(c, itemCtx, modelItemVar)).mkString(", ")})"
      s"ReactDOM.createPortal($childJs, document.querySelector($targetJs))"

    case dt: View.DataTable =>
      renderView(DataTableLowering.lower(dt), itemCtx, modelItemVar)

    // ── P2 semantic View cases ─────────────────────────────────────────────────

    case View.Column(children, spacing, align, style) =>
      val gapCss = if spacing > 0 then s"; gap: ${spacing}px" else ""
      val base   = s"display: flex; flex-direction: column; align-items: ${StyleUtils.hAlignToCSS(align)}$gapCss"
      val styleObj = cssStringToReactObject(StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style)))
      val kids = children.map(c => renderView(c, itemCtx, modelItemVar)).mkString(", ")
      if kids.isEmpty then s"h('div', { style: $styleObj })"
      else s"h('div', { style: $styleObj }, $kids)"

    case View.Row(children, spacing, align, style) =>
      val gapCss = if spacing > 0 then s"; gap: ${spacing}px" else ""
      val base   = s"display: flex; flex-direction: row; align-items: ${StyleUtils.vAlignToCSS(align)}$gapCss"
      val styleObj = cssStringToReactObject(StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style)))
      val kids = children.map(c => renderView(c, itemCtx, modelItemVar)).mkString(", ")
      if kids.isEmpty then s"h('div', { style: $styleObj })"
      else s"h('div', { style: $styleObj }, $kids)"

    case View.Stack(children, style) =>
      val base   = "position: relative"
      val styleObj = cssStringToReactObject(StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style)))
      val kids = children.map(c => renderView(c, itemCtx, modelItemVar)).mkString(", ")
      if kids.isEmpty then s"h('div', { style: $styleObj })"
      else s"h('div', { style: $styleObj }, $kids)"

    case View.ScrollView(child, axis, style) =>
      val base = axis match
        case Axis.Horizontal => "overflow-x: auto; overflow-y: hidden"
        case Axis.Vertical   => "overflow-y: auto; overflow-x: hidden"
        case Axis.Both       => "overflow: auto"
      val styleObj = cssStringToReactObject(StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style)))
      s"h('div', { style: $styleObj }, ${renderView(child, itemCtx, modelItemVar)})"

    case View.Spacer(size) =>
      val css = size match
        case Some(px) => s"width: ${px}px; height: ${px}px; flex-shrink: 0"
        case None     => "flex: 1; align-self: stretch"
      s"h('div', { style: ${cssStringToReactObject(css)} })"

    case View.Divider(axis, style) =>
      val base = axis match
        case Axis.Vertical   => "width: 1px; height: 100%; background: currentColor; opacity: 0.2; flex-shrink: 0"
        case _               => "width: 100%; height: 1px; background: currentColor; opacity: 0.2; flex-shrink: 0"
      val styleObj = cssStringToReactObject(StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style)))
      s"h('div', { 'role': 'separator', style: $styleObj })"

    case View.Text(content, style) =>
      val css = StyleUtils.styleToCSS(style)
      val styleField = if css.isEmpty then "" else s", style: ${cssStringToReactObject(css)}"
      s"h('span', { ${styleField.dropWhile(_ == ',').trim} }, ${jsString(content())})"

    case View.Image(source, style) =>
      val src = source match
        case ImageSource.Url(href)            => jsString(href)
        case ImageSource.Asset(name)          => jsString(s"/assets/$name")
        case ImageSource.Base64(data, mime)   => jsString(s"data:$mime;base64,$data")
      val css = StyleUtils.styleToCSS(style)
      val styleField = if css.isEmpty then "" else s", style: ${cssStringToReactObject(css)}"
      s"h('img', { 'src': $src$styleField })"

    case View.Icon(name, style) =>
      val css = StyleUtils.styleToCSS(style)
      val styleField = if css.isEmpty then "" else s", style: ${cssStringToReactObject(css)}"
      s"h('span', { 'aria-hidden': 'true', 'data-icon': ${jsString(name)}$styleField }, ${jsString(name)})"

    case View.Button(label, action, enabled, style) =>
      val base = "cursor: pointer; display: inline-flex; align-items: center; justify-content: center; border: none; padding: 6px 16px; border-radius: 4px"
      val css  = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
      val styleObj  = cssStringToReactObject(css)
      val onClickJs = eventHandlerJs("click", action, itemCtx, modelItemVar)
      val disabledJs = if !enabled() then ", 'disabled': true" else ""
      val clickField = onClickJs.map(f => s", $f").getOrElse("")
      s"h('button', { style: $styleObj$clickField$disabledJs }, ${renderView(label, itemCtx, modelItemVar)})"

    case View.TextInput(value, placeholder, multiline, secure, style) =>
      val base = "padding: 6px 10px; border: 1px solid #d1d5db; border-radius: 4px; font-size: inherit; font-family: inherit"
      val css  = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
      val styleObj = cssStringToReactObject(css)
      val setter   = setterName(value.id)
      if multiline then
        s"h('textarea', { style: $styleObj, 'value': ${value.id}, 'onChange': (e) => $setter(e.target.value), 'placeholder': ${jsString(placeholder)} })"
      else
        val typeAttr = if secure then "'type': 'password'" else "'type': 'text'"
        s"h('input', { style: $styleObj, $typeAttr, 'value': ${value.id}, 'onChange': (e) => $setter(e.target.value), 'placeholder': ${jsString(placeholder)} })"

    case View.Toggle(checked, label, style) =>
      val base = "display: inline-flex; align-items: center; gap: 6px; cursor: pointer"
      val css  = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
      val styleObj = cssStringToReactObject(css)
      val setter   = setterName(checked.id)
      val labelJs  = if label.isEmpty then "" else s", ${jsString(label)}"
      s"h('label', { style: $styleObj }, h('input', { 'type': 'checkbox', 'checked': ${checked.id}, 'onChange': () => $setter(c => !c) })$labelJs)"

    case View.Slider(value, min, max, step, style) =>
      val css = StyleUtils.styleToCSS(style)
      val styleField = if css.isEmpty then "" else s", style: ${cssStringToReactObject(css)}"
      val setter     = setterName(value.id)
      s"h('input', { 'type': 'range', 'min': $min, 'max': $max, 'step': $step, 'value': ${value.id}, 'onChange': (e) => $setter(Number(e.target.value))$styleField })"

    case View.Picker(options, selected, placeholder, style) =>
      val base = "padding: 6px 10px; border: 1px solid #d1d5db; border-radius: 4px; font-size: inherit; font-family: inherit"
      val css  = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
      val styleObj  = cssStringToReactObject(css)
      val setter    = setterName(selected.id)
      val opts      = options.map { (lbl, v) =>
        val vJs = try jsLiteral(v) catch { case _: Throwable => jsString(String.valueOf(v)) }
        s"h('option', { 'value': $vJs }, ${jsString(lbl)})"
      }
      val phOpt = if placeholder.nonEmpty then
        s"h('option', { 'value': '', 'disabled': true, 'hidden': true }, ${jsString(placeholder)})" +: opts
      else opts
      s"h('select', { style: $styleObj, 'value': ${selected.id}, 'onChange': (e) => $setter(e.target.value) }, ${phOpt.mkString(", ")})"

    case View.LazyList(items, render, _, style) =>
      val base = "overflow-y: auto"
      val css  = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
      val styleObj = cssStringToReactObject(css)
      val kids = items().toList.map(item => renderView(render(item), itemCtx, modelItemVar)).mkString(", ")
      s"h('div', { style: $styleObj }, $kids)"

    case View.LazyGrid(items, render, columns, spacing, style) =>
      val colsCss = StyleUtils.gridColumnsToCSS(columns)
      val gapCss  = if spacing > 0 then s"; gap: ${spacing}px" else ""
      val base    = s"display: grid; grid-template-columns: $colsCss$gapCss"
      val css     = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
      val styleObj = cssStringToReactObject(css)
      val kids = items().toList.map(item => renderView(render(item), itemCtx, modelItemVar)).mkString(", ")
      s"h('div', { style: $styleObj }, $kids)"

    case View.TabBar(tabs, current, style) =>
      val base     = StyleUtils.styleToCSS(style)
      val outerObj = if base.isEmpty then "null" else cssStringToReactObject(base)
      val headerObj = cssStringToReactObject("display: flex; border-bottom: 1px solid #e5e7eb; margin-bottom: 8px")
      val tabHeaders = tabs.zipWithIndex.map { (tab, i) =>
        val activeBase  = "cursor: pointer; padding: 8px 16px; border: none; background: transparent; font-family: inherit; font-size: inherit; border-bottom: 2px solid"
        s"h('button', { style: ${current.id} === $i ? ${cssStringToReactObject(s"$activeBase #3b82f6; font-weight: bold")} : ${cssStringToReactObject(s"$activeBase transparent")}, 'onClick': () => ${setterName(current.id)}($i) }, ${jsString(tab.label)})"
      }.mkString(", ")
      val tabContents = tabs.zipWithIndex.map { (tab, i) =>
        s"${current.id} === $i ? ${renderView(tab.content, itemCtx, modelItemVar)} : null"
      }.mkString(", ")
      s"h('div', { style: $outerObj }, h('div', { style: $headerObj }, $tabHeaders), $tabContents)"

    case View.NavigationStack(routes, current, style) =>
      val base     = StyleUtils.styleToCSS(style)
      val outerObj = if base.isEmpty then "null" else cssStringToReactObject(base)
      val branches = routes.toList.map { (key, fn) =>
        s"${current.id} === ${jsString(key)} ? ${renderView(fn(), itemCtx, modelItemVar)} : null"
      }.mkString(", ")
      s"h('div', { style: $outerObj }, $branches)"

    case View.Sheet(content, isPresented) =>
      val overlayObj  = cssStringToReactObject("position: fixed; bottom: 0; left: 0; right: 0; background: #fff; box-shadow: 0 -4px 12px rgba(0,0,0,0.15); border-radius: 12px 12px 0 0; padding: 16px; z-index: 1000")
      val backdropObj = cssStringToReactObject("position: fixed; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0,0,0,0.4); z-index: 999")
      val setter      = setterName(isPresented.id)
      s"${isPresented.id} ? h('div', null, h('div', { style: $backdropObj, 'onClick': () => $setter(false) }), h('div', { style: $overlayObj }, ${renderView(content, itemCtx, modelItemVar)})) : null"

    case View.AlertDialog(title, message, buttons, isPresented) =>
      val dialogObj   = cssStringToReactObject("position: fixed; top: 50%; left: 50%; transform: translate(-50%,-50%); background: #fff; padding: 24px; border-radius: 8px; box-shadow: 0 4px 32px rgba(0,0,0,0.2); z-index: 1001; min-width: 300px")
      val backdropObj = cssStringToReactObject("position: fixed; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0,0,0,0.4); z-index: 1000")
      val setter      = setterName(isPresented.id)
      val btnObjDefault     = cssStringToReactObject("background: #3b82f6; color: #fff; border: none; padding: 8px 16px; border-radius: 4px; cursor: pointer; font-family: inherit; font-size: inherit")
      val btnObjDestructive = cssStringToReactObject("background: #ef4444; color: #fff; border: none; padding: 8px 16px; border-radius: 4px; cursor: pointer; font-family: inherit; font-size: inherit")
      val btnsJs = buttons.map { btn =>
        val obj = if btn.role == ButtonRole.Destructive then btnObjDestructive else btnObjDefault
        s"h('button', { style: $obj, 'onClick': () => $setter(false) }, ${jsString(btn.label)})"
      }.mkString(", ")
      val btnRowObj = cssStringToReactObject("display: flex; gap: 8px; margin-top: 16px")
      s"${isPresented.id} ? h('div', null, h('div', { style: $backdropObj }), h('div', { style: $dialogObj }, h('h3', null, ${jsString(title)}), h('p', null, ${jsString(message)}), h('div', { style: $btnRowObj }, $btnsJs))) : null"

    case View.Form(child, onSubmit, style) =>
      val handlerBody = onSubmit match
        case EventHandler.SetSignalLiteral(sig, v) => s"${setterName(sig.id)}(${jsLiteral(v)})"
        case EventHandler.IncrementSignal(sig, by) => s"${setterName(sig.id)}(c => c + $by)"
        case EventHandler.ToggleSignal(sig)        => s"${setterName(sig.id)}(c => !c)"
        case EventHandler.FetchAction(method, url, body, tick, clearBody, hOpt) =>
          val setTick   = setterName(tick.id)
          val clear     = if clearBody then s" ${setterName(body.id)}('');" else ""
          val headersJs = hOpt.map(h => s", headers: JSON.parse(${h.id} || '{}')").getOrElse("")
          s"fetch(${jsString(url)}, {method: ${jsString(method)}, body: ${body.id}$headersJs}).then(r => r.text()).then(_ => { $setTick(t => t + 1);$clear })"
        case _ => ""
      val css = StyleUtils.styleToCSS(style)
      val styleField = if css.isEmpty then "" else s", style: ${cssStringToReactObject(css)}"
      s"h('form', { 'onSubmit': (e) => { e.preventDefault(); $handlerBody }$styleField }, ${renderView(child, itemCtx, modelItemVar)})"

    case View.FormField(label, value, validate, style) =>
      val currentVal = value()
      val errorMsg   = try validate(currentVal.asInstanceOf[Nothing]) catch { case _: Throwable => None }
      val inputType  = currentVal match
        case _: Int | _: Double | _: Long | _: Float => "'number'"
        case _: Boolean                               => "'checkbox'"
        case _                                        => "'text'"
      val setter     = setterName(value.id)
      val labelObj   = cssStringToReactObject("display: block; margin-bottom: 4px; font-size: 0.875em; font-weight: 500")
      val inputBase  = "padding: 6px 10px; border: 1px solid #d1d5db; border-radius: 4px; width: 100%; box-sizing: border-box; font-size: inherit; font-family: inherit"
      val inputCss   = StyleUtils.mergeCSS(inputBase, StyleUtils.styleToCSS(style))
      val inputObj   = cssStringToReactObject(inputCss)
      val errorJs    = errorMsg.map { msg =>
        s", h('span', { style: ${cssStringToReactObject("color: #ef4444; font-size: 0.75em; display: block; margin-top: 2px")} }, ${jsString(msg)})"
      }.getOrElse("")
      s"h('label', { style: $labelObj }, ${jsString(label)}, h('input', { 'type': $inputType, style: $inputObj, 'value': ${value.id}, 'onChange': (e) => $setter(e.target.value) })$errorJs)"

    case View.SafeArea(child, edges) =>
      val top    = if edges.contains(Edge.Top)      then "env(safe-area-inset-top, 0)" else "0"
      val right  = if edges.contains(Edge.Trailing) then "env(safe-area-inset-right, 0)" else "0"
      val bottom = if edges.contains(Edge.Bottom)   then "env(safe-area-inset-bottom, 0)" else "0"
      val left   = if edges.contains(Edge.Leading)  then "env(safe-area-inset-left, 0)" else "0"
      val css    = s"padding-top: $top; padding-right: $right; padding-bottom: $bottom; padding-left: $left"
      s"h('div', { style: ${cssStringToReactObject(css)} }, ${renderView(child, itemCtx, modelItemVar)})"

    case View.KeyboardAvoiding(child) =>
      renderView(child, itemCtx, modelItemVar)

    case View.Animated(child, transition, style) =>
      val dur    = transition.duration.toLong
      val delay  = if transition.delay > 0 then s" ${transition.delay.toLong}ms" else ""
      val base   = s"transition: all ${dur}ms ${StyleUtils.curveToCSS(transition.curve)}$delay"
      val css    = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
      val styleObj = cssStringToReactObject(css)
      s"h('div', { style: $styleObj }, ${renderView(child, itemCtx, modelItemVar)})"

    case View.Styled(child, style) =>
      val css = StyleUtils.styleToCSS(style)
      if css.isEmpty then renderView(child, itemCtx, modelItemVar)
      else s"h('div', { style: ${cssStringToReactObject(css)} }, ${renderView(child, itemCtx, modelItemVar)})"

    case View.ModelView(signal, _, template, _) =>
      s"${signal.id} && h(Fragment, null, ${renderView(template, itemCtx, modelItemVar)})"

    case View.ForModel(bindingVar, fieldPath, itemVar, template, _) =>
      val body     = renderView(template, itemCtx, itemVar)
      val listExpr = if fieldPath.isEmpty then bindingVar else s"$bindingVar.$fieldPath"
      s"($listExpr || []).map(($itemVar, _idx) => h(Fragment, {'key': _idx}, $body))"

    case View.ModelText(varName, fieldPath, _) =>
      s"String(${varName}.${fieldPath})"

    case View.EditableCell(varName, fieldPath, action) =>
      val urlJs      = jsString(action.url)
      val methodJs   = jsString(action.method.toUpperCase)
      val tickSetter = setterName(action.onSuccessTick.id)
      val idKey      = jsString(action.idField.split('.').last)
      val valKey     = jsString(fieldPath.split('.').last)
      val idExpr     = s"String($varName.${action.idField})"
      val inpCss     = "border:1px solid transparent;background:transparent;width:100%;font-family:inherit;font-size:inherit;color:inherit;outline:none;padding:0"
      val focusCss   = "border:1px solid #3b82f6;background:#fff;"
      val inpStyle   = cssStringToReactObject(inpCss)
      val focStyle   = cssStringToReactObject(focusCss)
      val blurJs     = s"(e) => { const _v = e.target.value; fetch($urlJs, {method: $methodJs, headers: {'Content-Type': 'application/json'}, body: JSON.stringify({[$idKey]: $idExpr, [$valKey]: _v})}).then(r => r.text()).then(_ => $tickSetter(t => t + 1)) }"
      val kdJs       = s"(e) => { if (e.key === 'Enter') e.target.blur(); if (e.key === 'Escape') { e.target.value = String($varName.$fieldPath); e.target.blur(); } }"
      s"h('input', { 'type': 'text', defaultValue: String($varName.$fieldPath), style: $inpStyle, onFocus: (e) => Object.assign(e.target.style, $focStyle), onBlur: $blurJs, onKeyDown: $kdJs })"

    case View.Adaptive(web, _, _, fallback) =>
      renderView(web.getOrElse(fallback), itemCtx, modelItemVar)

  /** Props object — combines attributes + event handlers into the
   *  single second argument of `React.createElement`.  When
   *  `itemCtx.isDefined`, this element is the ROOT of a
   *  ForSignal.itemTemplate and gets a synthetic `key: String(item)`
   *  injected (React requires keys on map'd children). */
  private def renderProps(
      attrs:        Map[String, AttrValue],
      events:       Map[String, EventHandler],
      itemCtx:      Option[ReactiveSignalList[?]],
      injectKey:    Boolean = false,
      modelItemVar: String = ""
  ): String =
    val attrFields = attrs.flatMap { (k, v) =>
      v match
        case AttrValue.RefBinding(ref) =>
          // A6 — React reserves the `ref` prop; map any RefBinding to it
          // regardless of the attribute key the user picked.  The ref
          // variable is the useRef object hoisted at the top of App().
          Some(s"'ref': ${ref.id}")
        case AttrValue.Str(css) if k == "style" =>
          // React requires style as a JS object, not a CSS string.
          Some(s"'style': ${cssStringToReactObject(css)}")
        case _ =>
          attrValueJs(v).map { value =>
            // React uses className not class; map at IR level.
            val key = if k == "class" then "className" else k
            s"${jsString(key)}: $value"
          }
    }
    val eventFields = events.flatMap { (eventName, handler) =>
      eventHandlerJs(eventName, handler, itemCtx, modelItemVar)
    }
    val keyField = if injectKey then List("'key': String(item)") else Nil
    // If `value` is set but no onChange was emitted (input handler is an
    // untranslatable JVM closure), use defaultValue so the field is
    // uncontrolled and the user can still type in the browser.
    val hasOnChange = eventFields.exists(_.startsWith("'onChange'"))
    // Only downgrade value/checked to their uncontrolled default* variants when
    // the value is a static literal (starts with quote/digit/true/false).
    // A value that starts with a letter is a JS variable (Reactive signal) and
    // must stay controlled so React re-evaluates it on every render.
    def isLiteral(field: String): Boolean =
      val v = field.dropWhile(_ != ':').drop(1).trim
      v.headOption.exists(c => c == '\'' || c == '"' || c.isDigit || v.startsWith("true") || v.startsWith("false") || v.startsWith("null"))
    val finalAttrFields = if hasOnChange then attrFields
      else attrFields.map { f =>
        if f.startsWith("'value'")    && isLiteral(f) then "'defaultValue'"  + f.drop("'value'".length)
        else if f.startsWith("'checked'") && isLiteral(f) then "'defaultChecked'" + f.drop("'checked'".length)
        else f
      }
    val all = keyField ++ finalAttrFields ++ eventFields
    if all.isEmpty then "null" else s"{ ${all.mkString(", ")} }"

  private def attrValueJs(av: AttrValue): Option[String] = av match
    case AttrValue.Str(value)        => Some(jsString(value))
    case AttrValue.Bool(value)       => Some(value.toString)
    case AttrValue.Num(value)        => Some(formatNumber(value))
    case AttrValue.Dynamic(read)     => Some(jsLiteral(read()))
    case AttrValue.Reactive(signal)  => Some(signal.id)
    case AttrValue.Absent            => None
    case AttrValue.RefBinding(_)     => None  // handled inline in renderProps as the React `ref` prop

  /** Translate an event handler.  Returns `Some((onClick, body))`
   *  pair as a single JS field source, or `None` for unsupported
   *  handlers (the marker is emitted as a separate `/* */` comment
   *  in the props object).  `itemCtx` is set when this handler is
   *  rendered inside a `ForSignal.itemTemplate`; `modelItemVar` names
   *  the iteration variable of the enclosing ForModel (needed by
   *  DeleteItem to emit `$itemVar.$idField` in the delete body). */
  private def eventHandlerJs(
      eventName:    String,
      handler:      EventHandler,
      itemCtx:      Option[ReactiveSignalList[?]],
      modelItemVar: String
  ): Option[String] =
    val onKey = onProp(eventName)
    handler match
      case EventHandler.SetSignalLiteral(signal, value) =>
        val setter = setterName(signal.id)
        val v      = jsLiteral(value)
        Some(s"${jsString(onKey)}: () => $setter($v)")
      case EventHandler.IncrementSignal(signal, by) =>
        val setter = setterName(signal.id)
        // Functional setState — avoids stale-closure read of `count`.
        Some(s"${jsString(onKey)}: () => $setter(c => c + $by)")
      case EventHandler.ToggleSignal(signal) =>
        val setter = setterName(signal.id)
        Some(s"${jsString(onKey)}: () => $setter(c => !c)")
      case EventHandler.PushSignalLiteral(list, value) =>
        val setter = setterName(list.id)
        val v      = jsLiteral(value)
        // Functional setState — concat into the previous array snapshot
        // so concurrent updates don't lose entries.
        Some(s"${jsString(onKey)}: () => $setter(prev => prev.concat([$v]))")
      case EventHandler.ClearSignalList(list) =>
        val setter = setterName(list.id)
        Some(s"${jsString(onKey)}: () => $setter([])")
      case EventHandler.RemoveSelfFromList(list) =>
        // A2e.2 — only meaningful inside an itemTemplate.  Capture
        // the map-callback `index` in the arrow so each item's
        // handler removes its own slot.
        if itemCtx.exists(_.id == list.id) then
          val setter = setterName(list.id)
          Some(s"${jsString(onKey)}: () => $setter(prev => prev.filter((_, i) => i !== index))")
        else
          Some(s"/* '$eventName' is RemoveSelfFromList used outside an item template — no-op */")
      case EventHandler.InputChange(signal) =>
        val setter = setterName(signal.id)
        Some(s"'onChange': (e) => $setter(e.target.value)")
      case EventHandler.FetchAction(method, url, body, tick, clearBody, hOpt) =>
        val getBody   = body.id
        val setTick   = setterName(tick.id)
        val setBody   = setterName(body.id)
        val urlJs     = jsString(url)
        val methodJs  = jsString(method)
        val clearJs   = if clearBody then s"; $setBody('')" else ""
        val headersJs = hOpt.map(h => s", headers: JSON.parse(${h.id} || '{}')").getOrElse("")
        Some(s"${jsString(onKey)}: () => fetch($urlJs, {method: $methodJs, body: $getBody$headersJs}).then(r => r.text()).then(_ => { $setTick(t => t + 1)$clearJs })")
      case EventHandler.DeleteItem(idField, deleteUrl, tick, hOpt) if modelItemVar.nonEmpty =>
        val setter    = setterName(tick.id)
        val delUrlJs  = jsString(deleteUrl)
        val headersJs = hOpt.map(h => s", headers: JSON.parse(${h.id} || '{}')").getOrElse("")
        Some(s"${jsString(onKey)}: () => fetch($delUrlJs, {method: 'POST', body: String($modelItemVar.$idField)$headersJs}).then(r => r.text()).then(_ => $setter(t => t + 1))")
      case EventHandler.DeleteItem(_, _, _, _) =>
        Some(s"/* '$eventName' is DeleteItem outside ForModel context — no-op */")
      case EventHandler.ItemAction(method, url, bodyField, tick, hOpt) if modelItemVar.nonEmpty =>
        val setter    = setterName(tick.id)
        val urlJs     = jsString(url)
        val methodJs  = jsString(method)
        val headersJs = hOpt.map(h => s", headers: JSON.parse(${h.id} || '{}')").getOrElse("")
        Some(s"${jsString(onKey)}: () => fetch($urlJs, {method: $methodJs, body: String($modelItemVar.$bodyField)$headersJs}).then(r => r.text()).then(_ => $setter(t => t + 1))")
      case EventHandler.ItemAction(_, _, _, _, _) =>
        Some(s"/* '$eventName' is ItemAction outside ForModel context — no-op */")
      case EventHandler.SetFieldToSignal(signal, fieldPath) if modelItemVar.nonEmpty =>
        val setter = setterName(signal.id)
        Some(s"${jsString(onKey)}: () => $setter(String($modelItemVar.$fieldPath))")
      case EventHandler.SetFieldToSignal(_, _) =>
        Some(s"/* '$eventName' is SetFieldToSignal outside ForModel context — no-op */")
      case EventHandler.Simple(_) | EventHandler.WithEvent(_) =>
        // JVM closure — emit a comment-prop that doesn't bind anything.
        // The presence of the marker tells dev "you wrote Simple/WithEvent
        // but A3 can't translate JVM closures yet".  Render still works.
        Some(s"/* '$eventName' is a JVM closure — A3 can't translate (richer IR coming later) */")

  /** DOM event name → React event prop.  React uses camelCase:
   *  'click' → 'onClick', 'mousedown' → 'onMouseDown', etc.  This
   *  is the simplest case mapping; production-grade would have a
   *  larger table.  Unknown events keep their lowercase form with
   *  a single capital, which React tolerates for custom events. */
  private def onProp(eventName: String): String =
    "on" + eventName.headOption.fold("")(_.toUpper.toString) + eventName.drop(1)

  /** State-variable name → React setter name. */
  private def setterName(varName: String): String =
    "set" + varName.headOption.fold("")(_.toUpper.toString) + varName.drop(1)

  /** JS literal for arbitrary Scala values used as signal initials
   *  or attribute defaults.  Mirrors the Custom backend's
   *  jsLiteral so the two stay consistent. */
  private def jsLiteral(value: Any): String = value match
    case s: String  => jsString(s)
    case i: Int     => i.toString
    case l: Long    => l.toString
    case d: Double  => formatNumber(d)
    case f: Float   => formatNumber(f.toDouble)
    case b: Boolean => b.toString
    case null       => "null"
    case other      => throw new IllegalArgumentException(
      s"jsLiteral: unsupported value type ${other.getClass.getName} ($other).  " +
      "Supported: String / Int / Long / Double / Float / Boolean / null."
    )

  /** A2e — JS array literal for a `ReactiveSignalList`'s initial.
   *  Each element passes through `jsLiteral` (same primitive-only
   *  restriction). */
  private def jsArrayLiteral(items: Seq[Any]): String =
    items.map(jsLiteral).mkString("[", ", ", "]")

  private def formatNumber(d: Double): String =
    if d == d.toLong.toDouble then d.toLong.toString else d.toString

  private def jsString(s: String): String =
    val sb = new StringBuilder
    sb += '\''
    s.foreach {
      case '\\' => sb ++= "\\\\"
      case '\'' => sb ++= "\\'"
      case '\n' => sb ++= "\\n"
      case '\r' => sb ++= "\\r"
      case '<'  => sb ++= "\\u003c"
      case c    => sb += c
    }
    sb += '\''
    sb.toString

  /** Convert a CSS declaration string (e.g. "display: flex; gap: 8px;")
   *  to a React style object literal (e.g. { display: 'flex', gap: '8px' }).
   *  CSS property names are camelCased; values stay as JS strings. */
  private def cssStringToReactObject(css: String): String =
    val fields = css.split(";").toSeq
      .map(_.trim).filter(_.nonEmpty)
      .flatMap { decl =>
        val idx = decl.indexOf(':')
        if idx < 0 then None
        else
          val prop  = decl.substring(0, idx).trim
          val value = decl.substring(idx + 1).trim
          val camel = prop.split('-').toSeq match
            case head +: tail => head + tail.map(p => p.head.toUpper.toString + p.tail).mkString
            case _            => prop
          Some(s"$camel: ${jsString(value)}")
      }
    if fields.isEmpty then "{}" else s"{ ${fields.mkString(", ")} }"
