package scalascript.frontend.electron

import scalascript.ast.DatabaseDecl

/** Generates the Electron main-process files for a desktop app bundle.
 *
 *  The renderer-process content (HTML + JS) comes from the existing
 *  `custom` emitter via [[ElectronFrameworkBackend]].  This object
 *  provides the three additional files every Electron project needs:
 *  `main.js`, `preload.js`, and `package.json`. */
object ElectronEmitter:

  /** Electron main process script.
   *
   *  Creates a BrowserWindow (1200×800), loads `index.html`, and
   *  handles macOS activate / window-all-closed lifecycle. */
  def mainJs(
    displayName: String,
    width:       Int                = 1200,
    height:      Int                = 800,
    databases:   List[DatabaseDecl] = Nil
  ): String =
    val electronImport =
      if ElectronPersistenceBridge.enabled(databases) then
        "const { app, BrowserWindow, ipcMain } = require('electron')"
      else
        "const { app, BrowserWindow } = require('electron')"
    val fsImport =
      if ElectronPersistenceBridge.enabled(databases) then "const fs = require('fs')" else ""
    val databaseInit =
      if ElectronPersistenceBridge.enabled(databases) then "  await __sscInitDatabases()\n" else ""
    val persistenceBridge = ElectronPersistenceBridge.mainProcessJs(databases)
    s"""'use strict'
       |$electronImport
       |const path = require('path')
       |$fsImport
       |$persistenceBridge
       |
       |function createWindow() {
       |  const win = new BrowserWindow({
       |    width: $width,
       |    height: $height,
       |    title: ${jsString(displayName)},
       |    webPreferences: {
       |      preload: path.join(__dirname, 'preload.js'),
       |      contextIsolation: true,
       |      nodeIntegration: false
       |    }
       |  })
       |  win.loadFile('index.html')
       |}
       |
       |app.whenReady().then(async () => {
       |$databaseInit
       |  createWindow()
       |  app.on('activate', () => {
       |    if (BrowserWindow.getAllWindows().length === 0) createWindow()
       |  })
       |})
       |
       |app.on('window-all-closed', () => {
       |  if (process.platform !== 'darwin') app.quit()
       |})
       |""".stripMargin

  /** Preload script — runs in a sandboxed context bridging main ↔ renderer.
   *  Extend with `contextBridge.exposeInMainWorld(...)` as needed (P3b+). */
  val preloadJs: String = ElectronPersistenceBridge.preloadJs(Nil)

  def preloadJs(databases: List[DatabaseDecl]): String =
    ElectronPersistenceBridge.preloadJs(databases)

  /** npm package manifest for the generated Electron project. */
  def packageJson(
    name:        String,
    version:     String     = "1.0.0",
    description: String     = "Generated by ScalaScript",
    electronVer: String     = "^30.0.0",
    builderVer:  String     = "^24.0.0",
    databases:   List[DatabaseDecl] = Nil
  ): String =
    val dependencies =
      if ElectronPersistenceBridge.enabled(databases) then
        s"""
           |  "dependencies": {
           |    "sql.js": "^1.10.3"
           |  },
           |""".stripMargin
      else ""
    val asarUnpack =
      if ElectronPersistenceBridge.enabled(databases) then
        """    "asarUnpack": ["node_modules/sql.js/dist/*.wasm"],
          |""".stripMargin
      else ""
    s"""{
       |  "name": "${sanitizePkgName(name)}",
       |  "version": "$version",
       |  "description": ${jsString(description)},
       |  "main": "main.js",
       |  "scripts": {
       |    "start": "electron .",
       |    "build": "electron-builder"
       |  },
       |$dependencies
       |  "devDependencies": {
       |    "electron": "$electronVer",
       |    "electron-builder": "$builderVer"
       |  },
       |  "build": {
       |    "appId": "com.scalascript.${sanitizePkgName(name)}",
       |    "productName": ${jsString(name)},
       |    "directories": { "output": "dist" },
       |$asarUnpack
       |    "mac":     { "target": "dmg" },
       |    "win":     { "target": "nsis" },
       |    "linux":   { "target": "AppImage" }
       |  }
       |}
       |""".stripMargin

  /** HTML shell that loads `app.js` as an ES module. */
  def indexHtml(title: String, css: String = ""): String =
    val styleBlock = if css.nonEmpty then s"\n  <style>\n$css\n  </style>" else ""
    s"""<!DOCTYPE html>
       |<html lang="en">
       |<head>
       |  <meta charset="UTF-8">
       |  <meta http-equiv="Content-Security-Policy"
       |        content="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'">
       |  <title>${escapeHtml(title)}</title>$styleBlock
       |</head>
       |<body>
       |  <div id="app"></div>
       |  <script type="module" src="./app.js"></script>
       |</body>
       |</html>
       |""".stripMargin

  // ── helpers ────────────────────────────────────────────────────────────

  private def jsString(s: String): String =
    "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n") + "\""

  private def escapeHtml(s: String): String =
    s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

  private def sanitizePkgName(s: String): String =
    s.toLowerCase.replaceAll("[^a-z0-9-]", "-").replaceAll("-+", "-").stripPrefix("-").stripSuffix("-")
      .pipe(n => if n.isEmpty then "ssc-app" else n)

  extension [A](a: A) private def pipe[B](f: A => B): B = f(a)
