package scalascript.frontend.custom

import scalascript.frontend.*

/** Walks a `View` tree at emit time and produces JS source that
 *  builds the corresponding DOM via imperative
 *  `document.createElement` / `setAttribute` / `appendChild` calls.
 *
 *  Static-subset only — see `CustomFrameworkBackend` for the
 *  documented A2 limitations (signals snapshot, events skipped,
 *  effects skipped).
 *
 *  Output shape (single ES module, no runtime deps):
 *  {{{
 *  // generated by ScalaScript v1.18 — frontend-custom Phase A2
 *  function mount(root) {
 *    const n0 = document.createElement('div');
 *    n0.setAttribute('class', 'hello');
 *    const n1 = document.createTextNode('Hello, world!');
 *    n0.appendChild(n1);
 *    root.appendChild(n0);
 *  }
 *  mount(document.getElementById('app'));
 *  }}}
 *  Variable names use a fresh counter (`n0`, `n1`, …) so the output
 *  is deterministic and diff-friendly. */
private[custom] object StaticJsEmitter:

  def emit(root: View, allComponents: List[ComponentDef]): String =
    val _ = allComponents  // reserved for the codegen-lowering pass when name-based ComponentInstance refs land
    val ctx = new Ctx
    val rootVar = ctx.compile(root)
    val sb = new StringBuilder
    sb ++= "// Generated by ScalaScript v1.18 — frontend-custom Phase A2 / A2b / A2c.\n"
    sb ++= "// Static + reactive (SignalText) + events (SetSignalLiteral / IncrementSignal).\n"

    // A2b — emit reactive signal cells + setSignal helper if any
    // SignalText was visited.  Done once per signal name; later
    // sets call __setSignal which fans out to all subscribers.
    if ctx.reactiveSignals.nonEmpty then
      sb ++= "const __ssc_signals = Object.create(null);\n"
      ctx.reactiveSignals.toSeq.sortBy(_._1).foreach { case (name, initial) =>
        sb ++= s"__ssc_signals[${jsString(name)}] = { value: ${initial}, subs: new Set() };\n"
      }
      sb ++= "function __setSignal(name, value) {\n"
      sb ++= "  const cell = __ssc_signals[name];\n"
      sb ++= "  if (!cell) throw new Error('unknown signal: ' + name);\n"
      sb ++= "  cell.value = value;\n"
      sb ++= "  cell.subs.forEach(fn => fn(value));\n"
      sb ++= "}\n"
      // Expose on window for browser-side tests + manual driving.
      sb ++= "if (typeof window !== 'undefined') window.__setSignal = __setSignal;\n"

    sb ++= "function mount(root) {\n"
    ctx.statements.foreach { stmt =>
      sb ++= "  "
      sb ++= stmt
      sb ++= "\n"
    }
    if rootVar != null then
      sb ++= s"  root.appendChild($rootVar);\n"
    sb ++= "}\n"
    sb ++= "mount(document.getElementById('app'));\n"
    sb.toString

  /** Per-emit state: a fresh-variable counter and the accumulating
   *  list of JS statements.  `reactiveSignals` collects every
   *  `ReactiveSignal` referenced by a `SignalText` (or future
   *  reactive View variant) so we can emit one cell per name at
   *  the top of the bundle. */
  private final class Ctx:
    private var counter: Int = 0
    val statements: scala.collection.mutable.ArrayBuffer[String] =
      scala.collection.mutable.ArrayBuffer.empty
    val reactiveSignals: scala.collection.mutable.LinkedHashMap[String, String] =
      scala.collection.mutable.LinkedHashMap.empty

    private def freshVar(): String =
      val v = s"n$counter"
      counter += 1
      v

    /** Validate + register a ReactiveSignal.  Name uniqueness is
     *  enforced (two signals with same jsName but different
     *  initial values throws — that's a user error worth catching
     *  early). */
    private def registerSignal(signal: ReactiveSignal[?]): Unit =
      val name = signal.jsName
      if !name.matches("[A-Za-z_][A-Za-z0-9_]*") then
        throw new IllegalArgumentException(
          s"ReactiveSignal jsName '$name' must match [A-Za-z_][A-Za-z0-9_]*."
        )
      val initialJs = jsLiteral(signal())
      reactiveSignals.get(name) match
        case Some(existing) if existing != initialJs =>
          throw new IllegalArgumentException(
            s"ReactiveSignal jsName '$name' registered twice with different " +
            s"initial values ($existing vs $initialJs).  Names must be unique."
          )
        case _ => reactiveSignals.update(name, initialJs)

    /** Compile a View node.  Returns the JS variable name that
     *  references the constructed DOM node, or `null` if the View
     *  emits zero nodes (an empty Fragment).  Caller decides whether
     *  to `appendChild` it. */
    def compile(view: View): String | Null = view match
      case View.Element(tag, attrs, events, children) =>
        val v = freshVar()
        statements += s"const $v = document.createElement(${jsString(tag)});"
        attrs.foreach { (k, av) =>
          attrValueJs(av) match
            case Some(value) =>
              statements += s"$v.setAttribute(${jsString(k)}, $value);"
            case None => () // Absent — skip
        }
        events.foreach { (eventName, handler) =>
          compileEventHandler(v, eventName, handler)
        }
        children.foreach { child =>
          val childVar = compile(child)
          if childVar != null then statements += s"$v.appendChild($childVar);"
        }
        v

      case View.TextNode(thunk) =>
        // Static — call once, embed as literal.
        val text = thunk()
        val v = freshVar()
        statements += s"const $v = document.createTextNode(${jsString(text)});"
        v

      case View.SignalText(signal) =>
        // Reactive — register the cell, create a text node bound
        // to its initial value, subscribe so future __setSignal
        // calls update the DOM.
        registerSignal(signal)
        val v = freshVar()
        val sigJs = jsString(signal.jsName)
        statements += s"const $v = document.createTextNode(__ssc_signals[$sigJs].value);"
        statements += s"__ssc_signals[$sigJs].subs.add((v) => { $v.textContent = v; });"
        v

      case View.Fragment(children) =>
        // Inline children into the parent — no DOM wrapper.  Return
        // null when the fragment is empty so the caller skips the
        // `appendChild`.
        if children.isEmpty then null
        else
          // Multi-child fragment: build a DocumentFragment so the
          // caller's single `appendChild` flushes all children.
          val v = freshVar()
          statements += s"const $v = document.createDocumentFragment();"
          children.foreach { child =>
            val childVar = compile(child)
            if childVar != null then statements += s"$v.appendChild($childVar);"
          }
          v

      case View.ComponentInstance(component, props) =>
        // Inline the component by calling its render(props) at emit
        // time and compiling the returned View.  This works as long
        // as the component's render is pure (no signal subscriptions
        // we need to wire up); A2b will switch to a structured IR.
        compile(component.render(props))

      case View.Show(cond, whenTrue, whenFalse) =>
        // Snapshot: pick the branch that cond() returns NOW.  Phase
        // A2b: emit conditional reactive subscription.
        val branch = if cond() then whenTrue() else whenFalse()
        compile(branch)

      case View.For(items, render) =>
        // Snapshot iteration: realise items() once and inline each
        // rendered view.  Phase A2b: emit a keyed-list reactive
        // patch loop.
        val realised = items()
        if realised.isEmpty then null
        else
          val v = freshVar()
          statements += s"const $v = document.createDocumentFragment();"
          realised.foreach { item =>
            val childVar = compile(render(item))
            if childVar != null then statements += s"$v.appendChild($childVar);"
          }
          v

    private def attrValueJs(av: AttrValue): Option[String] = av match
      case AttrValue.Str(value)     => Some(jsString(value))
      case AttrValue.Bool(value)    => Some(jsString(value.toString))
      case AttrValue.Num(value)     => Some(formatNumber(value))
      case AttrValue.Dynamic(read)  => Some(jsString(String.valueOf(read()))) // snapshot
      case AttrValue.Absent         => None

    private def formatNumber(d: Double): String =
      if d == d.toLong.toDouble then d.toLong.toString else d.toString

    /** Compile a single event handler into an `addEventListener`
     *  call on `targetVar`.  Simple / WithEvent are JVM closures
     *  that we can't translate to JS without a richer IR — they
     *  emit a marker comment for now.  SetSignalLiteral and
     *  IncrementSignal are A2c additions that lower cleanly. */
    private def compileEventHandler(targetVar: String, eventName: String, handler: EventHandler): Unit =
      handler match
        case EventHandler.Simple(_) | EventHandler.WithEvent(_) =>
          statements +=
            s"// $targetVar: '$eventName' handler is a JVM closure — A2c can't translate;" +
            " richer IR coming later."
        case EventHandler.SetSignalLiteral(signal, value) =>
          registerSignal(signal)
          val nameJs  = jsString(signal.jsName)
          val valueJs = jsLiteral(value)
          statements += s"$targetVar.addEventListener(${jsString(eventName)}, () => " +
                        s"__setSignal($nameJs, $valueJs));"
        case EventHandler.IncrementSignal(signal, by) =>
          registerSignal(signal)
          val nameJs = jsString(signal.jsName)
          statements += s"$targetVar.addEventListener(${jsString(eventName)}, () => " +
                        s"__setSignal($nameJs, __ssc_signals[$nameJs].value + $by));"

  /** JS literal for a signal value or SetSignalLiteral payload.
   *  Dispatches on runtime class because the trait surface is
   *  type-erased at the IR boundary. */
  private def jsLiteral(value: Any): String = value match
    case s: String     => jsString(s)
    case i: Int        => i.toString
    case l: Long       => l.toString
    case d: Double     => if d == d.toLong.toDouble then d.toLong.toString else d.toString
    case f: Float      => f.toDouble.toString
    case b: Boolean    => b.toString
    case null          => "null"
    case other         => throw new IllegalArgumentException(
      s"jsLiteral: unsupported value type ${other.getClass.getName} ($other).  " +
      "Supported: String / Int / Long / Double / Float / Boolean / null."
    )

  /** JS-encoded string literal — escapes the four characters
   *  (`\\`, `'`, newline, CR) that can break a single-quoted JS
   *  literal.  Other Unicode is passed through unchanged; the
   *  generated bundle is UTF-8 anyway. */
  private def jsString(s: String): String =
    val sb = new StringBuilder
    sb += '\''
    s.foreach {
      case '\\' => sb ++= "\\\\"
      case '\'' => sb ++= "\\'"
      case '\n' => sb ++= "\\n"
      case '\r' => sb ++= "\\r"
      case '<'  => sb ++= "\\u003c"  // belt-and-suspenders for inline scripts
      case c    => sb += c
    }
    sb += '\''
    sb.toString
