package scalascript.frontend.solid

import scala.annotation.nowarn
import scalascript.frontend.*

/** Emits idiomatic Solid that does NOT depend on `solid-js/h`.
 *  Reason: solid-js/h has an upstream import compatibility issue
 *  with recent solid-js/web (it tries to import `SVGElements`,
 *  which was removed).  Real Solid apps use the compiler-
 *  transformed JSX path instead.  We don't have a JSX compiler,
 *  so we hand-write what the compiler would produce: imperative
 *  DOM construction wired through `createSignal` +
 *  `createEffect` for fine-grained reactivity.
 *
 *  This is what makes Solid "Solid": each `createEffect` is its
 *  own reactive computation, subscribed only to the signals it
 *  reads.  No virtual DOM, no reconciliation pass.  Compare to
 *  Custom's `__ssc_signals` registry: same effect, slightly
 *  more code, but using the framework primitive instead of
 *  reimplementing it.
 *
 *  Lowerings:
 *    - `ReactiveSignal[T]`          → `const [x, setX] = createSignal(init)`
 *    - `View.Element`               → `document.createElement(tag)` +
 *                                     `setAttribute` + `appendChild`
 *    - `View.TextNode`              → `document.createTextNode(literal)`
 *    - `View.SignalText`            → `createTextNode(initialValue)` +
 *                                     `createEffect(() => node.textContent = signal())`
 *    - `View.Fragment`              → DocumentFragment with all children
 *    - `View.Show` / `View.For`     → emit-time snapshot
 *    - `SetSignalLiteral` event     → `addEventListener(evt, () => setX(value))`
 *    - `IncrementSignal` event      → `addEventListener(evt, () => setX(c => c + by))`
 *    - JVM-closure events           → marker comment */
@nowarn("cat=deprecation")
private[solid] object SolidEmitter:

  def emit(root: View[?]): String =
    val ctx = new Ctx
    val rootVar = ctx.compile(root)
    val sb = new StringBuilder
    sb ++= "// Generated by ScalaScript v1.18 — frontend-solid Phase A4 / A6.\n"
    sb ++= "// Idiomatic Solid: createSignal + createEffect + imperative DOM + refs/portals.\n"
    sb ++= "import { createSignal, createEffect } from 'solid-js';\n"
    // A6 — DomRef declarations live at module scope (above App) so user
    // JS can import / reference them after mount.  Also exposed on
    // window so out-of-module imperative JS can read them.
    if ctx.domRefs.nonEmpty then
      ctx.domRefs.toSeq.sorted.foreach { name =>
        sb ++= s"let $name = null;\n"
      }
      sb ++= "if (typeof window !== 'undefined') {\n"
      ctx.domRefs.toSeq.sorted.foreach { name =>
        sb ++= s"  Object.defineProperty(window, ${jsString(name)}, { get: () => $name, configurable: true });\n"
      }
      sb ++= "}\n"
    sb ++= "function App(root) {\n"
    ctx.signals.foreach { (name, initial) =>
      val setter = setterName(name)
      sb ++= s"  const [$name, $setter] = createSignal($initial);\n"
    }
    // A2e — list signals lower the same way scalar signals do: each
    // gets a createSignal pair.  Reads go through `name()` so
    // createEffect tracks them; writes go through `setName(next)`.
    ctx.lists.foreach { (name, initial) =>
      val setter = setterName(name)
      sb ++= s"  const [$name, $setter] = createSignal($initial);\n"
    }
    ctx.statements.foreach { stmt =>
      sb ++= "  "
      sb ++= stmt
      sb ++= "\n"
    }
    if rootVar != null then
      sb ++= s"  root.appendChild($rootVar);\n"
    sb ++= "}\n"
    sb ++= "App(document.getElementById('app'));\n"
    sb.toString

  private final class Ctx:
    private var counter: Int = 0
    val signals: scala.collection.mutable.LinkedHashMap[String, String] =
      scala.collection.mutable.LinkedHashMap.empty
    val lists: scala.collection.mutable.LinkedHashMap[String, String] =
      scala.collection.mutable.LinkedHashMap.empty
    // A6 — DomRef names referenced anywhere in the View tree; each
    // gets a module-scope `let <name> = null` declaration and is
    // assigned the live element node after createElement.
    val domRefs: scala.collection.mutable.LinkedHashSet[String] =
      scala.collection.mutable.LinkedHashSet.empty

    // A2e.2 — sub-scope state for capturing a render-item body.
    private var inItemTemplate: Boolean                          = false
    private var currentItemList: Option[ReactiveSignalList[?]]   = None
    private val statementStack: scala.collection.mutable.Stack[scala.collection.mutable.ArrayBuffer[String]] =
      scala.collection.mutable.Stack.empty

    private val _outerStatements: scala.collection.mutable.ArrayBuffer[String] =
      scala.collection.mutable.ArrayBuffer.empty

    def statements: scala.collection.mutable.ArrayBuffer[String] =
      if statementStack.isEmpty then _outerStatements
      else statementStack.top

    private def captureStatements[T](body: => T): (T, Seq[String]) =
      val buf = scala.collection.mutable.ArrayBuffer.empty[String]
      statementStack.push(buf)
      try (body, buf.toSeq)
      finally statementStack.pop()

    private def freshVar(): String =
      val v = s"n$counter"
      counter += 1
      v

    private def registerSignal(signal: ReactiveSignal[?]): Unit =
      val name = signal.id
      if !name.matches("[A-Za-z_][A-Za-z0-9_]*") then
        throw new IllegalArgumentException(
          s"ReactiveSignal id '$name' must match [A-Za-z_][A-Za-z0-9_]*."
        )
      val initJs = jsLiteral(signal())
      signals.get(name) match
        case Some(existing) if existing != initJs =>
          throw new IllegalArgumentException(
            s"ReactiveSignal id '$name' registered twice with different " +
            s"initial values ($existing vs $initJs)."
          )
        case _ => signals.update(name, initJs)

    private def registerList(list: ReactiveSignalList[?]): Unit =
      val name = list.id
      if !name.matches("[A-Za-z_][A-Za-z0-9_]*") then
        throw new IllegalArgumentException(
          s"ReactiveSignalList id '$name' must match [A-Za-z_][A-Za-z0-9_]*."
        )
      val initJs = jsArrayLiteral(list.initial)
      lists.get(name) match
        case Some(existing) if existing != initJs =>
          throw new IllegalArgumentException(
            s"ReactiveSignalList id '$name' registered twice with different " +
            s"initial values ($existing vs $initJs)."
          )
        case _ => lists.update(name, initJs)

    /** A6 — register a DomRef name + identifier-shape validation. */
    private def registerRef(ref: WidgetRef): Unit =
      val name = ref.id
      if !name.matches("[A-Za-z_][A-Za-z0-9_]*") then
        throw new IllegalArgumentException(
          s"WidgetRef id '$name' must match [A-Za-z_][A-Za-z0-9_]*."
        )
      domRefs += name

    def compile(view: View[?]): String | Null = view match
      case View.Element(tag, attrs, events, children) =>
        val v = freshVar()
        statements += s"const $v = document.createElement(${jsString(tag)});"
        attrs.foreach { (k, av) =>
          av match
            case AttrValue.RefBinding(ref) =>
              // A6 — imperative ref binding: assign the live node to the
              // module-scope variable after createElement.  Matches the
              // Custom backend's style (Solid's idiomatic `ref={el => x=el}`
              // requires the JSX path we don't transpile).
              registerRef(ref)
              statements += s"${ref.id} = $v;"
            case AttrValue.Bool(value) =>
              // Boolean IDL attributes (disabled, checked, required, …) must be
              // set as DOM properties — setAttribute("disabled","false") leaves
              // the attribute present so the browser still disables the element.
              // Hyphenated names (aria-*, data-*) are not valid JS identifiers,
              // so they go through setAttribute with the string value instead.
              if k.contains('-') then
                statements += s"$v.setAttribute(${jsString(k)}, ${jsString(value.toString)});"
              else
                statements += s"$v.$k = $value;"
            case AttrValue.Reactive(signal) =>
              // Reactive attrs must stay live — a snapshot via setAttribute
              // would bake in the initial value and never update.
              // Use createEffect so the property re-evaluates whenever
              // the signal changes.  Hyphenated names go via setAttribute.
              registerSignal(signal)
              if k.contains('-') then
                statements += s"createEffect(() => { $v.setAttribute(${jsString(k)}, String(${signal.id}())); });"
              else
                statements += s"createEffect(() => { $v.$k = ${signal.id}(); });"
            case _ =>
              attrValueJs(av) match
                case Some(value) => statements += s"$v.setAttribute(${jsString(k)}, $value);"
                case None        => ()
        }
        events.foreach { (eventName, handler) =>
          compileEventHandler(v, eventName, handler)
        }
        children.foreach { child =>
          val childVar = compile(child)
          if childVar != null then statements += s"$v.appendChild($childVar);"
        }
        v

      case View.TextNode(thunk) =>
        val v = freshVar()
        statements += s"const $v = document.createTextNode(${jsString(thunk())});"
        v

      case View.SignalText(signal, _) =>
        registerSignal(signal)
        val v = freshVar()
        // Solid's createEffect auto-tracks the signal read.  When
        // the signal changes, only this text node updates — no
        // virtual-DOM diff, no parent re-render.
        statements += s"const $v = document.createTextNode(${signal.id}());"
        statements += s"createEffect(() => { $v.textContent = ${signal.id}(); });"
        v

      case View.Fragment(children) =>
        if children.isEmpty then null
        else
          val v = freshVar()
          statements += s"const $v = document.createDocumentFragment();"
          children.foreach { child =>
            val childVar = compile(child)
            if childVar != null then statements += s"$v.appendChild($childVar);"
          }
          v

      case View.ComponentInstance(component, props) =>
        compile(component.render(props.asInstanceOf[Nothing]))

      case View.Show(cond, whenTrue, whenFalse) =>
        // Emit-time snapshot — use ShowSignal for reactive swap.
        val branch = if cond() then whenTrue() else whenFalse()
        compile(branch)

      case View.ShowSignal(cond, whenTrue, whenFalse) =>
        // Subscribe-and-swap, same shape as Custom but driven by
        // createEffect.  Wrapper span holds the currently-mounted
        // branch.  Pre-build both branches up front so nested
        // signal subscribers wire correctly.
        registerSignal(cond)
        val wrap = freshVar()
        statements += s"const $wrap = document.createElement('span'); $wrap.style.display = 'contents';"
        val tVar = compile(whenTrue)
        val fVar = compile(whenFalse)
        val tNode = if tVar != null then tVar else placeholderNode()
        val fNode = if fVar != null then fVar else placeholderNode()
        val currentVar = s"__show_${wrap}_current"
        statements += s"let $currentVar = ${cond.id}() ? $tNode : $fNode;"
        statements += s"$wrap.appendChild($currentVar);"
        statements += s"createEffect(() => {"
        statements += s"  const next = ${cond.id}() ? $tNode : $fNode;"
        statements += s"  if (next !== $currentVar) { $wrap.replaceChild(next, $currentVar); $currentVar = next; }"
        statements += s"});"
        wrap

      case View.For(items, render) =>
        val realised = items().toList
        if realised.isEmpty then null
        else
          val v = freshVar()
          statements += s"const $v = document.createDocumentFragment();"
          realised.foreach { item =>
            val childVar = compile(render(item))
            if childVar != null then statements += s"$v.appendChild($childVar);"
          }
          v

      case View.ForSignal(list, tag, attrs, itemTemplate) =>
        // A2e + A2e.2 — wrapper span + createEffect that rebuilds
        // children on every list change.  Simple form: render each
        // item as `<tag attrs>String(item)</tag>`.  Rich form: walk
        // the template inside a captured sub-scope so the buffered
        // statements form the body of the render-item function.
        registerList(list)
        val wrap     = freshVar()
        val renderFn = s"__render_item_${list.id}"
        statements += s"const $wrap = document.createElement('span');"

        itemTemplate match
          case None =>
            val tagJs = jsString(tag)
            val attrSetters = attrs.toSeq.flatMap { (k, av) =>
              attrValueJs(av).map(value => s"el.setAttribute(${jsString(k)}, $value);")
            }
            statements += s"function $renderFn(__item, __idx) {"
            statements += s"  const el = document.createElement($tagJs);"
            attrSetters.foreach(s => statements += s"  $s")
            statements += s"  el.textContent = String(__item);"
            statements += s"  return el;"
            statements += s"}"
          case Some(template) =>
            val prevFlag = inItemTemplate
            val prevList = currentItemList
            inItemTemplate  = true
            currentItemList = Some(list)
            val (rootVar, body) =
              try captureStatements(compile(template))
              finally
                inItemTemplate  = prevFlag
                currentItemList = prevList
            statements += s"function $renderFn(__item, __idx) {"
            body.foreach(stmt => statements += s"  $stmt")
            if rootVar == null then
              statements += s"  return document.createTextNode('');"
            else
              statements += s"  return $rootVar;"
            statements += s"}"

        statements += s"createEffect(() => {"
        statements += s"  while ($wrap.firstChild) $wrap.removeChild($wrap.firstChild);"
        statements += s"  let __idx = 0; for (const __item of ${list.id}()) { $wrap.appendChild($renderFn(__item, __idx)); __idx++; }"
        statements += s"});"
        wrap

      case View.ItemText =>
        val v = freshVar()
        if inItemTemplate then
          statements += s"const $v = document.createTextNode(String(__item));"
        else
          statements += s"const $v = document.createTextNode('');"
        v

      case View.Portal(target, children) =>
        // A6 — imperative portal: compile each child as usual, then
        // appendChild into document.querySelector(target).  Returns null
        // so the caller doesn't append anything to the parent.  Same
        // shape as Custom — solid-js/web's <Portal> needs JSX.
        val targetVar = freshVar()
        statements += s"const $targetVar = document.querySelector(${jsString(target)});"
        statements += s"if (!$targetVar) throw new Error('Portal target not found: ${target.replace("'", "\\'")}');"
        children.foreach { child =>
          val childVar = compile(child)
          if childVar != null then statements += s"$targetVar.appendChild($childVar);"
        }
        null

      case View.FetchTable(tableId, fetchUrl, deleteUrl, tick, hOpt) =>
        registerSignal(tick)
        hOpt.foreach(registerSignal)
        if !signals.contains(tableId) then signals.update(tableId, "[]")
        val setRows   = setterName(tableId)
        val setTick   = setterName(tick.id)
        val urlJs     = jsString(fetchUrl)
        val delUrlJs  = jsString(deleteUrl)
        val tickName  = tick.id
        val headersJs = hOpt.map(h => s", headers: JSON.parse(${h.id}() || '{}')").getOrElse("")
        val thStyle    = jsString("text-align:left;padding:6px 12px;border-bottom:2px solid #e5e7eb;font-weight:600;color:#111827")
        val tdStyle    = jsString("padding:6px 12px;border-bottom:1px solid #e5e7eb;color:#374151;vertical-align:middle")
        val btnStyle   = jsString("background:#ef4444;color:#fff;border:none;padding:6px 16px;border-radius:4px;cursor:pointer;font-size:inherit;font-family:inherit")
        val tableStyle = jsString("border-collapse:collapse;width:100%;font-family:inherit;font-size:inherit")
        val theadStyle = jsString("background:#f9fafb")
        val tableVar = freshVar()
        val tbodyVar = freshVar()
        val th1Var   = freshVar()
        val th2Var   = freshVar()
        val trHVar   = freshVar()
        val theadVar = freshVar()
        statements += s"const $tableVar = document.createElement('table'); $tableVar.setAttribute('style', $tableStyle);"
        statements += s"const $theadVar = document.createElement('thead'); $theadVar.setAttribute('style', $theadStyle);"
        statements += s"const $trHVar = document.createElement('tr');"
        statements += s"const $th1Var = document.createElement('th'); $th1Var.setAttribute('style', $thStyle); $th1Var.textContent = 'Task'; $trHVar.appendChild($th1Var);"
        statements += s"const $th2Var = document.createElement('th'); $th2Var.setAttribute('style', $thStyle); $th2Var.textContent = ''; $trHVar.appendChild($th2Var);"
        statements += s"$theadVar.appendChild($trHVar); $tableVar.appendChild($theadVar);"
        statements += s"const $tbodyVar = document.createElement('tbody'); $tableVar.appendChild($tbodyVar);"
        statements += s"fetch($urlJs$headersJs).then(r => r.json()).then(data => $setRows(data));"
        statements += s"createEffect(() => { const t = $tickName(); if (t > 0) fetch($urlJs$headersJs).then(r => r.json()).then(data => $setRows(data)); });"
        statements += s"createEffect(() => {"
        statements += s"  while ($tbodyVar.firstChild) $tbodyVar.removeChild($tbodyVar.firstChild);"
        statements += s"  for (const row of $tableId()) {"
        statements += s"    const tr = document.createElement('tr');"
        statements += s"    const td1 = document.createElement('td'); td1.setAttribute('style', $tdStyle); td1.textContent = String(row.text); tr.appendChild(td1);"
        statements += s"    const td2 = document.createElement('td'); td2.setAttribute('style', $tdStyle);"
        statements += s"    const btn = document.createElement('button'); btn.setAttribute('style', $btnStyle); btn.textContent = 'Delete';"
        statements += s"    btn.addEventListener('click', () => fetch($delUrlJs, {method: 'POST', body: String(row.id)$headersJs}).then(r => r.text()).then(_ => $setTick(t => t + 1)));"
        statements += s"    td2.appendChild(btn); tr.appendChild(td2); $tbodyVar.appendChild(tr);"
        statements += s"  }"
        statements += s"});"
        tableVar

      // ── P2 semantic View cases ───────────────────────────────────────────────

      case View.Column(children, spacing, align, style) =>
        val gapCss = if spacing > 0 then s"; gap: ${spacing}px" else ""
        val base   = s"display: flex; flex-direction: column; align-items: ${StyleUtils.hAlignToCSS(align)}$gapCss"
        val css    = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
        val v = freshVar()
        statements += s"const $v = document.createElement('div'); $v.setAttribute('style', ${jsString(css)});"
        children.foreach { child =>
          val cVar = compile(child)
          if cVar != null then statements += s"$v.appendChild($cVar);"
        }
        v

      case View.Row(children, spacing, align, style) =>
        val gapCss = if spacing > 0 then s"; gap: ${spacing}px" else ""
        val base   = s"display: flex; flex-direction: row; align-items: ${StyleUtils.vAlignToCSS(align)}$gapCss"
        val css    = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
        val v = freshVar()
        statements += s"const $v = document.createElement('div'); $v.setAttribute('style', ${jsString(css)});"
        children.foreach { child =>
          val cVar = compile(child)
          if cVar != null then statements += s"$v.appendChild($cVar);"
        }
        v

      case View.Stack(children, style) =>
        val css = StyleUtils.mergeCSS("position: relative", StyleUtils.styleToCSS(style))
        val v = freshVar()
        statements += s"const $v = document.createElement('div'); $v.setAttribute('style', ${jsString(css)});"
        children.foreach { child =>
          val cVar = compile(child)
          if cVar != null then statements += s"$v.appendChild($cVar);"
        }
        v

      case View.ScrollView(child, axis, style) =>
        val base = axis match
          case Axis.Horizontal => "overflow-x: auto; overflow-y: hidden"
          case Axis.Vertical   => "overflow-y: auto; overflow-x: hidden"
          case Axis.Both       => "overflow: auto"
        val css  = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
        val v    = freshVar()
        statements += s"const $v = document.createElement('div'); $v.setAttribute('style', ${jsString(css)});"
        val cVar = compile(child)
        if cVar != null then statements += s"$v.appendChild($cVar);"
        v

      case View.Spacer(size) =>
        val css = size match
          case Some(px) => s"width: ${px}px; height: ${px}px; flex-shrink: 0"
          case None     => "flex: 1; align-self: stretch"
        val v = freshVar()
        statements += s"const $v = document.createElement('div'); $v.setAttribute('style', ${jsString(css)});"
        v

      case View.Divider(axis, style) =>
        val base = axis match
          case Axis.Vertical => "width: 1px; height: 100%; background: currentColor; opacity: 0.2; flex-shrink: 0"
          case _             => "width: 100%; height: 1px; background: currentColor; opacity: 0.2; flex-shrink: 0"
        val css = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
        val v   = freshVar()
        statements += s"const $v = document.createElement('div'); $v.setAttribute('style', ${jsString(css)}); $v.setAttribute('role', 'separator');"
        v

      case View.Text(content, style) =>
        val css = StyleUtils.styleToCSS(style)
        val v   = freshVar()
        val txt = freshVar()
        statements += s"const $v = document.createElement('span');"
        if css.nonEmpty then statements += s"$v.setAttribute('style', ${jsString(css)});"
        statements += s"const $txt = document.createTextNode(${jsString(content())}); $v.appendChild($txt);"
        v

      case View.Image(source, style) =>
        val src = source match
          case ImageSource.Url(href)           => jsString(href)
          case ImageSource.Asset(name)         => jsString(s"/assets/$name")
          case ImageSource.Base64(data, mime)  => jsString(s"data:$mime;base64,$data")
        val v   = freshVar()
        val css = StyleUtils.styleToCSS(style)
        statements += s"const $v = document.createElement('img'); $v.setAttribute('src', $src);"
        if css.nonEmpty then statements += s"$v.setAttribute('style', ${jsString(css)});"
        v

      case View.Icon(name, style) =>
        val v   = freshVar()
        val css = StyleUtils.styleToCSS(style)
        statements += s"const $v = document.createElement('span'); $v.setAttribute('aria-hidden', 'true'); $v.setAttribute('data-icon', ${jsString(name)}); $v.textContent = ${jsString(name)};"
        if css.nonEmpty then statements += s"$v.setAttribute('style', ${jsString(css)});"
        v

      case View.Button(label, action, enabled, style) =>
        val base = "cursor: pointer; display: inline-flex; align-items: center; justify-content: center; border: none; padding: 6px 16px; border-radius: 4px"
        val css  = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
        val v    = freshVar()
        statements += s"const $v = document.createElement('button'); $v.setAttribute('style', ${jsString(css)});"
        if !enabled() then statements += s"$v.disabled = true;"
        val labelVar = compile(label)
        if labelVar != null then statements += s"$v.appendChild($labelVar);"
        compileEventHandler(v, "click", action)
        v

      case View.TextInput(value, placeholder, multiline, secure, style) =>
        registerSignal(value)
        val base = "padding: 6px 10px; border: 1px solid #d1d5db; border-radius: 4px; font-size: inherit; font-family: inherit"
        val css  = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
        val setter = setterName(value.id)
        val v = freshVar()
        if multiline then
          statements += s"const $v = document.createElement('textarea'); $v.setAttribute('style', ${jsString(css)}); $v.setAttribute('placeholder', ${jsString(placeholder)});"
          statements += s"$v.value = ${value.id}();"
          statements += s"createEffect(() => { $v.value = ${value.id}(); });"
          statements += s"$v.addEventListener('input', (e) => $setter(e.target.value));"
        else
          val typeStr = if secure then "password" else "text"
          statements += s"const $v = document.createElement('input'); $v.setAttribute('type', '$typeStr'); $v.setAttribute('style', ${jsString(css)}); $v.setAttribute('placeholder', ${jsString(placeholder)});"
          statements += s"$v.value = ${value.id}();"
          statements += s"createEffect(() => { $v.value = ${value.id}(); });"
          statements += s"$v.addEventListener('input', (e) => $setter(e.target.value));"
        v

      case View.Toggle(checked, label, style) =>
        registerSignal(checked)
        val base = "display: inline-flex; align-items: center; gap: 6px; cursor: pointer"
        val css  = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
        val setter = setterName(checked.id)
        val v   = freshVar()
        val inp = freshVar()
        statements += s"const $v = document.createElement('label'); $v.setAttribute('style', ${jsString(css)});"
        statements += s"const $inp = document.createElement('input'); $inp.setAttribute('type', 'checkbox');"
        statements += s"$inp.checked = ${checked.id}();"
        statements += s"createEffect(() => { $inp.checked = ${checked.id}(); });"
        statements += s"$inp.addEventListener('change', () => $setter(c => !c));"
        statements += s"$v.appendChild($inp);"
        if label.nonEmpty then
          statements += s"$v.appendChild(document.createTextNode(${jsString(label)}));"
        v

      case View.Slider(value, min, max, step, style) =>
        registerSignal(value)
        val css    = StyleUtils.styleToCSS(style)
        val setter = setterName(value.id)
        val v = freshVar()
        statements += s"const $v = document.createElement('input'); $v.setAttribute('type', 'range'); $v.setAttribute('min', '$min'); $v.setAttribute('max', '$max'); $v.setAttribute('step', '$step');"
        if css.nonEmpty then statements += s"$v.setAttribute('style', ${jsString(css)});"
        statements += s"$v.value = ${value.id}();"
        statements += s"createEffect(() => { $v.value = ${value.id}(); });"
        statements += s"$v.addEventListener('input', (e) => $setter(Number(e.target.value)));"
        v

      case View.Picker(options, selected, placeholder, style) =>
        registerSignal(selected)
        val base   = "padding: 6px 10px; border: 1px solid #d1d5db; border-radius: 4px; font-size: inherit; font-family: inherit"
        val css    = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
        val setter = setterName(selected.id)
        val v = freshVar()
        statements += s"const $v = document.createElement('select'); $v.setAttribute('style', ${jsString(css)});"
        if placeholder.nonEmpty then
          statements += s"{ const o = document.createElement('option'); o.value = ''; o.disabled = true; o.hidden = true; o.textContent = ${jsString(placeholder)}; $v.appendChild(o); }"
        options.foreach { (lbl, opt) =>
          val vJs = try jsLiteral(opt) catch { case _: Throwable => jsString(String.valueOf(opt)) }
          statements += s"{ const o = document.createElement('option'); o.value = $vJs; o.textContent = ${jsString(lbl)}; $v.appendChild(o); }"
        }
        statements += s"$v.value = String(${selected.id}());"
        statements += s"createEffect(() => { $v.value = String(${selected.id}()); });"
        statements += s"$v.addEventListener('change', (e) => $setter(e.target.value));"
        v

      case View.LazyList(items, render, _, style) =>
        val css = StyleUtils.mergeCSS("overflow-y: auto", StyleUtils.styleToCSS(style))
        val v   = freshVar()
        statements += s"const $v = document.createElement('div'); $v.setAttribute('style', ${jsString(css)});"
        items().toList.foreach { item =>
          val cVar = compile(render(item))
          if cVar != null then statements += s"$v.appendChild($cVar);"
        }
        v

      case View.LazyGrid(items, render, columns, spacing, style) =>
        val colsCss = StyleUtils.gridColumnsToCSS(columns)
        val gapCss  = if spacing > 0 then s"; gap: ${spacing}px" else ""
        val base    = s"display: grid; grid-template-columns: $colsCss$gapCss"
        val css     = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
        val v = freshVar()
        statements += s"const $v = document.createElement('div'); $v.setAttribute('style', ${jsString(css)});"
        items().toList.foreach { item =>
          val cVar = compile(render(item))
          if cVar != null then statements += s"$v.appendChild($cVar);"
        }
        v

      case View.TabBar(tabs, current, style) =>
        registerSignal(current)
        val outerCss  = StyleUtils.styleToCSS(style)
        val headerCss = "display: flex; border-bottom: 1px solid #e5e7eb; margin-bottom: 8px"
        val activeCss   = "cursor: pointer; padding: 8px 16px; border: none; background: transparent; font-family: inherit; font-size: inherit; border-bottom: 2px solid #3b82f6; font-weight: bold"
        val inactiveCss = "cursor: pointer; padding: 8px 16px; border: none; background: transparent; font-family: inherit; font-size: inherit; border-bottom: 2px solid transparent"
        val setter     = setterName(current.id)
        val v          = freshVar()
        val headerDiv  = freshVar()
        val contentDiv = freshVar()
        statements += s"const $v = document.createElement('div');"
        if outerCss.nonEmpty then statements += s"$v.setAttribute('style', ${jsString(outerCss)});"
        statements += s"const $headerDiv = document.createElement('div'); $headerDiv.setAttribute('style', ${jsString(headerCss)}); $v.appendChild($headerDiv);"
        statements += s"const $contentDiv = document.createElement('div'); $v.appendChild($contentDiv);"
        val tabVars = tabs.zipWithIndex.map { (tab, i) =>
          val btn = freshVar()
          statements += s"const $btn = document.createElement('button'); $btn.textContent = ${jsString(tab.label)};"
          statements += s"$btn.addEventListener('click', () => $setter($i));"
          statements += s"$headerDiv.appendChild($btn);"
          (i, btn, compile(tab.content))
        }
        statements += s"function __syncTabs_${v}() {"
        statements += s"  const t = ${current.id}();"
        tabVars.foreach { (i, btn, _) =>
          statements += s"  $btn.setAttribute('style', t === $i ? ${jsString(activeCss)} : ${jsString(inactiveCss)});"
        }
        statements += s"  while ($contentDiv.firstChild) $contentDiv.removeChild($contentDiv.firstChild);"
        tabVars.foreach { (i, _, cVar) =>
          if cVar != null then
            statements += s"  if (t === $i) $contentDiv.appendChild($cVar);"
        }
        statements += s"}"
        statements += s"__syncTabs_${v}();"
        statements += s"createEffect(() => __syncTabs_${v}());"
        v

      case View.NavigationStack(routes, current, style) =>
        registerSignal(current)
        val outerCss = StyleUtils.styleToCSS(style)
        val v        = freshVar()
        val content  = freshVar()
        statements += s"const $v = document.createElement('div');"
        if outerCss.nonEmpty then statements += s"$v.setAttribute('style', ${jsString(outerCss)});"
        statements += s"const $content = document.createElement('div'); $v.appendChild($content);"
        val routeVars = routes.toList.map { (key, fn) => (key, compile(fn())) }
        statements += s"function __syncNav_${v}() {"
        statements += s"  const r = ${current.id}();"
        statements += s"  while ($content.firstChild) $content.removeChild($content.firstChild);"
        routeVars.foreach { (key, cVar) =>
          if cVar != null then
            statements += s"  if (r === ${jsString(key)}) $content.appendChild($cVar);"
        }
        statements += s"}"
        statements += s"__syncNav_${v}();"
        statements += s"createEffect(() => __syncNav_${v}());"
        v

      case View.Sheet(content, isPresented) =>
        registerSignal(isPresented)
        val overlayCss  = "position: fixed; bottom: 0; left: 0; right: 0; background: #fff; box-shadow: 0 -4px 12px rgba(0,0,0,0.15); border-radius: 12px 12px 0 0; padding: 16px; z-index: 1000"
        val backdropCss = "position: fixed; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0,0,0,0.4); z-index: 999"
        val setter = setterName(isPresented.id)
        val wrap    = freshVar()
        val backdrop = freshVar()
        val overlay  = freshVar()
        val contentVar = compile(content)
        statements += s"const $wrap = document.createDocumentFragment();"
        statements += s"const $backdrop = document.createElement('div'); $backdrop.setAttribute('style', ${jsString(backdropCss)}); $backdrop.addEventListener('click', () => $setter(false)); $backdrop.style.display = 'none';"
        statements += s"const $overlay = document.createElement('div'); $overlay.setAttribute('style', ${jsString(overlayCss)}); $overlay.style.display = 'none';"
        if contentVar != null then statements += s"$overlay.appendChild($contentVar);"
        statements += s"$wrap.appendChild($backdrop); $wrap.appendChild($overlay);"
        statements += s"createEffect(() => { const show = ${isPresented.id}(); $backdrop.style.display = show ? 'block' : 'none'; $overlay.style.display = show ? 'block' : 'none'; });"
        wrap

      case View.AlertDialog(title, message, buttons, isPresented) =>
        registerSignal(isPresented)
        val dialogCss   = "position: fixed; top: 50%; left: 50%; transform: translate(-50%,-50%); background: #fff; padding: 24px; border-radius: 8px; box-shadow: 0 4px 32px rgba(0,0,0,0.2); z-index: 1001; min-width: 300px"
        val backdropCss = "position: fixed; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0,0,0,0.4); z-index: 1000"
        val btnDefault     = "background: #3b82f6; color: #fff; border: none; padding: 8px 16px; border-radius: 4px; cursor: pointer; font-family: inherit; font-size: inherit"
        val btnDestructive = "background: #ef4444; color: #fff; border: none; padding: 8px 16px; border-radius: 4px; cursor: pointer; font-family: inherit; font-size: inherit"
        val setter = setterName(isPresented.id)
        val wrap      = freshVar()
        val backdrop  = freshVar()
        val dialog    = freshVar()
        statements += s"const $wrap = document.createDocumentFragment();"
        statements += s"const $backdrop = document.createElement('div'); $backdrop.setAttribute('style', ${jsString(backdropCss)}); $backdrop.style.display = 'none';"
        statements += s"const $dialog = document.createElement('div'); $dialog.setAttribute('style', ${jsString(dialogCss)}); $dialog.style.display = 'none';"
        statements += s"{ const h3 = document.createElement('h3'); h3.textContent = ${jsString(title)}; $dialog.appendChild(h3); }"
        statements += s"{ const p = document.createElement('p'); p.textContent = ${jsString(message)}; $dialog.appendChild(p); }"
        statements += s"{ const row = document.createElement('div'); row.setAttribute('style', 'display: flex; gap: 8px; margin-top: 16px');"
        buttons.foreach { btn =>
          val css = if btn.role == ButtonRole.Destructive then btnDestructive else btnDefault
          statements += s"  { const b = document.createElement('button'); b.setAttribute('style', ${jsString(css)}); b.textContent = ${jsString(btn.label)}; b.addEventListener('click', () => $setter(false)); row.appendChild(b); }"
        }
        statements += s"  $dialog.appendChild(row); }"
        statements += s"$wrap.appendChild($backdrop); $wrap.appendChild($dialog);"
        statements += s"createEffect(() => { const show = ${isPresented.id}(); $backdrop.style.display = show ? 'block' : 'none'; $dialog.style.display = show ? 'block' : 'none'; });"
        wrap

      case View.Form(child, onSubmit, style) =>
        val css = StyleUtils.styleToCSS(style)
        val v   = freshVar()
        statements += s"const $v = document.createElement('form');"
        if css.nonEmpty then statements += s"$v.setAttribute('style', ${jsString(css)});"
        compileEventHandler(v, "submit", onSubmit)
        // Also prevent default on submit
        statements += s"$v.addEventListener('submit', (e) => e.preventDefault());"
        val cVar = compile(child)
        if cVar != null then statements += s"$v.appendChild($cVar);"
        v

      case View.FormField(label, value, validate, style) =>
        registerSignal(value)
        val errorMsg  = try validate(value().asInstanceOf[Nothing]) catch { case _: Throwable => None }
        val inputBase = "padding: 6px 10px; border: 1px solid #d1d5db; border-radius: 4px; width: 100%; box-sizing: border-box; font-size: inherit; font-family: inherit"
        val inputCss  = StyleUtils.mergeCSS(inputBase, StyleUtils.styleToCSS(style))
        val labelCss  = "display: block; margin-bottom: 4px; font-size: 0.875em; font-weight: 500"
        val setter    = setterName(value.id)
        val v   = freshVar()
        val inp = freshVar()
        statements += s"const $v = document.createElement('label'); $v.setAttribute('style', ${jsString(labelCss)});"
        statements += s"$v.appendChild(document.createTextNode(${jsString(label)}));"
        statements += s"const $inp = document.createElement('input'); $inp.setAttribute('style', ${jsString(inputCss)});"
        statements += s"$inp.value = String(${value.id}());"
        statements += s"createEffect(() => { $inp.value = String(${value.id}()); });"
        statements += s"$inp.addEventListener('input', (e) => $setter(e.target.value));"
        statements += s"$v.appendChild($inp);"
        errorMsg.foreach { msg =>
          statements += s"{ const err = document.createElement('span'); err.setAttribute('style', ${jsString("color: #ef4444; font-size: 0.75em; display: block; margin-top: 2px")}); err.textContent = ${jsString(msg)}; $v.appendChild(err); }"
        }
        v

      case View.SafeArea(child, edges) =>
        val top    = if edges.contains(Edge.Top)      then "env(safe-area-inset-top, 0)" else "0"
        val right  = if edges.contains(Edge.Trailing) then "env(safe-area-inset-right, 0)" else "0"
        val bottom = if edges.contains(Edge.Bottom)   then "env(safe-area-inset-bottom, 0)" else "0"
        val left   = if edges.contains(Edge.Leading)  then "env(safe-area-inset-left, 0)" else "0"
        val css    = s"padding-top: $top; padding-right: $right; padding-bottom: $bottom; padding-left: $left"
        val v = freshVar()
        statements += s"const $v = document.createElement('div'); $v.setAttribute('style', ${jsString(css)});"
        val cVar = compile(child)
        if cVar != null then statements += s"$v.appendChild($cVar);"
        v

      case View.KeyboardAvoiding(child) =>
        compile(child)

      case View.Animated(child, transition, style) =>
        val dur    = transition.duration.toLong
        val delay  = if transition.delay > 0 then s" ${transition.delay.toLong}ms" else ""
        val base   = s"transition: all ${dur}ms ${StyleUtils.curveToCSS(transition.curve)}$delay"
        val css    = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
        val v = freshVar()
        statements += s"const $v = document.createElement('div'); $v.setAttribute('style', ${jsString(css)});"
        val cVar = compile(child)
        if cVar != null then statements += s"$v.appendChild($cVar);"
        v

      case View.Styled(child, style) =>
        val css = StyleUtils.styleToCSS(style)
        if css.isEmpty then compile(child)
        else
          val v = freshVar()
          statements += s"const $v = document.createElement('div'); $v.setAttribute('style', ${jsString(css)});"
          val cVar = compile(child)
          if cVar != null then statements += s"$v.appendChild($cVar);"
          v

      case View.Adaptive(web, _, _, fallback) =>
        compile(web.getOrElse(fallback))

      case View.ModelView(_, _, template, _)   => compile(template)
      case View.ForModel(_, _, _, template, _) => compile(template)
      case View.ModelText(_, _, _)             => null

    private def compileEventHandler(targetVar: String, eventName: String, handler: EventHandler): Unit =
      handler match
        case EventHandler.Simple(_) | EventHandler.WithEvent(_) =>
          statements +=
            s"// $targetVar: '$eventName' handler is a JVM closure — A4 can't translate;" +
            " richer IR coming later."
        case EventHandler.InputChange(signal) =>
          registerSignal(signal)
          val setter = setterName(signal.id)
          statements += s"$targetVar.addEventListener('input', (e) => $setter(e.target.value));"
        case EventHandler.SetSignalLiteral(signal, value) =>
          registerSignal(signal)
          val setter = setterName(signal.id)
          val v      = jsLiteral(value)
          statements += s"$targetVar.addEventListener(${jsString(eventName)}, () => $setter($v));"
        case EventHandler.IncrementSignal(signal, by) =>
          registerSignal(signal)
          val setter = setterName(signal.id)
          statements += s"$targetVar.addEventListener(${jsString(eventName)}, () => $setter(c => c + $by));"
        case EventHandler.ToggleSignal(signal) =>
          registerSignal(signal)
          val setter = setterName(signal.id)
          statements += s"$targetVar.addEventListener(${jsString(eventName)}, () => $setter(c => !c));"
        case EventHandler.PushSignalLiteral(list, value) =>
          registerList(list)
          val setter = setterName(list.id)
          val v      = jsLiteral(value)
          statements += s"$targetVar.addEventListener(${jsString(eventName)}, () => $setter(prev => prev.concat([$v])));"
        case EventHandler.ClearSignalList(list) =>
          registerList(list)
          val setter = setterName(list.id)
          statements += s"$targetVar.addEventListener(${jsString(eventName)}, () => $setter([]));"
        case EventHandler.FetchAction(method, url, body, tick, clearBody, hOpt) =>
          registerSignal(body)
          registerSignal(tick)
          hOpt.foreach(registerSignal)
          val setTick   = setterName(tick.id)
          val setBody   = setterName(body.id)
          val urlJs     = jsString(url)
          val methodJs  = jsString(method)
          val clearJs   = if clearBody then s" $setBody('');" else ""
          val headersJs = hOpt.map(h => s", headers: JSON.parse(${h.id}() || '{}')").getOrElse("")
          statements += s"$targetVar.addEventListener(${jsString(eventName)}, () => " +
            s"fetch($urlJs, {method: $methodJs, body: ${body.id}()$headersJs})" +
            s".then(r => r.text()).then(_ => { $setTick(t => t + 1);$clearJs }));"
        case EventHandler.RemoveSelfFromList(list) =>
          // A2e.2 — only meaningful inside an item template.  Capture
          // __idx in an IIFE so each emitted listener remembers its
          // own slot for the .filter() call.
          if inItemTemplate && currentItemList.exists(_.id == list.id) then
            registerList(list)
            val setter = setterName(list.id)
            statements += s"$targetVar.addEventListener(${jsString(eventName)}, ((__capturedIdx) => () => " +
                          s"$setter(prev => prev.filter((_, i) => i !== __capturedIdx)))(__idx));"
          else
            statements +=
              s"// $targetVar: '$eventName' is RemoveSelfFromList used outside an item template — no-op."

    /** Empty-branch placeholder for ShowSignal — empty text node. */
    private def placeholderNode(): String =
      val v = freshVar()
      statements += s"const $v = document.createTextNode('');"
      v

    private def attrValueJs(av: AttrValue): Option[String] = av match
      case AttrValue.Str(value)     => Some(jsString(value))
      case AttrValue.Bool(_)        => None  // handled as property assignment before attrValueJs is called
      case AttrValue.Num(value)     => Some(formatNumber(value))
      case AttrValue.Dynamic(read)    => Some(jsString(String.valueOf(read())))
      case AttrValue.Reactive(_) => None  // handled as createEffect binding in View.Element
      case AttrValue.Absent           => None
      case AttrValue.RefBinding(_)    => None  // ref binding is wired imperatively in the Element case; no setAttribute

  private def setterName(varName: String): String =
    "set" + varName.headOption.fold("")(_.toUpper.toString) + varName.drop(1)

  private def jsLiteral(value: Any): String = value match
    case s: String  => jsString(s)
    case i: Int     => i.toString
    case l: Long    => l.toString
    case d: Double  => formatNumber(d)
    case f: Float   => formatNumber(f.toDouble)
    case b: Boolean => b.toString
    case null       => "null"
    case other      => throw new IllegalArgumentException(
      s"jsLiteral: unsupported value type ${other.getClass.getName} ($other).  " +
      "Supported: String / Int / Long / Double / Float / Boolean / null."
    )

  private def jsArrayLiteral(items: Seq[Any]): String =
    items.map(jsLiteral).mkString("[", ", ", "]")

  private def formatNumber(d: Double): String =
    if d == d.toLong.toDouble then d.toLong.toString else d.toString

  private def jsString(s: String): String =
    val sb = new StringBuilder
    sb += '\''
    s.foreach {
      case '\\' => sb ++= "\\\\"
      case '\'' => sb ++= "\\'"
      case '\n' => sb ++= "\\n"
      case '\r' => sb ++= "\\r"
      case '<'  => sb ++= "\\u003c"
      case c    => sb += c
    }
    sb += '\''
    sb.toString
