package scalascript.frontend.solid

import scalascript.frontend.*

/** Emits idiomatic Solid that does NOT depend on `solid-js/h`.
 *  Reason: solid-js/h has an upstream import compatibility issue
 *  with recent solid-js/web (it tries to import `SVGElements`,
 *  which was removed).  Real Solid apps use the compiler-
 *  transformed JSX path instead.  We don't have a JSX compiler,
 *  so we hand-write what the compiler would produce: imperative
 *  DOM construction wired through `createSignal` +
 *  `createEffect` for fine-grained reactivity.
 *
 *  This is what makes Solid "Solid": each `createEffect` is its
 *  own reactive computation, subscribed only to the signals it
 *  reads.  No virtual DOM, no reconciliation pass.  Compare to
 *  Custom's `__ssc_signals` registry: same effect, slightly
 *  more code, but using the framework primitive instead of
 *  reimplementing it.
 *
 *  Lowerings:
 *    - `ReactiveSignal[T]`          → `const [x, setX] = createSignal(init)`
 *    - `View.Element`               → `document.createElement(tag)` +
 *                                     `setAttribute` + `appendChild`
 *    - `View.TextNode`              → `document.createTextNode(literal)`
 *    - `View.SignalText`            → `createTextNode(initialValue)` +
 *                                     `createEffect(() => node.textContent = signal())`
 *    - `View.Fragment`              → DocumentFragment with all children
 *    - `View.Show` / `View.For`     → emit-time snapshot
 *    - `SetSignalLiteral` event     → `addEventListener(evt, () => setX(value))`
 *    - `IncrementSignal` event      → `addEventListener(evt, () => setX(c => c + by))`
 *    - JVM-closure events           → marker comment */
private[solid] object SolidEmitter:

  def emit(root: View): String =
    val ctx = new Ctx
    val rootVar = ctx.compile(root)
    val sb = new StringBuilder
    sb ++= "// Generated by ScalaScript v1.18 — frontend-solid Phase A4 / A6.\n"
    sb ++= "// Idiomatic Solid: createSignal + createEffect + imperative DOM + refs/portals.\n"
    sb ++= "import { createSignal, createEffect } from 'solid-js';\n"
    // A6 — DomRef declarations live at module scope (above App) so user
    // JS can import / reference them after mount.  Also exposed on
    // window so out-of-module imperative JS can read them.
    if ctx.domRefs.nonEmpty then
      ctx.domRefs.toSeq.sorted.foreach { name =>
        sb ++= s"let $name = null;\n"
      }
      sb ++= "if (typeof window !== 'undefined') {\n"
      ctx.domRefs.toSeq.sorted.foreach { name =>
        sb ++= s"  Object.defineProperty(window, ${jsString(name)}, { get: () => $name, configurable: true });\n"
      }
      sb ++= "}\n"
    sb ++= "function App(root) {\n"
    ctx.signals.foreach { (name, initial) =>
      val setter = setterName(name)
      sb ++= s"  const [$name, $setter] = createSignal($initial);\n"
    }
    // A2e — list signals lower the same way scalar signals do: each
    // gets a createSignal pair.  Reads go through `name()` so
    // createEffect tracks them; writes go through `setName(next)`.
    ctx.lists.foreach { (name, initial) =>
      val setter = setterName(name)
      sb ++= s"  const [$name, $setter] = createSignal($initial);\n"
    }
    ctx.statements.foreach { stmt =>
      sb ++= "  "
      sb ++= stmt
      sb ++= "\n"
    }
    if rootVar != null then
      sb ++= s"  root.appendChild($rootVar);\n"
    sb ++= "}\n"
    sb ++= "App(document.getElementById('app'));\n"
    sb.toString

  private final class Ctx:
    private var counter: Int = 0
    val signals: scala.collection.mutable.LinkedHashMap[String, String] =
      scala.collection.mutable.LinkedHashMap.empty
    val lists: scala.collection.mutable.LinkedHashMap[String, String] =
      scala.collection.mutable.LinkedHashMap.empty
    // A6 — DomRef names referenced anywhere in the View tree; each
    // gets a module-scope `let <name> = null` declaration and is
    // assigned the live element node after createElement.
    val domRefs: scala.collection.mutable.LinkedHashSet[String] =
      scala.collection.mutable.LinkedHashSet.empty

    // A2e.2 — sub-scope state for capturing a render-item body.
    private var inItemTemplate: Boolean                          = false
    private var currentItemList: Option[ReactiveSignalList[?]]   = None
    private val statementStack: scala.collection.mutable.Stack[scala.collection.mutable.ArrayBuffer[String]] =
      scala.collection.mutable.Stack.empty

    private val _outerStatements: scala.collection.mutable.ArrayBuffer[String] =
      scala.collection.mutable.ArrayBuffer.empty

    def statements: scala.collection.mutable.ArrayBuffer[String] =
      if statementStack.isEmpty then _outerStatements
      else statementStack.top

    private def captureStatements[T](body: => T): (T, Seq[String]) =
      val buf = scala.collection.mutable.ArrayBuffer.empty[String]
      statementStack.push(buf)
      try (body, buf.toSeq)
      finally statementStack.pop()

    private def freshVar(): String =
      val v = s"n$counter"
      counter += 1
      v

    private def registerSignal(signal: ReactiveSignal[?]): Unit =
      val name = signal.jsName
      if !name.matches("[A-Za-z_][A-Za-z0-9_]*") then
        throw new IllegalArgumentException(
          s"ReactiveSignal jsName '$name' must match [A-Za-z_][A-Za-z0-9_]*."
        )
      val initJs = jsLiteral(signal())
      signals.get(name) match
        case Some(existing) if existing != initJs =>
          throw new IllegalArgumentException(
            s"ReactiveSignal jsName '$name' registered twice with different " +
            s"initial values ($existing vs $initJs)."
          )
        case _ => signals.update(name, initJs)

    private def registerList(list: ReactiveSignalList[?]): Unit =
      val name = list.jsName
      if !name.matches("[A-Za-z_][A-Za-z0-9_]*") then
        throw new IllegalArgumentException(
          s"ReactiveSignalList jsName '$name' must match [A-Za-z_][A-Za-z0-9_]*."
        )
      val initJs = jsArrayLiteral(list.initial)
      lists.get(name) match
        case Some(existing) if existing != initJs =>
          throw new IllegalArgumentException(
            s"ReactiveSignalList jsName '$name' registered twice with different " +
            s"initial values ($existing vs $initJs)."
          )
        case _ => lists.update(name, initJs)

    /** A6 — register a DomRef name + identifier-shape validation. */
    private def registerRef(ref: DomRef): Unit =
      val name = ref.jsName
      if !name.matches("[A-Za-z_][A-Za-z0-9_]*") then
        throw new IllegalArgumentException(
          s"DomRef jsName '$name' must match [A-Za-z_][A-Za-z0-9_]*."
        )
      domRefs += name

    def compile(view: View): String | Null = view match
      case View.Element(tag, attrs, events, children) =>
        val v = freshVar()
        statements += s"const $v = document.createElement(${jsString(tag)});"
        attrs.foreach { (k, av) =>
          av match
            case AttrValue.RefBinding(ref) =>
              // A6 — imperative ref binding: assign the live node to the
              // module-scope variable after createElement.  Matches the
              // Custom backend's style (Solid's idiomatic `ref={el => x=el}`
              // requires the JSX path we don't transpile).
              registerRef(ref)
              statements += s"${ref.jsName} = $v;"
            case _ =>
              attrValueJs(av) match
                case Some(value) => statements += s"$v.setAttribute(${jsString(k)}, $value);"
                case None        => ()
        }
        events.foreach { (eventName, handler) =>
          compileEventHandler(v, eventName, handler)
        }
        children.foreach { child =>
          val childVar = compile(child)
          if childVar != null then statements += s"$v.appendChild($childVar);"
        }
        v

      case View.TextNode(thunk) =>
        val v = freshVar()
        statements += s"const $v = document.createTextNode(${jsString(thunk())});"
        v

      case View.SignalText(signal) =>
        registerSignal(signal)
        val v = freshVar()
        // Solid's createEffect auto-tracks the signal read.  When
        // the signal changes, only this text node updates — no
        // virtual-DOM diff, no parent re-render.
        statements += s"const $v = document.createTextNode(${signal.jsName}());"
        statements += s"createEffect(() => { $v.textContent = ${signal.jsName}(); });"
        v

      case View.Fragment(children) =>
        if children.isEmpty then null
        else
          val v = freshVar()
          statements += s"const $v = document.createDocumentFragment();"
          children.foreach { child =>
            val childVar = compile(child)
            if childVar != null then statements += s"$v.appendChild($childVar);"
          }
          v

      case View.ComponentInstance(component, props) =>
        compile(component.render(props.asInstanceOf[Nothing]))

      case View.Show(cond, whenTrue, whenFalse) =>
        // Emit-time snapshot — use ShowSignal for reactive swap.
        val branch = if cond() then whenTrue() else whenFalse()
        compile(branch)

      case View.ShowSignal(cond, whenTrue, whenFalse) =>
        // Subscribe-and-swap, same shape as Custom but driven by
        // createEffect.  Wrapper span holds the currently-mounted
        // branch.  Pre-build both branches up front so nested
        // signal subscribers wire correctly.
        registerSignal(cond)
        val wrap = freshVar()
        statements += s"const $wrap = document.createElement('span');"
        val tVar = compile(whenTrue)
        val fVar = compile(whenFalse)
        val tNode = if tVar != null then tVar else placeholderNode()
        val fNode = if fVar != null then fVar else placeholderNode()
        val currentVar = s"__show_${wrap}_current"
        statements += s"let $currentVar = ${cond.jsName}() ? $tNode : $fNode;"
        statements += s"$wrap.appendChild($currentVar);"
        statements += s"createEffect(() => {"
        statements += s"  const next = ${cond.jsName}() ? $tNode : $fNode;"
        statements += s"  if (next !== $currentVar) { $wrap.replaceChild(next, $currentVar); $currentVar = next; }"
        statements += s"});"
        wrap

      case View.For(items, render) =>
        val realised = items().toList
        if realised.isEmpty then null
        else
          val v = freshVar()
          statements += s"const $v = document.createDocumentFragment();"
          realised.foreach { item =>
            val childVar = compile(render(item))
            if childVar != null then statements += s"$v.appendChild($childVar);"
          }
          v

      case View.ForSignal(list, tag, attrs, itemTemplate) =>
        // A2e + A2e.2 — wrapper span + createEffect that rebuilds
        // children on every list change.  Simple form: render each
        // item as `<tag attrs>String(item)</tag>`.  Rich form: walk
        // the template inside a captured sub-scope so the buffered
        // statements form the body of the render-item function.
        registerList(list)
        val wrap     = freshVar()
        val renderFn = s"__render_item_${list.jsName}"
        statements += s"const $wrap = document.createElement('span');"

        itemTemplate match
          case None =>
            val tagJs = jsString(tag)
            val attrSetters = attrs.toSeq.flatMap { (k, av) =>
              attrValueJs(av).map(value => s"el.setAttribute(${jsString(k)}, $value);")
            }
            statements += s"function $renderFn(__item, __idx) {"
            statements += s"  const el = document.createElement($tagJs);"
            attrSetters.foreach(s => statements += s"  $s")
            statements += s"  el.textContent = String(__item);"
            statements += s"  return el;"
            statements += s"}"
          case Some(template) =>
            val prevFlag = inItemTemplate
            val prevList = currentItemList
            inItemTemplate  = true
            currentItemList = Some(list)
            val (rootVar, body) =
              try captureStatements(compile(template))
              finally
                inItemTemplate  = prevFlag
                currentItemList = prevList
            statements += s"function $renderFn(__item, __idx) {"
            body.foreach(stmt => statements += s"  $stmt")
            if rootVar == null then
              statements += s"  return document.createTextNode('');"
            else
              statements += s"  return $rootVar;"
            statements += s"}"

        statements += s"createEffect(() => {"
        statements += s"  while ($wrap.firstChild) $wrap.removeChild($wrap.firstChild);"
        statements += s"  let __idx = 0; for (const __item of ${list.jsName}()) { $wrap.appendChild($renderFn(__item, __idx)); __idx++; }"
        statements += s"});"
        wrap

      case View.ItemText =>
        val v = freshVar()
        if inItemTemplate then
          statements += s"const $v = document.createTextNode(String(__item));"
        else
          statements += s"const $v = document.createTextNode('');"
        v

      case View.Portal(target, children) =>
        // A6 — imperative portal: compile each child as usual, then
        // appendChild into document.querySelector(target).  Returns null
        // so the caller doesn't append anything to the parent.  Same
        // shape as Custom — solid-js/web's <Portal> needs JSX.
        val targetVar = freshVar()
        statements += s"const $targetVar = document.querySelector(${jsString(target)});"
        statements += s"if (!$targetVar) throw new Error('Portal target not found: ${target.replace("'", "\\'")}');"
        children.foreach { child =>
          val childVar = compile(child)
          if childVar != null then statements += s"$targetVar.appendChild($childVar);"
        }
        null

      case _: View.FetchTable =>
        val v = freshVar()
        statements += s"const $v = document.createTextNode('[FetchTable: React only]');"
        v

    private def compileEventHandler(targetVar: String, eventName: String, handler: EventHandler): Unit =
      handler match
        case EventHandler.Simple(_) | EventHandler.WithEvent(_) | EventHandler.InputChange(_) =>
          statements +=
            s"// $targetVar: '$eventName' handler is a JVM closure — A4 can't translate;" +
            " richer IR coming later."
        case EventHandler.SetSignalLiteral(signal, value) =>
          registerSignal(signal)
          val setter = setterName(signal.jsName)
          val v      = jsLiteral(value)
          statements += s"$targetVar.addEventListener(${jsString(eventName)}, () => $setter($v));"
        case EventHandler.IncrementSignal(signal, by) =>
          registerSignal(signal)
          val setter = setterName(signal.jsName)
          statements += s"$targetVar.addEventListener(${jsString(eventName)}, () => $setter(c => c + $by));"
        case EventHandler.ToggleSignal(signal) =>
          registerSignal(signal)
          val setter = setterName(signal.jsName)
          statements += s"$targetVar.addEventListener(${jsString(eventName)}, () => $setter(c => !c));"
        case EventHandler.PushSignalLiteral(list, value) =>
          registerList(list)
          val setter = setterName(list.jsName)
          val v      = jsLiteral(value)
          statements += s"$targetVar.addEventListener(${jsString(eventName)}, () => $setter(prev => prev.concat([$v])));"
        case EventHandler.ClearSignalList(list) =>
          registerList(list)
          val setter = setterName(list.jsName)
          statements += s"$targetVar.addEventListener(${jsString(eventName)}, () => $setter([]));"
        case EventHandler.FetchAction(method, url, body, tick, _) =>
          registerSignal(body)
          registerSignal(tick)
          val setTick  = setterName(tick.jsName)
          val urlJs    = jsString(url)
          val methodJs = jsString(method)
          statements += s"$targetVar.addEventListener(${jsString(eventName)}, () => " +
            s"fetch($urlJs, {method: $methodJs, body: ${body.jsName}()})" +
            s".then(r => r.text()).then(_ => $setTick(t => t + 1)));"
        case EventHandler.RemoveSelfFromList(list) =>
          // A2e.2 — only meaningful inside an item template.  Capture
          // __idx in an IIFE so each emitted listener remembers its
          // own slot for the .filter() call.
          if inItemTemplate && currentItemList.exists(_.jsName == list.jsName) then
            registerList(list)
            val setter = setterName(list.jsName)
            statements += s"$targetVar.addEventListener(${jsString(eventName)}, ((__capturedIdx) => () => " +
                          s"$setter(prev => prev.filter((_, i) => i !== __capturedIdx)))(__idx));"
          else
            statements +=
              s"// $targetVar: '$eventName' is RemoveSelfFromList used outside an item template — no-op."

    /** Empty-branch placeholder for ShowSignal — empty text node. */
    private def placeholderNode(): String =
      val v = freshVar()
      statements += s"const $v = document.createTextNode('');"
      v

    private def attrValueJs(av: AttrValue): Option[String] = av match
      case AttrValue.Str(value)     => Some(jsString(value))
      case AttrValue.Bool(value)    => Some(jsString(value.toString))
      case AttrValue.Num(value)     => Some(formatNumber(value))
      case AttrValue.Dynamic(read)    => Some(jsString(String.valueOf(read())))
      case AttrValue.Reactive(signal) => Some(jsString(String.valueOf(signal()))) // snapshot
      case AttrValue.Absent           => None
      case AttrValue.RefBinding(_)    => None  // ref binding is wired imperatively in the Element case; no setAttribute

  private def setterName(varName: String): String =
    "set" + varName.headOption.fold("")(_.toUpper.toString) + varName.drop(1)

  private def jsLiteral(value: Any): String = value match
    case s: String  => jsString(s)
    case i: Int     => i.toString
    case l: Long    => l.toString
    case d: Double  => formatNumber(d)
    case f: Float   => formatNumber(f.toDouble)
    case b: Boolean => b.toString
    case null       => "null"
    case other      => throw new IllegalArgumentException(
      s"jsLiteral: unsupported value type ${other.getClass.getName} ($other).  " +
      "Supported: String / Int / Long / Double / Float / Boolean / null."
    )

  private def jsArrayLiteral(items: Seq[Any]): String =
    items.map(jsLiteral).mkString("[", ", ", "]")

  private def formatNumber(d: Double): String =
    if d == d.toLong.toDouble then d.toLong.toString else d.toString

  private def jsString(s: String): String =
    val sb = new StringBuilder
    sb += '\''
    s.foreach {
      case '\\' => sb ++= "\\\\"
      case '\'' => sb ++= "\\'"
      case '\n' => sb ++= "\\n"
      case '\r' => sb ++= "\\r"
      case '<'  => sb ++= "\\u003c"
      case c    => sb += c
    }
    sb += '\''
    sb.toString
