package scalascript.frontend.react

import scalascript.frontend.*

/** Two-pass emit:
 *
 *    1. **Collect signals.**  Walk the entire View tree, gathering
 *       every `ReactiveSignal` referenced by `SignalText`, by
 *       `IncrementSignal`, or by `SetSignalLiteral`.  These become
 *       `useState` calls hoisted to the top of the App function.
 *
 *    2. **Emit expression tree.**  Walk again, this time producing
 *       a single nested `React.createElement(...)` expression that
 *       returns the View.  No imperative DOM ops — React handles
 *       reconciliation.
 *
 *  Naming convention for hoisted state: signal with `jsName="count"`
 *  becomes `[count, setCount]` (camelCase setter).  Duplicate
 *  names with different initial values is a hard error (same
 *  contract as the custom backend).
 *
 *  Pure-expression output is on purpose — React's mental model
 *  is "component is a function from props to a tree."  Imperative
 *  side-effects would be wrong (they'd run during render). */
private[react] object ReactEmitter:

  def emit(root: View): String =
    val signals = collectSignals(root)
    val lists   = collectLists(root)
    val refs    = collectRefs(root)
    val sb = new StringBuilder
    sb ++= "// Generated by ScalaScript v1.18 — frontend-react Phase A3 / A2e / A6.\n"
    sb ++= "// Signals + lists + DomRefs + Portals lower to useState / useRef / createPortal.\n"
    sb ++= "(function() {\n"
    sb ++= "  const { useState, useRef, createElement: h, Fragment } = React;\n"
    sb ++= "  function App() {\n"
    signals.foreach { (name, initial) =>
      val setter = setterName(name)
      sb ++= s"    const [$name, $setter] = useState($initial);\n"
    }
    lists.foreach { (name, initial) =>
      val setter = setterName(name)
      sb ++= s"    const [$name, $setter] = useState($initial);\n"
    }
    // A6 — each DomRef gets a useRef(null) hoisted at the top of App.
    // Expose on window so imperative user JS can read <name>.current.
    refs.foreach { name =>
      sb ++= s"    const $name = useRef(null);\n"
      sb ++= s"    if (typeof window !== 'undefined') window[${jsString(name)}] = $name;\n"
    }
    sb ++= "    return "
    sb ++= renderView(root)
    sb ++= ";\n"
    sb ++= "  }\n"
    sb ++= "  const root = ReactDOM.createRoot(document.getElementById('app'));\n"
    sb ++= "  root.render(h(App));\n"
    sb ++= "})();\n"
    sb.toString

  /** First pass — DFS over the View tree harvesting reactive
   *  signals.  Returns a LinkedHashMap so emit order is stable
   *  (first occurrence wins for ordering; duplicate names with
   *  different initial values throw). */
  private def collectSignals(view: View): scala.collection.mutable.LinkedHashMap[String, String] =
    val acc = scala.collection.mutable.LinkedHashMap.empty[String, String]
    def register(signal: ReactiveSignal[?]): Unit =
      val name = signal.jsName
      if !name.matches("[A-Za-z_][A-Za-z0-9_]*") then
        throw new IllegalArgumentException(
          s"ReactiveSignal jsName '$name' must match [A-Za-z_][A-Za-z0-9_]*."
        )
      val initJs = jsLiteral(signal())
      acc.get(name) match
        case Some(existing) if existing != initJs =>
          throw new IllegalArgumentException(
            s"ReactiveSignal jsName '$name' registered twice with different " +
            s"initial values ($existing vs $initJs)."
          )
        case _ => acc.update(name, initJs)
    def walk(v: View): Unit = v match
      case View.SignalText(signal) =>
        register(signal)
      case View.Element(_, _, events, children) =>
        events.foreach { (_, handler) =>
          handler match
            case EventHandler.SetSignalLiteral(signal, _) => register(signal)
            case EventHandler.IncrementSignal(signal, _)  => register(signal)
            case EventHandler.ToggleSignal(signal)        => register(signal)
            case _ => ()
        }
        children.foreach(walk)
      case View.Fragment(children) => children.foreach(walk)
      case View.ComponentInstance(component, props) =>
        walk(component.render(props.asInstanceOf[Nothing]))
      case View.Show(cond, whenTrue, whenFalse) =>
        // Walk both branches because either could end up rendered;
        // ALL signals they reference need state in the parent.
        walk(whenTrue())
        walk(whenFalse())
        val _ = cond  // cond is just a JVM thunk
      case View.ShowSignal(cond, whenTrue, whenFalse) =>
        register(cond)
        walk(whenTrue)
        walk(whenFalse)
      case View.For(items, render) =>
        // Render once with the realised items to discover signals
        // referenced inside.  If the list is empty no signals get
        // collected — Phase A3 limitation: empty initial lists with
        // signals declared inside won't get useState hoisting.  Caller
        // can work around by referencing the signal somewhere else.
        items().foreach(item => walk(render(item)))
      case _: View.ForSignal[?] =>
        // List items are JS-literal primitives stringified at render
        // time; no scalar ReactiveSignals nested inside (A2e scope).
        ()
      case View.Portal(_, children) =>
        // A6 — portals lift children into a foreign DOM node but the
        // signals they reference still live in the parent component's
        // state.  Walk into them for useState hoisting.
        children.foreach(walk)
      case _: View.TextNode => ()
    walk(view)
    acc

  /** A2e — second collection pass for list signals, indexed under
   *  the same name → JS-array-literal shape that fuels per-list
   *  `useState`.  Visits the same View kinds that can carry a list
   *  reference: `ForSignal` itself + the list-mutation events
   *  (Push / Clear) attached to any Element. */
  private def collectLists(view: View): scala.collection.mutable.LinkedHashMap[String, String] =
    val acc = scala.collection.mutable.LinkedHashMap.empty[String, String]
    def register(list: ReactiveSignalList[?]): Unit =
      val name = list.jsName
      if !name.matches("[A-Za-z_][A-Za-z0-9_]*") then
        throw new IllegalArgumentException(
          s"ReactiveSignalList jsName '$name' must match [A-Za-z_][A-Za-z0-9_]*."
        )
      val initJs = jsArrayLiteral(list.initial)
      acc.get(name) match
        case Some(existing) if existing != initJs =>
          throw new IllegalArgumentException(
            s"ReactiveSignalList jsName '$name' registered twice with different " +
            s"initial values ($existing vs $initJs)."
          )
        case _ => acc.update(name, initJs)
    def walk(v: View): Unit = v match
      case View.ForSignal(list, _, _) =>
        register(list)
      case View.Element(_, _, events, children) =>
        events.foreach { (_, handler) =>
          handler match
            case EventHandler.PushSignalLiteral(list, _) => register(list)
            case EventHandler.ClearSignalList(list)      => register(list)
            case _ => ()
        }
        children.foreach(walk)
      case View.Fragment(children) => children.foreach(walk)
      case View.ComponentInstance(component, props) =>
        walk(component.render(props.asInstanceOf[Nothing]))
      case View.Show(_, whenTrue, whenFalse) =>
        walk(whenTrue()); walk(whenFalse())
      case View.ShowSignal(_, whenTrue, whenFalse) =>
        walk(whenTrue); walk(whenFalse)
      case View.For(items, render) =>
        items().foreach(item => walk(render(item)))
      case View.Portal(_, children) =>
        children.foreach(walk)
      case _: View.SignalText | _: View.TextNode => ()
    walk(view)
    acc

  /** A6 — DomRef collection.  Walks the View tree harvesting the
   *  `jsName` of every `AttrValue.RefBinding` so each becomes a
   *  `useRef(null)` hoisted at the top of App().  LinkedHashSet
   *  preserves first-seen order for deterministic output. */
  private def collectRefs(view: View): scala.collection.mutable.LinkedHashSet[String] =
    val acc = scala.collection.mutable.LinkedHashSet.empty[String]
    def register(ref: DomRef): Unit =
      val name = ref.jsName
      if !name.matches("[A-Za-z_][A-Za-z0-9_]*") then
        throw new IllegalArgumentException(
          s"DomRef jsName '$name' must match [A-Za-z_][A-Za-z0-9_]*."
        )
      acc += name
    def walk(v: View): Unit = v match
      case View.Element(_, attrs, _, children) =>
        attrs.values.foreach {
          case AttrValue.RefBinding(ref) => register(ref)
          case _ => ()
        }
        children.foreach(walk)
      case View.Fragment(children) => children.foreach(walk)
      case View.ComponentInstance(component, props) =>
        walk(component.render(props.asInstanceOf[Nothing]))
      case View.Show(_, whenTrue, whenFalse) =>
        walk(whenTrue()); walk(whenFalse())
      case View.ShowSignal(_, whenTrue, whenFalse) =>
        walk(whenTrue); walk(whenFalse)
      case View.For(items, render) =>
        items().foreach(item => walk(render(item)))
      case View.Portal(_, children) =>
        children.foreach(walk)
      case _: View.ForSignal[?] | _: View.SignalText | _: View.TextNode => ()
    walk(view)
    acc

  /** Second pass — emit a React.createElement expression tree.  No
   *  side-effects; pure expression. */
  private def renderView(view: View): String = view match
    case View.Element(tag, attrs, events, children) =>
      val propsJs    = renderProps(attrs, events)
      val childrenJs = children.map(renderView).mkString(", ")
      val tail       = if children.isEmpty then "" else ", " + childrenJs
      s"h(${jsString(tag)}, $propsJs$tail)"

    case View.TextNode(thunk) =>
      jsString(thunk())

    case View.SignalText(signal) =>
      // Direct interpolation — React stringifies numbers / booleans.
      signal.jsName

    case View.Fragment(children) =>
      if children.isEmpty then "null"
      else
        val childrenJs = children.map(renderView).mkString(", ")
        s"h(Fragment, null, $childrenJs)"

    case View.ComponentInstance(component, props) =>
      renderView(component.render(props.asInstanceOf[Nothing]))

    case View.Show(cond, whenTrue, whenFalse) =>
      // Snapshot the condition AT EMIT TIME — `Show` is the
      // non-reactive variant.  Use `ShowSignal` for live swap.
      val branch = if cond() then whenTrue() else whenFalse()
      renderView(branch)

    case View.ShowSignal(cond, whenTrue, whenFalse) =>
      // Ternary inside render — React re-runs render on useState
      // change, the ternary re-evaluates, reconciliation handles
      // the DOM swap.  Idiomatic React conditional rendering.
      s"(${cond.jsName} ? ${renderView(whenTrue)} : ${renderView(whenFalse)})"

    case View.For(items, render) =>
      // Emit a literal array; React handles list rendering.
      val realised = items().toList
      if realised.isEmpty then "null"
      else
        val parts = realised.map(item => renderView(render(item)))
        s"[${parts.mkString(", ")}]"

    case View.ForSignal(list, tag, attrs) =>
      // A2e — lower to `<jsName>.map(item => h(tag, propsWithKey, String(item)))`.
      // React's keyed reconciliation handles add / remove / reorder
      // when the list state changes.  Key is the stringified item;
      // duplicates are the user's problem (same trade-off as plain JS).
      val tagJs = jsString(tag)
      val attrFields = attrs.flatMap { (k, av) =>
        attrValueJs(av).map { value =>
          val key = if k == "class" then "className" else k
          s"${jsString(key)}: $value"
        }
      }
      val propsParts = "'key': String(item)" :: attrFields.toList
      val propsJs    = s"{ ${propsParts.mkString(", ")} }"
      s"${list.jsName}.map(item => h($tagJs, $propsJs, String(item)))"

    case View.Portal(target, children) =>
      // A6 — ReactDOM.createPortal(child, document.querySelector(target)).
      // When there's more than one child wrap them in a Fragment so the
      // createPortal call gets a single React node to render.
      val targetJs = jsString(target)
      val childJs  =
        if children.isEmpty then "null"
        else if children.size == 1 then renderView(children.head)
        else s"h(Fragment, null, ${children.map(renderView).mkString(", ")})"
      s"ReactDOM.createPortal($childJs, document.querySelector($targetJs))"

  /** Props object — combines attributes + event handlers into the
   *  single second argument of `React.createElement`. */
  private def renderProps(attrs: Map[String, AttrValue], events: Map[String, EventHandler]): String =
    val attrFields = attrs.flatMap { (k, v) =>
      v match
        case AttrValue.RefBinding(ref) =>
          // A6 — React reserves the `ref` prop; map any RefBinding to it
          // regardless of the attribute key the user picked.  The ref
          // variable is the useRef object hoisted at the top of App().
          Some(s"'ref': ${ref.jsName}")
        case _ =>
          attrValueJs(v).map { value =>
            // React uses className not class; map at IR level.
            val key = if k == "class" then "className" else k
            s"${jsString(key)}: $value"
          }
    }
    val eventFields = events.flatMap { (eventName, handler) =>
      eventHandlerJs(eventName, handler)
    }
    val all = attrFields ++ eventFields
    if all.isEmpty then "null" else s"{ ${all.mkString(", ")} }"

  private def attrValueJs(av: AttrValue): Option[String] = av match
    case AttrValue.Str(value)     => Some(jsString(value))
    case AttrValue.Bool(value)    => Some(value.toString)
    case AttrValue.Num(value)     => Some(formatNumber(value))
    case AttrValue.Dynamic(read)  => Some(jsLiteral(read()))
    case AttrValue.Absent         => None
    case AttrValue.RefBinding(_)  => None  // handled inline in renderProps as the React `ref` prop

  /** Translate an event handler.  Returns `Some((onClick, body))`
   *  pair as a single JS field source, or `None` for unsupported
   *  handlers (the marker is emitted as a separate `/* */` comment
   *  in the props object). */
  private def eventHandlerJs(eventName: String, handler: EventHandler): Option[String] =
    val onKey = onProp(eventName)
    handler match
      case EventHandler.SetSignalLiteral(signal, value) =>
        val setter = setterName(signal.jsName)
        val v      = jsLiteral(value)
        Some(s"${jsString(onKey)}: () => $setter($v)")
      case EventHandler.IncrementSignal(signal, by) =>
        val setter = setterName(signal.jsName)
        // Functional setState — avoids stale-closure read of `count`.
        Some(s"${jsString(onKey)}: () => $setter(c => c + $by)")
      case EventHandler.ToggleSignal(signal) =>
        val setter = setterName(signal.jsName)
        Some(s"${jsString(onKey)}: () => $setter(c => !c)")
      case EventHandler.PushSignalLiteral(list, value) =>
        val setter = setterName(list.jsName)
        val v      = jsLiteral(value)
        // Functional setState — concat into the previous array snapshot
        // so concurrent updates don't lose entries.
        Some(s"${jsString(onKey)}: () => $setter(prev => prev.concat([$v]))")
      case EventHandler.ClearSignalList(list) =>
        val setter = setterName(list.jsName)
        Some(s"${jsString(onKey)}: () => $setter([])")
      case EventHandler.Simple(_) | EventHandler.WithEvent(_) =>
        // JVM closure — emit a comment-prop that doesn't bind anything.
        // The presence of the marker tells dev "you wrote Simple/WithEvent
        // but A3 can't translate JVM closures yet".  Render still works.
        Some(s"/* '$eventName' is a JVM closure — A3 can't translate (richer IR coming later) */")

  /** DOM event name → React event prop.  React uses camelCase:
   *  'click' → 'onClick', 'mousedown' → 'onMouseDown', etc.  This
   *  is the simplest case mapping; production-grade would have a
   *  larger table.  Unknown events keep their lowercase form with
   *  a single capital, which React tolerates for custom events. */
  private def onProp(eventName: String): String =
    "on" + eventName.headOption.fold("")(_.toUpper.toString) + eventName.drop(1)

  /** State-variable name → React setter name. */
  private def setterName(varName: String): String =
    "set" + varName.headOption.fold("")(_.toUpper.toString) + varName.drop(1)

  /** JS literal for arbitrary Scala values used as signal initials
   *  or attribute defaults.  Mirrors the Custom backend's
   *  jsLiteral so the two stay consistent. */
  private def jsLiteral(value: Any): String = value match
    case s: String  => jsString(s)
    case i: Int     => i.toString
    case l: Long    => l.toString
    case d: Double  => formatNumber(d)
    case f: Float   => formatNumber(f.toDouble)
    case b: Boolean => b.toString
    case null       => "null"
    case other      => throw new IllegalArgumentException(
      s"jsLiteral: unsupported value type ${other.getClass.getName} ($other).  " +
      "Supported: String / Int / Long / Double / Float / Boolean / null."
    )

  /** A2e — JS array literal for a `ReactiveSignalList`'s initial.
   *  Each element passes through `jsLiteral` (same primitive-only
   *  restriction). */
  private def jsArrayLiteral(items: Seq[Any]): String =
    items.map(jsLiteral).mkString("[", ", ", "]")

  private def formatNumber(d: Double): String =
    if d == d.toLong.toDouble then d.toLong.toString else d.toString

  private def jsString(s: String): String =
    val sb = new StringBuilder
    sb += '\''
    s.foreach {
      case '\\' => sb ++= "\\\\"
      case '\'' => sb ++= "\\'"
      case '\n' => sb ++= "\\n"
      case '\r' => sb ++= "\\r"
      case '<'  => sb ++= "\\u003c"
      case c    => sb += c
    }
    sb += '\''
    sb.toString
