package scalascript.frontend.vue

import scalascript.frontend.*

/** Two-pass emit (same shape as React / Solid):
 *
 *    1. Collect every `ReactiveSignal` referenced anywhere in
 *       the View tree.  Each becomes a `ref(init)` in `setup()`.
 *
 *    2. Emit a Vue 3 component with `setup` + `render`.  `setup`
 *       creates the refs and returns them on the proxy; `render`
 *       reads `this.x` (auto-unwrapped) and writes via
 *       `this.x = ...`.
 *
 *  Pattern produced:
 *  {{{
 *  import { ref, h, Fragment, createApp } from 'vue';
 *  const App = {
 *    setup() {
 *      const count = ref(0);
 *      return { count };
 *    },
 *    render() {
 *      return h('div', null, [
 *        h('button', { 'onClick': () => { this.count = this.count + 1; } }, '+'),
 *        h('span',   null, this.count)
 *      ]);
 *    }
 *  };
 *  createApp(App).mount('#app');
 *  }}}
 *  Note `this.count` not `count.value` — Vue's component proxy
 *  unwraps refs exposed from `setup`. */
private[vue] object VueEmitter:

  def emit(root: View): String =
    val signals = collectSignals(root)
    val lists   = collectLists(root)
    val refs    = collectRefs(root)
    val usesPortal = containsPortal(root)
    val sb = new StringBuilder
    sb ++= "// Generated by ScalaScript v1.18 — frontend-vue Phase A5 / A2e / A6.\n"
    sb ++= "// Signals + lists + DomRefs + Portals lowered to ref() / Teleport.\n"
    val teleportImport = if usesPortal then ", Teleport" else ""
    sb ++= s"import { ref, h, Fragment$teleportImport, createApp } from 'vue';\n"
    sb ++= "const App = {\n"
    sb ++= "  setup() {\n"
    signals.foreach { (name, initial) =>
      sb ++= s"    const $name = ref($initial);\n"
    }
    lists.foreach { (name, initial) =>
      sb ++= s"    const $name = ref($initial);\n"
    }
    // A6 — DomRefs lower to setup-level `ref(null)`s.  Vue's template
    // ref system binds the underlying DOM element to the ref's .value
    // once mounted.  Expose on window for imperative user JS.
    refs.foreach { name =>
      sb ++= s"    const $name = ref(null);\n"
      sb ++= s"    if (typeof window !== 'undefined') window[${jsString(name)}] = $name;\n"
    }
    val allNames = signals.keys.toList ++ lists.keys.toList ++ refs.toList
    val returned =
      if allNames.isEmpty then "{}"
      else "{ " + allNames.mkString(", ") + " }"
    sb ++= s"    return $returned;\n"
    sb ++= "  },\n"
    sb ++= "  render() {\n"
    sb ++= "    return "
    sb ++= renderView(root)
    sb ++= ";\n"
    sb ++= "  }\n"
    sb ++= "};\n"
    sb ++= "createApp(App).mount('#app');\n"
    sb.toString

  private def collectSignals(view: View): scala.collection.mutable.LinkedHashMap[String, String] =
    val acc = scala.collection.mutable.LinkedHashMap.empty[String, String]
    def register(signal: ReactiveSignal[?]): Unit =
      val name = signal.jsName
      if !name.matches("[A-Za-z_][A-Za-z0-9_]*") then
        throw new IllegalArgumentException(
          s"ReactiveSignal jsName '$name' must match [A-Za-z_][A-Za-z0-9_]*."
        )
      val initJs = jsLiteral(signal())
      acc.get(name) match
        case Some(existing) if existing != initJs =>
          throw new IllegalArgumentException(
            s"ReactiveSignal jsName '$name' registered twice with different " +
            s"initial values ($existing vs $initJs)."
          )
        case _ => acc.update(name, initJs)
    def walk(v: View): Unit = v match
      case View.SignalText(signal) =>
        register(signal)
      case View.Element(_, _, events, children) =>
        events.foreach { (_, handler) =>
          handler match
            case EventHandler.SetSignalLiteral(signal, _) => register(signal)
            case EventHandler.IncrementSignal(signal, _)  => register(signal)
            case EventHandler.ToggleSignal(signal)        => register(signal)
            case _ => ()
        }
        children.foreach(walk)
      case View.Fragment(children) => children.foreach(walk)
      case View.ComponentInstance(component, props) =>
        walk(component.render(props.asInstanceOf[Nothing]))
      case View.Show(_, whenTrue, whenFalse) =>
        walk(whenTrue())
        walk(whenFalse())
      case View.ShowSignal(cond, whenTrue, whenFalse) =>
        register(cond)
        walk(whenTrue)
        walk(whenFalse)
      case View.For(items, render) =>
        items().foreach(item => walk(render(item)))
      case View.ForSignal(_, _, _, itemTemplate) => itemTemplate.foreach(walk)
      case View.Portal(_, children) => children.foreach(walk)
      case _: View.TextNode | View.ItemText | _: View.FetchTable => ()
    walk(view)
    acc

  private def collectLists(view: View): scala.collection.mutable.LinkedHashMap[String, String] =
    val acc = scala.collection.mutable.LinkedHashMap.empty[String, String]
    def register(list: ReactiveSignalList[?]): Unit =
      val name = list.jsName
      if !name.matches("[A-Za-z_][A-Za-z0-9_]*") then
        throw new IllegalArgumentException(
          s"ReactiveSignalList jsName '$name' must match [A-Za-z_][A-Za-z0-9_]*."
        )
      val initJs = jsArrayLiteral(list.initial)
      acc.get(name) match
        case Some(existing) if existing != initJs =>
          throw new IllegalArgumentException(
            s"ReactiveSignalList jsName '$name' registered twice with different " +
            s"initial values ($existing vs $initJs)."
          )
        case _ => acc.update(name, initJs)
    def walk(v: View): Unit = v match
      case View.ForSignal(list, _, _, itemTemplate) =>
        register(list)
        itemTemplate.foreach(walk)
      case View.Element(_, _, events, children) =>
        events.foreach { (_, handler) =>
          handler match
            case EventHandler.PushSignalLiteral(list, _) => register(list)
            case EventHandler.ClearSignalList(list)      => register(list)
            case EventHandler.RemoveSelfFromList(list)   => register(list)
            case _ => ()
        }
        children.foreach(walk)
      case View.Fragment(children) => children.foreach(walk)
      case View.ComponentInstance(component, props) =>
        walk(component.render(props.asInstanceOf[Nothing]))
      case View.Show(_, whenTrue, whenFalse) =>
        walk(whenTrue()); walk(whenFalse())
      case View.ShowSignal(_, whenTrue, whenFalse) =>
        walk(whenTrue); walk(whenFalse)
      case View.For(items, render) =>
        items().foreach(item => walk(render(item)))
      case View.Portal(_, children) => children.foreach(walk)
      case _: View.SignalText | _: View.TextNode | View.ItemText | _: View.FetchTable => ()
    walk(view)
    acc

  /** A6 — DomRef collection.  Each becomes a `ref(null)` in setup()
   *  + a template-ref binding on the element. */
  private def collectRefs(view: View): scala.collection.mutable.LinkedHashSet[String] =
    val acc = scala.collection.mutable.LinkedHashSet.empty[String]
    def register(ref: DomRef): Unit =
      val name = ref.jsName
      if !name.matches("[A-Za-z_][A-Za-z0-9_]*") then
        throw new IllegalArgumentException(
          s"DomRef jsName '$name' must match [A-Za-z_][A-Za-z0-9_]*."
        )
      acc += name
    def walk(v: View): Unit = v match
      case View.Element(_, attrs, _, children) =>
        attrs.values.foreach {
          case AttrValue.RefBinding(ref) => register(ref)
          case _ => ()
        }
        children.foreach(walk)
      case View.Fragment(children) => children.foreach(walk)
      case View.ComponentInstance(component, props) =>
        walk(component.render(props.asInstanceOf[Nothing]))
      case View.Show(_, whenTrue, whenFalse) =>
        walk(whenTrue()); walk(whenFalse())
      case View.ShowSignal(_, whenTrue, whenFalse) =>
        walk(whenTrue); walk(whenFalse)
      case View.For(items, render) =>
        items().foreach(item => walk(render(item)))
      case View.Portal(_, children) => children.foreach(walk)
      case View.ForSignal(_, _, _, itemTemplate) => itemTemplate.foreach(walk)
      case _: View.SignalText | _: View.TextNode | View.ItemText | _: View.FetchTable => ()
    walk(view)
    acc

  /** A6 — cheap walk used at emit time to decide whether to import
   *  `Teleport` from 'vue'.  Pulling the import in unconditionally
   *  is harmless but `containsPortal` keeps the generated bundle
   *  diff-free for portal-less apps. */
  private def containsPortal(view: View): Boolean = view match
    case _: View.Portal => true
    case View.Element(_, _, _, children) => children.exists(containsPortal)
    case View.Fragment(children) => children.exists(containsPortal)
    case View.ComponentInstance(component, props) =>
      containsPortal(component.render(props.asInstanceOf[Nothing]))
    case View.Show(_, whenTrue, whenFalse) =>
      containsPortal(whenTrue()) || containsPortal(whenFalse())
    case View.ShowSignal(_, whenTrue, whenFalse) =>
      containsPortal(whenTrue) || containsPortal(whenFalse)
    case View.For(items, render) =>
      items().exists(item => containsPortal(render(item)))
    case View.ForSignal(_, _, _, itemTemplate) =>
      itemTemplate.exists(containsPortal)
    case _: View.SignalText | _: View.TextNode | View.ItemText | _: View.FetchTable => false

  private def renderView(view: View, itemCtx: Option[ReactiveSignalList[?]] = None): String = view match
    case View.Element(tag, attrs, events, children) =>
      val propsJs = renderProps(attrs, events, itemCtx)
      val childrenJs =
        if children.isEmpty then ""
        else ", [" + children.map(c => renderView(c, itemCtx)).mkString(", ") + "]"
      s"h(${jsString(tag)}, $propsJs$childrenJs)"

    case View.TextNode(thunk) =>
      jsString(thunk())

    case View.SignalText(signal) =>
      // `this.x` — Vue's component proxy auto-unwraps the ref.
      "this." + signal.jsName

    case View.ItemText =>
      // A2e.2 — `String(item)` when inside a render-arrow's
      // map callback; literal '' outside (graceful no-op).
      if itemCtx.isDefined then "String(item)" else "''"

    case View.Fragment(children) =>
      if children.isEmpty then "null"
      else s"h(Fragment, null, [${children.map(c => renderView(c, itemCtx)).mkString(", ")}])"

    case View.ComponentInstance(component, props) =>
      renderView(component.render(props.asInstanceOf[Nothing]), itemCtx)

    case View.Show(cond, whenTrue, whenFalse) =>
      val branch = if cond() then whenTrue() else whenFalse()
      renderView(branch, itemCtx)

    case View.ShowSignal(cond, whenTrue, whenFalse) =>
      // Ternary inside render — Vue re-runs render when the ref
      // (read via proxy) changes; the ternary re-evaluates.
      s"(this.${cond.jsName} ? ${renderView(whenTrue, itemCtx)} : ${renderView(whenFalse, itemCtx)})"

    case View.For(items, render) =>
      val realised = items().toList
      if realised.isEmpty then "null"
      else
        val parts = realised.map(item => renderView(render(item), itemCtx))
        s"[${parts.mkString(", ")}]"

    case View.ForSignal(list, tag, attrs, itemTemplate) =>
      // A2e / A2e.2 — map over `this.<jsName>`.  Two flavours:
      //
      //  - simple form: `h(tag, propsWithKey, String(item))`.
      //  - rich form: emit the template recursively with
      //    `itemCtx = Some(list)`; inject `key: String(item)` on
      //    the template's Element root.
      itemTemplate match
        case None =>
          val tagJs = jsString(tag)
          val attrFields = attrs.flatMap { (k, av) =>
            attrValueJs(av).map(value => s"${jsString(k)}: $value")
          }
          val propsParts = "'key': String(item)" :: attrFields.toList
          val propsJs    = s"{ ${propsParts.mkString(", ")} }"
          s"this.${list.jsName}.map((item, index) => h($tagJs, $propsJs, String(item)))"
        case Some(template) =>
          val body = template match
            case View.Element(tag, attrs, events, children) =>
              val propsJs    = renderProps(attrs, events, Some(list), injectKey = true)
              val childrenJs =
                if children.isEmpty then ""
                else ", [" + children.map(c => renderView(c, Some(list))).mkString(", ") + "]"
              s"h(${jsString(tag)}, $propsJs$childrenJs)"
            case other =>
              renderView(other, Some(list))
          s"this.${list.jsName}.map((item, index) => $body)"

    case View.Portal(target, children) =>
      // A6 — Vue's Teleport renders its slot content into the DOM
      // element matched by the `to` selector.  Same shape as our
      // Portal: `h(Teleport, { to: target }, [...children])`.
      val targetJs = jsString(target)
      val childrenJs =
        if children.isEmpty then ""
        else ", [" + children.map(c => renderView(c, itemCtx)).mkString(", ") + "]"
      s"h(Teleport, { 'to': $targetJs }$childrenJs)"

    case _: View.FetchTable =>
      "h('span', null, '[FetchTable: React only]')"

  private def renderProps(
      attrs:     Map[String, AttrValue],
      events:    Map[String, EventHandler],
      itemCtx:   Option[ReactiveSignalList[?]],
      injectKey: Boolean = false
  ): String =
    val attrFields = attrs.flatMap { (k, v) =>
      v match
        case AttrValue.RefBinding(ref) =>
          // A6 — Vue's template `ref` prop accepts the setup-time ref
          // object directly.  Vue assigns the DOM element to ref.value
          // after mount; ignore the user-picked attr key since Vue
          // reserves the `ref` name for this binding.
          Some(s"'ref': ${ref.jsName}")
        case _ =>
          attrValueJs(v).map { value =>
            // Vue accepts `class` natively (same as Solid; unlike React).
            s"${jsString(k)}: $value"
          }
    }
    val eventFields = events.flatMap { (eventName, handler) =>
      eventHandlerJs(eventName, handler, itemCtx)
    }
    val keyField = if injectKey then List("'key': String(item)") else Nil
    val all = keyField ++ attrFields ++ eventFields
    if all.isEmpty then "null" else s"{ ${all.mkString(", ")} }"

  private def attrValueJs(av: AttrValue): Option[String] = av match
    case AttrValue.Str(value)     => Some(jsString(value))
    case AttrValue.Bool(value)    => Some(value.toString)
    case AttrValue.Num(value)     => Some(formatNumber(value))
    case AttrValue.Dynamic(read)    => Some(jsLiteral(read()))
    case AttrValue.Reactive(signal) => Some(jsLiteral(signal())) // snapshot; Vue reactive support coming later
    case AttrValue.Absent           => None
    case AttrValue.RefBinding(_)    => None  // handled inline in renderProps as the Vue `ref` prop

  private def eventHandlerJs(
      eventName: String,
      handler:   EventHandler,
      itemCtx:   Option[ReactiveSignalList[?]]
  ): Option[String] =
    val onKey = onProp(eventName)
    // Arrow functions defined INSIDE render() lexically capture
    // render()'s `this` — which IS the Vue component proxy.  A
    // function expression instead would lose `this` because Vue's
    // DOM-listener invoker calls it with `this === null`.
    handler match
      case EventHandler.SetSignalLiteral(signal, value) =>
        val v = jsLiteral(value)
        Some(s"${jsString(onKey)}: () => { this.${signal.jsName} = $v; }")
      case EventHandler.IncrementSignal(signal, by) =>
        Some(s"${jsString(onKey)}: () => { this.${signal.jsName} = this.${signal.jsName} + $by; }")
      case EventHandler.ToggleSignal(signal) =>
        Some(s"${jsString(onKey)}: () => { this.${signal.jsName} = !this.${signal.jsName}; }")
      case EventHandler.PushSignalLiteral(list, value) =>
        val v = jsLiteral(value)
        Some(s"${jsString(onKey)}: () => { this.${list.jsName} = this.${list.jsName}.concat([$v]); }")
      case EventHandler.ClearSignalList(list) =>
        Some(s"${jsString(onKey)}: () => { this.${list.jsName} = []; }")
      case EventHandler.RemoveSelfFromList(list) =>
        // A2e.2 — inside an item template, capture the map-callback
        // `index` so the listener filters its own slot out.
        if itemCtx.exists(_.jsName == list.jsName) then
          Some(s"${jsString(onKey)}: () => { this.${list.jsName} = this.${list.jsName}.filter((_, i) => i !== index); }")
        else
          Some(s"/* '$eventName' is RemoveSelfFromList used outside an item template — no-op */")
      case EventHandler.FetchAction(method, url, body, tick, clearBody) =>
        val urlJs    = jsString(url)
        val methodJs = jsString(method)
        val clearJs  = if clearBody then s" this.${body.jsName} = '';" else ""
        Some(s"${jsString(onKey)}: () => { fetch($urlJs, {method: $methodJs, body: this.${body.jsName}})" +
          s".then(r => r.text()).then(_ => { this.${tick.jsName}++;$clearJs }); }")
      case EventHandler.Simple(_) | EventHandler.WithEvent(_) | EventHandler.InputChange(_) =>
        Some(s"/* '$eventName' is a JVM closure — A5 can't translate (richer IR coming later) */")

  /** Vue uses camelCase event props: 'click' → 'onClick'. */
  private def onProp(eventName: String): String =
    "on" + eventName.headOption.fold("")(_.toUpper.toString) + eventName.drop(1)

  private def jsLiteral(value: Any): String = value match
    case s: String  => jsString(s)
    case i: Int     => i.toString
    case l: Long    => l.toString
    case d: Double  => formatNumber(d)
    case f: Float   => formatNumber(f.toDouble)
    case b: Boolean => b.toString
    case null       => "null"
    case other      => throw new IllegalArgumentException(
      s"jsLiteral: unsupported value type ${other.getClass.getName} ($other).  " +
      "Supported: String / Int / Long / Double / Float / Boolean / null."
    )

  private def jsArrayLiteral(items: Seq[Any]): String =
    items.map(jsLiteral).mkString("[", ", ", "]")

  private def formatNumber(d: Double): String =
    if d == d.toLong.toDouble then d.toLong.toString else d.toString

  private def jsString(s: String): String =
    val sb = new StringBuilder
    sb += '\''
    s.foreach {
      case '\\' => sb ++= "\\\\"
      case '\'' => sb ++= "\\'"
      case '\n' => sb ++= "\\n"
      case '\r' => sb ++= "\\r"
      case '<'  => sb ++= "\\u003c"
      case c    => sb += c
    }
    sb += '\''
    sb.toString
