package scalascript.frontend.vue

import scala.annotation.nowarn
import scalascript.frontend.*

/** Two-pass emit (same shape as React / Solid):
 *
 *    1. Collect every `ReactiveSignal` referenced anywhere in
 *       the View tree.  Each becomes a `ref(init)` in `setup()`.
 *
 *    2. Emit a Vue 3 component with `setup` + `render`.  `setup`
 *       creates the refs and returns them on the proxy; `render`
 *       reads `this.x` (auto-unwrapped) and writes via
 *       `this.x = ...`.
 *
 *  Pattern produced:
 *  {{{
 *  import { ref, h, Fragment, createApp } from 'vue';
 *  const App = {
 *    setup() {
 *      const count = ref(0);
 *      return { count };
 *    },
 *    render() {
 *      return h('div', null, [
 *        h('button', { 'onClick': () => { this.count = this.count + 1; } }, '+'),
 *        h('span',   null, this.count)
 *      ]);
 *    }
 *  };
 *  createApp(App).mount('#app');
 *  }}}
 *  Note `this.count` not `count.value` — Vue's component proxy
 *  unwraps refs exposed from `setup`. */
@nowarn("cat=deprecation")
private[vue] object VueEmitter:

  def emit(root: View[?]): String =
    val signals     = collectSignals(root)
    val lists       = collectLists(root)
    val refs        = collectRefs(root)
    val fetchTables = collectFetchTables(root)
    val usesPortal  = containsPortal(root)
    val sb = new StringBuilder
    sb ++= "// Generated by ScalaScript v1.18 — frontend-vue Phase A5 / A2e / A6 / FetchTable.\n"
    sb ++= "// Signals + lists + DomRefs + Portals + FetchTable lowered to ref() / watch / Teleport.\n"
    val teleportImport = if usesPortal then ", Teleport" else ""
    val watchImport    = if fetchTables.nonEmpty then ", watch" else ""
    sb ++= s"import { ref, h, Fragment$teleportImport$watchImport, createApp } from 'vue';\n"
    sb ++= "const App = {\n"
    sb ++= "  setup() {\n"
    signals.foreach { (name, initial) =>
      sb ++= s"    const $name = ref($initial);\n"
    }
    lists.foreach { (name, initial) =>
      sb ++= s"    const $name = ref($initial);\n"
    }
    // FetchTable: one ref([]) per table + initial fetch + watch on the tick signal.
    fetchTables.foreach { ft =>
      val urlJs    = jsString(ft.fetchUrl)
      val tickName = ft.tick.id
      sb ++= s"    const ${ft.tableId} = ref([]);\n"
      sb ++= s"    fetch($urlJs).then(r => r.json()).then(data => { ${ft.tableId}.value = data; });\n"
      sb ++= s"    watch($tickName, (t) => { if (t > 0) fetch($urlJs).then(r => r.json()).then(data => { ${ft.tableId}.value = data; }); });\n"
    }
    // A6 — DomRefs lower to setup-level `ref(null)`s.  Vue's template
    // ref system binds the underlying DOM element to the ref's .value
    // once mounted.  Expose on window for imperative user JS.
    refs.foreach { name =>
      sb ++= s"    const $name = ref(null);\n"
      sb ++= s"    if (typeof window !== 'undefined') window[${jsString(name)}] = $name;\n"
    }
    val allNames = signals.keys.toList ++ lists.keys.toList ++ fetchTables.map(_.tableId) ++ refs.toList
    val returned =
      if allNames.isEmpty then "{}"
      else "{ " + allNames.mkString(", ") + " }"
    sb ++= s"    return $returned;\n"
    sb ++= "  },\n"
    sb ++= "  render() {\n"
    sb ++= "    return "
    sb ++= renderView(root)
    sb ++= ";\n"
    sb ++= "  }\n"
    sb ++= "};\n"
    sb ++= "createApp(App).mount('#app');\n"
    sb.toString

  private def collectSignals(view: View[?]): scala.collection.mutable.LinkedHashMap[String, String] =
    val acc = scala.collection.mutable.LinkedHashMap.empty[String, String]
    def register(signal: ReactiveSignal[?]): Unit =
      val name = signal.id
      if !name.matches("[A-Za-z_][A-Za-z0-9_]*") then
        throw new IllegalArgumentException(
          s"ReactiveSignal id '$name' must match [A-Za-z_][A-Za-z0-9_]*."
        )
      val initJs = jsLiteral(signal())
      acc.get(name) match
        case Some(existing) if existing != initJs =>
          throw new IllegalArgumentException(
            s"ReactiveSignal id '$name' registered twice with different " +
            s"initial values ($existing vs $initJs)."
          )
        case _ => acc.update(name, initJs)
    def walk(v: View[?]): Unit = v match
      case View.SignalText(signal, _) =>
        register(signal)
      case View.Element(_, _, events, children) =>
        events.foreach { (_, handler) =>
          handler match
            case EventHandler.SetSignalLiteral(signal, _) => register(signal)
            case EventHandler.IncrementSignal(signal, _)  => register(signal)
            case EventHandler.ToggleSignal(signal)        => register(signal)
            case _ => ()
        }
        children.foreach(walk)
      case View.Fragment(children) => children.foreach(walk)
      case View.ComponentInstance(component, props) =>
        walk(component.render(props.asInstanceOf[Nothing]))
      case View.Show(_, whenTrue, whenFalse) =>
        walk(whenTrue())
        walk(whenFalse())
      case View.ShowSignal(cond, whenTrue, whenFalse) =>
        register(cond)
        walk(whenTrue)
        walk(whenFalse)
      case View.For(items, render) =>
        items().foreach(item => walk(render(item)))
      case View.ForSignal(_, _, _, itemTemplate) => itemTemplate.foreach(walk)
      case View.Portal(_, children) => children.foreach(walk)
      case View.FetchTable(_, _, _, tick) => register(tick)
      // P2
      case View.Column(children, _, _, _)     => children.foreach(walk)
      case View.Row(children, _, _, _)        => children.foreach(walk)
      case View.Stack(children, _)            => children.foreach(walk)
      case View.ScrollView(child, _, _)       => walk(child)
      case View.SafeArea(child, _)            => walk(child)
      case View.KeyboardAvoiding(child)       => walk(child)
      case View.Animated(child, _, _)         => walk(child)
      case View.Styled(child, _)              => walk(child)
      case View.Adaptive(web, _, _, fallback) => web.foreach(walk); walk(fallback)
      case View.LazyList(items, render, _, _)    => items().foreach(item => walk(render(item)))
      case View.LazyGrid(items, render, _, _, _) => items().foreach(item => walk(render(item)))
      case View.Button(label, action, _, _)   => walkHandler(action); walk(label)
      case View.TextInput(value, _, _, _, _)  => register(value)
      case View.Toggle(checked, _, _)         => register(checked)
      case View.Slider(value, _, _, _, _)     => register(value)
      case View.Picker(_, selected, _, _)     => register(selected)
      case View.TabBar(tabs, current, _) =>
        register(current); tabs.foreach(t => walk(t.content))
      case View.NavigationStack(routes, current, _) =>
        register(current); routes.values.foreach(fn => walk(fn()))
      case View.Sheet(content, isPresented)       => register(isPresented); walk(content)
      case View.AlertDialog(_, _, _, isPresented) => register(isPresented)
      case View.Form(child, onSubmit, _)  => walkHandler(onSubmit); walk(child)
      case View.FormField(_, value, _, _) => register(value)
      case _ => ()
    def walkHandler(h: EventHandler): Unit = h match
      case EventHandler.SetSignalLiteral(sig, _)         => register(sig)
      case EventHandler.IncrementSignal(sig, _)          => register(sig)
      case EventHandler.ToggleSignal(sig)                => register(sig)
      case EventHandler.InputChange(sig)                 => register(sig)
      case EventHandler.FetchAction(_, _, body, tick, _) => register(body); register(tick)
      case _ => ()
    walk(view)
    acc

  private def collectFetchTables(view: View[?]): Seq[View.FetchTable] =
    val seen = scala.collection.mutable.LinkedHashMap.empty[String, View.FetchTable]
    def walk(v: View[?]): Unit = v match
      case ft: View.FetchTable if !seen.contains(ft.tableId) => seen(ft.tableId) = ft
      case View.Element(_, _, _, children)               => children.foreach(walk)
      case View.Fragment(children)                       => children.foreach(walk)
      case View.ShowSignal(_, whenTrue, whenFalse)       => walk(whenTrue); walk(whenFalse)
      case View.Show(_, whenTrue, whenFalse)             => walk(whenTrue()); walk(whenFalse())
      case View.For(items, render)                       => items().foreach(item => walk(render(item)))
      case View.ForSignal(_, _, _, itemTemplate)         => itemTemplate.foreach(walk)
      case View.Portal(_, children)                      => children.foreach(walk)
      case View.ComponentInstance(component, props)      => walk(component.render(props.asInstanceOf[Nothing]))
      case _ => ()
    walk(view)
    seen.values.toSeq

  private def collectLists(view: View[?]): scala.collection.mutable.LinkedHashMap[String, String] =
    val acc = scala.collection.mutable.LinkedHashMap.empty[String, String]
    def register(list: ReactiveSignalList[?]): Unit =
      val name = list.id
      if !name.matches("[A-Za-z_][A-Za-z0-9_]*") then
        throw new IllegalArgumentException(
          s"ReactiveSignalList id '$name' must match [A-Za-z_][A-Za-z0-9_]*."
        )
      val initJs = jsArrayLiteral(list.initial)
      acc.get(name) match
        case Some(existing) if existing != initJs =>
          throw new IllegalArgumentException(
            s"ReactiveSignalList id '$name' registered twice with different " +
            s"initial values ($existing vs $initJs)."
          )
        case _ => acc.update(name, initJs)
    def walk(v: View[?]): Unit = v match
      case View.ForSignal(list, _, _, itemTemplate) =>
        register(list)
        itemTemplate.foreach(walk)
      case View.Element(_, _, events, children) =>
        events.foreach { (_, handler) =>
          handler match
            case EventHandler.PushSignalLiteral(list, _) => register(list)
            case EventHandler.ClearSignalList(list)      => register(list)
            case EventHandler.RemoveSelfFromList(list)   => register(list)
            case _ => ()
        }
        children.foreach(walk)
      case View.Fragment(children) => children.foreach(walk)
      case View.ComponentInstance(component, props) =>
        walk(component.render(props.asInstanceOf[Nothing]))
      case View.Show(_, whenTrue, whenFalse) =>
        walk(whenTrue()); walk(whenFalse())
      case View.ShowSignal(_, whenTrue, whenFalse) =>
        walk(whenTrue); walk(whenFalse)
      case View.For(items, render) =>
        items().foreach(item => walk(render(item)))
      case View.Portal(_, children) => children.foreach(walk)
      case _ => ()
    walk(view)
    acc

  /** A6 — DomRef collection.  Each becomes a `ref(null)` in setup()
   *  + a template-ref binding on the element. */
  private def collectRefs(view: View[?]): scala.collection.mutable.LinkedHashSet[String] =
    val acc = scala.collection.mutable.LinkedHashSet.empty[String]
    def register(ref: WidgetRef): Unit =
      val name = ref.id
      if !name.matches("[A-Za-z_][A-Za-z0-9_]*") then
        throw new IllegalArgumentException(
          s"WidgetRef id '$name' must match [A-Za-z_][A-Za-z0-9_]*."
        )
      acc += name
    def walk(v: View[?]): Unit = v match
      case View.Element(_, attrs, _, children) =>
        attrs.values.foreach {
          case AttrValue.RefBinding(ref) => register(ref)
          case _ => ()
        }
        children.foreach(walk)
      case View.Fragment(children) => children.foreach(walk)
      case View.ComponentInstance(component, props) =>
        walk(component.render(props.asInstanceOf[Nothing]))
      case View.Show(_, whenTrue, whenFalse) =>
        walk(whenTrue()); walk(whenFalse())
      case View.ShowSignal(_, whenTrue, whenFalse) =>
        walk(whenTrue); walk(whenFalse)
      case View.For(items, render) =>
        items().foreach(item => walk(render(item)))
      case View.Portal(_, children) => children.foreach(walk)
      case View.ForSignal(_, _, _, itemTemplate) => itemTemplate.foreach(walk)
      case _ => ()
    walk(view)
    acc

  /** A6 — cheap walk used at emit time to decide whether to import
   *  `Teleport` from 'vue'.  Pulling the import in unconditionally
   *  is harmless but `containsPortal` keeps the generated bundle
   *  diff-free for portal-less apps. */
  private def containsPortal(view: View[?]): Boolean = view match
    case _: View.Portal => true
    case View.Element(_, _, _, children) => children.exists(containsPortal)
    case View.Fragment(children) => children.exists(containsPortal)
    case View.ComponentInstance(component, props) =>
      containsPortal(component.render(props.asInstanceOf[Nothing]))
    case View.Show(_, whenTrue, whenFalse) =>
      containsPortal(whenTrue()) || containsPortal(whenFalse())
    case View.ShowSignal(_, whenTrue, whenFalse) =>
      containsPortal(whenTrue) || containsPortal(whenFalse)
    case View.For(items, render) =>
      items().exists(item => containsPortal(render(item)))
    case View.ForSignal(_, _, _, itemTemplate) =>
      itemTemplate.exists(containsPortal)
    case _ => false

  private def renderView(view: View[?], itemCtx: Option[ReactiveSignalList[?]] = None): String = view match
    case View.Element(tag, attrs, events, children) =>
      val propsJs = renderProps(attrs, events, itemCtx)
      val childrenJs =
        if children.isEmpty then ""
        else ", [" + children.map(c => renderView(c, itemCtx)).mkString(", ") + "]"
      s"h(${jsString(tag)}, $propsJs$childrenJs)"

    case View.TextNode(thunk) =>
      jsString(thunk())

    case View.SignalText(signal, _) =>
      // `this.x` — Vue's component proxy auto-unwraps the ref.
      "this." + signal.id

    case View.ItemText =>
      // A2e.2 — `String(item)` when inside a render-arrow's
      // map callback; literal '' outside (graceful no-op).
      if itemCtx.isDefined then "String(item)" else "''"

    case View.Fragment(children) =>
      if children.isEmpty then "null"
      else s"h(Fragment, null, [${children.map(c => renderView(c, itemCtx)).mkString(", ")}])"

    case View.ComponentInstance(component, props) =>
      renderView(component.render(props.asInstanceOf[Nothing]), itemCtx)

    case View.Show(cond, whenTrue, whenFalse) =>
      val branch = if cond() then whenTrue() else whenFalse()
      renderView(branch, itemCtx)

    case View.ShowSignal(cond, whenTrue, whenFalse) =>
      // Ternary inside render — Vue re-runs render when the ref
      // (read via proxy) changes; the ternary re-evaluates.
      s"(this.${cond.id} ? ${renderView(whenTrue, itemCtx)} : ${renderView(whenFalse, itemCtx)})"

    case View.For(items, render) =>
      val realised = items().toList
      if realised.isEmpty then "null"
      else
        val parts = realised.map(item => renderView(render(item), itemCtx))
        s"[${parts.mkString(", ")}]"

    case View.ForSignal(list, tag, attrs, itemTemplate) =>
      // A2e / A2e.2 — map over `this.<jsName>`.  Two flavours:
      //
      //  - simple form: `h(tag, propsWithKey, String(item))`.
      //  - rich form: emit the template recursively with
      //    `itemCtx = Some(list)`; inject `key: String(item)` on
      //    the template's Element root.
      itemTemplate match
        case None =>
          val tagJs = jsString(tag)
          val attrFields = attrs.flatMap { (k, av) =>
            attrValueJs(av).map(value => s"${jsString(k)}: $value")
          }
          val propsParts = "'key': String(item)" :: attrFields.toList
          val propsJs    = s"{ ${propsParts.mkString(", ")} }"
          s"this.${list.id}.map((item, index) => h($tagJs, $propsJs, String(item)))"
        case Some(template) =>
          val body = template match
            case View.Element(tag, attrs, events, children) =>
              val propsJs    = renderProps(attrs, events, Some(list), injectKey = true)
              val childrenJs =
                if children.isEmpty then ""
                else ", [" + children.map(c => renderView(c, Some(list))).mkString(", ") + "]"
              s"h(${jsString(tag)}, $propsJs$childrenJs)"
            case other =>
              renderView(other, Some(list))
          s"this.${list.id}.map((item, index) => $body)"

    case View.Portal(target, children) =>
      // A6 — Vue's Teleport renders its slot content into the DOM
      // element matched by the `to` selector.  Same shape as our
      // Portal: `h(Teleport, { to: target }, [...children])`.
      val targetJs = jsString(target)
      val childrenJs =
        if children.isEmpty then ""
        else ", [" + children.map(c => renderView(c, itemCtx)).mkString(", ") + "]"
      s"h(Teleport, { 'to': $targetJs }$childrenJs)"

    case View.FetchTable(tableId, _, deleteUrl, tick) =>
      val tickName   = tick.id
      val delUrlJs   = jsString(deleteUrl)
      val thStyle    = "{ textAlign: 'left', padding: '6px 12px', borderBottom: '2px solid #e5e7eb', fontWeight: 600, color: '#111827' }"
      val tdStyle    = "{ padding: '6px 12px', borderBottom: '1px solid #e5e7eb', color: '#374151', verticalAlign: 'middle' }"
      val btnStyle   = "{ background: '#ef4444', color: '#fff', border: 'none', padding: '6px 16px', borderRadius: '4px', cursor: 'pointer', fontSize: 'inherit', fontFamily: 'inherit' }"
      val tableStyle = "{ borderCollapse: 'collapse', width: '100%', fontFamily: 'inherit', fontSize: 'inherit' }"
      val theadStyle = "{ background: '#f9fafb' }"
      val rowFn =
        s"this.$tableId.map((row, _i) => " +
        s"h('tr', { key: String(row.id) }, [" +
        s"h('td', { style: $tdStyle }, String(row.text)), " +
        s"h('td', { style: $tdStyle }, [" +
        s"h('button', { style: $btnStyle, onClick: () => { fetch($delUrlJs, { method: 'POST', body: String(row.id) }).then(r => r.text()).then(_ => { this.$tickName++; }); } }, 'Delete')" +
        s"])]))"
      s"h('table', { style: $tableStyle }, [" +
        s"h('thead', { style: $theadStyle }, [h('tr', null, [h('th', { style: $thStyle }, 'Task'), h('th', { style: $thStyle }, '')])]), " +
        s"h('tbody', null, $rowFn)])"

    // ── P2 semantic View cases ─────────────────────────────────────────────────
    // Vue h() children must be in an array; style prop accepts CSS string.

    case View.Column(children, spacing, align, style) =>
      val gapCss = if spacing > 0 then s"; gap: ${spacing}px" else ""
      val base   = s"display: flex; flex-direction: column; align-items: ${StyleUtils.hAlignToCSS(align)}$gapCss"
      val css    = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
      val kids   = children.map(c => renderView(c, itemCtx)).mkString(", ")
      s"h('div', { style: ${jsString(css)} }, [$kids])"

    case View.Row(children, spacing, align, style) =>
      val gapCss = if spacing > 0 then s"; gap: ${spacing}px" else ""
      val base   = s"display: flex; flex-direction: row; align-items: ${StyleUtils.vAlignToCSS(align)}$gapCss"
      val css    = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
      val kids   = children.map(c => renderView(c, itemCtx)).mkString(", ")
      s"h('div', { style: ${jsString(css)} }, [$kids])"

    case View.Stack(children, style) =>
      val css  = StyleUtils.mergeCSS("position: relative", StyleUtils.styleToCSS(style))
      val kids = children.map(c => renderView(c, itemCtx)).mkString(", ")
      s"h('div', { style: ${jsString(css)} }, [$kids])"

    case View.ScrollView(child, axis, style) =>
      val base = axis match
        case Axis.Horizontal => "overflow-x: auto; overflow-y: hidden"
        case Axis.Vertical   => "overflow-y: auto; overflow-x: hidden"
        case Axis.Both       => "overflow: auto"
      val css  = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
      s"h('div', { style: ${jsString(css)} }, [${renderView(child, itemCtx)}])"

    case View.Spacer(size) =>
      val css = size match
        case Some(px) => s"width: ${px}px; height: ${px}px; flex-shrink: 0"
        case None     => "flex: 1; align-self: stretch"
      s"h('div', { style: ${jsString(css)} })"

    case View.Divider(axis, style) =>
      val base = axis match
        case Axis.Vertical => "width: 1px; height: 100%; background: currentColor; opacity: 0.2; flex-shrink: 0"
        case _             => "width: 100%; height: 1px; background: currentColor; opacity: 0.2; flex-shrink: 0"
      val css = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
      s"h('div', { role: 'separator', style: ${jsString(css)} })"

    case View.Text(content, style) =>
      val css = StyleUtils.styleToCSS(style)
      val styleField = if css.isEmpty then "null" else s"{ style: ${jsString(css)} }"
      s"h('span', $styleField, ${jsString(content())})"

    case View.Image(source, style) =>
      val src = source match
        case ImageSource.Url(href)           => jsString(href)
        case ImageSource.Asset(name)         => jsString(s"/assets/$name")
        case ImageSource.Base64(data, mime)  => jsString(s"data:$mime;base64,$data")
      val css = StyleUtils.styleToCSS(style)
      val styleField = if css.isEmpty then "" else s", style: ${jsString(css)}"
      s"h('img', { 'src': $src$styleField })"

    case View.Icon(name, style) =>
      val css = StyleUtils.styleToCSS(style)
      val styleField = if css.isEmpty then "" else s", style: ${jsString(css)}"
      s"h('span', { 'aria-hidden': 'true', 'data-icon': ${jsString(name)}$styleField }, ${jsString(name)})"

    case View.Button(label, action, enabled, style) =>
      val base = "cursor: pointer; display: inline-flex; align-items: center; justify-content: center; border: none; padding: 6px 16px; border-radius: 4px"
      val css  = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
      val onClickJs = eventHandlerJs("click", action, itemCtx)
      val disabledField = if !enabled() then ", 'disabled': true" else ""
      val clickField    = onClickJs.map(f => s", $f").getOrElse("")
      s"h('button', { style: ${jsString(css)}$clickField$disabledField }, [${renderView(label, itemCtx)}])"

    case View.TextInput(value, placeholder, multiline, secure, style) =>
      val base = "padding: 6px 10px; border: 1px solid #d1d5db; border-radius: 4px; font-size: inherit; font-family: inherit"
      val css  = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
      if multiline then
        s"h('textarea', { style: ${jsString(css)}, 'value': this.${value.id}, 'onInput': (e) => { this.${value.id} = e.target.value; }, 'placeholder': ${jsString(placeholder)} })"
      else
        val typeAttr = if secure then "'type': 'password'" else "'type': 'text'"
        s"h('input', { style: ${jsString(css)}, $typeAttr, 'value': this.${value.id}, 'onInput': (e) => { this.${value.id} = e.target.value; }, 'placeholder': ${jsString(placeholder)} })"

    case View.Toggle(checked, label, style) =>
      val base = "display: inline-flex; align-items: center; gap: 6px; cursor: pointer"
      val css  = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
      val labelJs = if label.isEmpty then "" else s", ${jsString(label)}"
      s"h('label', { style: ${jsString(css)} }, [h('input', { 'type': 'checkbox', 'checked': this.${checked.id}, 'onChange': () => { this.${checked.id} = !this.${checked.id}; } })$labelJs])"

    case View.Slider(value, min, max, step, style) =>
      val css = StyleUtils.styleToCSS(style)
      val styleField = if css.isEmpty then "" else s", style: ${jsString(css)}"
      s"h('input', { 'type': 'range', 'min': $min, 'max': $max, 'step': $step, 'value': this.${value.id}, 'onInput': (e) => { this.${value.id} = Number(e.target.value); }$styleField })"

    case View.Picker(options, selected, placeholder, style) =>
      val base = "padding: 6px 10px; border: 1px solid #d1d5db; border-radius: 4px; font-size: inherit; font-family: inherit"
      val css  = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
      val opts = options.map { (lbl, v) =>
        val vJs = try jsLiteral(v) catch { case _: Throwable => jsString(String.valueOf(v)) }
        s"h('option', { 'value': $vJs }, ${jsString(lbl)})"
      }
      val phOpt = if placeholder.nonEmpty then
        s"h('option', { 'value': '', 'disabled': true, 'hidden': true }, ${jsString(placeholder)})" +: opts
      else opts
      s"h('select', { style: ${jsString(css)}, 'value': this.${selected.id}, 'onChange': (e) => { this.${selected.id} = e.target.value; } }, [${phOpt.mkString(", ")}])"

    case View.LazyList(items, render, _, style) =>
      val css  = StyleUtils.mergeCSS("overflow-y: auto", StyleUtils.styleToCSS(style))
      val kids = items().toList.map(item => renderView(render(item), itemCtx)).mkString(", ")
      s"h('div', { style: ${jsString(css)} }, [$kids])"

    case View.LazyGrid(items, render, columns, spacing, style) =>
      val colsCss = StyleUtils.gridColumnsToCSS(columns)
      val gapCss  = if spacing > 0 then s"; gap: ${spacing}px" else ""
      val base    = s"display: grid; grid-template-columns: $colsCss$gapCss"
      val css     = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
      val kids = items().toList.map(item => renderView(render(item), itemCtx)).mkString(", ")
      s"h('div', { style: ${jsString(css)} }, [$kids])"

    case View.TabBar(tabs, current, style) =>
      val outerCss  = StyleUtils.styleToCSS(style)
      val outerField = if outerCss.isEmpty then "null" else s"{ style: ${jsString(outerCss)} }"
      val headerCss  = "display: flex; border-bottom: 1px solid #e5e7eb; margin-bottom: 8px"
      val activeBase  = "cursor: pointer; padding: 8px 16px; border: none; background: transparent; font-family: inherit; font-size: inherit; border-bottom: 2px solid #3b82f6; font-weight: bold"
      val inactiveBase = "cursor: pointer; padding: 8px 16px; border: none; background: transparent; font-family: inherit; font-size: inherit; border-bottom: 2px solid transparent"
      val tabHeaders = tabs.zipWithIndex.map { (tab, i) =>
        val styleProp = s"this.${current.id} === $i ? ${jsString(activeBase)} : ${jsString(inactiveBase)}"
        s"h('button', { style: $styleProp, 'onClick': () => { this.${current.id} = $i; } }, ${jsString(tab.label)})"
      }.mkString(", ")
      val tabContents = tabs.zipWithIndex.map { (tab, i) =>
        s"this.${current.id} === $i ? ${renderView(tab.content, itemCtx)} : null"
      }.mkString(", ")
      s"h('div', $outerField, [h('div', { style: ${jsString(headerCss)} }, [$tabHeaders]), $tabContents])"

    case View.NavigationStack(routes, current, style) =>
      val outerCss   = StyleUtils.styleToCSS(style)
      val outerField = if outerCss.isEmpty then "null" else s"{ style: ${jsString(outerCss)} }"
      val branches   = routes.toList.map { (key, fn) =>
        s"this.${current.id} === ${jsString(key)} ? ${renderView(fn(), itemCtx)} : null"
      }.mkString(", ")
      s"h('div', $outerField, [$branches])"

    case View.Sheet(content, isPresented) =>
      val overlayCss  = "position: fixed; bottom: 0; left: 0; right: 0; background: #fff; box-shadow: 0 -4px 12px rgba(0,0,0,0.15); border-radius: 12px 12px 0 0; padding: 16px; z-index: 1000"
      val backdropCss = "position: fixed; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0,0,0,0.4); z-index: 999"
      s"this.${isPresented.id} ? h('div', null, [h('div', { style: ${jsString(backdropCss)}, 'onClick': () => { this.${isPresented.id} = false; } }), h('div', { style: ${jsString(overlayCss)} }, [${renderView(content, itemCtx)}])]) : null"

    case View.AlertDialog(title, message, buttons, isPresented) =>
      val dialogCss   = "position: fixed; top: 50%; left: 50%; transform: translate(-50%,-50%); background: #fff; padding: 24px; border-radius: 8px; box-shadow: 0 4px 32px rgba(0,0,0,0.2); z-index: 1001; min-width: 300px"
      val backdropCss = "position: fixed; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0,0,0,0.4); z-index: 1000"
      val btnDefault      = "background: #3b82f6; color: #fff; border: none; padding: 8px 16px; border-radius: 4px; cursor: pointer; font-family: inherit; font-size: inherit"
      val btnDestructive  = "background: #ef4444; color: #fff; border: none; padding: 8px 16px; border-radius: 4px; cursor: pointer; font-family: inherit; font-size: inherit"
      val btnsJs = buttons.map { btn =>
        val css = if btn.role == ButtonRole.Destructive then btnDestructive else btnDefault
        s"h('button', { style: ${jsString(css)}, 'onClick': () => { this.${isPresented.id} = false; } }, ${jsString(btn.label)})"
      }.mkString(", ")
      val btnRowCss = "display: flex; gap: 8px; margin-top: 16px"
      s"this.${isPresented.id} ? h('div', null, [h('div', { style: ${jsString(backdropCss)} }), h('div', { style: ${jsString(dialogCss)} }, [h('h3', null, ${jsString(title)}), h('p', null, ${jsString(message)}), h('div', { style: ${jsString(btnRowCss)} }, [$btnsJs])])]) : null"

    case View.Form(child, onSubmit, style) =>
      val handlerBody = onSubmit match
        case EventHandler.SetSignalLiteral(sig, v) => s"this.${sig.id} = ${jsLiteral(v)};"
        case EventHandler.IncrementSignal(sig, by) => s"this.${sig.id} = this.${sig.id} + $by;"
        case EventHandler.ToggleSignal(sig)        => s"this.${sig.id} = !this.${sig.id};"
        case EventHandler.FetchAction(method, url, body, tick, clearBody) =>
          val clear = if clearBody then s" this.${body.id} = '';" else ""
          s"fetch(${jsString(url)}, {method: ${jsString(method)}, body: this.${body.id}}).then(r => r.text()).then(_ => { this.${tick.id}++;$clear });"
        case _ => ""
      val css = StyleUtils.styleToCSS(style)
      val styleField = if css.isEmpty then "null" else s"{ style: ${jsString(css)} }"
      s"h('form', { 'onSubmit': (e) => { e.preventDefault(); $handlerBody }, ...($styleField === null ? {} : $styleField) }, [${renderView(child, itemCtx)}])"

    case View.FormField(label, value, validate, style) =>
      val errorMsg   = try validate(value().asInstanceOf[Nothing]) catch { case _: Throwable => None }
      val inputType  = value() match
        case _: Int | _: Double | _: Long | _: Float => "'number'"
        case _: Boolean                               => "'checkbox'"
        case _                                        => "'text'"
      val inputBase  = "padding: 6px 10px; border: 1px solid #d1d5db; border-radius: 4px; width: 100%; box-sizing: border-box; font-size: inherit; font-family: inherit"
      val inputCss   = StyleUtils.mergeCSS(inputBase, StyleUtils.styleToCSS(style))
      val errorJs    = errorMsg.map { msg =>
        s", h('span', { style: ${jsString("color: #ef4444; font-size: 0.75em; display: block; margin-top: 2px")} }, ${jsString(msg)})"
      }.getOrElse("")
      val labelCss   = "display: block; margin-bottom: 4px; font-size: 0.875em; font-weight: 500"
      s"h('label', { style: ${jsString(labelCss)} }, [${jsString(label)}, h('input', { 'type': $inputType, style: ${jsString(inputCss)}, 'value': this.${value.id}, 'onInput': (e) => { this.${value.id} = e.target.value; } })$errorJs])"

    case View.SafeArea(child, edges) =>
      val top    = if edges.contains(Edge.Top)      then "env(safe-area-inset-top, 0)" else "0"
      val right  = if edges.contains(Edge.Trailing) then "env(safe-area-inset-right, 0)" else "0"
      val bottom = if edges.contains(Edge.Bottom)   then "env(safe-area-inset-bottom, 0)" else "0"
      val left   = if edges.contains(Edge.Leading)  then "env(safe-area-inset-left, 0)" else "0"
      val css    = s"padding-top: $top; padding-right: $right; padding-bottom: $bottom; padding-left: $left"
      s"h('div', { style: ${jsString(css)} }, [${renderView(child, itemCtx)}])"

    case View.KeyboardAvoiding(child) =>
      renderView(child, itemCtx)

    case View.Animated(child, transition, style) =>
      val dur    = transition.duration.toLong
      val delay  = if transition.delay > 0 then s" ${transition.delay.toLong}ms" else ""
      val base   = s"transition: all ${dur}ms ${StyleUtils.curveToCSS(transition.curve)}$delay"
      val css    = StyleUtils.mergeCSS(base, StyleUtils.styleToCSS(style))
      s"h('div', { style: ${jsString(css)} }, [${renderView(child, itemCtx)}])"

    case View.Styled(child, style) =>
      val css = StyleUtils.styleToCSS(style)
      if css.isEmpty then renderView(child, itemCtx)
      else s"h('div', { style: ${jsString(css)} }, [${renderView(child, itemCtx)}])"

    case View.Adaptive(web, _, _, fallback) =>
      renderView(web.getOrElse(fallback), itemCtx)

  private def renderProps(
      attrs:     Map[String, AttrValue],
      events:    Map[String, EventHandler],
      itemCtx:   Option[ReactiveSignalList[?]],
      injectKey: Boolean = false
  ): String =
    val attrFields = attrs.flatMap { (k, v) =>
      v match
        case AttrValue.RefBinding(ref) =>
          // A6 — Vue's template `ref` prop accepts the setup-time ref
          // object directly.  Vue assigns the DOM element to ref.value
          // after mount; ignore the user-picked attr key since Vue
          // reserves the `ref` name for this binding.
          Some(s"'ref': ${ref.id}")
        case _ =>
          attrValueJs(v).map { value =>
            // Vue accepts `class` natively (same as Solid; unlike React).
            s"${jsString(k)}: $value"
          }
    }
    val eventFields = events.flatMap { (eventName, handler) =>
      eventHandlerJs(eventName, handler, itemCtx)
    }
    val keyField = if injectKey then List("'key': String(item)") else Nil
    val all = keyField ++ attrFields ++ eventFields
    if all.isEmpty then "null" else s"{ ${all.mkString(", ")} }"

  private def attrValueJs(av: AttrValue): Option[String] = av match
    case AttrValue.Str(value)     => Some(jsString(value))
    case AttrValue.Bool(value)    => Some(value.toString)
    case AttrValue.Num(value)     => Some(formatNumber(value))
    case AttrValue.Dynamic(read)    => Some(jsLiteral(read()))
    case AttrValue.Reactive(signal) => Some(s"this.${signal.id}")
    case AttrValue.Absent           => None
    case AttrValue.RefBinding(_)    => None  // handled inline in renderProps as the Vue `ref` prop

  private def eventHandlerJs(
      eventName: String,
      handler:   EventHandler,
      itemCtx:   Option[ReactiveSignalList[?]]
  ): Option[String] =
    val onKey = onProp(eventName)
    // Arrow functions defined INSIDE render() lexically capture
    // render()'s `this` — which IS the Vue component proxy.  A
    // function expression instead would lose `this` because Vue's
    // DOM-listener invoker calls it with `this === null`.
    handler match
      case EventHandler.SetSignalLiteral(signal, value) =>
        val v = jsLiteral(value)
        Some(s"${jsString(onKey)}: () => { this.${signal.id} = $v; }")
      case EventHandler.IncrementSignal(signal, by) =>
        Some(s"${jsString(onKey)}: () => { this.${signal.id} = this.${signal.id} + $by; }")
      case EventHandler.ToggleSignal(signal) =>
        Some(s"${jsString(onKey)}: () => { this.${signal.id} = !this.${signal.id}; }")
      case EventHandler.PushSignalLiteral(list, value) =>
        val v = jsLiteral(value)
        Some(s"${jsString(onKey)}: () => { this.${list.id} = this.${list.id}.concat([$v]); }")
      case EventHandler.ClearSignalList(list) =>
        Some(s"${jsString(onKey)}: () => { this.${list.id} = []; }")
      case EventHandler.RemoveSelfFromList(list) =>
        // A2e.2 — inside an item template, capture the map-callback
        // `index` so the listener filters its own slot out.
        if itemCtx.exists(_.id == list.id) then
          Some(s"${jsString(onKey)}: () => { this.${list.id} = this.${list.id}.filter((_, i) => i !== index); }")
        else
          Some(s"/* '$eventName' is RemoveSelfFromList used outside an item template — no-op */")
      case EventHandler.FetchAction(method, url, body, tick, clearBody) =>
        val urlJs    = jsString(url)
        val methodJs = jsString(method)
        val clearJs  = if clearBody then s" this.${body.id} = '';" else ""
        Some(s"${jsString(onKey)}: () => { fetch($urlJs, {method: $methodJs, body: this.${body.id}})" +
          s".then(r => r.text()).then(_ => { this.${tick.id}++;$clearJs }); }")
      case EventHandler.InputChange(signal) =>
        Some(s"'onInput': (e) => { this.${signal.id} = e.target.value; }")
      case EventHandler.Simple(_) | EventHandler.WithEvent(_) =>
        Some(s"/* '$eventName' is a JVM closure — A5 can't translate (richer IR coming later) */")

  /** Vue uses camelCase event props: 'click' → 'onClick'. */
  private def onProp(eventName: String): String =
    "on" + eventName.headOption.fold("")(_.toUpper.toString) + eventName.drop(1)

  private def jsLiteral(value: Any): String = value match
    case s: String  => jsString(s)
    case i: Int     => i.toString
    case l: Long    => l.toString
    case d: Double  => formatNumber(d)
    case f: Float   => formatNumber(f.toDouble)
    case b: Boolean => b.toString
    case null       => "null"
    case other      => throw new IllegalArgumentException(
      s"jsLiteral: unsupported value type ${other.getClass.getName} ($other).  " +
      "Supported: String / Int / Long / Double / Float / Boolean / null."
    )

  private def jsArrayLiteral(items: Seq[Any]): String =
    items.map(jsLiteral).mkString("[", ", ", "]")

  private def formatNumber(d: Double): String =
    if d == d.toLong.toDouble then d.toLong.toString else d.toString

  private def jsString(s: String): String =
    val sb = new StringBuilder
    sb += '\''
    s.foreach {
      case '\\' => sb ++= "\\\\"
      case '\'' => sb ++= "\\'"
      case '\n' => sb ++= "\\n"
      case '\r' => sb ++= "\\r"
      case '<'  => sb ++= "\\u003c"
      case c    => sb += c
    }
    sb += '\''
    sb.toString
