package scalascript

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, StandardOpenOption}

import org.scalatest.funsuite.AnyFunSuite

import scalascript.codegen.JvmGen
import scalascript.parser.Parser

/** v1.26 Phase 7 (deferred) — end-to-end JvmGen smoke test that
 *  compiles + runs the emitted Scala source through `scala-cli`.
 *
 *  Without publishing `scalascript-backend-sql-runtime` to Maven
 *  Central, the `//> using lib "io.scalascript::…"` directive that
 *  JvmGen emits doesn't resolve.  Workaround: build the runtime JAR
 *  locally (`sbt backendSqlRuntime/Compile/packageBin`, wired into
 *  the `Test / resourceGenerators` of `backendInterpreter` so the jar
 *  is always fresh) and replace the directive in the emitted source
 *  with `//> using jar "<absolute-path>"` before handing it to
 *  scala-cli.
 *
 *  Skipped (not failed) when `scala-cli` is unavailable on PATH so
 *  CI environments without it keep working. */
class JvmGenSqlRuntimeTest extends AnyFunSuite {

  private lazy val hasScalaCli: Boolean =
    try ProcessBuilder("scala-cli", "--version").start().waitFor() == 0
    catch case _: Throwable => false

  /** Path to the freshly-built `scalascript-backend-sql-runtime` JAR,
   *  injected via `Test / resourceGenerators` in `build.sbt`. */
  private lazy val sqlRuntimeJar: String =
    val url = getClass.getClassLoader.getResource("scalascript/sql-runtime-jar.path")
    assert(url != null, "missing classpath resource `scalascript/sql-runtime-jar.path` — " +
      "expected to be generated by `Test / resourceGenerators` in build.sbt")
    val src = io.Source.fromURL(url)
    try src.mkString.trim finally src.close()

  /** Replace the `//> using lib "io.scalascript::scalascript-backend-sql-runtime:…"`
   *  directive emitted by JvmGen with `//> using jar "<absolute-path>"`
   *  so scala-cli picks up the locally-built artifact instead of
   *  trying to resolve it from Maven Central. */
  private def rewriteLibToJar(src: String): String =
    val libLine =
      """//> using lib "io.scalascript::scalascript-backend-sql-runtime:0.1.0-SNAPSHOT""""
    val jarLine = s"""//> using jar "$sqlRuntimeJar""""
    assert(src.contains(libLine),
      s"emitted JvmGen source missing the expected `using lib` directive — got first 400 chars:\n${src.take(400)}")
    src.replace(libLine, jarLine)

  /** Build, transform, and run the JvmGen emission through `scala-cli`.
   *  Returns (exitCode, stdout, stderr). */
  private def runViaScalaCli(ssc: String): (Int, String, String) =
    val module = Parser.parse(ssc)
    val raw    = JvmGen.generate(module)
    val patched = rewriteLibToJar(raw)
    val tmp = Files.createTempFile("ssc-jvmgen-sql-", ".sc")
    tmp.toFile.deleteOnExit()
    Files.write(tmp, patched.getBytes(StandardCharsets.UTF_8),
      StandardOpenOption.WRITE, StandardOpenOption.TRUNCATE_EXISTING)
    val pb = ProcessBuilder("scala-cli", "run", tmp.toAbsolutePath.toString)
      .redirectErrorStream(false)
    val proc = pb.start()
    val out  = new String(proc.getInputStream.readAllBytes(), StandardCharsets.UTF_8)
    val err  = new String(proc.getErrorStream.readAllBytes(), StandardCharsets.UTF_8)
    val code = proc.waitFor()
    (code, out, err)

  // ── Tests ───────────────────────────────────────────────────────────

  test("scala-cli compiles + runs JvmGen-emitted SQL block against H2") {
    assume(hasScalaCli, "scala-cli not available on PATH")
    val ssc =
      """|---
         |databases:
         |  default:
         |    url: "jdbc:h2:mem:jvmgen-rt;DB_CLOSE_DELAY=-1"
         |---
         |
         |# Schema
         |
         |```sql
         |CREATE TABLE t (id INT PRIMARY KEY, name VARCHAR(64))
         |```
         |
         |# Seed
         |
         |```scala
         |val id   = 1
         |val nm   = "Alice"
         |```
         |
         |```sql
         |INSERT INTO t (id, name) VALUES (${id}, ${nm})
         |```
         |
         |# Read
         |
         |```sql
         |SELECT name FROM t WHERE id = ${id}
         |```
         |
         |```scala
         |val row = Read.sql match
         |  case scalascript.sql.SqlResult.Rows(rs) => rs.head
         |  case other                              => sys.error("expected Rows, got " + other)
         |println("got=" + row("NAME"))
         |```
         |""".stripMargin

    val (code, stdout, stderr) = runViaScalaCli(ssc)
    assert(code == 0,
      s"scala-cli exit $code\n--- stdout ---\n$stdout\n--- stderr ---\n$stderr")
    assert(stdout.contains("got=Alice"),
      s"expected `got=Alice` in stdout, got:\n$stdout\n---stderr---\n$stderr")
  }

  test("scala-cli runs DDL + UPDATE returning affected-row count") {
    assume(hasScalaCli, "scala-cli not available on PATH")
    val ssc =
      """|---
         |databases:
         |  default:
         |    url: "jdbc:h2:mem:jvmgen-update;DB_CLOSE_DELAY=-1"
         |---
         |
         |# Setup
         |
         |```sql
         |CREATE TABLE t (id INT, n INT)
         |```
         |
         |```sql
         |INSERT INTO t VALUES (1, 10)
         |```
         |
         |```sql
         |INSERT INTO t VALUES (2, 20)
         |```
         |
         |# Mutate
         |
         |```sql
         |UPDATE t SET n = n + 1
         |```
         |
         |```scala
         |Mutate.sql match
         |  case scalascript.sql.SqlResult.UpdateCount(n) => println("affected=" + n)
         |  case other                                    => sys.error("expected UpdateCount, got " + other)
         |```
         |""".stripMargin

    val (code, stdout, stderr) = runViaScalaCli(ssc)
    assert(code == 0,
      s"scala-cli exit $code\n--- stdout ---\n$stdout\n--- stderr ---\n$stderr")
    assert(stdout.contains("affected=2"),
      s"expected `affected=2` in stdout, got:\n$stdout\n---stderr---\n$stderr")
  }
}
