package scalascript.micropayment.probabilistic

import java.security.MessageDigest
import javax.crypto.Mac
import javax.crypto.spec.SecretKeySpec

/** Pure lottery math — no blockchain dependency, cross-compiles to Scala.js.
 *
 *  Win condition: `SHA-256(preimage XOR salt) < threshold`
 *  where `threshold = claimedAmount * 2^256 / maxPayout`.
 *  Expected value per ticket: `P(win) * maxPayout = claimedAmount`. */
object LotteryMath:

  /** True iff the (preimage, salt) pair is a winner.
   *
   *  @param preimage     32-byte random secret generated by the payer
   *  @param salt         32-byte challenge generated by the server
   *  @param claimedAmount value the payer claims for this ticket
   *  @param maxPayout    maximum payout per winning ticket (= batch redemption unit) */
  def isWinner(
    preimage:     Array[Byte],
    salt:         Array[Byte],
    claimedAmount: BigInt,
    maxPayout:     BigInt,
  ): Boolean =
    require(preimage.length == 32, "preimage must be 32 bytes")
    require(salt.length     == 32, "salt must be 32 bytes")
    require(claimedAmount > 0,     "claimedAmount must be positive")
    require(maxPayout >= claimedAmount, "maxPayout must be >= claimedAmount")
    val xored     = xor32(preimage, salt)
    val hashVal   = BigInt(1, sha256(xored))       // interpret 32-byte digest as uint256
    val threshold = claimedAmount * BigInt(2).pow(256) / maxPayout
    hashVal < threshold

  /** Server-side salt derived from a secret key and the ticket commitment.
   *
   *  Uses HMAC-SHA-256 so the salt is deterministic per (key, commitment) pair,
   *  preventing the server from adaptive salt selection.
   *  Note: for stronger security use interactive challenges (server sends random
   *  salt after receiving the commitment, before the payer reveals the preimage). */
  def serverSalt(serverKey: Array[Byte], commitment: Array[Byte]): Array[Byte] =
    val mac = Mac.getInstance("HmacSHA256")
    mac.init(new SecretKeySpec(serverKey, "HmacSHA256"))
    mac.doFinal(commitment).take(32)

  /** SHA-256 commitment to a preimage. The payer sends this before revealing
   *  the preimage, so the server cannot choose a biased salt. */
  def commitment(preimage: Array[Byte]): Array[Byte] = sha256(preimage)

  /** Win probability for given amounts: `claimedAmount / maxPayout`. */
  def winProbability(claimedAmount: BigInt, maxPayout: BigInt): Double =
    claimedAmount.toDouble / maxPayout.toDouble

  private[probabilistic] def sha256(data: Array[Byte]): Array[Byte] =
    MessageDigest.getInstance("SHA-256").digest(data)

  private def xor32(a: Array[Byte], b: Array[Byte]): Array[Byte] =
    Array.tabulate(32)(i => (a(i) ^ b(i)).toByte)
