package scalascript

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, StandardOpenOption}

import org.scalatest.funsuite.AnyFunSuite

import scalascript.codegen.JvmGen
import scalascript.parser.Parser

/** v1.26 Phase 7 (deferred) — end-to-end JvmGen smoke test that
 *  compiles + runs the emitted Scala source through `scala-cli`.
 *
 *  Without publishing the internal runtime modules to Maven Central,
 *  the `//> using lib "io.scalascript::…"` directives that JvmGen emits
 *  don't resolve.  Workaround: build the runtime JARs locally (wired
 *  into the `Test / resourceGenerators` of `backendInterpreter` so the
 *  jars are always fresh) and replace the directives in the emitted
 *  source with `//> using jar "<absolute-path>"` before handing it to
 *  scala-cli.
 *
 *  Skipped (not failed) when `scala-cli` is unavailable on PATH so
 *  CI environments without it keep working. */
class JvmGenSqlRuntimeTest extends AnyFunSuite {

  private lazy val hasScalaCli: Boolean = ProcTestUtil.commandOk("scala-cli")

  /** Path to the freshly-built `scalascript-backend-sql-runtime` JAR,
   *  injected via `Test / resourceGenerators` in `build.sbt`. */
  private lazy val sqlRuntimeJar: String =
    readRuntimeJarPath("sql-runtime-jar.path")

  private lazy val typedDataRuntimeJar: String =
    readRuntimeJarPath("typed-data-runtime-jar.path")

  private lazy val wireCoreJar: String =
    readRuntimeJarPath("wire-core-jar.path")

  private def readRuntimeJarPath(fileName: String): String =
    val url = getClass.getClassLoader.getResource(s"scalascript/$fileName")
    assert(url != null, s"missing classpath resource `scalascript/$fileName` — " +
      "expected to be generated by `Test / resourceGenerators` in build.sbt")
    val src = scala.io.Source.fromURL(url)
    try src.mkString.trim finally src.close()

  /** Replace internal `io.scalascript` directives emitted by JvmGen with
   *  `//> using jar "<absolute-path>"` so scala-cli picks up freshly-built
   *  local artifacts instead of trying to resolve unpublished snapshots. */
  private def rewriteLibToJar(src: String): String =
    val withWire = rewriteInternalDepToJarIfPresent(
      src,
      artifact = "scalascript-wire-core",
      jarPath = wireCoreJar
    )
    val withTypedData = rewriteInternalDepToJar(
      withWire,
      artifact = "scalascript-backend-typed-data-runtime",
      jarPath = typedDataRuntimeJar
    )
    rewriteInternalDepToJar(
      withTypedData,
      artifact = "scalascript-backend-sql-runtime",
      jarPath = sqlRuntimeJar
    )

  private def rewriteInternalDepToJar(src: String, artifact: String, jarPath: String): String =
    val depLine = s"""//> using dep "io.scalascript::$artifact:0.1.0-SNAPSHOT""""
    val libLine = s"""//> using lib "io.scalascript::$artifact:0.1.0-SNAPSHOT""""
    val jarLine = s"""//> using jar "$jarPath""""
    if src.contains(depLine) then src.replace(depLine, jarLine)
    else if src.contains(libLine) then src.replace(libLine, jarLine)
    else
      fail(
        s"emitted JvmGen source missing expected directive for `$artifact` — got first 500 chars:\n${src.take(500)}"
      )

  private def rewriteInternalDepToJarIfPresent(src: String, artifact: String, jarPath: String): String =
    val depLine = s"""//> using dep "io.scalascript::$artifact:0.1.0-SNAPSHOT""""
    val libLine = s"""//> using lib "io.scalascript::$artifact:0.1.0-SNAPSHOT""""
    val jarLine = s"""//> using jar "$jarPath""""
    if src.contains(depLine) then src.replace(depLine, jarLine)
    else if src.contains(libLine) then src.replace(libLine, jarLine)
    else src

  /** Build, transform, and run the JvmGen emission through `scala-cli`.
   *  Returns (exitCode, stdout, stderr). */
  private def runViaScalaCli(ssc: String): (Int, String, String) =
    val module = Parser.parse(ssc)
    val raw    = JvmGen.generate(module)
    val patched = rewriteLibToJar(raw)
    val tmp = Files.createTempFile("ssc-jvmgen-sql-", ".sc")
    tmp.toFile.deleteOnExit()
    Files.write(tmp, patched.getBytes(StandardCharsets.UTF_8),
      StandardOpenOption.WRITE, StandardOpenOption.TRUNCATE_EXISTING)
    val pb = ProcessBuilder("scala-cli", "run", "--server=false", tmp.toAbsolutePath.toString)
      .redirectErrorStream(false)
    val proc = pb.start()
    val out  = new String(proc.getInputStream.readAllBytes(), StandardCharsets.UTF_8)
    val err  = new String(proc.getErrorStream.readAllBytes(), StandardCharsets.UTF_8)
    val code = ProcTestUtil.awaitExit(proc)
    (code, out, err)

  // ── Tests ───────────────────────────────────────────────────────────

  test("scala-cli compiles + runs JvmGen-emitted SQL block against H2") {
    assume(hasScalaCli, "scala-cli not available on PATH")
    val ssc =
      """|---
         |databases:
         |  default:
         |    url: "jdbc:h2:mem:jvmgen-rt;DB_CLOSE_DELAY=-1"
         |---
         |
         |# Schema
         |
         |```sql
         |CREATE TABLE t (id INT PRIMARY KEY, name VARCHAR(64))
         |```
         |
         |# Seed
         |
         |```scala
         |val id   = 1
         |val nm   = "Alice"
         |```
         |
         |```sql
         |INSERT INTO t (id, name) VALUES (${id}, ${nm})
         |```
         |
         |# Read
         |
         |```sql
         |SELECT name FROM t WHERE id = ${id}
         |```
         |
         |```scala
         |val row = Read.sql match
         |  case scalascript.sql.SqlResult.Rows(rs) => rs.head
         |  case other                              => sys.error("expected Rows, got " + other)
         |println("got=" + row("NAME"))
         |```
         |""".stripMargin

    val (code, stdout, stderr) = runViaScalaCli(ssc)
    assert(code == 0,
      s"scala-cli exit $code\n--- stdout ---\n$stdout\n--- stderr ---\n$stderr")
    assert(stdout.contains("got=Alice"),
      s"expected `got=Alice` in stdout, got:\n$stdout\n---stderr---\n$stderr")
  }


  test("scala-cli compiles + runs typed Db.query overload through RowCodec") {
    assume(hasScalaCli, "scala-cli not available on PATH")
    val ssc =
      """|---
         |databases:
         |  default:
         |    url: "jdbc:h2:mem:jvmgen-typed-query;DB_CLOSE_DELAY=-1"
         |---
         |
         |# Model
         |
         |```scala
         |import scalascript.typeddata.RowCodec
         |case class Person(id: Int, name: String) derives RowCodec
         |```
         |
         |# Schema
         |
         |```sql
         |CREATE TABLE people (id INT PRIMARY KEY, name VARCHAR(64))
         |```
         |
         |# Seed
         |
         |```sql
         |INSERT INTO people (id, name) VALUES (1, 'Alice')
         |```
         |
         |```sql
         |INSERT INTO people (id, name) VALUES (2, 'Bob')
         |```
         |
         |# Read
         |
         |```scala
         |val people = Db.query[Person]("default", "SELECT id AS id, name AS name FROM people ORDER BY id", [])
         |println("people=" + people.map(_.name).mkString(","))
         |```
         |""".stripMargin

    val (code, stdout, stderr) = runViaScalaCli(ssc)
    assert(code == 0,
      s"scala-cli exit $code\n--- stdout ---\n$stdout\n--- stderr ---\n$stderr")
    assert(stdout.contains("people=Alice,Bob"),
      s"expected `people=Alice,Bob` in stdout, got:\n$stdout\n---stderr---\n$stderr")
  }

  test("scala-cli compiles + runs typed Db.insert and Db.update through RowCodec") {
    assume(hasScalaCli, "scala-cli not available on PATH")
    val ssc =
      """|---
         |databases:
         |  default:
         |    url: "jdbc:h2:mem:jvmgen-typed-write;DB_CLOSE_DELAY=-1"
         |---
         |
         |# Model
         |
         |```scala
         |import scalascript.typeddata.RowCodec
         |case class Person(id: Int, name: String, active: Boolean) derives RowCodec
         |```
         |
         |# Schema
         |
         |```sql
         |CREATE TABLE people (id INT PRIMARY KEY, name VARCHAR(64), active BOOLEAN NOT NULL)
         |```
         |
         |# Write
         |
         |```scala
         |val inserted = Db.insert("default", "people", Person(1, "Alice", true))
         |val updated = Db.update("default", "people", "id", 1, Person(1, "Alicia", false))
         |val people = Db.query[Person]("default", "SELECT id AS id, name AS name, active AS active FROM people", [])
         |println("write=" + inserted + "/" + updated + ":" + people.map(p => p.name + ":" + p.active).mkString(","))
         |```
         |""".stripMargin

    val (code, stdout, stderr) = runViaScalaCli(ssc)
    assert(code == 0,
      s"scala-cli exit $code\n--- stdout ---\n$stdout\n--- stderr ---\n$stderr")
    assert(stdout.contains("write=1/1:Alicia:false"),
      s"expected `write=1/1:Alicia:false` in stdout, got:\n$stdout\n---stderr---\n$stderr")
  }

  test("scala-cli runs DDL + UPDATE returning affected-row count") {
    assume(hasScalaCli, "scala-cli not available on PATH")
    val ssc =
      """|---
         |databases:
         |  default:
         |    url: "jdbc:h2:mem:jvmgen-update;DB_CLOSE_DELAY=-1"
         |---
         |
         |# Setup
         |
         |```sql
         |CREATE TABLE t (id INT, n INT)
         |```
         |
         |```sql
         |INSERT INTO t VALUES (1, 10)
         |```
         |
         |```sql
         |INSERT INTO t VALUES (2, 20)
         |```
         |
         |# Mutate
         |
         |```sql
         |UPDATE t SET n = n + 1
         |```
         |
         |```scala
         |Mutate.sql match
         |  case scalascript.sql.SqlResult.UpdateCount(n) => println("affected=" + n)
         |  case other                                    => sys.error("expected UpdateCount, got " + other)
         |```
         |""".stripMargin

    val (code, stdout, stderr) = runViaScalaCli(ssc)
    assert(code == 0,
      s"scala-cli exit $code\n--- stdout ---\n$stdout\n--- stderr ---\n$stderr")
    assert(stdout.contains("affected=2"),
      s"expected `affected=2` in stdout, got:\n$stdout\n---stderr---\n$stderr")
  }
}
