package scalascript.codegen.rust

import scalascript.backend.spi.*
import scalascript.parser.Parser
import scalascript.transform.Normalize
import org.scalatest.funsuite.AnyFunSuite

/** Phase R.1.3d — src/main.rs assembly + Cargo.toml `[[bin]]` cross-check. */
class RustGenMainAssemblyTest extends AnyFunSuite:

  private val emptyOpts = BackendOptions(
    baseDir = None, outputDir = None,
    optimizationLevel = 0, emitSourceMaps = false, emitAssertions = false,
    target = None, extra = Map.empty
  )

  private def assets(src: String): Map[String, String] =
    new RustBackend().compile(Normalize(Parser.parse(src)), emptyOpts) match
      case CompileResult.Segmented(segs) =>
        segs.collect { case Segment.Asset(n, b, _) => n -> new String(b, "UTF-8") }.toMap
      case other => fail(s"expected Segmented, got $other")

  test("emits src/main.rs + Cargo.toml [[bin]] when @main is present"):
    val src =
      """```scalascript
        |@main def run(): Unit = println("Hello from Rust")
        |```
        |""".stripMargin
    val a = assets(src)
    assert(a.contains("src/main.rs"))
    assert(!a.contains("src/lib.rs"))
    val mainRs = a("src/main.rs")
    assert(mainRs.contains("mod runtime;"))
    assert(mainRs.contains("mod value;"))
    assert(mainRs.contains("mod generated;"))
    assert(mainRs.contains("fn main() {"))
    assert(mainRs.contains("generated::ssc_program::run();"))
    assert(a("Cargo.toml").contains("[[bin]]"))

  test("emits src/lib.rs + Cargo.toml [lib] when no @main"):
    val src =
      """```scalascript
        |def helper(): Unit = println("not entrypoint")
        |```
        |""".stripMargin
    val a = assets(src)
    assert(a.contains("src/lib.rs"))
    assert(!a.contains("src/main.rs"))
    val libRs = a("src/lib.rs")
    assert(libRs.contains("pub mod runtime;"))
    assert(libRs.contains("pub mod value;"))
    assert(libRs.contains("pub mod generated;"))
    assert(a("Cargo.toml").contains("[lib]"))
    assert(!a("Cargo.toml").contains("[[bin]]"))

  test("src/generated/mod.rs re-exports the crate module"):
    val a = assets(
      """```scalascript
        |def x(): Unit = println("x")
        |```
        |""".stripMargin
    )
    assert(a("src/generated/mod.rs").contains("pub mod ssc_program;"))

  test("end-to-end golden — hello-world crate file set"):
    val src =
      """```scalascript
        |@main def run(): Unit = println("Hello from Rust")
        |```
        |""".stripMargin
    val a = assets(src)

    val expectedCargo =
      """[package]
        |name = "ssc_program"
        |version = "0.1.0"
        |edition = "2021"
        |
        |[dependencies]
        |
        |[[bin]]
        |name = "ssc_program"
        |path = "src/main.rs"
        |""".stripMargin
    assert(a("Cargo.toml") == expectedCargo, s"Cargo.toml:\n${a("Cargo.toml")}")

    val expectedMain =
      """//! Crate entry point.  Emitted by RustGen; do not edit by hand.
        |
        |mod runtime;
        |mod value;
        |mod generated;
        |
        |fn main() {
        |    generated::ssc_program::run();
        |}
        |""".stripMargin
    assert(a("src/main.rs") == expectedMain, s"main.rs:\n${a("src/main.rs")}")

    val expectedGenIdx =
      """//! Generated module index — re-exports per-source modules.
        |
        |pub mod ssc_program;
        |""".stripMargin
    assert(a("src/generated/mod.rs") == expectedGenIdx)

    val expectedGen =
      """//! Generated by RustGen.  Do not edit by hand.
        |//!
        |//! One `pub fn` per ScalaScript top-level `def`.  Calls to console
        |//! intrinsics (`println`, `print`) route to `crate::runtime::_*`.
        |//! `rust` fence blocks from the source are appended verbatim.
        |
        |pub fn run() {
        |    crate::runtime::_println("Hello from Rust".to_string());
        |}
        |""".stripMargin
    assert(a("src/generated/ssc_program.rs") == expectedGen,
      s"generated/ssc_program.rs:\n${a("src/generated/ssc_program.rs")}")
