package scalascript.codegen.rust

import scalascript.backend.spi.*
import scalascript.ir
import scalascript.parser.Parser
import scalascript.transform.Normalize
import org.scalatest.funsuite.AnyFunSuite

/** Phase R.1.3c — code-walk: Denormalize + scalameta-driven emit of
 *  `src/generated/<crate>.rs`. */
class RustGenCodeWalkTest extends AnyFunSuite:

  private val emptyOpts = BackendOptions(
    baseDir = None, outputDir = None,
    optimizationLevel = 0, emitSourceMaps = false, emitAssertions = false,
    target = None, extra = Map.empty
  )

  /** Build a `NormalizedModule` from an `.ssc` source fragment.  The
   *  Parser+Normalize pipeline is the same one used by the CLI. */
  private def normalizeSsc(src: String): ir.NormalizedModule =
    val astModule = Parser.parse(src)
    Normalize(astModule)

  private def compileResult(src: String): CompileResult =
    new RustBackend().compile(normalizeSsc(src), emptyOpts)

  private def assets(src: String): Map[String, String] = compileResult(src) match
    case CompileResult.Segmented(segs) =>
      segs.collect { case Segment.Asset(n, b, _) => n -> new String(b, "UTF-8") }.toMap
    case other => fail(s"expected Segmented, got ${other.getClass.getSimpleName}")

  private def diagnostics(src: String): List[Diagnostic] = compileResult(src) match
    case CompileResult.Failed(ds) => ds
    case other => fail(s"expected Failed, got ${other.getClass.getSimpleName}")

  // ── hello-world emit ────────────────────────────────────────────────

  test("hello-world: emits one pub fn calling crate::runtime::_println"):
    val src =
      """# Hello
        |
        |```scalascript
        |def run(): Unit = println("Hello from Rust")
        |```
        |""".stripMargin
    val gen = assets(src).get("src/generated/ssc_program.rs")
      .getOrElse(fail("generated file missing"))
    assert(gen.contains("pub fn run() {"))
    assert(gen.contains("""crate::runtime::_println("Hello from Rust".to_string());"""))

  test("hello-world: print → crate::runtime::_print, Console.println → _println"):
    val src =
      """```scalascript
        |def first(): Unit = print("a")
        |def second(): Unit = Console.println("b")
        |```
        |""".stripMargin
    val gen = assets(src)("src/generated/ssc_program.rs")
    assert(gen.contains("""crate::runtime::_print("a".to_string());"""))
    assert(gen.contains("""crate::runtime::_println("b".to_string());"""))

  test("hello-world: escapes string-literal metacharacters in the emit"):
    val src =
      """```scalascript
        |def run(): Unit = println("hi \"world\"\n")
        |```
        |""".stripMargin
    val gen = assets(src)("src/generated/ssc_program.rs")
    assert(gen.contains("""crate::runtime::_println("hi \"world\"\n".to_string());"""))

  test("empty module: generated file still emitted (header only, no defs)"):
    val src =
      """# Nothing yet
        |
        |Just prose, no code blocks.
        |""".stripMargin
    val gen = assets(src)("src/generated/ssc_program.rs")
    assert(gen.startsWith("//! Generated by RustGen"))
    // No actual `pub fn …()` declaration line — only the comment that mentions one.
    val hasFnDecl = gen.linesIterator.exists(_.stripLeading.startsWith("pub fn "))
    assert(!hasFnDecl, s"unexpected pub fn declaration:\n$gen")

  // ── R.1 capability surface — anything outside hello-world fails ─────

  test("Failed: param with a non-primitive type yields a structured diagnostic"):
    // R.2 accepts primitives, enums, function types, and List/Vec (with
    // type args).  A truly-out-of-scope type still surfaces a diagnostic.
    val src =
      """```scalascript
        |def greet(items: Set[Long]): Unit = println("len")
        |```
        |""".stripMargin
    val ds = diagnostics(src)
    assert(ds.exists {
      case Diagnostic.Generic(m, _) => m.contains("greet") && m.contains("Set")
      case _                        => false
    }, s"diags: $ds")

  test("Failed: unsupported expression in the body yields a structured diagnostic"):
    // R.2 lowers infix arithmetic, so use something genuinely out of scope.
    val src =
      """```scalascript
      |def run(): Unit = throw new RuntimeException("nope")
      |```
      |""".stripMargin
    val ds = diagnostics(src)
    assert(ds.nonEmpty, "expected at least one diagnostic")
    assert(ds.forall {
      case Diagnostic.Generic(_, src) => src.contains("rust")
      case _                          => false
    }, s"diags: $ds")

  // ── P0 benchmark gaps — numeric conversion + string concat ───────────

  test("toLong / toInt / toDouble / toFloat are rendered to Rust casts"):
    val src =
      """```scalascript
      |def toLongFn(n: Int): Long = n.toLong
      |def toIntFn(s: String): Int = s.trim.toInt
      |def toDoubleFn(n: Int): Double = n.toDouble
      |def toFloatFn(n: Int): Float = n.toFloat
      |```
      |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("(n as i64)"))
    assert(g.contains("parse::<i64>().unwrap_or(0)"), s"toInt parse path missing in:\n$g")
    assert(g.contains("(n as f64)"), s"toDouble missing in $g")
    assert(g.contains("(n as f64)"), s"toFloat missing in $g")

  test("String + Long emits Rust format! for mixed-type concatenation"):
    val src =
      """```scalascript
      |def label(n: Long): String = "item-" + n
      |```
      |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("""format!("{}{}","""), s"format concat missing in:\n$g")
    assert(g.contains("\"item-\".to_string()"), s"string literal shape missing in:\n$g")
