package scalascript.codegen.rust

import scalascript.backend.spi.*
import scalascript.ir
import scalascript.parser.Parser
import scalascript.transform.Normalize
import org.scalatest.funsuite.AnyFunSuite

/** Phase R.1.3c — code-walk: Denormalize + scalameta-driven emit of
 *  `src/generated/<crate>.rs`. */
class RustGenCodeWalkTest extends AnyFunSuite:

  private val emptyOpts = BackendOptions(
    baseDir = None, outputDir = None,
    optimizationLevel = 0, emitSourceMaps = false, emitAssertions = false,
    target = None, extra = Map.empty
  )

  /** Build a `NormalizedModule` from an `.ssc` source fragment.  The
   *  Parser+Normalize pipeline is the same one used by the CLI. */
  private def normalizeSsc(src: String): ir.NormalizedModule =
    val astModule = Parser.parse(src)
    Normalize(astModule)

  private def compileResult(src: String): CompileResult =
    new RustBackend().compile(normalizeSsc(src), emptyOpts)

  private def assets(src: String): Map[String, String] = compileResult(src) match
    case CompileResult.Segmented(segs) =>
      segs.collect { case Segment.Asset(n, b, _) => n -> new String(b, "UTF-8") }.toMap
    case other => fail(s"expected Segmented, got ${other.getClass.getSimpleName}")

  private def diagnostics(src: String): List[Diagnostic] = compileResult(src) match
    case CompileResult.Failed(ds) => ds
    case other => fail(s"expected Failed, got ${other.getClass.getSimpleName}")

  // ── hello-world emit ────────────────────────────────────────────────

  test("hello-world: emits one pub fn calling crate::runtime::_println"):
    val src =
      """# Hello
        |
        |```scalascript
        |def run(): Unit = println("Hello from Rust")
        |```
        |""".stripMargin
    val gen = assets(src).get("src/generated/ssc_program.rs")
      .getOrElse(fail("generated file missing"))
    assert(gen.contains("pub fn run() {"))
    assert(gen.contains("""crate::runtime::_println("Hello from Rust");"""))

  test("hello-world: print → crate::runtime::_print, Console.println → _println"):
    val src =
      """```scalascript
        |def first(): Unit = print("a")
        |def second(): Unit = Console.println("b")
        |```
        |""".stripMargin
    val gen = assets(src)("src/generated/ssc_program.rs")
    assert(gen.contains("""crate::runtime::_print("a");"""))
    assert(gen.contains("""crate::runtime::_println("b");"""))

  test("hello-world: escapes string-literal metacharacters in the emit"):
    val src =
      """```scalascript
        |def run(): Unit = println("hi \"world\"\n")
        |```
        |""".stripMargin
    val gen = assets(src)("src/generated/ssc_program.rs")
    assert(gen.contains("""crate::runtime::_println("hi \"world\"\n");"""))

  test("empty module: generated file still emitted (header only, no defs)"):
    val src =
      """# Nothing yet
        |
        |Just prose, no code blocks.
        |""".stripMargin
    val gen = assets(src)("src/generated/ssc_program.rs")
    assert(gen.startsWith("//! Generated by RustGen"))
    // No actual `pub fn …()` declaration line — only the comment that mentions one.
    val hasFnDecl = gen.linesIterator.exists(_.stripLeading.startsWith("pub fn "))
    assert(!hasFnDecl, s"unexpected pub fn declaration:\n$gen")

  // ── R.1 capability surface — anything outside hello-world fails ─────

  test("Failed: def with parameters yields a structured diagnostic"):
    val src =
      """```scalascript
        |def greet(name: String): Unit = println(name)
        |```
        |""".stripMargin
    val ds = diagnostics(src)
    assert(ds.exists {
      case Diagnostic.Generic(m, _) => m.contains("greet") && m.contains("parameters")
      case _                        => false
    }, s"diags: $ds")

  test("Failed: unsupported expression in the body yields a structured diagnostic"):
    val src =
      """```scalascript
        |def run(): Unit = 1 + 2
        |```
        |""".stripMargin
    val ds = diagnostics(src)
    assert(ds.nonEmpty, "expected at least one diagnostic")
    assert(ds.forall {
      case Diagnostic.Generic(_, src) => src.contains("rust")
      case _                          => false
    }, s"diags: $ds")
