package scalascript.codegen.rust

import scala.meta as m
import scala.meta.prettyprinters.XtensionSyntax
import scala.meta.transversers.XtensionCollectionLikeUI
import scalascript.ast
import scalascript.backend.spi.*
import scalascript.ir.QualifiedName

/** Walk an `ast.Module` and emit `src/generated/<crate>.rs`.
 *
 *  Phase R.1.3c is intentionally narrow: only the hello-world shape
 *  is accepted —
 *
 *    `[@main] def name(): Unit = println("string-literal")`
 *
 *  Anything outside that subset returns a `Diagnostic.Generic` so the
 *  caller can convert it into `CompileResult.Failed`.  Each later
 *  R.x slice widens the accepted shapes; the narrow start keeps the
 *  goldens stable while the runtime preamble + main-assembly slices
 *  catch up. */
object RustCodeWalk:

  /** A single rendered `pub fn` extracted from a `Defn.Def`. */
  final case class GeneratedDef(name: String, render: String, isMain: Boolean)

  /** Outcome of walking a module — either a list of diagnostics or
   *  the assembled `src/generated/<crate>.rs` text plus the names of
   *  the defs it contains and the `@main`-annotated entry point, so
   *  the main-assembly slice can stitch a
   *  `fn main() { generated::<crate>::<entry>(); }` shim. */
  final case class WalkResult(
      generated: String,
      defNames:  List[String],
      mainEntry: Option[String]
  )

  def walk(
      module:     ast.Module,
      intrinsics: Map[QualifiedName, IntrinsicImpl]
  ): Either[List[Diagnostic], WalkResult] =
    val defs       = collectDefs(module)
    val rustBlocks = collectRustBlocks(module)
    val results    = defs.map(renderDef(_, intrinsics))
    val (errors, ok) = results.partitionMap(identity)
    if errors.nonEmpty then Left(errors.flatten)
    else
      val rustVerbatim = rustBlocks.zipWithIndex.map { case (src, i) =>
        s"""// ── rust block ${i + 1} ──
           |$src
           |""".stripMargin
      }.mkString
      val body =
        (if ok.isEmpty then "" else ok.map(_.render).mkString("\n")) +
        (if rustBlocks.isEmpty then "" else "\n" + rustVerbatim)
      val text =
        if body.isEmpty then headerComment
        else headerComment + "\n" + body
      Right(WalkResult(
        generated = text,
        defNames  = ok.map(_.name),
        mainEntry = ok.find(_.isMain).map(_.name)
      ))

  /** Header for the generated file.  Stable so goldens diff cleanly. */
  private val headerComment: String =
    """//! Generated by RustGen.  Do not edit by hand.
      |//!
      |//! One `pub fn` per ScalaScript top-level `def`.  Calls to console
      |//! intrinsics (`println`, `print`) route to `crate::runtime::_*`.
      |//! `rust` fence blocks from the source are appended verbatim.
      |""".stripMargin

  // ── Defn.Def collection ──────────────────────────────────────────────

  /** Top-level defs across every parsed `scalascript`/`ssc`/`scala` block. */
  private def collectDefs(module: ast.Module): List[m.Defn.Def] =
    module.sections.flatMap(sectionDefs)

  private def sectionDefs(s: ast.Section): List[m.Defn.Def] =
    s.content.flatMap(contentDefs) ++ s.subsections.flatMap(sectionDefs)

  private def contentDefs(c: ast.Content): List[m.Defn.Def] = c match
    case ast.Content.CodeBlock(lang, _, Some(node), _, _, _, _)
        if isScalaLang(lang) =>
      node.tree.collect { case d: m.Defn.Def => d }.toList
    case _ => Nil

  private def isScalaLang(lang: String): Boolean =
    val n = lang.toLowerCase
    n == "scalascript" || n == "ssc" || n == "scala"

  // ── rust block collection (verbatim passthrough) ─────────────────────

  /** Raw Rust source from `rust` fence blocks — concatenated into the
   *  emitted `src/generated/<crate>.rs` after the ScalaScript-derived
   *  defs.  Cross-block typing (Rust → SS) is a future slice; today
   *  the rust source just contributes top-level items that any SS
   *  emit can reach via `pub fn` / `pub struct` lookups. */
  private def collectRustBlocks(module: ast.Module): List[String] =
    module.sections.flatMap(sectionRustBlocks)

  private def sectionRustBlocks(s: ast.Section): List[String] =
    s.content.flatMap(contentRustBlocks) ++ s.subsections.flatMap(sectionRustBlocks)

  private def contentRustBlocks(c: ast.Content): List[String] = c match
    case ast.Content.CodeBlock(lang, source, _, _, _, _, _)
        if lang.equalsIgnoreCase("rust") =>
      List(source)
    case _ => Nil

  // ── Per-def rendering ────────────────────────────────────────────────

  private def renderDef(
      d: m.Defn.Def,
      intrinsics: Map[QualifiedName, IntrinsicImpl]
  ): Either[List[Diagnostic], GeneratedDef] =
    val name = d.name.value
    for
      _      <- ensureZeroParamGroups(d, name)
      _      <- ensureUnitOrInferredReturn(d, name)
      bodyRs <- renderBody(d.body, intrinsics, name)
    yield
      val src =
        s"""pub fn $name() {
           |${indent(bodyRs)}
           |}
           |""".stripMargin
      GeneratedDef(name = name, render = src, isMain = hasMainAnnotation(d))

  /** A def is the entry point when it carries an `@main` annotation. */
  private def hasMainAnnotation(d: m.Defn.Def): Boolean =
    d.mods.exists {
      case m.Mod.Annot(m.Init.After_4_6_0(m.Type.Name("main"), _, _)) => true
      case _                                                          => false
    }

  private def ensureZeroParamGroups(
      d: m.Defn.Def, name: String
  ): Either[List[Diagnostic], Unit] =
    if d.paramClauseGroups.flatMap(_.paramClauses).flatMap(_.values).isEmpty
    then Right(())
    else Left(List(unsupported(
      s"def `$name` has parameters; R.1 hello-emit accepts only zero-parameter defs"
    )))

  private def ensureUnitOrInferredReturn(
      d: m.Defn.Def, name: String
  ): Either[List[Diagnostic], Unit] =
    d.decltpe match
      case None                          => Right(())
      case Some(m.Type.Name("Unit"))     => Right(())
      case Some(other)                   => Left(List(unsupported(
        s"def `$name` declares return type `${other.syntax}`; R.1 hello-emit accepts only `Unit` or no annotation"
      )))

  private def renderBody(
      body: m.Term,
      intrinsics: Map[QualifiedName, IntrinsicImpl],
      defName: String
  ): Either[List[Diagnostic], String] = body match
    // Simple block — emit as Rust block, one stmt per line.
    case b: m.Term.Block =>
      val rendered = b.stats.map(renderStmt(_, intrinsics, defName))
      val (errs, ok) = rendered.partitionMap(identity)
      if errs.nonEmpty then Left(errs.flatten)
      else Right(ok.mkString("\n"))
    // Single-expression body — render that single statement.
    case t: m.Term =>
      renderStmt(t, intrinsics, defName)

  private def renderStmt(
      stat: m.Stat,
      intrinsics: Map[QualifiedName, IntrinsicImpl],
      defName: String
  ): Either[List[Diagnostic], String] = stat match
    case t: m.Term => renderTerm(t, intrinsics, defName).map(_ + ";")
    case other     => Left(List(unsupported(
      s"def `$defName` body contains an unsupported statement: ${other.productPrefix}"
    )))

  private def renderTerm(
      t: m.Term,
      intrinsics: Map[QualifiedName, IntrinsicImpl],
      defName: String
  ): Either[List[Diagnostic], String] = t match
    case m.Term.Apply.After_4_6_0(fn, args) =>
      val callee = qualifiedName(fn)
      val intr   = callee.flatMap(qn => intrinsics.get(qn).map(qn -> _))
      intr match
        case Some((_, RuntimeCall(target))) =>
          val renderedArgs = args.values.map(renderTerm(_, intrinsics, defName))
          val (errs, ok)   = renderedArgs.partitionMap(identity)
          if errs.nonEmpty then Left(errs.flatten)
          else Right(s"$target(${ok.mkString(", ")})")
        case Some((qn, other)) =>
          Left(List(unsupported(
            s"intrinsic `${qn.value}` uses ${other.getClass.getSimpleName}; R.1 accepts only RuntimeCall"
          )))
        case None =>
          Left(List(unsupported(
            s"def `$defName` calls `${fn.syntax}`, which has no rust-target intrinsic and direct calls land in R.2"
          )))
    case m.Lit.String(s) =>
      Right("\"" + escapeRustString(s) + "\"")
    case m.Lit.Int(n) =>
      Right(s"${n}i64")
    case m.Lit.Long(n) =>
      Right(s"${n}i64")
    case m.Lit.Double(d) =>
      Right(s"${d}f64")
    case m.Lit.Boolean(b) =>
      Right(b.toString)
    case m.Lit.Unit() =>
      Right("()")
    case other =>
      Left(List(unsupported(
        s"def `$defName` contains an unsupported expression: ${other.productPrefix} (${other.syntax})"
      )))

  /** Resolve a callee tree to its lookup key in the intrinsic table.
   *  Supports plain names (`println`) and one-level qualified
   *  selects (`Console.println`). */
  private def qualifiedName(fn: m.Term): Option[QualifiedName] = fn match
    case m.Term.Name(n)                                    => Some(QualifiedName(n))
    case m.Term.Select(m.Term.Name(qual), m.Term.Name(n))  => Some(QualifiedName(s"$qual.$n"))
    case _                                                 => None

  // ── Helpers ──────────────────────────────────────────────────────────

  private def unsupported(message: String): Diagnostic =
    Diagnostic.Generic(message = message, source = Some("rust"))

  private def indent(s: String): String =
    s.linesIterator.map(line => if line.isEmpty then "" else "    " + line).mkString("\n")

  private[rust] def escapeRustString(s: String): String =
    val sb = new StringBuilder(s.length)
    s.foreach {
      case '\\' => sb.append("\\\\")
      case '"'  => sb.append("\\\"")
      case '\n' => sb.append("\\n")
      case '\r' => sb.append("\\r")
      case '\t' => sb.append("\\t")
      case c    => sb.append(c)
    }
    sb.toString
