package scalascript.codegen.rust

import scala.meta as m
import scala.meta.prettyprinters.XtensionSyntax
import scala.meta.transversers.XtensionCollectionLikeUI
import scalascript.ast
import scalascript.backend.spi.*
import scalascript.ir.QualifiedName

/** Walk an `ast.Module` and emit `src/generated/<crate>.rs`.
 *
 *  Phase R.1.3c is intentionally narrow: only the hello-world shape
 *  is accepted —
 *
 *    `[@main] def name(): Unit = println("string-literal")`
 *
 *  Anything outside that subset returns a `Diagnostic.Generic` so the
 *  caller can convert it into `CompileResult.Failed`.  Each later
 *  R.x slice widens the accepted shapes; the narrow start keeps the
 *  goldens stable while the runtime preamble + main-assembly slices
 *  catch up. */
object RustCodeWalk:

  /** A single rendered `pub fn` extracted from a `Defn.Def`. */
  final case class GeneratedDef(name: String, render: String, isMain: Boolean)

  /** Outcome of walking a module — either a list of diagnostics or
   *  the assembled `src/generated/<crate>.rs` text plus the names of
   *  the defs it contains and the `@main`-annotated entry point, so
   *  the main-assembly slice can stitch a
   *  `fn main() { generated::<crate>::<entry>(); }` shim. */
  final case class WalkResult(
      generated: String,
      defNames:  List[String],
      mainEntry: Option[String]
  )

  def walk(
      module:     ast.Module,
      intrinsics: Map[QualifiedName, IntrinsicImpl]
  ): Either[List[Diagnostic], WalkResult] =
    val defs       = collectDefs(module)
    val rustBlocks = collectRustBlocks(module)
    val userDefs   = defs.map(_.name.value).toSet
    val results    = defs.map(renderDef(_, intrinsics, userDefs))
    val (errors, ok) = results.partitionMap(identity)
    if errors.nonEmpty then Left(errors.flatten)
    else
      val rustVerbatim = rustBlocks.zipWithIndex.map { case (src, i) =>
        s"""// ── rust block ${i + 1} ──
           |$src
           |""".stripMargin
      }.mkString
      val body =
        (if ok.isEmpty then "" else ok.map(_.render).mkString("\n")) +
        (if rustBlocks.isEmpty then "" else "\n" + rustVerbatim)
      val text =
        if body.isEmpty then headerComment
        else headerComment + "\n" + body
      Right(WalkResult(
        generated = text,
        defNames  = ok.map(_.name),
        mainEntry = ok.find(_.isMain).map(_.name)
      ))

  /** Header for the generated file.  Stable so goldens diff cleanly. */
  private val headerComment: String =
    """//! Generated by RustGen.  Do not edit by hand.
      |//!
      |//! One `pub fn` per ScalaScript top-level `def`.  Calls to console
      |//! intrinsics (`println`, `print`) route to `crate::runtime::_*`.
      |//! `rust` fence blocks from the source are appended verbatim.
      |""".stripMargin

  // ── Defn.Def collection ──────────────────────────────────────────────

  /** Top-level defs across every parsed `scalascript`/`ssc`/`scala` block. */
  private def collectDefs(module: ast.Module): List[m.Defn.Def] =
    module.sections.flatMap(sectionDefs)

  private def sectionDefs(s: ast.Section): List[m.Defn.Def] =
    s.content.flatMap(contentDefs) ++ s.subsections.flatMap(sectionDefs)

  private def contentDefs(c: ast.Content): List[m.Defn.Def] = c match
    case ast.Content.CodeBlock(lang, _, Some(node), _, _, _, _)
        if isScalaLang(lang) =>
      node.tree.collect { case d: m.Defn.Def => d }.toList
    case _ => Nil

  private def isScalaLang(lang: String): Boolean =
    val n = lang.toLowerCase
    n == "scalascript" || n == "ssc" || n == "scala"

  // ── rust block collection (verbatim passthrough) ─────────────────────

  /** Raw Rust source from `rust` fence blocks — concatenated into the
   *  emitted `src/generated/<crate>.rs` after the ScalaScript-derived
   *  defs.  Cross-block typing (Rust → SS) is a future slice; today
   *  the rust source just contributes top-level items that any SS
   *  emit can reach via `pub fn` / `pub struct` lookups. */
  private def collectRustBlocks(module: ast.Module): List[String] =
    module.sections.flatMap(sectionRustBlocks)

  private def sectionRustBlocks(s: ast.Section): List[String] =
    s.content.flatMap(contentRustBlocks) ++ s.subsections.flatMap(sectionRustBlocks)

  private def contentRustBlocks(c: ast.Content): List[String] = c match
    case ast.Content.CodeBlock(lang, source, _, _, _, _, _)
        if lang.equalsIgnoreCase("rust") =>
      List(source)
    case _ => Nil

  // ── Per-def rendering ────────────────────────────────────────────────

  /** Rendering context: the set of user-defined fn names in scope.
   *  R.2 lets call sites against any in-scope user def emit as direct
   *  Rust calls (`other_fn(args…)`), in addition to intrinsics. */
  private case class Ctx(
      intrinsics: Map[QualifiedName, IntrinsicImpl],
      userDefs:   Set[String],
      defName:    String
  )

  private def renderDef(
      d: m.Defn.Def,
      intrinsics: Map[QualifiedName, IntrinsicImpl],
      userDefs:   Set[String]
  ): Either[List[Diagnostic], GeneratedDef] =
    val name = d.name.value
    val ctx  = Ctx(intrinsics, userDefs, name)
    for
      params  <- renderParams(d, ctx)
      ret     <- renderReturnType(d, ctx)
      bodyRs  <- renderBody(d.body, ctx, isUnit = ret.isEmpty)
    yield
      val signature = if ret.isEmpty then s"pub fn $name($params)"
                      else                s"pub fn $name($params) -> $ret"
      val src =
        s"""$signature {
           |${indent(bodyRs)}
           |}
           |""".stripMargin
      GeneratedDef(name = name, render = src, isMain = hasMainAnnotation(d))

  /** A def is the entry point when it carries an `@main` annotation. */
  private def hasMainAnnotation(d: m.Defn.Def): Boolean =
    d.mods.exists {
      case m.Mod.Annot(m.Init.After_4_6_0(m.Type.Name("main"), _, _)) => true
      case _                                                          => false
    }

  /** Map a Scala type name to its Rust equivalent.  R.2 supports the
   *  primitive surface needed for the fib / string-interp fixtures;
   *  anything else returns a diagnostic. */
  private def mapType(t: m.Type, defName: String): Either[List[Diagnostic], String] = t match
    case m.Type.Name("Unit")    => Right("")          // empty → no `-> T` clause
    case m.Type.Name("Boolean") => Right("bool")
    case m.Type.Name("Int")     => Right("i64")       // ScalaScript `Int` widens to 64-bit
    case m.Type.Name("Long")    => Right("i64")
    case m.Type.Name("Double")  => Right("f64")
    case m.Type.Name("Float")   => Right("f64")
    case m.Type.Name("String")  => Right("String")
    case other =>
      Left(List(unsupported(
        s"def `$defName` uses type `${other.syntax}`; R.2 accepts only primitive types"
      )))

  private def renderParams(
      d: m.Defn.Def, ctx: Ctx
  ): Either[List[Diagnostic], String] =
    val groups = d.paramClauseGroups.flatMap(_.paramClauses)
    if groups.size > 1 then
      Left(List(unsupported(
        s"def `${ctx.defName}` has multiple parameter groups; R.2 accepts a single `(…)` group"
      )))
    else
      val params = groups.flatMap(_.values)
      val rendered = params.map { p =>
        p.decltpe match
          case Some(t) => mapType(t, ctx.defName).map(r => s"${p.name.value}: $r")
          case None    => Left(List(unsupported(
            s"def `${ctx.defName}` parameter `${p.name.value}` has no type annotation; R.2 requires explicit param types"
          )))
      }
      val (errs, ok) = rendered.partitionMap(identity)
      if errs.nonEmpty then Left(errs.flatten)
      else Right(ok.mkString(", "))

  private def renderReturnType(
      d: m.Defn.Def, ctx: Ctx
  ): Either[List[Diagnostic], String] =
    d.decltpe match
      case None                       => Right("")    // inferred — treat as Unit
      case Some(m.Type.Name("Unit"))  => Right("")
      case Some(other)                => mapType(other, ctx.defName)

  private def renderBody(
      body:   m.Term,
      ctx:    Ctx,
      isUnit: Boolean
  ): Either[List[Diagnostic], String] = body match
    case b: m.Term.Block =>
      // For non-Unit returns the tail term must NOT terminate with `;` —
      // Rust uses block-trailing-expression as the result.
      // For Unit returns we terminate every statement with `;` so the
      // emitted block is purely statement-oriented (matches the R.1
      // golden shape).
      if isUnit then
        val rendered = b.stats.map(renderStmt(_, ctx))
        val (errs, ok) = rendered.partitionMap(identity)
        if errs.nonEmpty then Left(errs.flatten)
        else Right(ok.mkString("\n"))
      else
        val (initStats, tail) = b.stats.splitAt(b.stats.length - 1)
        val initRendered = initStats.map(renderStmt(_, ctx))
        val tailRendered: Either[List[Diagnostic], String] = tail.headOption match
          case Some(t: m.Term) => renderTerm(t, ctx)
          case Some(other)     => Left(List(unsupported(
            s"def `${ctx.defName}` body tail is a non-expression: ${other.productPrefix}"
          )))
          case None            => Right("")
        val (errs1, initOk) = initRendered.partitionMap(identity)
        tailRendered match
          case Left(errs2)   => Left(errs1.flatten ++ errs2)
          case Right(tailRs) =>
            if errs1.nonEmpty then Left(errs1.flatten)
            else
              val parts = (initOk :+ tailRs).filter(_.nonEmpty)
              Right(parts.mkString("\n"))
    case t: m.Term =>
      // Single-expression body — for Unit returns add the trailing `;`
      // so the emitted block matches the statement-oriented R.1 golden.
      // For non-Unit returns the expression IS the return value.
      renderTerm(t, ctx).map(r => if isUnit then s"$r;" else r)

  private def renderStmt(
      stat: m.Stat, ctx: Ctx
  ): Either[List[Diagnostic], String] = stat match
    // `var name: T = init` → `let mut name: T = init;`.  R.2.2 covers
    // single-pat bindings only (no pattern destructuring).
    case v: m.Defn.Var =>
      renderLetBinding(v.pats, v.decltpe, v.body, mutable = true, ctx)
    // `val name: T = init` → `let name: T = init;`.
    case v: m.Defn.Val =>
      renderLetBinding(v.pats, v.decltpe, v.rhs, mutable = false, ctx)
    case t: m.Term => renderTerm(t, ctx).map(_ + ";")
    case other     => Left(List(unsupported(
      s"def `${ctx.defName}` body contains an unsupported statement: ${other.productPrefix}"
    )))

  private def renderTerm(
      t: m.Term, ctx: Ctx
  ): Either[List[Diagnostic], String] = t match
    // Plain identifier — parameter reference or in-scope fn name.
    case m.Term.Name(n) =>
      Right(n)

    // `if (cond) thenp else elsep` — Rust if expression.
    case ifExpr: m.Term.If =>
      for
        c <- renderTerm(ifExpr.cond, ctx)
        t1 <- renderTerm(ifExpr.thenp, ctx)
        e1 <- renderTerm(ifExpr.elsep, ctx)
      yield
        s"if $c { $t1 } else { $e1 }"

    // `while (cond) body` — Rust while loop.  Body always wrapped in
    // a `{ … }` block so multi-stmt bodies stay statement-oriented.
    case w: m.Term.While =>
      for
        c <- renderTerm(w.expr, ctx)
        // Body is Unit-typed by construction.
        b <- renderBody(w.body, ctx, isUnit = true)
      yield
        s"while $c {\n${indent(b)}\n}"

    // `lhs = rhs` — Rust reassignment of a previously declared `var`.
    case a: m.Term.Assign =>
      for
        l <- renderTerm(a.lhs, ctx)
        r <- renderTerm(a.rhs, ctx)
      yield
        s"$l = $r"

    // s"…" interpolation → `format!("…", args)`.
    case m.Term.Interpolate(m.Term.Name("s"), parts, args) =>
      renderStringInterpolation(parts, args, ctx)

    // Application — intrinsic, user-defined fn, or unsupported.
    case m.Term.Apply.After_4_6_0(fn, args) =>
      val callee  = qualifiedName(fn)
      val argList = args.values.map(renderTerm(_, ctx))
      val (errs, renderedArgs) = argList.partitionMap(identity)
      if errs.nonEmpty then Left(errs.flatten)
      else
        val joined = renderedArgs.mkString(", ")
        val intr   = callee.flatMap(qn => ctx.intrinsics.get(qn).map(qn -> _))
        intr match
          case Some((_, RuntimeCall(target))) =>
            Right(s"$target($joined)")
          case Some((qn, other)) =>
            Left(List(unsupported(
              s"intrinsic `${qn.value}` uses ${other.getClass.getSimpleName}; rust target accepts only RuntimeCall"
            )))
          case None =>
            // User-defined fn in the same module?  R.2 allows direct calls.
            val plainName = fn match
              case m.Term.Name(n) => Some(n)
              case _              => None
            plainName.filter(ctx.userDefs.contains) match
              case Some(n) => Right(s"$n($joined)")
              case None    => Left(List(unsupported(
                s"def `${ctx.defName}` calls `${fn.syntax}` which is neither a rust-target intrinsic nor an in-scope user def"
              )))

    // Infix operators: arithmetic, comparison, boolean.
    case m.Term.ApplyInfix.After_4_6_0(lhs, m.Term.Name(op), _, args) =>
      val rhsTerms = args.values
      val rendered =
        for
          l <- renderTerm(lhs, ctx)
          rs <- rhsTerms.foldLeft[Either[List[Diagnostic], List[String]]](Right(Nil)) {
            (acc, t) => acc.flatMap(xs => renderTerm(t, ctx).map(xs :+ _))
          }
        yield (l, rs)
      rendered.flatMap { case (l, rs) =>
        mapInfixOp(op, ctx.defName) match
          case Right(rustOp) if rs.size == 1 => Right(s"($l $rustOp ${rs.head})")
          case Right(_)                      => Left(List(unsupported(
            s"def `${ctx.defName}`: infix `$op` with ${rs.size} rhs args"
          )))
          case Left(diags)                   => Left(diags)
      }

    // Always emit owned `String`s — every user-typed `String` parameter
    // expects an owned value, and the `_println` runtime helper is
    // Display-generic so the extra allocation is harmless.  A future
    // optimisation pass may infer when a borrowed `&str` is enough.
    case m.Lit.String(s)  => Right("\"" + escapeRustString(s) + "\".to_string()")
    case m.Lit.Int(n)     => Right(s"${n}i64")
    case m.Lit.Long(n)    => Right(s"${n}i64")
    case m.Lit.Double(d)  => Right(s"${d}f64")
    case m.Lit.Boolean(b) => Right(b.toString)
    case m.Lit.Unit()     => Right("()")

    case other =>
      Left(List(unsupported(
        s"def `${ctx.defName}` contains an unsupported expression: ${other.productPrefix} (${other.syntax})"
      )))

  /** Render a `val`/`var` binding to a Rust `let` (optionally `mut`)
   *  statement.  Only single-name patterns are supported; destructuring
   *  binders lower to a structured diagnostic. */
  private def renderLetBinding(
      pats:    List[m.Pat],
      decltpe: Option[m.Type],
      rhs:     m.Term,
      mutable: Boolean,
      ctx:     Ctx
  ): Either[List[Diagnostic], String] =
    pats match
      case List(m.Pat.Var(m.Term.Name(name))) =>
        val kw = if mutable then "let mut" else "let"
        val annotated: Either[List[Diagnostic], String] = decltpe match
          case None    => Right("")
          case Some(t) => mapType(t, ctx.defName).map { r =>
            if r.isEmpty then "" else s": $r"
          }
        for
          tyAnn <- annotated
          rhsRs <- renderTerm(rhs, ctx)
        yield
          s"$kw $name$tyAnn = $rhsRs;"
      case _ =>
        Left(List(unsupported(
          s"def `${ctx.defName}` has a non-single-name binding; R.2 accepts only `${if mutable then "var" else "val"} name: T = expr`"
        )))

  /** Lower a Scala infix operator to its Rust equivalent.  R.2 covers
   *  arithmetic + comparison + boolean — enough for fib + a basic
   *  string-interp example. */
  private def mapInfixOp(op: String, defName: String): Either[List[Diagnostic], String] = op match
    case "+" | "-" | "*" | "/" | "%" => Right(op)
    case "<" | "<=" | ">" | ">=" | "==" | "!=" => Right(op)
    case "&&" | "||" => Right(op)
    case other => Left(List(unsupported(
      s"def `$defName` uses unsupported infix operator `$other`"
    )))

  /** Lower `s"prefix ${expr} suffix"` to `format!("prefix {} suffix", expr)`. */
  private def renderStringInterpolation(
      parts: List[m.Lit],
      args:  List[m.Term],
      ctx:   Ctx
  ): Either[List[Diagnostic], String] =
    val partsStr = parts.collect { case m.Lit.String(s) => s }
    if partsStr.size != parts.size then
      Left(List(unsupported(
        s"def `${ctx.defName}` has a non-string interpolation part"
      )))
    else
      val argRendered = args.map(renderTerm(_, ctx))
      val (errs, ok)  = argRendered.partitionMap(identity)
      if errs.nonEmpty then Left(errs.flatten)
      else
        val formatStr = partsStr.zipWithIndex.foldLeft(new StringBuilder) { (sb, p) =>
          val (text, i) = p
          sb.append(escapeForFormat(text))
          if i < args.size then sb.append("{}")
          sb
        }.toString
        val tail = if ok.isEmpty then "" else ", " + ok.mkString(", ")
        Right(s"""format!("$formatStr"$tail)""")

  /** Escape a string for `format!("…")` — same rules as the Rust lexer
   *  plus `{` / `}` are doubled to avoid being read as format markers. */
  private[rust] def escapeForFormat(s: String): String =
    val sb = new StringBuilder(s.length)
    s.foreach {
      case '\\' => sb.append("\\\\")
      case '"'  => sb.append("\\\"")
      case '\n' => sb.append("\\n")
      case '\r' => sb.append("\\r")
      case '\t' => sb.append("\\t")
      case '{'  => sb.append("{{")
      case '}'  => sb.append("}}")
      case c    => sb.append(c)
    }
    sb.toString

  /** Resolve a callee tree to its lookup key in the intrinsic table.
   *  Supports plain names (`println`) and one-level qualified
   *  selects (`Console.println`). */
  private def qualifiedName(fn: m.Term): Option[QualifiedName] = fn match
    case m.Term.Name(n)                                    => Some(QualifiedName(n))
    case m.Term.Select(m.Term.Name(qual), m.Term.Name(n))  => Some(QualifiedName(s"$qual.$n"))
    case _                                                 => None

  // ── Helpers ──────────────────────────────────────────────────────────

  private def unsupported(message: String): Diagnostic =
    Diagnostic.Generic(message = message, source = Some("rust"))

  private def indent(s: String): String =
    s.linesIterator.map(line => if line.isEmpty then "" else "    " + line).mkString("\n")

  private[rust] def escapeRustString(s: String): String =
    val sb = new StringBuilder(s.length)
    s.foreach {
      case '\\' => sb.append("\\\\")
      case '"'  => sb.append("\\\"")
      case '\n' => sb.append("\\n")
      case '\r' => sb.append("\\r")
      case '\t' => sb.append("\\t")
      case c    => sb.append(c)
    }
    sb.toString
