package scalascript.codegen.rust

import scala.meta as m
import scala.meta.prettyprinters.XtensionSyntax
import scala.meta.transversers.XtensionCollectionLikeUI
import scalascript.ast
import scalascript.backend.spi.*
import scalascript.ir.QualifiedName

/** Walk an `ast.Module` and emit `src/generated/<crate>.rs`.
 *
 *  Phase R.1.3c is intentionally narrow: only the hello-world shape
 *  is accepted —
 *
 *    `[@main] def name(): Unit = println("string-literal")`
 *
 *  Anything outside that subset returns a `Diagnostic.Generic` so the
 *  caller can convert it into `CompileResult.Failed`.  Each later
 *  R.x slice widens the accepted shapes; the narrow start keeps the
 *  goldens stable while the runtime preamble + main-assembly slices
 *  catch up. */
object RustCodeWalk:

  /** A single rendered `pub fn` extracted from a `Defn.Def`. */
  final case class GeneratedDef(name: String, render: String, isMain: Boolean)

  /** Outcome of walking a module — either a list of diagnostics or
   *  the assembled `src/generated/<crate>.rs` text plus the names of
   *  the defs it contains and the `@main`-annotated entry point, so
   *  the main-assembly slice can stitch a
   *  `fn main() { generated::<crate>::<entry>(); }` shim. */
  final case class WalkResult(
      generated: String,
      defNames:  List[String],
      mainEntry: Option[String]
  )

  def walk(
      module:     ast.Module,
      intrinsics: Map[QualifiedName, IntrinsicImpl]
  ): Either[List[Diagnostic], WalkResult] =
    val defs       = collectDefs(module)
    val enums      = collectEnums(module)
    val rustBlocks = collectRustBlocks(module)
    val userDefs   = defs.map(_.name.value).toSet
    val enumRendered = enums.map(renderEnum)
    val (enumErrs, enumOk) = enumRendered.partitionMap(identity)
    val ctorMap = enumOk.flatMap(_.ctors).toMap
    val results = defs.map(renderDef(_, intrinsics, userDefs, ctorMap))
    val (errors, ok) = results.partitionMap(identity)
    val allErrs = enumErrs.flatten ++ errors.flatten
    if allErrs.nonEmpty then Left(allErrs)
    else
      val enumBlock = enumOk.map(_.render).mkString
      val rustVerbatim = rustBlocks.zipWithIndex.map { case (src, i) =>
        s"""// ── rust block ${i + 1} ──
           |$src
           |""".stripMargin
      }.mkString
      val body =
        enumBlock +
        (if enumBlock.nonEmpty && ok.nonEmpty then "\n" else "") +
        (if ok.isEmpty then "" else ok.map(_.render).mkString("\n")) +
        (if rustBlocks.isEmpty then "" else "\n" + rustVerbatim)
      val text =
        if body.isEmpty then headerComment
        else headerComment + "\n" + body
      Right(WalkResult(
        generated = text,
        defNames  = ok.map(_.name),
        mainEntry = ok.find(_.isMain).map(_.name)
      ))

  /** Header for the generated file.  Stable so goldens diff cleanly. */
  private val headerComment: String =
    """//! Generated by RustGen.  Do not edit by hand.
      |//!
      |//! One `pub fn` per ScalaScript top-level `def`.  Calls to console
      |//! intrinsics (`println`, `print`) route to `crate::runtime::_*`.
      |//! `rust` fence blocks from the source are appended verbatim.
      |""".stripMargin

  // ── Defn.Def collection ──────────────────────────────────────────────

  /** Top-level defs across every parsed `scalascript`/`ssc`/`scala` block. */
  private def collectDefs(module: ast.Module): List[m.Defn.Def] =
    module.sections.flatMap(sectionDefs)

  private def sectionDefs(s: ast.Section): List[m.Defn.Def] =
    s.content.flatMap(contentDefs) ++ s.subsections.flatMap(sectionDefs)

  private def contentDefs(c: ast.Content): List[m.Defn.Def] = c match
    case ast.Content.CodeBlock(lang, _, Some(node), _, _, _, _)
        if isScalaLang(lang) =>
      node.tree.collect { case d: m.Defn.Def => d }.toList
    case _ => Nil

  private def isScalaLang(lang: String): Boolean =
    val n = lang.toLowerCase
    n == "scalascript" || n == "ssc" || n == "scala"

  // ── rust block collection (verbatim passthrough) ─────────────────────

  /** Raw Rust source from `rust` fence blocks — concatenated into the
   *  emitted `src/generated/<crate>.rs` after the ScalaScript-derived
   *  defs.  Cross-block typing (Rust → SS) is a future slice; today
   *  the rust source just contributes top-level items that any SS
   *  emit can reach via `pub fn` / `pub struct` lookups. */
  private def collectRustBlocks(module: ast.Module): List[String] =
    module.sections.flatMap(sectionRustBlocks)

  private def sectionRustBlocks(s: ast.Section): List[String] =
    s.content.flatMap(contentRustBlocks) ++ s.subsections.flatMap(sectionRustBlocks)

  private def contentRustBlocks(c: ast.Content): List[String] = c match
    case ast.Content.CodeBlock(lang, source, _, _, _, _, _)
        if lang.equalsIgnoreCase("rust") =>
      List(source)
    case _ => Nil

  // ── Enum collection + rendering ──────────────────────────────────────

  /** Collect every `Defn.Enum` reachable from a `scalascript` / `ssc` /
   *  `scala` code block.  Order is source order. */
  private def collectEnums(module: ast.Module): List[m.Defn.Enum] =
    module.sections.flatMap(sectionEnums)

  private def sectionEnums(s: ast.Section): List[m.Defn.Enum] =
    s.content.flatMap(contentEnums) ++ s.subsections.flatMap(sectionEnums)

  private def contentEnums(c: ast.Content): List[m.Defn.Enum] = c match
    case ast.Content.CodeBlock(lang, _, Some(node), _, _, _, _)
        if isScalaLang(lang) =>
      node.tree.collect { case d: m.Defn.Enum => d }.toList
    case _ => Nil

  /** Lower a Scala 3 `enum E { case A(x: T); … }` to a Rust enum:
   *
   *  ```rust
   *  pub enum E {
   *      A { x: T },
   *      B { y: U },
   *      …
   *  }
   *  ```
   *
   *  Struct-style variants (named fields) keep the field names so the
   *  pattern-match emit can destructure by name. */
  private def renderEnum(e: m.Defn.Enum): Either[List[Diagnostic], GeneratedEnum] =
    val enumName = e.name.value
    val cases    = e.templ.body.stats.collect { case c: m.Defn.EnumCase => c }
    if cases.isEmpty then
      Left(List(unsupported(s"enum `$enumName` has no `case` variants")))
    else
      val rendered = cases.map(c => renderEnumCase(enumName, c))
      val (errs, ok) = rendered.partitionMap(identity)
      if errs.nonEmpty then Left(errs.flatten)
      else
        val variantText = ok.map(_._1).mkString(",\n")
        val src =
          s"""#[allow(dead_code)]
             |#[derive(Debug, Clone)]
             |pub enum $enumName {
             |${indent(variantText)},
             |}
             |""".stripMargin
        val ctors = ok.map(_._2)
        Right(GeneratedEnum(render = src, ctors = ctors))

  /** Render one `case Ctor(field1: T1, …)` into a Rust struct-style
   *  enum variant.  Returns the variant text + the ctor metadata. */
  private def renderEnumCase(
      enumName: String, c: m.Defn.EnumCase
  ): Either[List[Diagnostic], (String, (String, EnumCtor))] =
    val ctor   = c.name.value
    val params = c.ctor.paramClauses.flatMap(_.values).toList
    val fieldRendered = params.map { p =>
      p.decltpe match
        case Some(t) => mapType(t, s"enum $enumName.$ctor").map(r => (p.name.value, r))
        case None    => Left(List(unsupported(
          s"enum `$enumName.$ctor` parameter `${p.name.value}` has no type annotation"
        )))
    }
    val (errs, ok) = fieldRendered.partitionMap(identity)
    if errs.nonEmpty then Left(errs.flatten)
    else
      val fields = ok
      val body   =
        if fields.isEmpty then ""
        else " { " + fields.map((n, t) => s"$n: $t").mkString(", ") + " }"
      val variant = s"$ctor$body"
      Right((variant, (ctor, EnumCtor(enumName, fields.map(_._1)))))

  // ── Per-def rendering ────────────────────────────────────────────────

  /** Rendering context: the set of user-defined fn names in scope, plus
   *  the constructor-name → enum-name map collected from `Defn.Enum`. */
  private case class Ctx(
      intrinsics: Map[QualifiedName, IntrinsicImpl],
      userDefs:   Set[String],
      ctorMap:    Map[String, EnumCtor],
      defName:    String
  ):
    def enumNames: Set[String] = ctorMap.values.map(_.enumName).toSet

  /** Per-ctor record carrying the enum it belongs to and its field
   *  names (in order).  R.2.3 lowers ctor application as
   *  `EnumName::Ctor { field0: arg0, field1: arg1, … }`. */
  private case class EnumCtor(
      enumName:   String,
      fieldNames: List[String]
  )

  /** A rendered Rust `enum` block + its ctor table. */
  private case class GeneratedEnum(
      render: String,
      ctors:  List[(String, EnumCtor)]
  )

  private def renderDef(
      d: m.Defn.Def,
      intrinsics: Map[QualifiedName, IntrinsicImpl],
      userDefs:   Set[String],
      ctorMap:    Map[String, EnumCtor]
  ): Either[List[Diagnostic], GeneratedDef] =
    val name = d.name.value
    val ctx  = Ctx(intrinsics, userDefs, ctorMap, name)
    for
      params  <- renderParams(d, ctx)
      ret     <- renderReturnType(d, ctx)
      bodyRs  <- renderBody(d.body, ctx, isUnit = ret.isEmpty)
    yield
      val signature = if ret.isEmpty then s"pub fn $name($params)"
                      else                s"pub fn $name($params) -> $ret"
      val src =
        s"""$signature {
           |${indent(bodyRs)}
           |}
           |""".stripMargin
      GeneratedDef(name = name, render = src, isMain = hasMainAnnotation(d))

  /** A def is the entry point when it carries an `@main` annotation. */
  private def hasMainAnnotation(d: m.Defn.Def): Boolean =
    d.mods.exists {
      case m.Mod.Annot(m.Init.After_4_6_0(m.Type.Name("main"), _, _)) => true
      case _                                                          => false
    }

  /** Map a Scala type name to its Rust equivalent.  R.2 supports
   *  primitive types and (when `enumNames` is non-empty) any
   *  user-defined enum name passed through verbatim. */
  private def mapType(
      t: m.Type, defName: String, enumNames: Set[String] = Set.empty
  ): Either[List[Diagnostic], String] = t match
    case m.Type.Name("Unit")    => Right("")          // empty → no `-> T` clause
    case m.Type.Name("Boolean") => Right("bool")
    case m.Type.Name("Int")     => Right("i64")       // ScalaScript `Int` widens to 64-bit
    case m.Type.Name("Long")    => Right("i64")
    case m.Type.Name("Double")  => Right("f64")
    case m.Type.Name("Float")   => Right("f64")
    case m.Type.Name("String")  => Right("String")
    case m.Type.Name(n) if enumNames.contains(n) => Right(n)
    // Scala 3 `A => B` and `(A1, A2, …) => B` lower to `impl Fn(…) -> …`.
    // R.2.4 only renders function types at parameter positions; stored
    // closure values (`Box<dyn Fn>` boxing) land in a later slice.
    case ft: m.Type.Function =>
      val params = ft.paramClause.values.toList
      for
        pRs <- traverseTypes(params, defName, enumNames)
        rRs <- mapType(ft.res, defName, enumNames)
      yield
        if rRs.isEmpty then s"impl Fn(${pRs.mkString(", ")})"
        else                s"impl Fn(${pRs.mkString(", ")}) -> $rRs"
    // R.2.5 — `List[T]` / `Vec[T]` lower to `Vec<T>`.
    case m.Type.Apply.After_4_6_0(m.Type.Name("List" | "Vec"), argClause) =>
      argClause.values.toList match
        case List(elem) => mapType(elem, defName, enumNames).map(r => s"Vec<$r>")
        case other      => Left(List(unsupported(
          s"def `$defName` has `List`/`Vec` with ${other.size} type args; expected exactly one"
        )))
    case other =>
      Left(List(unsupported(
        s"def `$defName` uses type `${other.syntax}`; R.2 accepts primitives, enums, function types, and List/Vec"
      )))

  /** Map a list of types, accumulating diagnostics. */
  private def traverseTypes(
      ts: List[m.Type], defName: String, enumNames: Set[String]
  ): Either[List[Diagnostic], List[String]] =
    val rendered = ts.map(t => mapType(t, defName, enumNames))
    val (errs, ok) = rendered.partitionMap(identity)
    if errs.nonEmpty then Left(errs.flatten) else Right(ok)

  private def renderParams(
      d: m.Defn.Def, ctx: Ctx
  ): Either[List[Diagnostic], String] =
    val groups = d.paramClauseGroups.flatMap(_.paramClauses)
    if groups.size > 1 then
      Left(List(unsupported(
        s"def `${ctx.defName}` has multiple parameter groups; R.2 accepts a single `(…)` group"
      )))
    else
      val params = groups.flatMap(_.values)
      val rendered = params.map { p =>
        p.decltpe match
          case Some(t) => mapType(t, ctx.defName, ctx.enumNames).map(r => s"${p.name.value}: $r")
          case None    => Left(List(unsupported(
            s"def `${ctx.defName}` parameter `${p.name.value}` has no type annotation; R.2 requires explicit param types"
          )))
      }
      val (errs, ok) = rendered.partitionMap(identity)
      if errs.nonEmpty then Left(errs.flatten)
      else Right(ok.mkString(", "))

  private def renderReturnType(
      d: m.Defn.Def, ctx: Ctx
  ): Either[List[Diagnostic], String] =
    d.decltpe match
      case None                       => Right("")    // inferred — treat as Unit
      case Some(m.Type.Name("Unit"))  => Right("")
      case Some(other)                => mapType(other, ctx.defName, ctx.enumNames)

  private def renderBody(
      body:   m.Term,
      ctx:    Ctx,
      isUnit: Boolean
  ): Either[List[Diagnostic], String] = body match
    case b: m.Term.Block =>
      // For non-Unit returns the tail term must NOT terminate with `;` —
      // Rust uses block-trailing-expression as the result.
      // For Unit returns we terminate every statement with `;` so the
      // emitted block is purely statement-oriented (matches the R.1
      // golden shape).
      if isUnit then
        val rendered = b.stats.map(renderStmt(_, ctx))
        val (errs, ok) = rendered.partitionMap(identity)
        if errs.nonEmpty then Left(errs.flatten)
        else Right(ok.mkString("\n"))
      else
        val (initStats, tail) = b.stats.splitAt(b.stats.length - 1)
        val initRendered = initStats.map(renderStmt(_, ctx))
        val tailRendered: Either[List[Diagnostic], String] = tail.headOption match
          case Some(t: m.Term) => renderTerm(t, ctx)
          case Some(other)     => Left(List(unsupported(
            s"def `${ctx.defName}` body tail is a non-expression: ${other.productPrefix}"
          )))
          case None            => Right("")
        val (errs1, initOk) = initRendered.partitionMap(identity)
        tailRendered match
          case Left(errs2)   => Left(errs1.flatten ++ errs2)
          case Right(tailRs) =>
            if errs1.nonEmpty then Left(errs1.flatten)
            else
              val parts = (initOk :+ tailRs).filter(_.nonEmpty)
              Right(parts.mkString("\n"))
    case t: m.Term =>
      // Single-expression body — for Unit returns add the trailing `;`
      // so the emitted block matches the statement-oriented R.1 golden.
      // For non-Unit returns the expression IS the return value.
      renderTerm(t, ctx).map(r => if isUnit then s"$r;" else r)

  private def renderStmt(
      stat: m.Stat, ctx: Ctx
  ): Either[List[Diagnostic], String] = stat match
    // `var name: T = init` → `let mut name: T = init;`.  R.2.2 covers
    // single-pat bindings only (no pattern destructuring).
    case v: m.Defn.Var =>
      renderLetBinding(v.pats, v.decltpe, v.body, mutable = true, ctx)
    // `val name: T = init` → `let name: T = init;`.
    case v: m.Defn.Val =>
      renderLetBinding(v.pats, v.decltpe, v.rhs, mutable = false, ctx)
    case t: m.Term => renderTerm(t, ctx).map(_ + ";")
    case other     => Left(List(unsupported(
      s"def `${ctx.defName}` body contains an unsupported statement: ${other.productPrefix}"
    )))

  private def renderTerm(
      t: m.Term, ctx: Ctx
  ): Either[List[Diagnostic], String] = t match
    // Plain identifier — parameter reference or in-scope fn name.
    case m.Term.Name(n) =>
      Right(n)

    // `if (cond) thenp else elsep` — Rust if expression.
    case ifExpr: m.Term.If =>
      for
        c <- renderTerm(ifExpr.cond, ctx)
        t1 <- renderTerm(ifExpr.thenp, ctx)
        e1 <- renderTerm(ifExpr.elsep, ctx)
      yield
        s"if $c { $t1 } else { $e1 }"

    // `while (cond) body` — Rust while loop.  Body always wrapped in
    // a `{ … }` block so multi-stmt bodies stay statement-oriented.
    case w: m.Term.While =>
      for
        c <- renderTerm(w.expr, ctx)
        // Body is Unit-typed by construction.
        b <- renderBody(w.body, ctx, isUnit = true)
      yield
        s"while $c {\n${indent(b)}\n}"

    // `lhs = rhs` — Rust reassignment of a previously declared `var`.
    case a: m.Term.Assign =>
      for
        l <- renderTerm(a.lhs, ctx)
        r <- renderTerm(a.rhs, ctx)
      yield
        s"$l = $r"

    // `subject match { case … => …; … }` — Rust `match` expression.
    case mt: m.Term.Match =>
      renderMatch(mt.expr, mt.casesBlock.cases.toList, ctx)

    // `(params) => body` — Rust closure `move |params| body`.  Optional
    // param types are honoured; missing types defer to Rust's inference.
    case fn: m.Term.Function =>
      renderClosure(fn.paramClause.values.toList, fn.body, ctx)

    // `for x <- xs yield expr` with a single generator → Rust
    // `xs.into_iter().map(|x| expr).collect::<Vec<_>>()`.  Multi-
    // generator / guarded / val-enumerator shapes land later.
    case fy: m.Term.ForYield =>
      renderForYield(fy.enumsBlock.enums.toList, fy.body, ctx)

    // `xs.size` / `xs.length` / `xs.len` — every shape reads as
    // `xs.len() as i64` (Vec::len returns `usize`).
    case m.Term.Select(qual, m.Term.Name("size" | "length" | "len")) =>
      renderTerm(qual, ctx).map(q => s"($q.len() as i64)")
    // Some scalameta versions parse `x => body` as `Term.AnonymousFunction`
    // with a placeholder; cover the same shape conservatively.
    case _: m.Term.AnonymousFunction =>
      Left(List(unsupported(
        s"def `${ctx.defName}` uses an anonymous-function placeholder; R.2.4 accepts only explicit `(params) => body`"
      )))

    // s"…" interpolation → `format!("…", args)`.
    case m.Term.Interpolate(m.Term.Name("s"), parts, args) =>
      renderStringInterpolation(parts, args, ctx)

    // Application — intrinsic, user-defined fn, or unsupported.
    case m.Term.Apply.After_4_6_0(fn, args) =>
      val callee  = qualifiedName(fn)
      val argList = args.values.map(renderTerm(_, ctx))
      val (errs, renderedArgs) = argList.partitionMap(identity)
      if errs.nonEmpty then Left(errs.flatten)
      else
        val joined = renderedArgs.mkString(", ")
        // `List(1, 2, 3)` / `Vec(1, 2, 3)` → Rust `vec![1, 2, 3]`.
        val isListCtor = fn match
          case m.Term.Name("List" | "Vec") => true
          case _                            => false
        if isListCtor then Right(s"vec![$joined]")
        else applyNonListCtor(fn, callee, renderedArgs, joined, ctx)

    // Infix operators: arithmetic, comparison, boolean.
    case m.Term.ApplyInfix.After_4_6_0(lhs, m.Term.Name(op), _, args) =>
      val rhsTerms = args.values
      val rendered =
        for
          l <- renderTerm(lhs, ctx)
          rs <- rhsTerms.foldLeft[Either[List[Diagnostic], List[String]]](Right(Nil)) {
            (acc, t) => acc.flatMap(xs => renderTerm(t, ctx).map(xs :+ _))
          }
        yield (l, rs)
      rendered.flatMap { case (l, rs) =>
        mapInfixOp(op, ctx.defName) match
          case Right(rustOp) if rs.size == 1 => Right(s"($l $rustOp ${rs.head})")
          case Right(_)                      => Left(List(unsupported(
            s"def `${ctx.defName}`: infix `$op` with ${rs.size} rhs args"
          )))
          case Left(diags)                   => Left(diags)
      }

    // Always emit owned `String`s — every user-typed `String` parameter
    // expects an owned value, and the `_println` runtime helper is
    // Display-generic so the extra allocation is harmless.  A future
    // optimisation pass may infer when a borrowed `&str` is enough.
    case m.Lit.String(s)  => Right("\"" + escapeRustString(s) + "\".to_string()")
    case m.Lit.Int(n)     => Right(s"${n}i64")
    case m.Lit.Long(n)    => Right(s"${n}i64")
    case m.Lit.Double(d)  => Right(s"${d}f64")
    case m.Lit.Boolean(b) => Right(b.toString)
    case m.Lit.Unit()     => Right("()")

    case other =>
      Left(List(unsupported(
        s"def `${ctx.defName}` contains an unsupported expression: ${other.productPrefix} (${other.syntax})"
      )))

  /** Resolve a non-List/Vec `Term.Apply` callee against intrinsics,
   *  enum constructors, in-scope user defs, and finally a passthrough
   *  fallback (see R.2.4). */
  private def applyNonListCtor(
      fn:           m.Term,
      callee:       Option[QualifiedName],
      renderedArgs: List[String],
      joined:       String,
      ctx:          Ctx
  ): Either[List[Diagnostic], String] =
    val intr = callee.flatMap(qn => ctx.intrinsics.get(qn).map(qn -> _))
    intr match
      case Some((_, RuntimeCall(target))) =>
        Right(s"$target($joined)")
      case Some((qn, other)) =>
        Left(List(unsupported(
          s"intrinsic `${qn.value}` uses ${other.getClass.getSimpleName}; rust target accepts only RuntimeCall"
        )))
      case None =>
        val plainName = fn match
          case m.Term.Name(n) => Some(n)
          case _              => None
        plainName.flatMap { n =>
          ctx.ctorMap.get(n).map { ec =>
            val fields = ec.fieldNames.zip(renderedArgs)
            val body   =
              if fields.isEmpty then ""
              else " { " + fields.map((fn, a) => s"$fn: $a").mkString(", ") + " }"
            s"${ec.enumName}::$n$body"
          }
        } match
          case Some(rs) => Right(rs)
          case None     =>
            plainName.filter(ctx.userDefs.contains) match
              case Some(n) => Right(s"$n($joined)")
              case None    =>
                // Fallback: assume closure parameter or local binding;
                // Cargo will reject if not.  See R.2.4.
                plainName match
                  case Some(n) => Right(s"$n($joined)")
                  case None    => Left(List(unsupported(
                    s"def `${ctx.defName}` calls `${fn.syntax}` which has no resolvable name"
                  )))

  /** Lower a `for x <- xs yield body` (single-generator) to
   *  `xs.into_iter().map(|x| body).collect::<Vec<_>>()`.  Multi-generator
   *  / guarded / val-enumerator shapes are out of scope for R.2.5. */
  private def renderForYield(
      enums: List[m.Enumerator], body: m.Term, ctx: Ctx
  ): Either[List[Diagnostic], String] =
    enums match
      case List(g: m.Enumerator.Generator) =>
        g.pat match
          case m.Pat.Var(m.Term.Name(name)) =>
            for
              xs <- renderTerm(g.rhs, ctx)
              b  <- renderTerm(body, ctx)
            yield
              s"$xs.into_iter().map(move |$name| { $b }).collect::<Vec<_>>()"
          case other =>
            Left(List(unsupported(
              s"def `${ctx.defName}` for-yield generator pattern `${other.syntax}` is not a plain name"
            )))
      case _ =>
        Left(List(unsupported(
          s"def `${ctx.defName}` for-yield has ${enums.size} enumerators; R.2.5 accepts only a single generator"
        )))

  /** Lower `(params) => body` to a Rust `move |params| body` closure.
   *  Parameter type annotations are honoured when present; otherwise
   *  Rust's inference picks them up from the call site. */
  private def renderClosure(
      params: List[m.Term.Param], body: m.Term, ctx: Ctx
  ): Either[List[Diagnostic], String] =
    val rendered = params.map { p =>
      p.decltpe match
        case None    => Right(p.name.value)
        case Some(t) => mapType(t, ctx.defName, ctx.enumNames).map(r =>
          if r.isEmpty then p.name.value else s"${p.name.value}: $r"
        )
    }
    val (errs, ok) = rendered.partitionMap(identity)
    if errs.nonEmpty then Left(errs.flatten)
    else
      for b <- renderTerm(body, ctx)
      yield s"move |${ok.mkString(", ")}| { $b }"

  /** Lower a `Term.Match(subject, cases)` to a Rust `match` expression.
   *  Each case's pattern is lowered via `renderPattern`; the body is
   *  rendered as a non-Unit expression (the match itself is an
   *  expression). */
  private def renderMatch(
      subject: m.Term, cases: List[m.Case], ctx: Ctx
  ): Either[List[Diagnostic], String] =
    val subjRendered = renderTerm(subject, ctx)
    val caseRendered = cases.map { c =>
      if c.cond.nonEmpty then
        Left(List(unsupported(
          s"def `${ctx.defName}` has a match-case guard (`if …`); R.2.3 accepts only plain patterns"
        )))
      else
        for
          pat <- renderPattern(c.pat, ctx)
          bod <- renderTerm(c.body, ctx)
        yield s"$pat => $bod,"
    }
    val (errs, ok) = caseRendered.partitionMap(identity)
    subjRendered.flatMap { s =>
      if errs.nonEmpty then Left(errs.flatten)
      else
        val arms = ok.mkString("\n")
        Right(s"match $s {\n${indent(arms)}\n}")
    }

  /** Lower a scalameta `Pat` to a Rust pattern.  R.2.3 covers the
   *  shapes the case-class fixture needs: extractor (`Pat.Extract`)
   *  against an enum constructor, var-bind, wildcard, literals. */
  private def renderPattern(p: m.Pat, ctx: Ctx): Either[List[Diagnostic], String] = p match
    case m.Pat.Wildcard()           => Right("_")
    case m.Pat.Var(m.Term.Name(n))  => Right(n)
    case m.Lit.Int(n)               => Right(s"${n}i64")
    case m.Lit.Long(n)              => Right(s"${n}i64")
    case m.Lit.Double(d)            => Right(s"${d}f64")
    case m.Lit.Boolean(b)           => Right(b.toString)
    case m.Lit.String(s)            => Right("\"" + escapeRustString(s) + "\"")
    case m.Pat.Extract.After_4_6_0(m.Term.Name(ctor), argClause) =>
      val args = argClause.values
      ctx.ctorMap.get(ctor) match
        case None =>
          Left(List(unsupported(
            s"def `${ctx.defName}` extracts `$ctor` which is not a known enum constructor"
          )))
        case Some(ec) =>
          val argPats = args.map(renderPattern(_, ctx))
          val (errs, ok) = argPats.partitionMap(identity)
          if errs.nonEmpty then Left(errs.flatten)
          else
            if ec.fieldNames.size != ok.size then
              Left(List(unsupported(
                s"def `${ctx.defName}` extracts `$ctor` with ${ok.size} args, expected ${ec.fieldNames.size}"
              )))
            else
              val fieldBinds = ec.fieldNames.zip(ok)
              val body = if fieldBinds.isEmpty then ""
                         else " { " + fieldBinds.map { case (f, p) =>
                           if f == p then f else s"$f: $p"
                         }.mkString(", ") + " }"
              Right(s"${ec.enumName}::$ctor$body")
    case other =>
      Left(List(unsupported(
        s"def `${ctx.defName}` has unsupported pattern: ${other.productPrefix} (${other.syntax})"
      )))

  /** Render a `val`/`var` binding to a Rust `let` (optionally `mut`)
   *  statement.  Only single-name patterns are supported; destructuring
   *  binders lower to a structured diagnostic. */
  private def renderLetBinding(
      pats:    List[m.Pat],
      decltpe: Option[m.Type],
      rhs:     m.Term,
      mutable: Boolean,
      ctx:     Ctx
  ): Either[List[Diagnostic], String] =
    pats match
      case List(m.Pat.Var(m.Term.Name(name))) =>
        val kw = if mutable then "let mut" else "let"
        val annotated: Either[List[Diagnostic], String] = decltpe match
          case None    => Right("")
          case Some(t) => mapType(t, ctx.defName, ctx.enumNames).map { r =>
            if r.isEmpty then "" else s": $r"
          }
        for
          tyAnn <- annotated
          rhsRs <- renderTerm(rhs, ctx)
        yield
          s"$kw $name$tyAnn = $rhsRs;"
      case _ =>
        Left(List(unsupported(
          s"def `${ctx.defName}` has a non-single-name binding; R.2 accepts only `${if mutable then "var" else "val"} name: T = expr`"
        )))

  /** Lower a Scala infix operator to its Rust equivalent.  R.2 covers
   *  arithmetic + comparison + boolean — enough for fib + a basic
   *  string-interp example. */
  private def mapInfixOp(op: String, defName: String): Either[List[Diagnostic], String] = op match
    case "+" | "-" | "*" | "/" | "%" => Right(op)
    case "<" | "<=" | ">" | ">=" | "==" | "!=" => Right(op)
    case "&&" | "||" => Right(op)
    case other => Left(List(unsupported(
      s"def `$defName` uses unsupported infix operator `$other`"
    )))

  /** Lower `s"prefix ${expr} suffix"` to `format!("prefix {} suffix", expr)`. */
  private def renderStringInterpolation(
      parts: List[m.Lit],
      args:  List[m.Term],
      ctx:   Ctx
  ): Either[List[Diagnostic], String] =
    val partsStr = parts.collect { case m.Lit.String(s) => s }
    if partsStr.size != parts.size then
      Left(List(unsupported(
        s"def `${ctx.defName}` has a non-string interpolation part"
      )))
    else
      val argRendered = args.map(renderTerm(_, ctx))
      val (errs, ok)  = argRendered.partitionMap(identity)
      if errs.nonEmpty then Left(errs.flatten)
      else
        val formatStr = partsStr.zipWithIndex.foldLeft(new StringBuilder) { (sb, p) =>
          val (text, i) = p
          sb.append(escapeForFormat(text))
          if i < args.size then sb.append("{}")
          sb
        }.toString
        val tail = if ok.isEmpty then "" else ", " + ok.mkString(", ")
        Right(s"""format!("$formatStr"$tail)""")

  /** Escape a string for `format!("…")` — same rules as the Rust lexer
   *  plus `{` / `}` are doubled to avoid being read as format markers. */
  private[rust] def escapeForFormat(s: String): String =
    val sb = new StringBuilder(s.length)
    s.foreach {
      case '\\' => sb.append("\\\\")
      case '"'  => sb.append("\\\"")
      case '\n' => sb.append("\\n")
      case '\r' => sb.append("\\r")
      case '\t' => sb.append("\\t")
      case '{'  => sb.append("{{")
      case '}'  => sb.append("}}")
      case c    => sb.append(c)
    }
    sb.toString

  /** Resolve a callee tree to its lookup key in the intrinsic table.
   *  Supports plain names (`println`) and one-level qualified
   *  selects (`Console.println`). */
  private def qualifiedName(fn: m.Term): Option[QualifiedName] = fn match
    case m.Term.Name(n)                                    => Some(QualifiedName(n))
    case m.Term.Select(m.Term.Name(qual), m.Term.Name(n))  => Some(QualifiedName(s"$qual.$n"))
    case _                                                 => None

  // ── Helpers ──────────────────────────────────────────────────────────

  private def unsupported(message: String): Diagnostic =
    Diagnostic.Generic(message = message, source = Some("rust"))

  private def indent(s: String): String =
    s.linesIterator.map(line => if line.isEmpty then "" else "    " + line).mkString("\n")

  private[rust] def escapeRustString(s: String): String =
    val sb = new StringBuilder(s.length)
    s.foreach {
      case '\\' => sb.append("\\\\")
      case '"'  => sb.append("\\\"")
      case '\n' => sb.append("\\n")
      case '\r' => sb.append("\\r")
      case '\t' => sb.append("\\t")
      case c    => sb.append(c)
    }
    sb.toString
