package scalascript.control

/** Marker supertype for an effect-row member. */
trait Effect

/** Stable, target-neutral identity of an effect algebra. */
final case class EffectId(value: String)

/** Stable, target-neutral identity of one operation in an effect algebra. */
final case class OperationId(effect: EffectId, name: String)

/** Whether an operation's captured continuation may be invoked more than once. */
enum ResumeMultiplicity:
  case Reusable, OneShot

/** Typed rejection produced when a one-shot continuation was already invoked. */
enum ResumeRejected:
  case AlreadyResumed(operation: OperationId)

/**
 * Local type evidence and stable descriptor identity for an effect algebra.
 *
 * A key retains the exact singleton owner. Handler matching uses owner identity;
 * the stable descriptor is checked after that match so a malformed declaration
 * can never turn a handled row member into a forwarded residual operation.
 */
final class EffectKey[Fx <: Effect] private (
    val id: EffectId,
    private val owner: Effect,
    candidate: EffectKey.Authority
):
  EffectKey.requireAuthority(candidate)
  if owner == null then
    throw new NullPointerException("effect owner")

  private[control] def sameRuntime(other: EffectKey[?]): Boolean =
    if other == null then false
    else if other.hasOwner(owner)
    then
      if id != other.id then
        throw new IllegalArgumentException(
          s"effect owner declared with both $id and ${other.id}"
        )
      true
    else false

  private def hasOwner(candidate: Effect): Boolean =
    owner.asInstanceOf[AnyRef] eq candidate.asInstanceOf[AnyRef]

object EffectKey:
  /** JVM-visible only as an unforgeable constructor parameter. */
  private[control] final class Authority private[EffectKey] ()

  private val authority = new Authority()

  private[control] def requireAuthority(candidate: Authority): Unit =
    if (candidate eq null) || !(candidate eq authority) then
      throw new IllegalArgumentException("invalid EffectKey authority")

  def named[Fx <: Effect & Singleton](
      id: EffectId,
      witness: Fx
  ): EffectKey[witness.type] =
    if id == null then throw new NullPointerException("effect id")
    if id.value == null then throw new NullPointerException("effect id value")
    if witness == null then throw new NullPointerException("effect owner")
    new EffectKey[witness.type](id, witness, authority)

/** A typed request in an effect algebra. */
trait Operation[Fx <: Effect, A]:
  def effect: EffectKey[Fx]
  def id: OperationId
  def multiplicity: ResumeMultiplicity = ResumeMultiplicity.Reusable

/** Private prompt-indexed effect row discharged only by its matching reset. */
sealed trait Control[P] extends Effect

object Control:
  private final class Witness[P] extends Control[P]

  private[control] def freshKey[P](
      candidate: Prompt.Authority
  ): EffectKey[Control[P]] =
    Prompt.requireAuthority(candidate)
    val witness = new Witness[P]
    // P is generated by Prompt.scoped. This is the sole invariant widening
    // from its private singleton owner to the prompt-indexed Control[P] row.
    EffectKey
      .named(EffectId("scalascript.control.Control"), witness)
      .asInstanceOf[EffectKey[Control[P]]]

/** Typed reasons that a managed continuation cannot cross the save boundary. */
enum CaptureFailure:
  case UnmanagedCapture(site: String)
  case CaptureBarrier(site: String, detail: String)
  case OneShotSource(site: String)
  case MissingCodec(site: String, typeId: String)
  case UnsupportedGraph(site: String, detail: String)

object Save extends Effect:
  val key: EffectKey[Save.type] =
    EffectKey.named(EffectId("scalascript.control.Save"), this)

  final case class Rejected(failure: CaptureFailure)
      extends Operation[Save.type, Nothing]:
    val effect: EffectKey[Save.type] = Save.key
    val id: OperationId = OperationId(effect.id, "rejected")
    override val multiplicity: ResumeMultiplicity =
      ResumeMultiplicity.OneShot

/** Effect row used while a managed continuation is being saved. */
type Save = Save.type

/** Effect row used while a saved continuation is admitted and restored. */
object Restore extends Effect:
  val key: EffectKey[Restore.type] =
    EffectKey.named(EffectId("scalascript.control.Restore"), this)

  /**
   * Discharge the `Restore` capability for an in-process run that performs no
   * provider-backed restore. Nothing constructs an `Operation[Restore.type, ?]`
   * yet, so the handler's `onOperation` is unreachable; a provider-backed
   * admission slice replaces this with real restore operations
   * (control-interoperability §9.2). Until then `Restore` in a run's row is a
   * declared call-site capability marker, discharged here.
   */
  def admitLocally[Fx <: Effect, R](body: Eff[Fx | Restore, R]): Eff[Fx, R] =
    handle[Restore.type, Fx, R, R](body)(
      new Handler[Restore.type, Fx, R, R]:
        val effect: EffectKey[Restore.type] = key

        def onReturn(value: R): Eff[Fx, R] = Eff.pure(value)

        def onOperation[X](
            @scala.annotation.unused operation: Operation[Restore.type, X],
            @scala.annotation.unused resumption: Resumption[X, Fx, R]
        ): Eff[Fx, R] =
          throw new IllegalStateException(
            "Restore.admitLocally received a restore operation; no provider is bound"
          )
    )

type Restore = Restore.type
