package scalascript.control

/** Marker supertype for an effect-row member. */
trait Effect

/** Stable, target-neutral identity of an effect algebra. */
final case class EffectId(value: String)

/** Stable, target-neutral identity of one operation in an effect algebra. */
final case class OperationId(effect: EffectId, name: String)

/** Whether an operation's captured continuation may be invoked more than once. */
enum ResumeMultiplicity:
  case Reusable, OneShot

/**
 * Typed rejection produced when a continuation cannot be resumed or cancelled.
 *
 * `Cancelled` and `TooLateToCancel` are DELIBERATELY separate rows (owner decision D1,
 * `specs/durable-cancellation-open-decisions.md`): collapsing "your cancel arrived after the
 * resume claim" into `AlreadyResumed` would report the caller's *cancel* under a name that means
 * *resumption*, and §13 requires diagnostics to stay non-collapsible. A caller asking "did I manage
 * to stop it?" gets an unambiguous answer instead of having to reinterpret `AlreadyResumed` by
 * context.
 */
enum ResumeRejected:
  case AlreadyResumed(operation: OperationId)
  /** A run was requested on a continuation the caller had cancelled. */
  case Cancelled(operation: OperationId)
  /** A cancel lost the race to a resume that had already claimed the slot. */
  case TooLateToCancel(operation: OperationId)


/** What a lane's `cancel` promises about work already running (owner decision D2). The base
 *  contract is portable and blocks only NEW admissions; a lane able to interrupt a running suffix
 *  says so here, so callers can DETECT the difference instead of guessing from a footnote. */
enum CancellationScope:
  case BlocksNewAdmissions, InterruptsInFlight

/** Thrown by `SavedContinuation.run` when admission rejects it; `tryRun` returns the same rejection
 *  as a value. The typed `rejection` — never a message — is the embedding contract. */
final class RunRejected(val rejection: ResumeRejected)
    extends RuntimeException(s"run rejected: $rejection")

/** Evidence that a cancellation took effect. Named apart from `ResumeRejected.Cancelled` so the
 *  success and failure sides of `tryCancel` never read as the same thing. */
final case class CancelAccepted(operation: OperationId)

/**
 * Local type evidence and stable descriptor identity for an effect algebra.
 *
 * A key retains the exact singleton owner. Handler matching uses owner identity;
 * the stable descriptor is checked after that match so a malformed declaration
 * can never turn a handled row member into a forwarded residual operation.
 */
final class EffectKey[Fx <: Effect] private (
    val id: EffectId,
    private val owner: Effect,
    candidate: EffectKey.Authority
):
  EffectKey.requireAuthority(candidate)
  if owner == null then
    throw new NullPointerException("effect owner")

  private[control] def sameRuntime(other: EffectKey[?]): Boolean =
    if other == null then false
    else if other.hasOwner(owner)
    then
      if id != other.id then
        throw new IllegalArgumentException(
          s"effect owner declared with both $id and ${other.id}"
        )
      true
    else false

  private def hasOwner(candidate: Effect): Boolean =
    owner.asInstanceOf[AnyRef] eq candidate.asInstanceOf[AnyRef]

object EffectKey:
  /** JVM-visible only as an unforgeable constructor parameter. */
  private[control] final class Authority private[EffectKey] ()

  private val authority = new Authority()

  private[control] def requireAuthority(candidate: Authority): Unit =
    if (candidate eq null) || !(candidate eq authority) then
      throw new IllegalArgumentException("invalid EffectKey authority")

  def named[Fx <: Effect & Singleton](
      id: EffectId,
      witness: Fx
  ): EffectKey[witness.type] =
    if id == null then throw new NullPointerException("effect id")
    if id.value == null then throw new NullPointerException("effect id value")
    if witness == null then throw new NullPointerException("effect owner")
    new EffectKey[witness.type](id, witness, authority)

/** A typed request in an effect algebra. */
trait Operation[Fx <: Effect, A]:
  def effect: EffectKey[Fx]
  def id: OperationId
  def multiplicity: ResumeMultiplicity = ResumeMultiplicity.Reusable

/** Private prompt-indexed effect row discharged only by its matching reset. */
sealed trait Control[P] extends Effect

object Control:
  private final class Witness[P] extends Control[P]

  private[control] def freshKey[P](
      candidate: Prompt.Authority
  ): EffectKey[Control[P]] =
    Prompt.requireAuthority(candidate)
    val witness = new Witness[P]
    // P is generated by Prompt.scoped. This is the sole invariant widening
    // from its private singleton owner to the prompt-indexed Control[P] row.
    EffectKey
      .named(EffectId("scalascript.control.Control"), witness)
      .asInstanceOf[EffectKey[Control[P]]]

/** Typed reasons that a managed continuation cannot cross the save boundary. */
enum CaptureFailure:
  case UnmanagedCapture(site: String)
  case CaptureBarrier(site: String, detail: String)
  case OneShotSource(site: String)
  case MissingCodec(site: String, typeId: String)
  case UnsupportedGraph(site: String, detail: String)

object Save extends Effect:
  val key: EffectKey[Save.type] =
    EffectKey.named(EffectId("scalascript.control.Save"), this)

  final case class Rejected(failure: CaptureFailure)
      extends Operation[Save.type, Nothing]:
    val effect: EffectKey[Save.type] = Save.key
    val id: OperationId = OperationId(effect.id, "rejected")
    override val multiplicity: ResumeMultiplicity =
      ResumeMultiplicity.OneShot

/** Effect row used while a managed continuation is being saved. */
type Save = Save.type

/** Effect row used while a saved continuation is admitted and restored. */
object Restore extends Effect:
  val key: EffectKey[Restore.type] =
    EffectKey.named(EffectId("scalascript.control.Restore"), this)

  /** Resolve an inert `DurableRef` to its value — the one real restore operation. */
  final case class Resolve[A](ref: DurableRef[A])
      extends Operation[Restore.type, A]:
    val effect: EffectKey[Restore.type] = Restore.key
    val id: OperationId = OperationId(effect.id, "resolve")

  /** Perform a post-admission resolution of a durable reference (§9.2). */
  def resolve[A](ref: DurableRef[A]): Eff[Restore, A] =
    perform(Resolve(ref))

  /** Turns a `DurableRef` into its live value once admission has succeeded. */
  trait Resolver:
    def resolve[A](ref: DurableRef[A]): A

  /**
   * Discharge the `Restore` capability by resolving every `Resolve` through the
   * provider-backed `resolver`. Each resolution runs once and the handler
   * reinstalls around the suffix, so a multi-shot suffix that resolves twice
   * calls the resolver twice; each run resolves independently (§8.2).
   */
  def withResolver[Fx <: Effect, R](resolver: Resolver)(
      body: Eff[Fx | Restore, R]
  ): Eff[Fx, R] =
    handle[Restore.type, Fx, R, R](body)(
      new Handler[Restore.type, Fx, R, R]:
        val effect: EffectKey[Restore.type] = key

        def onReturn(value: R): Eff[Fx, R] = Eff.pure(value)

        def onOperation[X](
            operation: Operation[Restore.type, X],
            resumption: Resumption[X, Fx, R]
        ): Eff[Fx, R] =
          operation match
            case resolveOp: Resolve[?] =>
              // Resolve[A] <: Operation[Restore.type, A], so X is that A.
              val resolved = resolver.resolve(resolveOp.ref).asInstanceOf[X]
              resumption match
                case Resumption.Reusable(continuation) =>
                  continuation.resume(resolved)
                case Resumption.OneShot(continuation) =>
                  continuation.tryResume(resolved) match
                    case Right(next)    => next
                    case Left(rejected) =>
                      throw new IllegalStateException(
                        s"restore resolution resumed an already-claimed continuation: $rejected"
                      )
            case other =>
              throw new IllegalStateException(
                s"unknown Restore operation ${other.id}"
              )
    )

  /**
   * Discharge the `Restore` capability for an in-process run that performs no
   * provider-backed resolution. A run that never resolves a `DurableRef` returns
   * directly; one that does resolve fails here, because no provider is bound —
   * use `withResolver` to supply one.
   */
  def admitLocally[Fx <: Effect, R](body: Eff[Fx | Restore, R]): Eff[Fx, R] =
    handle[Restore.type, Fx, R, R](body)(
      new Handler[Restore.type, Fx, R, R]:
        val effect: EffectKey[Restore.type] = key

        def onReturn(value: R): Eff[Fx, R] = Eff.pure(value)

        def onOperation[X](
            operation: Operation[Restore.type, X],
            @scala.annotation.unused resumption: Resumption[X, Fx, R]
        ): Eff[Fx, R] =
          throw new IllegalStateException(
            s"Restore.admitLocally received ${operation.id}; no provider is bound"
          )
    )

type Restore = Restore.type
