package scalascript.frontend.solid

import scalascript.frontend.*

/** Emits idiomatic Solid that does NOT depend on `solid-js/h`.
 *  Reason: solid-js/h has an upstream import compatibility issue
 *  with recent solid-js/web (it tries to import `SVGElements`,
 *  which was removed).  Real Solid apps use the compiler-
 *  transformed JSX path instead.  We don't have a JSX compiler,
 *  so we hand-write what the compiler would produce: imperative
 *  DOM construction wired through `createSignal` +
 *  `createEffect` for fine-grained reactivity.
 *
 *  This is what makes Solid "Solid": each `createEffect` is its
 *  own reactive computation, subscribed only to the signals it
 *  reads.  No virtual DOM, no reconciliation pass.  Compare to
 *  Custom's `__ssc_signals` registry: same effect, slightly
 *  more code, but using the framework primitive instead of
 *  reimplementing it.
 *
 *  Lowerings:
 *    - `ReactiveSignal[T]`          → `const [x, setX] = createSignal(init)`
 *    - `View.Element`               → `document.createElement(tag)` +
 *                                     `setAttribute` + `appendChild`
 *    - `View.TextNode`              → `document.createTextNode(literal)`
 *    - `View.SignalText`            → `createTextNode(initialValue)` +
 *                                     `createEffect(() => node.textContent = signal())`
 *    - `View.Fragment`              → DocumentFragment with all children
 *    - `View.Show` / `View.For`     → emit-time snapshot
 *    - `SetSignalLiteral` event     → `addEventListener(evt, () => setX(value))`
 *    - `IncrementSignal` event      → `addEventListener(evt, () => setX(c => c + by))`
 *    - JVM-closure events           → marker comment */
private[solid] object SolidEmitter:

  def emit(root: View): String =
    val ctx = new Ctx
    val rootVar = ctx.compile(root)
    val sb = new StringBuilder
    sb ++= "// Generated by ScalaScript v1.18 — frontend-solid Phase A4.\n"
    sb ++= "// Idiomatic Solid: createSignal + createEffect + imperative DOM.\n"
    sb ++= "import { createSignal, createEffect } from 'solid-js';\n"
    sb ++= "function App(root) {\n"
    ctx.signals.foreach { (name, initial) =>
      val setter = setterName(name)
      sb ++= s"  const [$name, $setter] = createSignal($initial);\n"
    }
    ctx.statements.foreach { stmt =>
      sb ++= "  "
      sb ++= stmt
      sb ++= "\n"
    }
    if rootVar != null then
      sb ++= s"  root.appendChild($rootVar);\n"
    sb ++= "}\n"
    sb ++= "App(document.getElementById('app'));\n"
    sb.toString

  private final class Ctx:
    private var counter: Int = 0
    val signals: scala.collection.mutable.LinkedHashMap[String, String] =
      scala.collection.mutable.LinkedHashMap.empty
    val statements: scala.collection.mutable.ArrayBuffer[String] =
      scala.collection.mutable.ArrayBuffer.empty

    private def freshVar(): String =
      val v = s"n$counter"
      counter += 1
      v

    private def registerSignal(signal: ReactiveSignal[?]): Unit =
      val name = signal.jsName
      if !name.matches("[A-Za-z_][A-Za-z0-9_]*") then
        throw new IllegalArgumentException(
          s"ReactiveSignal jsName '$name' must match [A-Za-z_][A-Za-z0-9_]*."
        )
      val initJs = jsLiteral(signal())
      signals.get(name) match
        case Some(existing) if existing != initJs =>
          throw new IllegalArgumentException(
            s"ReactiveSignal jsName '$name' registered twice with different " +
            s"initial values ($existing vs $initJs)."
          )
        case _ => signals.update(name, initJs)

    def compile(view: View): String | Null = view match
      case View.Element(tag, attrs, events, children) =>
        val v = freshVar()
        statements += s"const $v = document.createElement(${jsString(tag)});"
        attrs.foreach { (k, av) =>
          attrValueJs(av) match
            case Some(value) => statements += s"$v.setAttribute(${jsString(k)}, $value);"
            case None        => ()
        }
        events.foreach { (eventName, handler) =>
          compileEventHandler(v, eventName, handler)
        }
        children.foreach { child =>
          val childVar = compile(child)
          if childVar != null then statements += s"$v.appendChild($childVar);"
        }
        v

      case View.TextNode(thunk) =>
        val v = freshVar()
        statements += s"const $v = document.createTextNode(${jsString(thunk())});"
        v

      case View.SignalText(signal) =>
        registerSignal(signal)
        val v = freshVar()
        // Solid's createEffect auto-tracks the signal read.  When
        // the signal changes, only this text node updates — no
        // virtual-DOM diff, no parent re-render.
        statements += s"const $v = document.createTextNode(${signal.jsName}());"
        statements += s"createEffect(() => { $v.textContent = ${signal.jsName}(); });"
        v

      case View.Fragment(children) =>
        if children.isEmpty then null
        else
          val v = freshVar()
          statements += s"const $v = document.createDocumentFragment();"
          children.foreach { child =>
            val childVar = compile(child)
            if childVar != null then statements += s"$v.appendChild($childVar);"
          }
          v

      case View.ComponentInstance(component, props) =>
        compile(component.render(props.asInstanceOf[Nothing]))

      case View.Show(cond, whenTrue, whenFalse) =>
        // Emit-time snapshot.  Reactive <Show> arrives with the
        // richer-IR phase.
        val branch = if cond() then whenTrue() else whenFalse()
        compile(branch)

      case View.For(items, render) =>
        val realised = items().toList
        if realised.isEmpty then null
        else
          val v = freshVar()
          statements += s"const $v = document.createDocumentFragment();"
          realised.foreach { item =>
            val childVar = compile(render(item))
            if childVar != null then statements += s"$v.appendChild($childVar);"
          }
          v

    private def compileEventHandler(targetVar: String, eventName: String, handler: EventHandler): Unit =
      handler match
        case EventHandler.Simple(_) | EventHandler.WithEvent(_) =>
          statements +=
            s"// $targetVar: '$eventName' handler is a JVM closure — A4 can't translate;" +
            " richer IR coming later."
        case EventHandler.SetSignalLiteral(signal, value) =>
          registerSignal(signal)
          val setter = setterName(signal.jsName)
          val v      = jsLiteral(value)
          statements += s"$targetVar.addEventListener(${jsString(eventName)}, () => $setter($v));"
        case EventHandler.IncrementSignal(signal, by) =>
          registerSignal(signal)
          val setter = setterName(signal.jsName)
          statements += s"$targetVar.addEventListener(${jsString(eventName)}, () => $setter(c => c + $by));"

    private def attrValueJs(av: AttrValue): Option[String] = av match
      case AttrValue.Str(value)    => Some(jsString(value))
      case AttrValue.Bool(value)   => Some(jsString(value.toString))
      case AttrValue.Num(value)    => Some(formatNumber(value))
      case AttrValue.Dynamic(read) => Some(jsString(String.valueOf(read())))
      case AttrValue.Absent        => None

  private def setterName(varName: String): String =
    "set" + varName.headOption.fold("")(_.toUpper.toString) + varName.drop(1)

  private def jsLiteral(value: Any): String = value match
    case s: String  => jsString(s)
    case i: Int     => i.toString
    case l: Long    => l.toString
    case d: Double  => formatNumber(d)
    case f: Float   => formatNumber(f.toDouble)
    case b: Boolean => b.toString
    case null       => "null"
    case other      => throw new IllegalArgumentException(
      s"jsLiteral: unsupported value type ${other.getClass.getName} ($other).  " +
      "Supported: String / Int / Long / Double / Float / Boolean / null."
    )

  private def formatNumber(d: Double): String =
    if d == d.toLong.toDouble then d.toLong.toString else d.toString

  private def jsString(s: String): String =
    val sb = new StringBuilder
    sb += '\''
    s.foreach {
      case '\\' => sb ++= "\\\\"
      case '\'' => sb ++= "\\'"
      case '\n' => sb ++= "\\n"
      case '\r' => sb ++= "\\r"
      case '<'  => sb ++= "\\u003c"
      case c    => sb += c
    }
    sb += '\''
    sb.toString
