package ssc

/** Static call surface for GENERATED BYTECODE (Phase 4 jvm-lane).
 *
 *  The ASM emitter compiles CoreIR STRUCTURE (seq/if/let/app/match) and
 *  delegates every prim and closure application to these shims — one
 *  invokestatic per site, no collection building inside bytecode. Keeping
 *  the surface tiny and stable is what makes the emitter small. */
object Emit:
  // resolve is string-keyed and non-trivial — cache per op (hot: every prim site)
  private val fnCache = new java.util.concurrent.ConcurrentHashMap[String, List[Value] => Value]()
  private def fn(op: String) = fnCache.computeIfAbsent(op, o => Prims.resolve(o))

  /** Direct arithmetic — no resolve, no List, no StrV boxing of the op. */
  def arith(op: String, a: Value, b: Value): Value = Prims.arithFast(op, a, b)

  // Fused accumulator: `cell = cell <op> r` for a Long cell, unboxed on the cell side.
  // Emitted for the hot foreach/loop accumulator pattern `lcell.set(c, arith(op,
  // lcell.get(c), r))` where r is a boxed element (not statically Long) — replaces
  // box(lcell.get) + Emit.arith + prim2(lcell.set) with a single unboxed op. Matches the
  // old semantics `c.v = asInt1(arithFast(op, IntV(c.v), r))` (a non-Int result into a Long
  // cell is a type error under both paths).
  def lcellAccum(cell: Value, op: String, r: Value): Value =
    val c = cell.asInstanceOf[Value.LongCellV]
    r match
      case Value.IntV(n) =>
        op match
          case "+" => c.v = c.v + n
          case "-" => c.v = c.v - n
          case "*" => c.v = c.v * n
          case "/" => c.v = c.v / n
          case "%" => c.v = c.v % n
          case _   => c.v = accLong(Prims.arithFast(op, Value.IntV(c.v), r))
      case _ => c.v = accLong(Prims.arithFast(op, Value.IntV(c.v), r))
    Value.UnitV
  private def accLong(v: Value): Long = v match
    case Value.IntV(n) => n
    case other         => sys.error(s"lcellAccum: non-Int result ${Show.show(other)}")

  // Double twin of lcellAccum: `cell = cell <op> r` for a Double cell, unboxed on the cell
  // side. r is a boxed element (FloatV, or IntV widened — matching the VM's Float+Int→Float).
  // Matches `c.v = asFloat1(arithFast(op, FloatV(c.v), r))`.
  def dcellAccum(cell: Value, op: String, r: Value): Value =
    val c = cell.asInstanceOf[Value.DoubleCellV]
    r match
      case Value.FloatV(d) =>
        op match
          case "+" => c.v = c.v + d
          case "-" => c.v = c.v - d
          case "*" => c.v = c.v * d
          case "/" => c.v = c.v / d
          case _   => c.v = accDouble(Prims.arithFast(op, Value.FloatV(c.v), r))
      case Value.IntV(n) =>
        op match
          case "+" => c.v = c.v + n
          case "-" => c.v = c.v - n
          case "*" => c.v = c.v * n
          case "/" => c.v = c.v / n
          case _   => c.v = accDouble(Prims.arithFast(op, Value.FloatV(c.v), r))
      case _ => c.v = accDouble(Prims.arithFast(op, Value.FloatV(c.v), r))
    Value.UnitV
  private def accDouble(v: Value): Double = v match
    case Value.FloatV(d) => d
    case Value.IntV(n)   => n.toDouble
    case other           => sys.error(s"dcellAccum: non-numeric result ${Show.show(other)}")

  def prim0(op: String): Value = fn(op)(Nil)
  def prim1(op: String, a: Value): Value = fn(op)(a :: Nil)
  def prim2(op: String, a: Value, b: Value): Value =
    // global.reg is a COMPILER-internal prim (top-level val registration);
    // in the bytecode lane it writes straight into the shared globals map.
    if op == "global.reg" then
      a match { case Value.StrV(n) => registerGlobal(n, b); case _ => () }
      Value.UnitV
    else fn(op)(a :: b :: Nil)
  def prim3(op: String, a: Value, b: Value, c: Value): Value = fn(op)(a :: b :: c :: Nil)
  def primN(op: String, args: Array[Value]): Value = fn(op)(args.toList)

  /** Apply a closure/value to args (mirrors the VM's application semantics). */
  def app(f: Value, args: Array[Value]): Value = f match
    case c: Value.ClosV =>
      if c.arity >= 0 && c.arity != args.length then
        sys.error(s"arity: ${c.arity} expected, ${args.length} given")
      Runtime.run(c.code, if args.isEmpty then c.env else Runtime.extend(c.env, args))
    case other =>
      Runtime.applyFallback(other, args) match
        case Done(v)        => v
        case Call(c, cargs) => Runtime.run(c.code, if cargs.isEmpty then c.env else Runtime.extend(c.env, cargs))

  /** VM parity: provider-owned Signal/ComputedSignal constructors win when
   *  installed; the raw mutable cell remains the bare-kernel fallback. */
  def signalNew(tag: String, init: Value): Value =
    V2PluginRegistry.lookupGlobal(tag) match
      case Some(provider: Value.ClosV) => app(provider, Array(init))
      case _ => Value.ForeignV(Array[Value](init))

  def ctor(tag: String, fields: Array[Value]): Value = Value.DataV(tag, fields.toVector)

  /** SAM for compiled lambda bodies (invokedynamic target from generated code). */
  trait LamFn { def call(env: Array[Value]): Value }

  /** Wrap a compiled lambda body as a VM-compatible closure: interop with the
   *  VM (Runtime.run / callClos) is by construction — the ClosV's code just
   *  forwards to the compiled static method. */
  def clos(arity: Int, fn: LamFn, captured: Array[Value]): Value =
    Value.ClosV(captured, arity, env => Done(unroll(fn.call(env))))

  /** Canonical one-argument handler partial function. The private marker only
   *  authorizes Runtime.dispatchHandler1 to scope its root-match probe. */
  def handlerClos(arity: Int, fn: LamFn, captured: Array[Value]): Value =
    Runtime.handlerClosure(captured, arity, env => Done(unroll(fn.call(env))))

  /** LetRec: create the closures, extend env, tie the cyclic frame (VM semantics). */
  def letrec(
      arities: Array[Int],
      fns: Array[LamFn],
      env: Array[Value]
  ): Array[Value] =
    // Persisted direct-ASM artifacts link this historical descriptor. New
    // handler metadata is additive; old classes retain all-false behavior.
    letrec(arities, fns, Array.fill(fns.length)(false), env)

  def letrec(
      arities: Array[Int],
      fns: Array[LamFn],
      handlerRoots: Array[Boolean],
      env: Array[Value]
  ): Array[Value] =
    val cs = new Array[Value](fns.length)
    var i = 0
    while i < fns.length do
      val f = fns(i)
      val raw: Code = e => Done(unroll(f.call(e)))
      val closure =
        if handlerRoots(i) then Runtime.handlerClosure(Array.empty[Value], arities(i), raw)
        else Value.ClosV(Array.empty[Value], arities(i), raw)
      cs(i) = closure
      i += 1
    val envP = Runtime.extend(env, cs)
    i = 0
    while i < fns.length do
      cs(i).asInstanceOf[Value.ClosV].env = envP
      i += 1
    envP

  /** Statement-position effect threading (the bytecode mirror of the VM's
   *  seqThreadOp): a non-last Seq statement evaluating to an un-handled Op
   *  re-emerges as Op(l, a, x -> { k(x); rest(env) }) — the handler resumes
   *  the original continuation first, then the REST of the sequence runs.
   *  restFn is the compiled chain method for the remaining statements. */
  def isOp(v: Value): Boolean = v match
    case Value.DataV("Op", _) => true
    case _ => false
  def seqThread(op: Value, restFn: LamFn, env: Array[Value]): Value = op match
    case Value.DataV("Op", fs) if fs.length == 3 =>
      seqThreadK(fs(0), fs(1), fs(2), restFn, env)
    case v => v
  private def seqThreadK(l: Value, a: Value, k: Value, restFn: LamFn, env: Array[Value]): Value =
    val kc = k.asInstanceOf[Value.ClosV]
    Value.DataV("Op", Vector(l, a, Value.ClosV(Runtime.emptyEnv, 1, env2 => {
      val resumed = Runtime.run(kc.code, if kc.env.isEmpty then Array(env2.last) else Runtime.extend(kc.env, Array(env2.last)))
      Done(resumed match
        case op2 @ Value.DataV("Op", _) => seqThread(op2, restFn, env)
        case _ => unroll(restFn.call(env)))
    })))

  /** Let-binding effect threading (VM letThreadOp mirror): an Op in a Let rhs
   *  re-emerges with a continuation that BINDS the resumed value and runs the
   *  rest of the let-chain. restFn receives env :+ boundValue. */
  def extend1(env: Array[Value], v: Value): Array[Value] =
    val n = new Array[Value](env.length + 1)
    System.arraycopy(env, 0, n, 0, env.length)
    n(env.length) = v
    n
  def letThread(op: Value, restFn: LamFn, env: Array[Value]): Value = op match
    case Value.DataV("Op", fs) if fs.length == 3 =>
      val kc = fs(2).asInstanceOf[Value.ClosV]
      Value.DataV("Op", Vector(fs(0), fs(1), Value.ClosV(Runtime.emptyEnv, 1, env2 => {
        val resumed = Runtime.run(kc.code, if kc.env.isEmpty then Array(env2.last) else Runtime.extend(kc.env, Array(env2.last)))
        Done(resumed match
          case op2 @ Value.DataV("Op", _) => letThread(op2, restFn, env)
          case v => unroll(restFn.call(extend1(env, v))))
      })))
    case v => v

  /** Mutual-tail trampoline: a TAIL call to another compiled def RETURNS a
   *  Bounce instead of invoking (constant stack); every consumer of a compiled
   *  method's result unrolls bounces in a loop. Wrapped in ForeignV so the
   *  kernel Value ADT stays untouched; Bounce is private to the lane, so no
   *  user value can collide with it. */
  final class Bounce(val fn: LamFn, val args: Array[Value])
  def bounce(fn: LamFn, args: Array[Value]): Value = Value.ForeignV(new Bounce(fn, args))
  def unroll(v0: Value): Value =
    var v = v0
    while v.isInstanceOf[Value.ForeignV] && v.asInstanceOf[Value.ForeignV].h.isInstanceOf[Bounce] do
      val b = v.asInstanceOf[Value.ForeignV].h.asInstanceOf[Bounce]
      v = b.fn.call(b.args)
    v

  /** Self-tail-call frame rebind: the frame is envP ++ args with envP fixed —
   *  clone and overwrite the arg suffix (the array may be aliased by captured
   *  closures, so no in-place mutation). Top-level defs have envP empty:
   *  same-length fast path returns the new args array directly. */
  def rebind(env: Array[Value], args: Array[Value]): Array[Value] =
    if env.length == args.length then args
    else
      val n = env.clone()
      System.arraycopy(args, 0, n, n.length - args.length, args.length)
      n

  /** Local LetRec tail-call frame rebind. The frame is
   * captured ++ tied-group ++ current-args; peer functions may have different
   * arities, so retain the prefix and append the target call's argument array. */
  def localRebind(env: Array[Value], currentArity: Int, args: Array[Value]): Array[Value] =
    val prefix = env.length - currentArity
    if prefix < 0 then sys.error(s"local tail frame: arity $currentArity exceeds ${env.length}")
    val n = new Array[Value](prefix + args.length)
    System.arraycopy(env, 0, n, 0, prefix)
    System.arraycopy(args, 0, n, prefix, args.length)
    n

  /** Concatenate the array part of the frame with materialized let-slot values
   *  (closure capture: the compiled code keeps lets in JVM slots; a nested Lam
   *  must see them as env entries). */
  def capture(env: Array[Value], slots: Array[Value]): Array[Value] =
    if slots.length == 0 then env else Runtime.extend(env, slots)

  def matchFields(v: Value, tag: String, arity: Int): Array[Value] | Null = v match
    case Value.DataV(t, fs) if t == tag && fs.length == arity => fs.toArray
    case _ => null
  def isData(v: Value): Boolean = v.isInstanceOf[Value.DataV]
  def dataTag(v: Value): String = v match { case Value.DataV(t, _) => t; case _ => "" }
  // Cons-walk helpers for the bytecode lane's inline foreach (avoids
  // dataFields array extraction + tag-string compare per element).
  def isCons(v: Value): Boolean = v match { case Value.DataV("Cons", _) => true; case _ => false }
  def consHead(v: Value): Value = v.asInstanceOf[Value.DataV].fields(0)
  def consTail(v: Value): Value = v.asInstanceOf[Value.DataV].fields(1)
  /** Direct `.length`/`.size` for the bytecode lane's hot path — a typed match
   *  instead of the generic __method__ dispatch (prim2 -> resolve -> big
   *  match). Falls back to methodOp for exotic receivers. */
  def len(v: Value, name: String): Value = v match
    case Value.StrV(s) => Value.IntV(s.length.toLong)
    case Value.DataV("Cons", _) | Value.DataV("Nil", _) =>
      var n = 0L; var cur = v
      while cur.isInstanceOf[Value.DataV] && cur.asInstanceOf[Value.DataV].tag == "Cons" do
        n += 1; cur = cur.asInstanceOf[Value.DataV].fields(1)
      Value.IntV(n)
    case _ => Prims.methodOp(name, v, Nil)  // preserve length/size for exotic receivers
  def dataArity(v: Value): Int = v match { case Value.DataV(_, fs) => fs.length; case _ => -1 }
  def dataFields(v: Value): Array[Value] = v match { case Value.DataV(_, fs) => fs.toArray; case _ => Array.empty }
  def matchFail(tag: String, ar: Int): Value = sys.error(s"match: no arm for $tag/$ar")
  def handlerMatchEnter(v: Value): Boolean = Runtime.handlerMatchEnter(v)
  def handlerMatchSelected(active: Boolean): Unit = Runtime.handlerMatchSelected(active)
  def handlerMatchFailed(active: Boolean, tag: String, ar: Int): Value =
    Runtime.handlerMatchFailed(active, tag, ar)

  /** Program globals for the generated class (set once before invocation). */
  @volatile var globalsRef: scala.collection.Map[String, Value] = Map.empty
  def registerGlobal(name: String, v: Value): Unit =
    globalsRef match
      case m: scala.collection.mutable.Map[String, Value] @unchecked => m(name) = v
      case ro => globalsRef = scala.collection.concurrent.TrieMap.from(ro).addOne(name -> v)
  def global(name: String): Value =
    globalsRef.getOrElse(name,
      V2PluginRegistry.lookupGlobal(name)
        .orElse(V2PluginRegistry.lookup(name).map { handler =>
          Value.ClosV(Runtime.emptyEnv, -1, env => Done(handler(env.toList)))
        })
        .getOrElse {
        // VM parity: @xxx cell globals AUTO-CREATE on first access (lazy
        // UnitV init) — readers and writers then share the same cell object
        // through the mutable globals map.
        if name.startsWith("@") then
          val cell = Value.ForeignV(Array[Value](Value.UnitV))
          registerGlobal(name, cell)
          cell
        else sys.error(s"unbound global: $name")
        })
  def strV(s: String): Value = Value.StrV(s)
  def intV(n: Long): Value = Value.IntV(n)
  def floatV(d: Double): Value = Value.FloatV(d)
  def boolV(b: Boolean): Value = Value.BoolV(b)
  def unitV: Value = Value.UnitV
  // wide bytecode lane: BigInt / byte-vector literals — the emitter cannot `ldc` a
  // BigInt or a Vector[Byte], so it emits a decimal / base64 String and reconstructs
  // here (previously `Lit(CBig)`/`Lit(CBytes)` hard-failed the whole bytecode compile).
  def bigVStr(s: String): Value = Value.BigV(BigInt(s))
  def bytesVB64(s: String): Value =
    Value.BytesV(java.util.Base64.getDecoder.decode(s).toVector)
  def bool(v: Value): Boolean = v match
    case Value.BoolV(b) => b
    case other          => sys.error(s"if: condition not Bool: ${Show.show(other)}")
