package ssc

/** Static call surface for GENERATED BYTECODE (Phase 4 jvm-lane).
 *
 *  The ASM emitter compiles CoreIR STRUCTURE (seq/if/let/app/match) and
 *  delegates every prim and closure application to these shims — one
 *  invokestatic per site, no collection building inside bytecode. Keeping
 *  the surface tiny and stable is what makes the emitter small. */
object Emit:
  private def fn(op: String) = Prims.resolve(op)

  def prim0(op: String): Value = fn(op)(Nil)
  def prim1(op: String, a: Value): Value = fn(op)(a :: Nil)
  def prim2(op: String, a: Value, b: Value): Value = fn(op)(a :: b :: Nil)
  def prim3(op: String, a: Value, b: Value, c: Value): Value = fn(op)(a :: b :: c :: Nil)
  def primN(op: String, args: Array[Value]): Value = fn(op)(args.toList)

  /** Apply a closure/value to args (mirrors the VM's application semantics). */
  def app(f: Value, args: Array[Value]): Value = f match
    case c: Value.ClosV =>
      Runtime.run(c.code, if args.isEmpty then c.env else Runtime.extend(c.env, args))
    case other =>
      Runtime.applyFallback(other, args) match
        case Done(v)        => v
        case Call(c, cargs) => Runtime.run(c.code, if cargs.isEmpty then c.env else Runtime.extend(c.env, cargs))

  def ctor(tag: String, fields: Array[Value]): Value = Value.DataV(tag, fields.toVector)

  /** Program globals for the generated class (set once before invocation). */
  @volatile var globalsRef: scala.collection.Map[String, Value] = Map.empty
  def global(name: String): Value =
    globalsRef.getOrElse(name, sys.error(s"unbound global: $name"))
  def strV(s: String): Value = Value.StrV(s)
  def intV(n: Long): Value = Value.IntV(n)
  def floatV(d: Double): Value = Value.FloatV(d)
  def boolV(b: Boolean): Value = Value.BoolV(b)
  def unitV: Value = Value.UnitV
  def bool(v: Value): Boolean = v match
    case Value.BoolV(b) => b
    case other          => sys.error(s"if: condition not Bool: ${Show.show(other)}")
