package scalascript.blockchain.evm

import scalascript.blockchain.spi.TxHash
import scalascript.crypto.{CryptoBackend, HashAlgo}

/** EIP-1559 transaction envelope (tx type 0x02). This is the modern
 *  fee-market format; the legacy / EIP-2930 forms aren't generated by
 *  the adapter today (every EVM chain x402 currently targets supports
 *  EIP-1559).
 *
 *  Field order matches the Yellow Paper / EIP-1559 encoding:
 *    rlp([chainId, nonce, maxPriorityFeePerGas, maxFeePerGas,
 *         gasLimit, to, value, data, accessList, …]).
 *
 *  `to = None` represents a contract-creation transaction. `data` is
 *  the calldata for a call or the init bytecode for a deploy.
 *  `accessList` is empty for everything we currently emit. */
case class EvmTx(
  chainId:              BigInt,
  nonce:                BigInt,
  maxPriorityFeePerGas: BigInt,
  maxFeePerGas:         BigInt,
  gasLimit:             BigInt,
  to:                   Option[String],     // None = contract creation
  value:                BigInt,
  data:                 Array[Byte],
):

  /** RLP-encoded body without signature: used both as the input to
   *  `keccak256` for the sighash and as the structural backbone of
   *  the eventual signed envelope. */
  def encodeUnsigned: Array[Byte] =
    val toNode = to match
      case None    => Rlp.bytes(Array.emptyByteArray)
      case Some(a) => Rlp.bytes(Hex.decode(a))
    val body = Rlp.list(
      Rlp.uint(chainId),
      Rlp.uint(nonce),
      Rlp.uint(maxPriorityFeePerGas),
      Rlp.uint(maxFeePerGas),
      Rlp.uint(gasLimit),
      toNode,
      Rlp.uint(value),
      Rlp.bytes(data),
      Rlp.Lst(Seq.empty),                     // empty accessList
    )
    Array[Byte](0x02) ++ Rlp.encode(body)

  /** Keccak-256 of the unsigned tx envelope; this is what the signer
   *  ECDSA-signs. */
  def sighash: Array[Byte] =
    CryptoBackend.get().hash(HashAlgo.Keccak256, encodeUnsigned)

/** Signed EIP-1559 transaction: the original envelope plus a recovery
 *  parity bit, `r`, and `s`. The raw serialised form is what
 *  `eth_sendRawTransaction` consumes. */
case class EvmSignedTx(tx: EvmTx, yParity: Int, r: Array[Byte], s: Array[Byte]):

  /** Final on-chain encoding:
   *    0x02 || rlp([chainId, nonce, …, accessList, yParity, r, s]). */
  def encodeSigned: Array[Byte] =
    val toNode = tx.to match
      case None    => Rlp.bytes(Array.emptyByteArray)
      case Some(a) => Rlp.bytes(Hex.decode(a))
    val body = Rlp.list(
      Rlp.uint(tx.chainId),
      Rlp.uint(tx.nonce),
      Rlp.uint(tx.maxPriorityFeePerGas),
      Rlp.uint(tx.maxFeePerGas),
      Rlp.uint(tx.gasLimit),
      toNode,
      Rlp.uint(tx.value),
      Rlp.bytes(tx.data),
      Rlp.Lst(Seq.empty),
      Rlp.uint(BigInt(yParity)),
      Rlp.uint(BigInt(1, r)),
      Rlp.uint(BigInt(1, s)),
    )
    Array[Byte](0x02) ++ Rlp.encode(body)

  /** Tx hash for tracking — keccak256 of the signed encoding. */
  def hash: TxHash =
    val h = CryptoBackend.get().hash(HashAlgo.Keccak256, encodeSigned)
    TxHash("0x" + Hex.encode(h, withPrefix = false))

  /** Hex form of `encodeSigned`, prefixed with `0x` — ready for
   *  `eth_sendRawTransaction`. */
  def rawHex: String =
    Hex.encode(encodeSigned, withPrefix = true)
