package scalascript.codegen.rust

import scalascript.backend.spi.*
import scalascript.ir
import scalascript.parser.Parser
import scalascript.transform.Normalize
import org.scalatest.funsuite.AnyFunSuite

/** Phase R.1.3c — code-walk: Denormalize + scalameta-driven emit of
 *  `src/generated/<crate>.rs`. */
class RustGenCodeWalkTest extends AnyFunSuite:

  private val emptyOpts = BackendOptions(
    baseDir = None, outputDir = None,
    optimizationLevel = 0, emitSourceMaps = false, emitAssertions = false,
    target = None, extra = Map.empty
  )

  /** Build a `NormalizedModule` from an `.ssc` source fragment.  The
   *  Parser+Normalize pipeline is the same one used by the CLI. */
  private def normalizeSsc(src: String): ir.NormalizedModule =
    val astModule = Parser.parse(src)
    Normalize(astModule)

  private def compileResult(src: String): CompileResult =
    new RustBackend().compile(normalizeSsc(src), emptyOpts)

  private def assets(src: String): Map[String, String] = compileResult(src) match
    case CompileResult.Segmented(segs) =>
      segs.collect { case Segment.Asset(n, b, _) => n -> new String(b, "UTF-8") }.toMap
    case other => fail(s"expected Segmented, got ${other.getClass.getSimpleName}")

  private def diagnostics(src: String): List[Diagnostic] = compileResult(src) match
    case CompileResult.Failed(ds) => ds
    case other => fail(s"expected Failed, got ${other.getClass.getSimpleName}")

  // ── hello-world emit ────────────────────────────────────────────────

  test("hello-world: emits one pub fn calling crate::runtime::_println"):
    val src =
      """# Hello
        |
        |```scalascript
        |def run(): Unit = println("Hello from Rust")
        |```
        |""".stripMargin
    val gen = assets(src).get("src/generated/ssc_program.rs")
      .getOrElse(fail("generated file missing"))
    assert(gen.contains("pub fn run() {"))
    assert(gen.contains("""crate::runtime::_println("Hello from Rust".to_string());"""))

  test("hello-world: print → crate::runtime::_print, Console.println → _println"):
    val src =
      """```scalascript
        |def first(): Unit = print("a")
        |def second(): Unit = Console.println("b")
        |```
        |""".stripMargin
    val gen = assets(src)("src/generated/ssc_program.rs")
    assert(gen.contains("""crate::runtime::_print("a".to_string());"""))
    assert(gen.contains("""crate::runtime::_println("b".to_string());"""))

  test("hello-world: escapes string-literal metacharacters in the emit"):
    val src =
      """```scalascript
        |def run(): Unit = println("hi \"world\"\n")
        |```
        |""".stripMargin
    val gen = assets(src)("src/generated/ssc_program.rs")
    assert(gen.contains("""crate::runtime::_println("hi \"world\"\n".to_string());"""))

  test("empty module: generated file still emitted (header only, no defs)"):
    val src =
      """# Nothing yet
        |
        |Just prose, no code blocks.
        |""".stripMargin
    val gen = assets(src)("src/generated/ssc_program.rs")
    assert(gen.startsWith("//! Generated by RustGen"))
    // No actual `pub fn …()` declaration line — only the comment that mentions one.
    val hasFnDecl = gen.linesIterator.exists(_.stripLeading.startsWith("pub fn "))
    assert(!hasFnDecl, s"unexpected pub fn declaration:\n$gen")

  // ── R.1 capability surface — anything outside hello-world fails ─────

  test("headOption without parentheses lowers, and does not become a Rust field"):
    // INBOX no-paren-list-method-becomes-a-field. `renderTerm`'s catch-all turns any no-paren
    // select into `q.field`, which is right for a case class and wrong for a Vec: rustc reported
    // `no field \`headOption\` on type \`Vec<String>\`` on the USER's line.
    val src =
      """```scalascript
        |def main(): Unit =
        |  val kept = ["a", "bb"].filter(r => r.length > 1)
        |  println(kept.headOption.getOrElse("-"))
        |main()
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains(".first().cloned()"), s"headOption did not lower:\n$g")
    assert(!g.contains(".headOption"), s"headOption survived as a field access:\n$g")

  test("a declared-Vector local initialized via `.empty` is still a known seq"):
    // `var elements: Vector[String] = Vector.empty` (uniml's `XmlScanner.scan`) has an rhs neither
    // `seqCtor` nor `rootedInSeq` recognise — `.empty` is not a `SeqMethods` conversion or a
    // `List(...)`/`Vector(...)` literal call — so the local was never recorded as a seq and
    // `elements.nonEmpty` fell to the no-paren-member refusal. The DECLARED type settles it.
    val src =
      """```scalascript
        |def main(): Unit =
        |  var elements: Vector[String] = Vector.empty
        |  elements = elements :+ "a"
        |  println(elements.nonEmpty)
        |main()
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("!elements.is_empty()"), s"nonEmpty did not lower:\n$g")

  test("Failed: an unlowered no-paren member on a List is refused, not emitted as a field"):
    // The half that matters more than `headOption` itself: the by-name refusal already existed
    // for method CALLS and could not reach a select, so the NEXT unlowered member would have
    // reached a user as `no field X on type Vec<…>` again.
    val src =
      """```scalascript
        |def main(): Unit =
        |  val kept = ["a", "bb"].filter(r => r.length > 1)
        |  println(kept.thereIsNoSuchMember)
        |main()
        |```
        |""".stripMargin
    val ds = diagnostics(src)
    assert(ds.exists {
      case Diagnostic.Generic(m, _) => m.contains("thereIsNoSuchMember") && m.contains("List")
      case _                        => false
    }, s"expected a named refusal, got: $ds")

  test("Failed: param with a non-primitive type yields a structured diagnostic"):
    // R.2 accepts primitives, enums, function types, and List/Vec/Set/Map (with
    // type args).  A truly-out-of-scope type still surfaces a diagnostic.
    // `Set[Long]` USED to be that example; it stopped being out-of-scope once `mapType`
    // learned to lower `Set` alongside `List`/`Vec` (see that case's own comment) — this
    // test kept asserting a premise the code had already moved past. `java.time.Instant`
    // has no case anywhere in `mapType` and is not expected to grow one.
    val src =
      """```scalascript
        |def greet(items: java.time.Instant): Unit = println("len")
        |```
        |""".stripMargin
    val ds = diagnostics(src)
    assert(ds.exists {
      case Diagnostic.Generic(m, _) => m.contains("greet") && m.contains("Instant")
      case _                        => false
    }, s"diags: $ds")

  test("Failed: unsupported expression in the body yields a structured diagnostic"):
    // R.2 lowers infix arithmetic, so use something genuinely out of scope. `throw` USED to be the
    // example here and stopped being out of scope on 2026-08-09, when the Rust lane learned
    // throw/try/catch — the second construct to vacate this slot. Whoever teaches this target
    // `finally` should expect to pick the third: the test asserts the SHAPE of a refusal, and it
    // needs one construct that still refuses.
    val src =
      """```scalascript
      |def run(): Unit =
      |  try println("a")
      |  catch case _ => println("b")
      |  finally println("c")
      |```
      |""".stripMargin
    val ds = diagnostics(src)
    assert(ds.nonEmpty, "expected at least one diagnostic")
    assert(ds.forall {
      case Diagnostic.Generic(_, src) => src.contains("rust")
      case _                          => false
    }, s"diags: $ds")

  // ── P0 benchmark gaps — numeric conversion + string concat ───────────

  test("toLong / toInt / toDouble / toFloat are rendered to Rust casts"):
    val src =
      """```scalascript
      |def toLongFn(n: Int): Long = n.toLong
      |def toIntFn(s: String): Int = s.trim.toInt
      |def toDoubleFn(n: Int): Double = n.toDouble
      |def toFloatFn(n: Int): Float = n.toFloat
      |```
      |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("(n as i64)"))
    // The String path is `_to_int`, not an inline parse: `parse::<i64>().unwrap_or(0)` answered 0
    // for a non-integer while `run` throws, so the semantics moved into the runtime helper where
    // there is one implementation of them (toint-on-a-non-integer-diverges).
    assert(g.contains("crate::runtime::_to_int("), s"toInt parse path missing in:\n$g")
    assert(g.contains("(n as f64)"), s"toDouble missing in $g")
    assert(g.contains("(n as f64)"), s"toFloat missing in $g")

  test("String + Long emits Rust format! for mixed-type concatenation"):
    val src =
      """```scalascript
      |def label(n: Long): String = "item-" + n
      |```
      |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("""format!("{}{}","""), s"format concat missing in:\n$g")
    assert(g.contains("\"item-\".to_string()"), s"string literal shape missing in:\n$g")

  // Reported from rozum: a String whose PROVENANCE the walker had not recorded fell out of the
  // string-concat path and emitted Rust's `String + String`, which needs `&str` on the right.
  // `val plain = "s1"` on the line above compiled, so the operand's origin was the whole difference.
  test("a String from Option.getOrElse still concatenates as a String"):
    val src =
      """```scalascript
      |def path(m: Map[String, String]): String =
      |  val stamp = m.get("stamp").getOrElse("")
      |  "/tmp" + "/" + stamp
      |```
      |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    // Asserts the concat PATH, not the placeholder count: since 2026-08-11 a chain of `+` flattens
    // into ONE `format!` with N placeholders instead of nesting one per operand (std/ui/theme.ssc
    // builds ~50 and rustc answered "recursion limit reached while expanding format!"). A
    // three-operand concat is `format!("{}{}{}", …)` now, and pinning `{}{}` here would be pinning
    // the nesting the flattening removed.
    assert(g.contains("""format!("""") && g.contains("stamp"),
      s"getOrElse operand left the concat path in:\n$g")
    assert(!g.contains(") + stamp"), s"emitted a raw Rust `+` on two Strings in:\n$g")

  // The same fact from the other direction: the return type is DECLARED, so reading it is not a
  // guess. Mirrors `defReturnsEither`, which already does this for Either-shaped returns.
  test("a call to a def declared : String still concatenates as a String"):
    val src =
      """```scalascript
      |def dir(): String = "/tmp"
      |def path(seg: String): String =
      |  val d = dir()
      |  d + "/" + seg
      |```
      |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("""format!("""") && !g.contains(" + "),
      s"declared-String return left the concat path in:\n$g")

  // ── uniml/xml diagnostic-reduction batch ──────────────────────────────

  test("a qualified pattern under an OBJECT NAMESPACE (not the trait's own name) still lowers"):
    // `uniml/xml`'s `Doc.scala` nests every variant inside `object Markup:` and writes
    // `case Markup.Text(chars) => …`, where `Markup` is the wrapping object, not `Node` (the
    // sealed trait `Text` extends). The existing qualified-pattern support only ever recognised
    // the qualifier being the TRAIT's own name (`Shape.Circle`); this is the object-namespaced
    // spelling, which needs the `ctx.ctorMap` fallback.
    val src =
      """```scalascript
        |object Wrap:
        |  sealed trait Shape
        |  case class Circle(r: Double) extends Shape
        |  case class Square(s: Double) extends Shape
        |
        |def area(s: Wrap.Shape): Double = s match
        |  case Wrap.Circle(r) => 3.14 * r * r
        |  case Wrap.Square(s) => s * s
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("Shape::Circle { r }"), s"qualified pattern did not lower:\n$g")

  test("f-interpolation with a printf-style conversion lowers to Rust's format spec"):
    val src =
      """```scalascript
        |def hex(codePoint: Long): String = f"U+$codePoint%04X"
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("""format!("U+{:04X}", codePoint)"""), s"f-interpolation did not lower:\n$g")

  test("throw of a standard-library exception built without `new` still lowers to a panic"):
    // `throw UnsupportedOperationException(msg)` (`uniml/xml`'s `Doc.scala`, `MarkupCodec.validate`'s
    // default body) — `throwPayload` only ever recognised `new X(msg)` or a known user-defined
    // ctor; a standard exception named by convention (`*Exception`, built WITHOUT `new`, which
    // Scala 3 allows) reached the ordinary call path instead and refused as an unknown callee.
    val src =
      """```scalascript
        |def bad(): Long = throw UnsupportedOperationException("nope")
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("""panic!("{}", "nope".to_string())"""), s"exception-by-name throw did not lower:\n$g")

  test("`<<` and a `|` pattern alternative both lower"):
    val src =
      """```scalascript
        |def widen(n: Long): Long = n << 10
        |def isQuote(c: Char): Boolean = c match
        |  case '\'' | '"' => true
        |  case _          => false
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("(n) << (10i64)") || g.contains("n << 10i64") || g.contains("<<"),
      s"`<<` did not lower:\n$g")
    assert(g.contains("|"), s"pattern alternative did not lower:\n$g")
