package scalascript.codegen.rust

import scalascript.backend.spi.*
import scalascript.ir
import scalascript.parser.Parser
import scalascript.transform.Normalize
import org.scalatest.funsuite.AnyFunSuite

/** Phase R.1.3c — code-walk: Denormalize + scalameta-driven emit of
 *  `src/generated/<crate>.rs`. */
class RustGenCodeWalkTest extends AnyFunSuite:

  private val emptyOpts = BackendOptions(
    baseDir = None, outputDir = None,
    optimizationLevel = 0, emitSourceMaps = false, emitAssertions = false,
    target = None, extra = Map.empty
  )

  /** Build a `NormalizedModule` from an `.ssc` source fragment.  The
   *  Parser+Normalize pipeline is the same one used by the CLI. */
  private def normalizeSsc(src: String): ir.NormalizedModule =
    val astModule = Parser.parse(src)
    Normalize(astModule)

  private def compileResult(src: String): CompileResult =
    new RustBackend().compile(normalizeSsc(src), emptyOpts)

  private def assets(src: String): Map[String, String] = compileResult(src) match
    case CompileResult.Segmented(segs) =>
      segs.collect { case Segment.Asset(n, b, _) => n -> new String(b, "UTF-8") }.toMap
    case other => fail(s"expected Segmented, got ${other.getClass.getSimpleName}")

  private def diagnostics(src: String): List[Diagnostic] = compileResult(src) match
    case CompileResult.Failed(ds) => ds
    case other => fail(s"expected Failed, got ${other.getClass.getSimpleName}")

  // ── hello-world emit ────────────────────────────────────────────────

  test("hello-world: emits one pub fn calling crate::runtime::_println"):
    val src =
      """# Hello
        |
        |```scalascript
        |def run(): Unit = println("Hello from Rust")
        |```
        |""".stripMargin
    val gen = assets(src).get("src/generated/ssc_program.rs")
      .getOrElse(fail("generated file missing"))
    assert(gen.contains("pub fn run() {"))
    assert(gen.contains("""crate::runtime::_println("Hello from Rust".to_string());"""))

  test("hello-world: print → crate::runtime::_print, Console.println → _println"):
    val src =
      """```scalascript
        |def first(): Unit = print("a")
        |def second(): Unit = Console.println("b")
        |```
        |""".stripMargin
    val gen = assets(src)("src/generated/ssc_program.rs")
    assert(gen.contains("""crate::runtime::_print("a".to_string());"""))
    assert(gen.contains("""crate::runtime::_println("b".to_string());"""))

  test("hello-world: escapes string-literal metacharacters in the emit"):
    val src =
      """```scalascript
        |def run(): Unit = println("hi \"world\"\n")
        |```
        |""".stripMargin
    val gen = assets(src)("src/generated/ssc_program.rs")
    assert(gen.contains("""crate::runtime::_println("hi \"world\"\n".to_string());"""))

  test("empty module: generated file still emitted (header only, no defs)"):
    val src =
      """# Nothing yet
        |
        |Just prose, no code blocks.
        |""".stripMargin
    val gen = assets(src)("src/generated/ssc_program.rs")
    assert(gen.startsWith("//! Generated by RustGen"))
    // No actual `pub fn …()` declaration line — only the comment that mentions one.
    val hasFnDecl = gen.linesIterator.exists(_.stripLeading.startsWith("pub fn "))
    assert(!hasFnDecl, s"unexpected pub fn declaration:\n$gen")

  // ── R.1 capability surface — anything outside hello-world fails ─────

  test("headOption without parentheses lowers, and does not become a Rust field"):
    // INBOX no-paren-list-method-becomes-a-field. `renderTerm`'s catch-all turns any no-paren
    // select into `q.field`, which is right for a case class and wrong for a Vec: rustc reported
    // `no field \`headOption\` on type \`Vec<String>\`` on the USER's line.
    val src =
      """```scalascript
        |def main(): Unit =
        |  val kept = ["a", "bb"].filter(r => r.length > 1)
        |  println(kept.headOption.getOrElse("-"))
        |main()
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains(".first().cloned()"), s"headOption did not lower:\n$g")
    assert(!g.contains(".headOption"), s"headOption survived as a field access:\n$g")

  test("a declared-Vector local initialized via `.empty` is still a known seq"):
    // `var elements: Vector[String] = Vector.empty` (uniml's `XmlScanner.scan`) has an rhs neither
    // `seqCtor` nor `rootedInSeq` recognise — `.empty` is not a `SeqMethods` conversion or a
    // `List(...)`/`Vector(...)` literal call — so the local was never recorded as a seq and
    // `elements.nonEmpty` fell to the no-paren-member refusal. The DECLARED type settles it.
    val src =
      """```scalascript
        |def main(): Unit =
        |  var elements: Vector[String] = Vector.empty
        |  elements = elements :+ "a"
        |  println(elements.nonEmpty)
        |main()
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("!elements.is_empty()"), s"nonEmpty did not lower:\n$g")

  test("Failed: an unlowered no-paren member on a List is refused, not emitted as a field"):
    // The half that matters more than `headOption` itself: the by-name refusal already existed
    // for method CALLS and could not reach a select, so the NEXT unlowered member would have
    // reached a user as `no field X on type Vec<…>` again.
    val src =
      """```scalascript
        |def main(): Unit =
        |  val kept = ["a", "bb"].filter(r => r.length > 1)
        |  println(kept.thereIsNoSuchMember)
        |main()
        |```
        |""".stripMargin
    val ds = diagnostics(src)
    assert(ds.exists {
      case Diagnostic.Generic(m, _) => m.contains("thereIsNoSuchMember") && m.contains("List")
      case _                        => false
    }, s"expected a named refusal, got: $ds")

  test("Failed: param with a non-primitive type yields a structured diagnostic"):
    // R.2 accepts primitives, enums, function types, and List/Vec/Set/Map (with
    // type args).  A truly-out-of-scope type still surfaces a diagnostic.
    // `Set[Long]` USED to be that example; it stopped being out-of-scope once `mapType`
    // learned to lower `Set` alongside `List`/`Vec` (see that case's own comment) — this
    // test kept asserting a premise the code had already moved past. `java.time.Instant`
    // has no case anywhere in `mapType` and is not expected to grow one.
    val src =
      """```scalascript
        |def greet(items: java.time.Instant): Unit = println("len")
        |```
        |""".stripMargin
    val ds = diagnostics(src)
    assert(ds.exists {
      case Diagnostic.Generic(m, _) => m.contains("greet") && m.contains("Instant")
      case _                        => false
    }, s"diags: $ds")

  test("Failed: unsupported expression in the body yields a structured diagnostic"):
    // R.2 lowers infix arithmetic, so use something genuinely out of scope. `throw` USED to be the
    // example here and stopped being out of scope on 2026-08-09, when the Rust lane learned
    // throw/try/catch — the second construct to vacate this slot. Whoever teaches this target
    // `finally` should expect to pick the third: the test asserts the SHAPE of a refusal, and it
    // needs one construct that still refuses.
    val src =
      """```scalascript
      |def run(): Unit =
      |  try println("a")
      |  catch case _ => println("b")
      |  finally println("c")
      |```
      |""".stripMargin
    val ds = diagnostics(src)
    assert(ds.nonEmpty, "expected at least one diagnostic")
    assert(ds.forall {
      case Diagnostic.Generic(_, src) => src.contains("rust")
      case _                          => false
    }, s"diags: $ds")

  // ── P0 benchmark gaps — numeric conversion + string concat ───────────

  test("toLong / toInt / toDouble / toFloat are rendered to Rust casts"):
    val src =
      """```scalascript
      |def toLongFn(n: Int): Long = n.toLong
      |def toIntFn(s: String): Int = s.trim.toInt
      |def toDoubleFn(n: Int): Double = n.toDouble
      |def toFloatFn(n: Int): Float = n.toFloat
      |```
      |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("(n as i64)"))
    // The String path is `_to_int`, not an inline parse: `parse::<i64>().unwrap_or(0)` answered 0
    // for a non-integer while `run` throws, so the semantics moved into the runtime helper where
    // there is one implementation of them (toint-on-a-non-integer-diverges).
    assert(g.contains("crate::runtime::_to_int("), s"toInt parse path missing in:\n$g")
    assert(g.contains("(n as f64)"), s"toDouble missing in $g")
    assert(g.contains("(n as f64)"), s"toFloat missing in $g")

  test("String + Long emits Rust format! for mixed-type concatenation"):
    val src =
      """```scalascript
      |def label(n: Long): String = "item-" + n
      |```
      |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("""format!("{}{}","""), s"format concat missing in:\n$g")
    assert(g.contains("\"item-\".to_string()"), s"string literal shape missing in:\n$g")

  // Reported from rozum: a String whose PROVENANCE the walker had not recorded fell out of the
  // string-concat path and emitted Rust's `String + String`, which needs `&str` on the right.
  // `val plain = "s1"` on the line above compiled, so the operand's origin was the whole difference.
  test("a String from Option.getOrElse still concatenates as a String"):
    val src =
      """```scalascript
      |def path(m: Map[String, String]): String =
      |  val stamp = m.get("stamp").getOrElse("")
      |  "/tmp" + "/" + stamp
      |```
      |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    // Asserts the concat PATH, not the placeholder count: since 2026-08-11 a chain of `+` flattens
    // into ONE `format!` with N placeholders instead of nesting one per operand (std/ui/theme.ssc
    // builds ~50 and rustc answered "recursion limit reached while expanding format!"). A
    // three-operand concat is `format!("{}{}{}", …)` now, and pinning `{}{}` here would be pinning
    // the nesting the flattening removed.
    assert(g.contains("""format!("""") && g.contains("stamp"),
      s"getOrElse operand left the concat path in:\n$g")
    assert(!g.contains(") + stamp"), s"emitted a raw Rust `+` on two Strings in:\n$g")

  // The same fact from the other direction: the return type is DECLARED, so reading it is not a
  // guess. Mirrors `defReturnsEither`, which already does this for Either-shaped returns.
  test("a call to a def declared : String still concatenates as a String"):
    val src =
      """```scalascript
      |def dir(): String = "/tmp"
      |def path(seg: String): String =
      |  val d = dir()
      |  d + "/" + seg
      |```
      |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("""format!("""") && !g.contains(" + "),
      s"declared-String return left the concat path in:\n$g")

  // ── uniml/xml diagnostic-reduction batch ──────────────────────────────

  test("a qualified pattern under an OBJECT NAMESPACE (not the trait's own name) still lowers"):
    // `uniml/xml`'s `Doc.scala` nests every variant inside `object Markup:` and writes
    // `case Markup.Text(chars) => …`, where `Markup` is the wrapping object, not `Node` (the
    // sealed trait `Text` extends). The existing qualified-pattern support only ever recognised
    // the qualifier being the TRAIT's own name (`Shape.Circle`); this is the object-namespaced
    // spelling, which needs the `ctx.ctorMap` fallback.
    val src =
      """```scalascript
        |object Wrap:
        |  sealed trait Shape
        |  case class Circle(r: Double) extends Shape
        |  case class Square(s: Double) extends Shape
        |
        |def area(s: Wrap.Shape): Double = s match
        |  case Wrap.Circle(r) => 3.14 * r * r
        |  case Wrap.Square(s) => s * s
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("Shape::Circle { r }"), s"qualified pattern did not lower:\n$g")

  test("f-interpolation with a printf-style conversion lowers to Rust's format spec"):
    val src =
      """```scalascript
        |def hex(codePoint: Long): String = f"U+$codePoint%04X"
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("""format!("U+{:04X}", codePoint)"""), s"f-interpolation did not lower:\n$g")

  test("throw of a standard-library exception built without `new` still lowers to a panic"):
    // `throw UnsupportedOperationException(msg)` (`uniml/xml`'s `Doc.scala`, `MarkupCodec.validate`'s
    // default body) — `throwPayload` only ever recognised `new X(msg)` or a known user-defined
    // ctor; a standard exception named by convention (`*Exception`, built WITHOUT `new`, which
    // Scala 3 allows) reached the ordinary call path instead and refused as an unknown callee.
    val src =
      """```scalascript
        |def bad(): Long = throw UnsupportedOperationException("nope")
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("""panic!("{}", "nope".to_string())"""), s"exception-by-name throw did not lower:\n$g")

  test("two defs sharing a bare name with DIFFERENT return types don't cross-contaminate"):
    // `_returnTypes` is keyed by bare def name, module-wide. `uniml/xml`'s `Doc.scala` has both
    // a `trait`'s `validate(...): List[X]` default method and a plain object's `validate(...):
    // Result` — sharing the name `validate`. Before this fix, whichever won the flat map (or the
    // dispatch-trait table, which was `++`-ed on UNCONDITIONALLY and could silently re-clobber a
    // collision the def-side check had already caught) answered for BOTH: a struct-returning
    // `validate`'s result got treated as a `Vec`, and reading a genuine field on it
    // (`r.complete`) refused as an unlowered List member.
    val src =
      """```scalascript
        |trait Codec:
        |  def validate(x: Long): List[Long] = List(x)
        |
        |case class Result(complete: Boolean)
        |
        |object Foo:
        |  def validate(x: Long): Result = Result(x > 0)
        |  def check(x: Long): Boolean =
        |    val r = validate(x)
        |    r.complete
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("r.complete"), s"struct field read after a name-colliding call did not lower:\n$g")

  test("a STRING-preserving chain rooted in a String param is still known to be a String"):
    // `value.drop(2).takeWhile(pred)` (`uniml/xml`'s `Doc.scala`'s `validatePi`, `value: String`)
    // is a String at every step, but `collectLocalStrings` only recognised `.toString`/`.trim`/
    // `.mkString`/`.substring` directly, and its qualifier chain bottoms out in a bare PARAM name
    // it had never seen (that set is seeded by the CALLER, after this function used to run) — so
    // `target.isEmpty` fell to the by-name-only "collection member" refusal, unable to tell this
    // was a String rather than a List.
    val src =
      """```scalascript
        |def firstWord(value: String): String =
        |  val target = value.drop(2).takeWhile(c => c != ' ')
        |  if target.isEmpty then "-" else target
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("target.is_empty()"), s"chained-String isEmpty did not lower:\n$g")

  test("`.nonEmpty` on an UNQUALIFIED call to a Vec-returning def lowers"):
    // `unresolvedReferences(result).nonEmpty` (`uniml/xml`'s `Doc.scala`'s `projectMarkup`) calls
    // a bare top-level def WITH an argument and immediately chains `.nonEmpty` — `isKnownVecReceiver`
    // only recognised a QUALIFIED zero-arg call (`recv.method()`) or a bare NAME already bound to a
    // known seq, neither of which this shape is.
    val src =
      """```scalascript
        |def evens(n: Long): List[Long] = List(n, n + 2)
        |def hasEvens(n: Long): Boolean = evens(n).nonEmpty
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("!evens(n).is_empty()") || g.contains(".is_empty()"),
      s"nonEmpty on an unqualified Vec-returning call did not lower:\n$g")
    assert(!g.contains(".nonEmpty"), s"nonEmpty survived unlowered:\n$g")

  test("`<<` and a `|` pattern alternative both lower"):
    val src =
      """```scalascript
        |def widen(n: Long): Long = n << 10
        |def isQuote(c: Char): Boolean = c match
        |  case '\'' | '"' => true
        |  case _          => false
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("(n) << (10i64)") || g.contains("n << 10i64") || g.contains("<<"),
      s"`<<` did not lower:\n$g")
    assert(g.contains("|"), s"pattern alternative did not lower:\n$g")

  test("a typed match-arm bind (`case e: Element =>`, BARE spelling) knows its own List fields"):
    // `case e: Element =>` (unqualified — the QUALIFIED spelling, `case e: Wrap.Element =>`,
    // already worked via a separate field-DESTRUCTURING mechanism that binds `children` directly
    // and never reads `e.children` at all) never populated `ctx.seqFields` for the bound name `e`
    // before this fix, so `e.children.isEmpty` (`Element.children: List[Node]`) fell to the
    // by-name-only "collection member" refusal — the typed bind's OWN ctor is known (`ctorMap`),
    // it just never got threaded through.
    val src =
      """```scalascript
        |sealed trait Node
        |case class Element(children: List[Node]) extends Node
        |case class Text(chars: String) extends Node
        |
        |def render(n: Node): String =
        |  n match
        |    case e: Element => if e.children.isEmpty then "<empty/>" else "<full/>"
        |    case Text(chars) => chars
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("e.children.is_empty()") || g.contains("children.is_empty()"),
      s"typed-bind field isEmpty did not lower:\n$g")

  test("`.isInstanceOf[T]` lowers to Rust's `matches!` against a known enum variant"):
    val src =
      """```scalascript
        |sealed trait Node
        |case class Element(children: List[Node]) extends Node
        |case class Text(chars: String) extends Node
        |
        |def hasElementChild(children: List[Node]): Boolean =
        |  children.exists(_.isInstanceOf[Element])
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("matches!(") && g.contains("Node::Element"), s"isInstanceOf did not lower:\n$g")

  test("`.mkString` without parens on a Vec chain lowers"):
    val src =
      """```scalascript
        |def joined(xs: List[String]): String = xs.map(s => s).mkString
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains(".join(\"\")"), s"no-paren mkString did not lower:\n$g")

  test("`.collect { case p if g => body }` lowers to `filter_map`"):
    val src =
      """```scalascript
        |case class Item(name: String, ok: Boolean)
        |def bad(items: List[Item]): List[String] =
        |  items.collect { case i if !i.ok => i.name }
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("filter_map") && g.contains("Some(") && g.contains("_ => None"),
      s"collect(pf) did not lower:\n$g")

  test("`.takeWhile { case ... }` (partial function) lowers to `take_while`"):
    val src =
      """```scalascript
        |def prefix(xs: List[Long]): List[Long] =
        |  xs.takeWhile {
        |    case n if n > 0 => true
        |    case _          => false
        |  }
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("take_while"), s"takeWhile(pf) did not lower:\n$g")

  test("`.sortBy(_.field)` lowers to `sort_by_key`"):
    val src =
      """```scalascript
        |case class Item(id: Long)
        |def ordered(xs: List[Item]): List[Item] = xs.sortBy(_.id)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("sort_by_key"), s"sortBy did not lower:\n$g")

  test("`.flatMap(Obj.member)` — an object-qualified function reference — lowers"):
    val src =
      """```scalascript
        |object Helper:
        |  def dup(n: Long): List[Long] = List(n, n)
        |
        |def widen(xs: List[Long]): List[Long] = xs.flatMap(Helper.dup)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("flat_map"), s"flatMap(Obj.member) did not lower:\n$g")
    assert(g.contains("dup("), s"the eta-expanded reference did not resolve to a call:\n$g")

  test("ListBuffer.empty + += + .toList lowers to a mutable Vec"):
    val src =
      """```scalascript
        |def build(n: Long): List[Long] =
        |  val buf = scala.collection.mutable.ListBuffer.empty[Long]
        |  buf += n
        |  buf += n + 1
        |  buf.toList
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("let mut buf") && g.contains("Vec::new()"), s"ListBuffer ctor did not lower:\n$g")
    assert(g.contains("buf.push("), s"+= did not lower to .push:\n$g")

  test("LinkedHashMap.empty + subscript-assign + .toMap lowers to a mutable HashMap"):
    val src =
      """```scalascript
        |def build(k: String, v: String): Map[String, String] =
        |  val m = scala.collection.mutable.LinkedHashMap.empty[String, String]
        |  m(k) = v
        |  m.toMap
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("let mut m") && g.contains("HashMap::new()"), s"LinkedHashMap ctor did not lower:\n$g")
    assert(g.contains("m.insert("), s"subscript-assign did not lower to .insert:\n$g")

  test("Vector.newBuilder + += + .result() lowers to a mutable Vec"):
    val src =
      """```scalascript
        |def build(n: Long): Vector[Long] =
        |  val b = Vector.newBuilder[Long]
        |  b += n
        |  b.result()
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("let mut b") && g.contains("Vec::new()"), s"Vector.newBuilder did not lower:\n$g")
    assert(g.contains("b.push("), s"+= did not lower to .push:\n$g")

  test("bare ArrayBuffer(...) constructor lowers to a mutable Vec literal"):
    val src =
      """```scalascript
        |import scala.collection.mutable.ArrayBuffer
        |def build(n: Long): List[Long] =
        |  val stack = ArrayBuffer(n, n + 1)
        |  stack.toList
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("vec!["), s"ArrayBuffer ctor did not lower:\n$g")

  test("HashSet.empty + .add lowers to a mutable HashSet + .insert"):
    val src =
      """```scalascript
        |def firstDup(xs: List[String]): Option[String] =
        |  val seen = scala.collection.mutable.HashSet.empty[String]
        |  xs.find(x => !seen.add(x))
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("let mut seen") && g.contains("HashSet::new()"), s"HashSet ctor did not lower:\n$g")
    assert(g.contains(".insert("), s".add did not lower to .insert:\n$g")

  test("ArrayBuffer.remove(i) lowers to Vec::remove"):
    val src =
      """```scalascript
        |import scala.collection.mutable.ArrayBuffer
        |def pop(n: Long): Long =
        |  val stack = ArrayBuffer(n, n + 1)
        |  stack.remove(stack.size - 1)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains(".remove(("), s".remove did not lower:\n$g")

  test("a genuinely mutable class (`class`, not `case class`) renders as struct + &mut self impl"):
    // `private final class Counter(label: String): private var count = 0; ...` (a MINIMAL stand-in
    // for `uniml/xml`'s `Doc.scala`'s hand-written recursive-descent `Parser` — a real stateful OOP
    // class, ~18 methods, none of it constructor-param data). Verified end-to-end via a real `cargo
    // build` on this exact shape before landing (see the commit message); this test pins the
    // generated TEXT shape so a regression here is caught without needing rustc.
    val src =
      """```scalascript
        |private final class Counter(label: String):
        |  private var count = 0
        |
        |  private def bump(): Unit =
        |    count += 1
        |
        |  def run(n: Long): Long =
        |    var i = 0L
        |    while i < n do
        |      bump()
        |      i += 1
        |    count
        |
        |def useIt(n: Long): Long =
        |  Counter("x").run(n)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("pub struct Counter") && g.contains("pub count: i64"),
      s"mutable-class struct did not render:\n$g")
    assert(g.contains("fn new(label: String) -> Counter"), s"::new ctor did not render:\n$g")
    assert(g.contains("pub fn bump(&mut self)") && g.contains("self.count += 1"),
      s"self-field write did not render:\n$g")
    assert(g.contains("pub fn run(&mut self, n: i64)") && g.contains("self.bump()"),
      s"self-method call did not render:\n$g")
    assert(g.contains("Counter::new(\"x\".to_string()).run(n)"),
      s"construct-then-call chain did not render:\n$g")

  test("a mutable class's non-writing methods render `&self`, not `&mut self`"):
    // E0499 regression: `selfMethodMut` originally marked EVERY mutable-class method `&mut self`
    // uniformly. `self.isNameStart(self.cur())` then failed to borrow-check (`cannot borrow
    // *self as mutable more than once at a time`) because BOTH the outer call and the argument
    // evaluation needed their own `&mut self` reservation — two-phase borrows only admit a
    // NESTED read, not a nested write, during the outer call's argument evaluation. `cur` and
    // `isNameStart` never write a field, so they must render `&self`; only `advance` (which
    // does write `pos`) may render `&mut self`. Mirrors `uniml/xml`'s real
    // `Parser.readName()`/`isNameStart(cur())` shape.
    val src =
      """```scalascript
        |private final class Scanner(src: String):
        |  private var pos = 0
        |
        |  private def cur(): Long = pos
        |
        |  private def isNameStart(c: Long): Boolean = c > 0
        |
        |  private def advance(): Unit =
        |    pos += 1
        |
        |  def readName(): Boolean =
        |    val ok = isNameStart(cur())
        |    advance()
        |    ok
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("pub fn cur(&self)"), s"non-writing method should render &self:\n$g")
    assert(g.contains("pub fn is_name_start(&self,") || g.contains("pub fn isNameStart(&self,"),
      s"non-writing method should render &self:\n$g")
    assert(g.contains("pub fn advance(&mut self)"), s"field-writing method should render &mut self:\n$g")
    assert(g.contains("pub fn read_name(&mut self)") || g.contains("pub fn readName(&mut self)"),
      s"a method calling a &mut self method should itself render &mut self:\n$g")

  test("`Option[(String, X)]` built via an if/else chain is still recognised as an Option"):
    // `isOptionExpr` had no case for `Term.If` at all — `val digits = if ... then Some(...) else
    // if ... then Some(...) else None` (`uniml/xml`'s `Doc.scala`'s `numericReferenceValue`) never
    // registered as an Option anywhere downstream, so `digits.flatMap { case (value, radix) => … }`
    // took no Option-aware path and the tuple-bound `value`'s String-ness (from the ORIGINAL `->`
    // construction) never reached the closure body at all.
    val src =
      """```scalascript
        |def parseIt(reference: String): Option[Long] =
        |  val digits =
        |    if reference.startsWith("&#x") then Some(reference.substring(3, reference.length - 1) -> 16L)
        |    else None
        |  digits.flatMap { case (value, radix) =>
        |    if value.nonEmpty then Some(radix) else None
        |  }
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("value.is_empty()") || g.contains("!value.is_empty()"),
      s"tuple-bound String param's nonEmpty did not lower:\n$g")
    assert(g.contains(".and_then("), s"Option.flatMap over an if/else-built local did not lower:\n$g")

  test("`startsWith(prefix, toffset)` (two-arg) lowers to a Unicode-safe runtime helper"):
    val src =
      """```scalascript
        |def isXmlDecl(src: String, pos: Long): Boolean = src.startsWith("<?xml", pos)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("crate::runtime::_str_starts_with_at("), s"two-arg startsWith did not lower:\n$g")

  test("a chained `sb.append(a).append(b)` flattens into one statement sequence"):
    val src =
      """```scalascript
        |def build(): String =
        |  val sb = StringBuilder()
        |  sb.append('<').append("tag").append('>')
        |  sb.toString
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("sb.push(") && g.contains("sb.push_str("), s"chained append did not flatten:\n$g")
    assert(!g.contains(").append("), s"a raw .append survived unlowered:\n$g")

  test("a field read on a value typed as a SPECIFIC enum variant lowers via a single-arm match"):
    // `document.root` where `document: Wrap.Doc` (object-namespaced, `uniml/xml`'s own spelling —
    // a case class extending a shared sealed trait, reached via `case Right(document) => …`, never
    // a `match` arm that itself DESTRUCTURES `Doc`'s own fields) — Rust has no unchecked `.field`
    // access on an enum; this needs a match to extract the one field.
    val src =
      """```scalascript
        |object Wrap:
        |  sealed trait Node
        |  case class Doc(root: Long, docType: Option[Long]) extends Node
        |  case class Other(x: Long) extends Node
        |
        |def tryParse(x: Long): Either[Long, Wrap.Doc] = if x > 0 then Right(Wrap.Doc(x, None)) else Left(x)
        |
        |def readRoot(x: Long): Long = tryParse(x) match
        |  case Left(e) => e
        |  case Right(document) => document.root
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("match &") && g.contains("Node::Doc"), s"enum-variant field read did not lower:\n$g")

  test("`.copy(field = value)` on a value typed as a SPECIFIC enum variant rebuilds via match"):
    val src =
      """```scalascript
        |object Wrap:
        |  sealed trait Node
        |  case class Doc(root: Long, docType: Option[Long]) extends Node
        |  case class Other(x: Long) extends Node
        |
        |def tryParse(x: Long): Either[Long, Wrap.Doc] = if x > 0 then Right(Wrap.Doc(x, None)) else Left(x)
        |
        |def withRoot(x: Long, n: Long): Long = tryParse(x) match
        |  case Left(e) => e
        |  case Right(document) => document.copy(root = n).root
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("match &") && g.contains("Node::Doc"), s"enum-variant .copy did not lower:\n$g")
    assert(!g.contains("__copy_"), s"a dangling __copy_ binder leaked into the output:\n$g")

  test("`either.left.map(f)` lowers, transforming Left and passing Right through"):
    val src =
      """```scalascript
        |def tryParse(x: Long): Either[Long, String] = if x > 0 then Right(x.toString) else Left(x)
        |def widen(x: Long): Either[String, String] = tryParse(x).left.map(n => n.toString)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("Either::Left(") && g.contains("Either::Right(v) => Either::Right(v)"),
      s".left.map did not lower:\n$g")

  test("`s.forall(p)` / `s.exists(p)` on a String lower via `.chars()`"):
    val src =
      """```scalascript
        |def isHexDigit(c: Long): Boolean = c >= 48
        |def allHex(s: String): Boolean = s.forall(isHexDigit)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains(".chars().all("), s"String.forall did not lower:\n$g")

  test("`opt.forall(p)` lowers to `.map_or(true, p)`"):
    val src =
      """```scalascript
        |def isLegal(n: Long): Boolean = n >= 0
        |def parseIt(s: String): Option[Long] = if s.nonEmpty then Some(s.length) else None
        |def check(s: String): Boolean = parseIt(s).forall(isLegal)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains(".map_or(true, "), s"Option.forall did not lower:\n$g")

  test("`s.indexOf(needle, fromIndex)` (two-arg, String or Char needle) lowers"):
    val src =
      """```scalascript
        |def findTag(s: String, from: Long): Long = s.indexOf("?>", from)
        |def findChar(s: String, from: Long): Long = s.indexOf(';', from)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("crate::runtime::_str_index_of_from("), s"two-arg indexOf did not lower:\n$g")

  test("a Map-typed `var` (not just `val`) is tracked, so `.get`/`.contains` lower correctly"):
    // `var bindings = inherited` (`uniml/xml`'s `Doc.scala`'s `validateNamespaces`/
    // `resolveElement`) — `collectLocalMaps`'s walk had a `Defn.Val` case but no `Defn.Var` one.
    val src =
      """```scalascript
        |def useIt(inherited: Map[String, String], key: String): Option[String] =
        |  var bindings = inherited
        |  Some(key).flatMap(bindings.get)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("bindings.get(&__k)"), s"Map var's .get-as-value did not lower:\n$g")

  test("`Integer.parseInt(s, radix)` and `math.max(a, b)` lower"):
    val src =
      """```scalascript
        |def parseHex(s: String): Long = Integer.parseInt(s, 16)
        |def clampLow(n: Long): Long = math.max(1, n)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("i64::from_str_radix("), s"Integer.parseInt did not lower:\n$g")
    assert(g.contains(").max("), s"math.max did not lower:\n$g")

  test("`Nothing` maps to Rust's `!`, so a diverging call unifies with either if/else branch"):
    // `def err(msg: String): Nothing = throw ...; if cond then err(msg) else ()` (`uniml/xml`'s
    // `Doc.scala`'s `Parser`) — `Nothing` had no case in `mapType` at all and fell to the
    // unknown-type-name `i64` default, so `err(...)`'s call-site type was a CONCRETE `i64` instead
    // of coercing to whatever the branch needed — `error[E0308]: if and else have incompatible
    // types` against the `()` sibling branch.
    val src =
      """```scalascript
        |def err(msg: String): Nothing = throw new RuntimeException(msg)
        |def maybeErr(cond: Boolean): Unit = if cond then err("bad") else ()
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("-> !"), s"Nothing did not map to !:\n$g")

  test("a positional ctor destructure (`case Ctor(a, b) =>`) types each field from the ctor"):
    // `case PI(target, data) => data.nonEmpty` (`uniml/xml`'s `Doc.scala`'s `serializeNode`,
    // shape simplified here) — `data`'s type comes from `PI`'s OWN declared field type
    // (`data: String`), never threaded to `ctx.localStrings` before this fix for a BARE
    // (non-`@`-bound) positional destructure.
    val src =
      """```scalascript
        |sealed trait Node
        |case class PI(target: String, data: String) extends Node
        |case class Text(chars: String) extends Node
        |
        |def render(n: Node): String = n match
        |  case PI(target, data) => if data.nonEmpty then data else target
        |  case Text(chars) => chars
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("data.is_empty()") || g.contains("!data.is_empty()"),
      s"positional-destructure field isEmpty/nonEmpty did not lower:\n$g")
