package scalascript.codegen.rust

import scalascript.backend.spi.*
import scalascript.ir
import scalascript.parser.Parser
import scalascript.transform.Normalize
import org.scalatest.funsuite.AnyFunSuite

/** Phase R.1.3c — code-walk: Denormalize + scalameta-driven emit of
 *  `src/generated/<crate>.rs`. */
class RustGenCodeWalkTest extends AnyFunSuite:

  private val emptyOpts = BackendOptions(
    baseDir = None, outputDir = None,
    optimizationLevel = 0, emitSourceMaps = false, emitAssertions = false,
    target = None, extra = Map.empty
  )

  /** Build a `NormalizedModule` from an `.ssc` source fragment.  The
   *  Parser+Normalize pipeline is the same one used by the CLI. */
  private def normalizeSsc(src: String): ir.NormalizedModule =
    val astModule = Parser.parse(src)
    Normalize(astModule)

  private def compileResult(src: String): CompileResult =
    new RustBackend().compile(normalizeSsc(src), emptyOpts)

  private def assets(src: String): Map[String, String] = compileResult(src) match
    case CompileResult.Segmented(segs) =>
      segs.collect { case Segment.Asset(n, b, _) => n -> new String(b, "UTF-8") }.toMap
    case other => fail(s"expected Segmented, got ${other.getClass.getSimpleName}")

  private def diagnostics(src: String): List[Diagnostic] = compileResult(src) match
    case CompileResult.Failed(ds) => ds
    case other => fail(s"expected Failed, got ${other.getClass.getSimpleName}")

  // ── hello-world emit ────────────────────────────────────────────────

  test("hello-world: emits one pub fn calling crate::runtime::_println"):
    val src =
      """# Hello
        |
        |```scalascript
        |def run(): Unit = println("Hello from Rust")
        |```
        |""".stripMargin
    val gen = assets(src).get("src/generated/ssc_program.rs")
      .getOrElse(fail("generated file missing"))
    assert(gen.contains("pub fn run() {"))
    assert(gen.contains("""crate::runtime::_println("Hello from Rust".to_string());"""))

  test("hello-world: print → crate::runtime::_print, Console.println → _println"):
    val src =
      """```scalascript
        |def first(): Unit = print("a")
        |def second(): Unit = Console.println("b")
        |```
        |""".stripMargin
    val gen = assets(src)("src/generated/ssc_program.rs")
    assert(gen.contains("""crate::runtime::_print("a".to_string());"""))
    assert(gen.contains("""crate::runtime::_println("b".to_string());"""))

  test("hello-world: escapes string-literal metacharacters in the emit"):
    val src =
      """```scalascript
        |def run(): Unit = println("hi \"world\"\n")
        |```
        |""".stripMargin
    val gen = assets(src)("src/generated/ssc_program.rs")
    assert(gen.contains("""crate::runtime::_println("hi \"world\"\n".to_string());"""))

  test("empty module: generated file still emitted (header only, no defs)"):
    val src =
      """# Nothing yet
        |
        |Just prose, no code blocks.
        |""".stripMargin
    val gen = assets(src)("src/generated/ssc_program.rs")
    assert(gen.startsWith("//! Generated by RustGen"))
    // No actual `pub fn …()` declaration line — only the comment that mentions one.
    val hasFnDecl = gen.linesIterator.exists(_.stripLeading.startsWith("pub fn "))
    assert(!hasFnDecl, s"unexpected pub fn declaration:\n$gen")

  // ── R.1 capability surface — anything outside hello-world fails ─────

  test("headOption without parentheses lowers, and does not become a Rust field"):
    // INBOX no-paren-list-method-becomes-a-field. `renderTerm`'s catch-all turns any no-paren
    // select into `q.field`, which is right for a case class and wrong for a Vec: rustc reported
    // `no field \`headOption\` on type \`Vec<String>\`` on the USER's line.
    val src =
      """```scalascript
        |def main(): Unit =
        |  val kept = ["a", "bb"].filter(r => r.length > 1)
        |  println(kept.headOption.getOrElse("-"))
        |main()
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains(".first().cloned()"), s"headOption did not lower:\n$g")
    assert(!g.contains(".headOption"), s"headOption survived as a field access:\n$g")

  test("a declared-Vector local initialized via `.empty` is still a known seq"):
    // `var elements: Vector[String] = Vector.empty` (uniml's `XmlScanner.scan`) has an rhs neither
    // `seqCtor` nor `rootedInSeq` recognise — `.empty` is not a `SeqMethods` conversion or a
    // `List(...)`/`Vector(...)` literal call — so the local was never recorded as a seq and
    // `elements.nonEmpty` fell to the no-paren-member refusal. The DECLARED type settles it.
    val src =
      """```scalascript
        |def main(): Unit =
        |  var elements: Vector[String] = Vector.empty
        |  elements = elements :+ "a"
        |  println(elements.nonEmpty)
        |main()
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("!elements.is_empty()"), s"nonEmpty did not lower:\n$g")

  test("Failed: an unlowered no-paren member on a List is refused, not emitted as a field"):
    // The half that matters more than `headOption` itself: the by-name refusal already existed
    // for method CALLS and could not reach a select, so the NEXT unlowered member would have
    // reached a user as `no field X on type Vec<…>` again.
    val src =
      """```scalascript
        |def main(): Unit =
        |  val kept = ["a", "bb"].filter(r => r.length > 1)
        |  println(kept.thereIsNoSuchMember)
        |main()
        |```
        |""".stripMargin
    val ds = diagnostics(src)
    assert(ds.exists {
      case Diagnostic.Generic(m, _) => m.contains("thereIsNoSuchMember") && m.contains("List")
      case _                        => false
    }, s"expected a named refusal, got: $ds")

  test("Failed: param with a non-primitive type yields a structured diagnostic"):
    // R.2 accepts primitives, enums, function types, and List/Vec/Set/Map (with
    // type args).  A truly-out-of-scope type still surfaces a diagnostic.
    // `Set[Long]` USED to be that example; it stopped being out-of-scope once `mapType`
    // learned to lower `Set` alongside `List`/`Vec` (see that case's own comment) — this
    // test kept asserting a premise the code had already moved past. `java.time.Instant`
    // has no case anywhere in `mapType` and is not expected to grow one.
    val src =
      """```scalascript
        |def greet(items: java.time.Instant): Unit = println("len")
        |```
        |""".stripMargin
    val ds = diagnostics(src)
    assert(ds.exists {
      case Diagnostic.Generic(m, _) => m.contains("greet") && m.contains("Instant")
      case _                        => false
    }, s"diags: $ds")

  test("Failed: unsupported expression in the body yields a structured diagnostic"):
    // R.2 lowers infix arithmetic, so use something genuinely out of scope. `throw` USED to be the
    // example here and stopped being out of scope on 2026-08-09, when the Rust lane learned
    // throw/try/catch — the second construct to vacate this slot. Whoever teaches this target
    // `finally` should expect to pick the third: the test asserts the SHAPE of a refusal, and it
    // needs one construct that still refuses.
    val src =
      """```scalascript
      |def run(): Unit =
      |  try println("a")
      |  catch case _ => println("b")
      |  finally println("c")
      |```
      |""".stripMargin
    val ds = diagnostics(src)
    assert(ds.nonEmpty, "expected at least one diagnostic")
    assert(ds.forall {
      case Diagnostic.Generic(_, src) => src.contains("rust")
      case _                          => false
    }, s"diags: $ds")

  // ── P0 benchmark gaps — numeric conversion + string concat ───────────

  test("toLong / toInt / toDouble / toFloat are rendered to Rust casts"):
    val src =
      """```scalascript
      |def toLongFn(n: Int): Long = n.toLong
      |def toIntFn(s: String): Int = s.trim.toInt
      |def toDoubleFn(n: Int): Double = n.toDouble
      |def toFloatFn(n: Int): Float = n.toFloat
      |```
      |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("(n as i64)"))
    // The String path is `_to_int`, not an inline parse: `parse::<i64>().unwrap_or(0)` answered 0
    // for a non-integer while `run` throws, so the semantics moved into the runtime helper where
    // there is one implementation of them (toint-on-a-non-integer-diverges).
    assert(g.contains("crate::runtime::_to_int("), s"toInt parse path missing in:\n$g")
    assert(g.contains("(n as f64)"), s"toDouble missing in $g")
    assert(g.contains("(n as f64)"), s"toFloat missing in $g")

  test("String + Long emits Rust format! for mixed-type concatenation"):
    val src =
      """```scalascript
      |def label(n: Long): String = "item-" + n
      |```
      |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("""format!("{}{}","""), s"format concat missing in:\n$g")
    assert(g.contains("\"item-\".to_string()"), s"string literal shape missing in:\n$g")

  // Reported from rozum: a String whose PROVENANCE the walker had not recorded fell out of the
  // string-concat path and emitted Rust's `String + String`, which needs `&str` on the right.
  // `val plain = "s1"` on the line above compiled, so the operand's origin was the whole difference.
  test("a String from Option.getOrElse still concatenates as a String"):
    val src =
      """```scalascript
      |def path(m: Map[String, String]): String =
      |  val stamp = m.get("stamp").getOrElse("")
      |  "/tmp" + "/" + stamp
      |```
      |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    // Asserts the concat PATH, not the placeholder count: since 2026-08-11 a chain of `+` flattens
    // into ONE `format!` with N placeholders instead of nesting one per operand (std/ui/theme.ssc
    // builds ~50 and rustc answered "recursion limit reached while expanding format!"). A
    // three-operand concat is `format!("{}{}{}", …)` now, and pinning `{}{}` here would be pinning
    // the nesting the flattening removed.
    assert(g.contains("""format!("""") && g.contains("stamp"),
      s"getOrElse operand left the concat path in:\n$g")
    assert(!g.contains(") + stamp"), s"emitted a raw Rust `+` on two Strings in:\n$g")

  // The same fact from the other direction: the return type is DECLARED, so reading it is not a
  // guess. Mirrors `defReturnsEither`, which already does this for Either-shaped returns.
  test("a call to a def declared : String still concatenates as a String"):
    val src =
      """```scalascript
      |def dir(): String = "/tmp"
      |def path(seg: String): String =
      |  val d = dir()
      |  d + "/" + seg
      |```
      |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("""format!("""") && !g.contains(" + "),
      s"declared-String return left the concat path in:\n$g")

  // ── uniml/xml diagnostic-reduction batch ──────────────────────────────

  test("a qualified pattern under an OBJECT NAMESPACE (not the trait's own name) still lowers"):
    // `uniml/xml`'s `Doc.scala` nests every variant inside `object Markup:` and writes
    // `case Markup.Text(chars) => …`, where `Markup` is the wrapping object, not `Node` (the
    // sealed trait `Text` extends). The existing qualified-pattern support only ever recognised
    // the qualifier being the TRAIT's own name (`Shape.Circle`); this is the object-namespaced
    // spelling, which needs the `ctx.ctorMap` fallback.
    val src =
      """```scalascript
        |object Wrap:
        |  sealed trait Shape
        |  case class Circle(r: Double) extends Shape
        |  case class Square(s: Double) extends Shape
        |
        |def area(s: Wrap.Shape): Double = s match
        |  case Wrap.Circle(r) => 3.14 * r * r
        |  case Wrap.Square(s) => s * s
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("Shape::Circle { r }"), s"qualified pattern did not lower:\n$g")

  test("f-interpolation with a printf-style conversion lowers to Rust's format spec"):
    val src =
      """```scalascript
        |def hex(codePoint: Long): String = f"U+$codePoint%04X"
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("""format!("U+{:04X}", codePoint)"""), s"f-interpolation did not lower:\n$g")

  test("throw of a standard-library exception built without `new` still lowers to a panic"):
    // `throw UnsupportedOperationException(msg)` (`uniml/xml`'s `Doc.scala`, `MarkupCodec.validate`'s
    // default body) — `throwPayload` only ever recognised `new X(msg)` or a known user-defined
    // ctor; a standard exception named by convention (`*Exception`, built WITHOUT `new`, which
    // Scala 3 allows) reached the ordinary call path instead and refused as an unknown callee.
    val src =
      """```scalascript
        |def bad(): Long = throw UnsupportedOperationException("nope")
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("""panic!("{}", "nope".to_string())"""), s"exception-by-name throw did not lower:\n$g")

  test("two defs sharing a bare name with DIFFERENT return types don't cross-contaminate"):
    // `_returnTypes` is keyed by bare def name, module-wide. `uniml/xml`'s `Doc.scala` has both
    // a `trait`'s `validate(...): List[X]` default method and a plain object's `validate(...):
    // Result` — sharing the name `validate`. Before this fix, whichever won the flat map (or the
    // dispatch-trait table, which was `++`-ed on UNCONDITIONALLY and could silently re-clobber a
    // collision the def-side check had already caught) answered for BOTH: a struct-returning
    // `validate`'s result got treated as a `Vec`, and reading a genuine field on it
    // (`r.complete`) refused as an unlowered List member.
    val src =
      """```scalascript
        |trait Codec:
        |  def validate(x: Long): List[Long] = List(x)
        |
        |case class Result(complete: Boolean)
        |
        |object Foo:
        |  def validate(x: Long): Result = Result(x > 0)
        |  def check(x: Long): Boolean =
        |    val r = validate(x)
        |    r.complete
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("r.complete"), s"struct field read after a name-colliding call did not lower:\n$g")

  test("a dispatch trait's default method reads a SIBLING abstract member bare, as `self.member()`"):
    // `trait MarkupCodec: def id: String; def validate(...) = throw …(s"…codec '$id'")`
    // (`uniml/xml`'s `Doc.scala`) — Scala's implicit `this.id` inside a trait DEFAULT method,
    // referencing another (abstract) member of the SAME trait with no `this.`/`self.` prefix. The
    // default body's own `Ctx` carried no `selfMethods` at all, so `id` fell to the bare-name
    // fallback and rustc said `cannot find value id in this scope` — a name one member declares,
    // unreachable from the very next member's own default body.
    val src =
      """```scalascript
        |trait Codec:
        |  def id: String
        |  def describe(): String = "codec: " + id
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("self.id()"), s"sibling abstract member read bare should become self.id():\n$g")

  test("a STRING-preserving chain rooted in a String param is still known to be a String"):
    // `value.drop(2).takeWhile(pred)` (`uniml/xml`'s `Doc.scala`'s `validatePi`, `value: String`)
    // is a String at every step, but `collectLocalStrings` only recognised `.toString`/`.trim`/
    // `.mkString`/`.substring` directly, and its qualifier chain bottoms out in a bare PARAM name
    // it had never seen (that set is seeded by the CALLER, after this function used to run) — so
    // `target.isEmpty` fell to the by-name-only "collection member" refusal, unable to tell this
    // was a String rather than a List.
    val src =
      """```scalascript
        |def firstWord(value: String): String =
        |  val target = value.drop(2).takeWhile(c => c != ' ')
        |  if target.isEmpty then "-" else target
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("target.is_empty()"), s"chained-String isEmpty did not lower:\n$g")

  test("`.nonEmpty` on an UNQUALIFIED call to a Vec-returning def lowers"):
    // `unresolvedReferences(result).nonEmpty` (`uniml/xml`'s `Doc.scala`'s `projectMarkup`) calls
    // a bare top-level def WITH an argument and immediately chains `.nonEmpty` — `isKnownVecReceiver`
    // only recognised a QUALIFIED zero-arg call (`recv.method()`) or a bare NAME already bound to a
    // known seq, neither of which this shape is.
    val src =
      """```scalascript
        |def evens(n: Long): List[Long] = List(n, n + 2)
        |def hasEvens(n: Long): Boolean = evens(n).nonEmpty
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("!evens(n).is_empty()") || g.contains(".is_empty()"),
      s"nonEmpty on an unqualified Vec-returning call did not lower:\n$g")
    assert(!g.contains(".nonEmpty"), s"nonEmpty survived unlowered:\n$g")

  test("`<<` and a `|` pattern alternative both lower"):
    val src =
      """```scalascript
        |def widen(n: Long): Long = n << 10
        |def isQuote(c: Char): Boolean = c match
        |  case '\'' | '"' => true
        |  case _          => false
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("(n) << (10i64)") || g.contains("n << 10i64") || g.contains("<<"),
      s"`<<` did not lower:\n$g")
    assert(g.contains("|"), s"pattern alternative did not lower:\n$g")

  test("a typed match-arm bind (`case e: Element =>`, BARE spelling) knows its own List fields"):
    // `case e: Element =>` (unqualified — the QUALIFIED spelling, `case e: Wrap.Element =>`,
    // already worked via a separate field-DESTRUCTURING mechanism that binds `children` directly
    // and never reads `e.children` at all) never populated `ctx.seqFields` for the bound name `e`
    // before this fix, so `e.children.isEmpty` (`Element.children: List[Node]`) fell to the
    // by-name-only "collection member" refusal — the typed bind's OWN ctor is known (`ctorMap`),
    // it just never got threaded through.
    val src =
      """```scalascript
        |sealed trait Node
        |case class Element(children: List[Node]) extends Node
        |case class Text(chars: String) extends Node
        |
        |def render(n: Node): String =
        |  n match
        |    case e: Element => if e.children.isEmpty then "<empty/>" else "<full/>"
        |    case Text(chars) => chars
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("e.children.is_empty()") || g.contains("children.is_empty()"),
      s"typed-bind field isEmpty did not lower:\n$g")

  test("`.isInstanceOf[T]` lowers to Rust's `matches!` against a known enum variant"):
    val src =
      """```scalascript
        |sealed trait Node
        |case class Element(children: List[Node]) extends Node
        |case class Text(chars: String) extends Node
        |
        |def hasElementChild(children: List[Node]): Boolean =
        |  children.exists(_.isInstanceOf[Element])
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("matches!(") && g.contains("Node::Element"), s"isInstanceOf did not lower:\n$g")

  test("`.mkString` without parens on a Vec chain lowers"):
    val src =
      """```scalascript
        |def joined(xs: List[String]): String = xs.map(s => s).mkString
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains(".join(\"\")"), s"no-paren mkString did not lower:\n$g")

  test("`.collect { case p if g => body }` lowers to `filter_map`"):
    val src =
      """```scalascript
        |case class Item(name: String, ok: Boolean)
        |def bad(items: List[Item]): List[String] =
        |  items.collect { case i if !i.ok => i.name }
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("filter_map") && g.contains("Some(") && g.contains("_ => None"),
      s"collect(pf) did not lower:\n$g")

  test("`.takeWhile { case ... }` (partial function) lowers to `take_while`"):
    val src =
      """```scalascript
        |def prefix(xs: List[Long]): List[Long] =
        |  xs.takeWhile {
        |    case n if n > 0 => true
        |    case _          => false
        |  }
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("take_while"), s"takeWhile(pf) did not lower:\n$g")

  test("`.sortBy(_.field)` lowers to `sort_by_key`"):
    val src =
      """```scalascript
        |case class Item(id: Long)
        |def ordered(xs: List[Item]): List[Item] = xs.sortBy(_.id)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("sort_by_key"), s"sortBy did not lower:\n$g")

  test("`.flatMap(Obj.member)` — an object-qualified function reference — lowers"):
    val src =
      """```scalascript
        |object Helper:
        |  def dup(n: Long): List[Long] = List(n, n)
        |
        |def widen(xs: List[Long]): List[Long] = xs.flatMap(Helper.dup)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("flat_map"), s"flatMap(Obj.member) did not lower:\n$g")
    assert(g.contains("dup("), s"the eta-expanded reference did not resolve to a call:\n$g")

  test("ListBuffer.empty + += + .toList lowers to a mutable Vec"):
    val src =
      """```scalascript
        |def build(n: Long): List[Long] =
        |  val buf = scala.collection.mutable.ListBuffer.empty[Long]
        |  buf += n
        |  buf += n + 1
        |  buf.toList
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("let mut buf") && g.contains("Vec::new()"), s"ListBuffer ctor did not lower:\n$g")
    assert(g.contains("buf.push("), s"+= did not lower to .push:\n$g")

  test("LinkedHashMap.empty + subscript-assign + .toMap lowers to a mutable HashMap"):
    val src =
      """```scalascript
        |def build(k: String, v: String): Map[String, String] =
        |  val m = scala.collection.mutable.LinkedHashMap.empty[String, String]
        |  m(k) = v
        |  m.toMap
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("let mut m") && g.contains("HashMap::new()"), s"LinkedHashMap ctor did not lower:\n$g")
    assert(g.contains("m.insert("), s"subscript-assign did not lower to .insert:\n$g")

  test("Vector.newBuilder + += + .result() lowers to a mutable Vec"):
    val src =
      """```scalascript
        |def build(n: Long): Vector[Long] =
        |  val b = Vector.newBuilder[Long]
        |  b += n
        |  b.result()
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("let mut b") && g.contains("Vec::new()"), s"Vector.newBuilder did not lower:\n$g")
    assert(g.contains("b.push("), s"+= did not lower to .push:\n$g")

  test("bare ArrayBuffer(...) constructor lowers to a mutable Vec literal"):
    val src =
      """```scalascript
        |import scala.collection.mutable.ArrayBuffer
        |def build(n: Long): List[Long] =
        |  val stack = ArrayBuffer(n, n + 1)
        |  stack.toList
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("vec!["), s"ArrayBuffer ctor did not lower:\n$g")

  test("HashSet.empty + .add lowers to a mutable HashSet + .insert"):
    val src =
      """```scalascript
        |def firstDup(xs: List[String]): Option[String] =
        |  val seen = scala.collection.mutable.HashSet.empty[String]
        |  xs.find(x => !seen.add(x))
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("let mut seen") && g.contains("HashSet::new()"), s"HashSet ctor did not lower:\n$g")
    assert(g.contains(".insert("), s".add did not lower to .insert:\n$g")

  test("ArrayBuffer.remove(i) lowers to Vec::remove"):
    val src =
      """```scalascript
        |import scala.collection.mutable.ArrayBuffer
        |def pop(n: Long): Long =
        |  val stack = ArrayBuffer(n, n + 1)
        |  stack.remove(stack.size - 1)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains(".remove(("), s".remove did not lower:\n$g")

  test("a genuinely mutable class (`class`, not `case class`) renders as struct + &mut self impl"):
    // `private final class Counter(label: String): private var count = 0; ...` (a MINIMAL stand-in
    // for `uniml/xml`'s `Doc.scala`'s hand-written recursive-descent `Parser` — a real stateful OOP
    // class, ~18 methods, none of it constructor-param data). Verified end-to-end via a real `cargo
    // build` on this exact shape before landing (see the commit message); this test pins the
    // generated TEXT shape so a regression here is caught without needing rustc.
    val src =
      """```scalascript
        |private final class Counter(label: String):
        |  private var count = 0
        |
        |  private def bump(): Unit =
        |    count += 1
        |
        |  def run(n: Long): Long =
        |    var i = 0L
        |    while i < n do
        |      bump()
        |      i += 1
        |    count
        |
        |def useIt(n: Long): Long =
        |  Counter("x").run(n)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("pub struct Counter") && g.contains("pub count: i64"),
      s"mutable-class struct did not render:\n$g")
    assert(g.contains("fn new(label: String) -> Counter"), s"::new ctor did not render:\n$g")
    assert(g.contains("pub fn bump(&mut self)") && g.contains("self.count += 1"),
      s"self-field write did not render:\n$g")
    assert(g.contains("pub fn run(&mut self, n: i64)") && g.contains("self.bump()"),
      s"self-method call did not render:\n$g")
    assert(g.contains("Counter::new(\"x\".to_string()).run(n)"),
      s"construct-then-call chain did not render:\n$g")

  test("a mutable class's non-writing methods render `&self`, not `&mut self`"):
    // E0499 regression: `selfMethodMut` originally marked EVERY mutable-class method `&mut self`
    // uniformly. `self.isNameStart(self.cur())` then failed to borrow-check (`cannot borrow
    // *self as mutable more than once at a time`) because BOTH the outer call and the argument
    // evaluation needed their own `&mut self` reservation — two-phase borrows only admit a
    // NESTED read, not a nested write, during the outer call's argument evaluation. `cur` and
    // `isNameStart` never write a field, so they must render `&self`; only `advance` (which
    // does write `pos`) may render `&mut self`. Mirrors `uniml/xml`'s real
    // `Parser.readName()`/`isNameStart(cur())` shape.
    val src =
      """```scalascript
        |private final class Scanner(src: String):
        |  private var pos = 0
        |
        |  private def cur(): Long = pos
        |
        |  private def isNameStart(c: Long): Boolean = c > 0
        |
        |  private def advance(): Unit =
        |    pos += 1
        |
        |  def readName(): Boolean =
        |    val ok = isNameStart(cur())
        |    advance()
        |    ok
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("pub fn cur(&self)"), s"non-writing method should render &self:\n$g")
    assert(g.contains("pub fn is_name_start(&self,") || g.contains("pub fn isNameStart(&self,"),
      s"non-writing method should render &self:\n$g")
    assert(g.contains("pub fn advance(&mut self)"), s"field-writing method should render &mut self:\n$g")
    assert(g.contains("pub fn read_name(&mut self)") || g.contains("pub fn readName(&mut self)"),
      s"a method calling a &mut self method should itself render &mut self:\n$g")

  test("`Option[(String, X)]` built via an if/else chain is still recognised as an Option"):
    // `isOptionExpr` had no case for `Term.If` at all — `val digits = if ... then Some(...) else
    // if ... then Some(...) else None` (`uniml/xml`'s `Doc.scala`'s `numericReferenceValue`) never
    // registered as an Option anywhere downstream, so `digits.flatMap { case (value, radix) => … }`
    // took no Option-aware path and the tuple-bound `value`'s String-ness (from the ORIGINAL `->`
    // construction) never reached the closure body at all.
    val src =
      """```scalascript
        |def parseIt(reference: String): Option[Long] =
        |  val digits =
        |    if reference.startsWith("&#x") then Some(reference.substring(3, reference.length - 1) -> 16L)
        |    else None
        |  digits.flatMap { case (value, radix) =>
        |    if value.nonEmpty then Some(radix) else None
        |  }
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("value.is_empty()") || g.contains("!value.is_empty()"),
      s"tuple-bound String param's nonEmpty did not lower:\n$g")
    assert(g.contains(".and_then("), s"Option.flatMap over an if/else-built local did not lower:\n$g")

  test("`startsWith(prefix, toffset)` (two-arg) lowers to a Unicode-safe runtime helper"):
    val src =
      """```scalascript
        |def isXmlDecl(src: String, pos: Long): Boolean = src.startsWith("<?xml", pos)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("crate::runtime::_str_starts_with_at("), s"two-arg startsWith did not lower:\n$g")

  test("a chained `sb.append(a).append(b)` flattens into one statement sequence"):
    val src =
      """```scalascript
        |def build(): String =
        |  val sb = StringBuilder()
        |  sb.append('<').append("tag").append('>')
        |  sb.toString
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("sb.push(") && g.contains("sb.push_str("), s"chained append did not flatten:\n$g")
    assert(!g.contains(").append("), s"a raw .append survived unlowered:\n$g")

  test("a field read on a value typed as a SPECIFIC enum variant lowers via a single-arm match"):
    // `document.root` where `document: Wrap.Doc` (object-namespaced, `uniml/xml`'s own spelling —
    // a case class extending a shared sealed trait, reached via `case Right(document) => …`, never
    // a `match` arm that itself DESTRUCTURES `Doc`'s own fields) — Rust has no unchecked `.field`
    // access on an enum; this needs a match to extract the one field.
    val src =
      """```scalascript
        |object Wrap:
        |  sealed trait Node
        |  case class Doc(root: Long, docType: Option[Long]) extends Node
        |  case class Other(x: Long) extends Node
        |
        |def tryParse(x: Long): Either[Long, Wrap.Doc] = if x > 0 then Right(Wrap.Doc(x, None)) else Left(x)
        |
        |def readRoot(x: Long): Long = tryParse(x) match
        |  case Left(e) => e
        |  case Right(document) => document.root
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("match &") && g.contains("Node::Doc"), s"enum-variant field read did not lower:\n$g")

  test("`.copy(field = value)` on a value typed as a SPECIFIC enum variant rebuilds via match"):
    val src =
      """```scalascript
        |object Wrap:
        |  sealed trait Node
        |  case class Doc(root: Long, docType: Option[Long]) extends Node
        |  case class Other(x: Long) extends Node
        |
        |def tryParse(x: Long): Either[Long, Wrap.Doc] = if x > 0 then Right(Wrap.Doc(x, None)) else Left(x)
        |
        |def withRoot(x: Long, n: Long): Long = tryParse(x) match
        |  case Left(e) => e
        |  case Right(document) => document.copy(root = n).root
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("match &") && g.contains("Node::Doc"), s"enum-variant .copy did not lower:\n$g")
    assert(!g.contains("__copy_"), s"a dangling __copy_ binder leaked into the output:\n$g")

  test("`either.left.map(f)` lowers, transforming Left and passing Right through"):
    val src =
      """```scalascript
        |def tryParse(x: Long): Either[Long, String] = if x > 0 then Right(x.toString) else Left(x)
        |def widen(x: Long): Either[String, String] = tryParse(x).left.map(n => n.toString)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("Either::Left(") && g.contains("Either::Right(v) => Either::Right(v)"),
      s".left.map did not lower:\n$g")

  test("`s.forall(p)` / `s.exists(p)` on a String lower via `.chars()`"):
    val src =
      """```scalascript
        |def isHexDigit(c: Long): Boolean = c >= 48
        |def allHex(s: String): Boolean = s.forall(isHexDigit)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains(".chars().all("), s"String.forall did not lower:\n$g")

  test("`opt.forall(p)` lowers to `.map_or(true, p)`"):
    val src =
      """```scalascript
        |def isLegal(n: Long): Boolean = n >= 0
        |def parseIt(s: String): Option[Long] = if s.nonEmpty then Some(s.length) else None
        |def check(s: String): Boolean = parseIt(s).forall(isLegal)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains(".map_or(true, "), s"Option.forall did not lower:\n$g")

  test("`s.indexOf(needle, fromIndex)` (two-arg, String or Char needle) lowers"):
    val src =
      """```scalascript
        |def findTag(s: String, from: Long): Long = s.indexOf("?>", from)
        |def findChar(s: String, from: Long): Long = s.indexOf(';', from)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("crate::runtime::_str_index_of_from("), s"two-arg indexOf did not lower:\n$g")

  test("a Map-typed `var` (not just `val`) is tracked, so `.get`/`.contains` lower correctly"):
    // `var bindings = inherited` (`uniml/xml`'s `Doc.scala`'s `validateNamespaces`/
    // `resolveElement`) — `collectLocalMaps`'s walk had a `Defn.Val` case but no `Defn.Var` one.
    val src =
      """```scalascript
        |def useIt(inherited: Map[String, String], key: String): Option[String] =
        |  var bindings = inherited
        |  Some(key).flatMap(bindings.get)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("bindings.get(&__k)"), s"Map var's .get-as-value did not lower:\n$g")

  test("`Integer.parseInt(s, radix)` and `math.max(a, b)` lower"):
    val src =
      """```scalascript
        |def parseHex(s: String): Long = Integer.parseInt(s, 16)
        |def clampLow(n: Long): Long = math.max(1, n)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("i64::from_str_radix("), s"Integer.parseInt did not lower:\n$g")
    assert(g.contains(").max("), s"math.max did not lower:\n$g")

  test("`Nothing` maps to Rust's `!`, so a diverging call unifies with either if/else branch"):
    // `def err(msg: String): Nothing = throw ...; if cond then err(msg) else ()` (`uniml/xml`'s
    // `Doc.scala`'s `Parser`) — `Nothing` had no case in `mapType` at all and fell to the
    // unknown-type-name `i64` default, so `err(...)`'s call-site type was a CONCRETE `i64` instead
    // of coercing to whatever the branch needed — `error[E0308]: if and else have incompatible
    // types` against the `()` sibling branch.
    val src =
      """```scalascript
        |def err(msg: String): Nothing = throw new RuntimeException(msg)
        |def maybeErr(cond: Boolean): Unit = if cond then err("bad") else ()
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("-> !"), s"Nothing did not map to !:\n$g")

  test("a positional ctor destructure (`case Ctor(a, b) =>`) types each field from the ctor"):
    // `case PI(target, data) => data.nonEmpty` (`uniml/xml`'s `Doc.scala`'s `serializeNode`,
    // shape simplified here) — `data`'s type comes from `PI`'s OWN declared field type
    // (`data: String`), never threaded to `ctx.localStrings` before this fix for a BARE
    // (non-`@`-bound) positional destructure.
    val src =
      """```scalascript
        |sealed trait Node
        |case class PI(target: String, data: String) extends Node
        |case class Text(chars: String) extends Node
        |
        |def render(n: Node): String = n match
        |  case PI(target, data) => if data.nonEmpty then data else target
        |  case Text(chars) => chars
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("data.is_empty()") || g.contains("!data.is_empty()"),
      s"positional-destructure field isEmpty/nonEmpty did not lower:\n$g")

  test("two companion objects each declaring their own `val default` don't shadow each other"):
    // `object Limits: val default = Limits()` / `object XmlLimits: val default = XmlLimits()`
    // (`uniml/xml`'s `Doc.scala`) — a SINGLE-owner `_topValOwners` map remembered only the LAST
    // "default" registered, so `Limits.default` (referenced from XmlLimits's own ctor-default fill
    // for its `core` field) matched neither the topval case NOR the def case and fell to the
    // zero-arg-def-call fallback, which appended `()` to a VAL: `Limits.default()`,
    // `error[E0423]: expected value, found struct Limits`. Two fixes needed at once: the topval's
    // own PREAMBLE BINDING is qualified (`XmlLimits_default`) when the bare name is contested, and
    // a topval's init referencing an EARLIER topval (rendered with no preamble mechanism live at
    // all) gets that earlier topval's init text INLINED rather than a name reference.
    val src =
      """```scalascript
        |final case class Limits(maxDepth: Long = 10L)
        |
        |object Limits:
        |  val default: Limits = Limits()
        |
        |final case class XmlLimits(core: Limits = Limits.default, maxSize: Long = 100L)
        |
        |object XmlLimits:
        |  val default: XmlLimits = XmlLimits()
        |
        |def useIt(): XmlLimits = XmlLimits.default
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(!g.contains("Limits.default") && !g.contains("XmlLimits.default"),
      s"a companion topval reference should never keep the Scala dot-qualified spelling:\n$g")
    assert(g.contains("Limits { maxDepth: 10i64 }"),
      s"XmlLimits's own default-fill for `core` should inline Limits's already-known init:\n$g")
    assert(g.contains("XmlLimits_default"),
      s"the contested topval name should get an owner-qualified preamble binding:\n$g")

  test("a local variable bare-shadowing a GLOBAL runtime intrinsic name stays a local reference"):
    // Regression on the `isHexDigit` fix just above: that fix routed a bare `Term.Name` through
    // `ctx.intrinsics` so a SIBLING def (flattened with an owner prefix) resolves when referenced
    // as a value with no call. But `ctx.intrinsics` is SITE-3's per-def sibling map `++`-merged
    // with `intrinsics0`, the GLOBAL runtime registry (`println`, `element`, …), unconditionally
    // for every def — so `case element @ Shape.Box(w) => element.area` (a pattern-bind named
    // "element", colliding with `std/ui`'s builtin `element(...)` builder) rewrote the LOCAL
    // variable into `crate::runtime::ui::_ui_element`, the function itself:
    // `error[E0609]: no field area on type fn(...) -> View {_ui_element}`. Fixed by gating the
    // fallback on `ctx.userDefs.contains(target)` — true only for a def THIS MODULE generates
    // (a genuine sibling call), never for a `crate::runtime::…` runtime intrinsic's own target.
    val src =
      """```scalascript
        |case class Box(w: Long)
        |
        |def describe(b: Box): Long =
        |  b match
        |    case element @ Box(w) => element.w
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(!g.contains("_ui_element"), s"a local `element` bind must not resolve to the runtime intrinsic:\n$g")
    assert(g.contains("element).w"), s"the local bind should still read its own field:\n$g")

  test("an `object X extends Trait` used bare as a value gets a unit struct + forwarding impl"):
    // `object PureMarkupCodec extends MarkupCodec: ...` (`uniml/xml`'s `Doc.scala`) referenced bare
    // AS A VALUE (`case "pure" => PureMarkupCodec`, expected type `MarkupCodec` = `Rc<dyn
    // MarkupCodec>`) — this backend flattens EVERY object's own members to free functions with no
    // struct at all, so there was nothing to construct: `error[E0425]: cannot find value
    // PureMarkupCodec in this scope`. `renderValueObjectImpl` gives such an object a zero-field
    // unit struct + a THIN FORWARDING `impl Trait for X` (calling the already-flattened free
    // functions, since an object's own methods never touch instance state); the bare reference
    // itself stays UNWRAPPED (no `Rc::new` at the reference site) because `named`'s own return type
    // IS the dyn trait, so `renderDef`'s existing whole-body wrap already applies `Rc::new` once —
    // self-wrapping too gave `Rc<Rc<dyn MarkupCodec>>`, caught by an isolated `cargo build` before
    // it reached the real corpus.
    val src =
      """```scalascript
        |trait Codec:
        |  def id: String
        |  def encode(x: Long): String
        |
        |object PureCodec extends Codec:
        |  def id: String = "pure"
        |  def encode(x: Long): String = x.toString
        |
        |object Codec:
        |  def named(name: String): Codec = name match
        |    case "pure" => PureCodec
        |    case other  => throw new NoSuchElementException(s"no codec: $other")
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("pub struct PureCodec;"), s"value object should get a unit struct:\n$g")
    assert(g.contains("impl Codec for PureCodec"), s"value object should get a forwarding impl:\n$g")
    assert(g.contains("\"pure\" => PureCodec,"),
      s"the bare reference must stay UNWRAPPED, relying on the enclosing def's own Rc::new:\n$g")
    assert(!g.contains("Rc::new(PureCodec)"), s"self-wrapping would double-wrap under named's own Rc::new:\n$g")

  test("a value object's trait member satisfied by a `val`, or by neither, is not force-forwarded"):
    // Regression on the FIRST cut of `renderValueObjectImpl`, which blindly forwarded EVERY trait
    // member to `${owner}_${member}()` — correct only when the object overrides the member as a
    // genuine `def` (SITE 1 flattens that to a free function). `uniml/xml`'s real
    // `PureMarkupCodec extends MarkupCodec` breaks that assumption two ways at once: `val id =
    // "pure"` satisfies an ABSTRACT member with a VAL, not a def (no `PureMarkupCodec_id` free
    // function was ever generated — `error[E0425]: cannot find function id`), and `Literal`/
    // `XmlDialect extends DialectAdapter` (a SEPARATE trait) don't override `aliases` at all,
    // relying on the trait's own DEFAULT body (same error, for a member the object never declared).
    // Fixed with three-way per-member dispatch: forward a real `def` override; INLINE a `val`
    // override's already-known init text (a topval, immutable, so re-evaluating it per call is
    // exactly Scala's own single evaluation); OMIT a member the object does not override at all
    // when the trait supplies its own default (Rust auto-inherits it — no override needed).
    val src =
      """```scalascript
        |trait Codec:
        |  def id: String
        |  def describe(): String = "codec " + id
        |
        |object PureCodec extends Codec:
        |  val id = "pure"
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("impl Codec for PureCodec"), s"value object should still get a forwarding impl:\n$g")
    assert(g.contains("fn id(&self) -> String { \"pure\".to_string() }"),
      s"a val-satisfied abstract member should inline its init, not forward to a nonexistent function:\n$g")
    val implBlock = g.substring(g.indexOf("impl Codec for PureCodec"))
    assert(!implBlock.contains("fn describe"),
      s"a member the object never overrides, with a trait default, must be OMITTED from the impl (Rust inherits it from the trait declaration):\n$g")

  test("global mutable companion-object state (`private var` in an `object`) uses a thread_local"):
    // `object MarkupCodec: private var _default: MarkupCodec = PureMarkupCodec; def default =
    // _default; def setDefault(codec) = _default = codec` (`uniml/xml`'s `Doc.scala`) — GLOBAL
    // mutable state with no owning instance at all, unlike `Parser`'s per-instance `private var`s
    // (`renderMutableClass`). No `self` exists to hang a field off, so this needs Rust's own answer
    // for shared mutable state with no owner: `thread_local!` + `RefCell` (`Rc<dyn Trait>` is not
    // `Sync`, so a plain `static` + `Mutex` could not hold it at all). A bare READ inside the SAME
    // object (`_default`) becomes `.with(|c| c.borrow().clone())`; a bare WRITE (`_default = codec`)
    // becomes `.with(|c| *c.borrow_mut() = …)`. The read is ALSO the regression case for a SEPARATE
    // bug this feature exposed: `default`'s OWN return type is the dyn trait, so `renderDef`'s
    // existing whole-body "wrap in Rc::new if returning a dyn trait" fired a SECOND Rc::new on top
    // of the thread_local's own already-`Rc<dyn Trait>`-typed read.
    val src =
      """```scalascript
        |trait Codec:
        |  def id: String
        |
        |object PureCodec extends Codec:
        |  def id: String = "pure"
        |
        |object Codec:
        |  private var _default: Codec = PureCodec
        |  def default: Codec = _default
        |  def setDefault(codec: Codec): Unit = _default = codec
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("thread_local!"), s"a companion mutable var should render as a thread_local:\n$g")
    assert(g.contains("RefCell<std::rc::Rc<dyn Codec>>"),
      s"the thread_local should hold the field's own dyn-trait type:\n$g")
    assert(g.contains(".with(|c| c.borrow().clone())"), s"a bare read should borrow+clone:\n$g")
    assert(g.contains(".with(|c| *c.borrow_mut() = "), s"a bare write should borrow_mut+assign:\n$g")
    assert(!g.contains("Rc::new(CODEC"),
      s"the read must NOT be double-wrapped by the def's own dyn-trait return-wrap:\n$g")

  test("a topval referenced inside a LIFTED LOCAL fn item is inlined, not captured"):
    // `object XmlDialect: val id = "xml.1.0"` referenced (bare AND qualified) from inside a local
    // `def` that `liftLocalDefs` lifts to a real Rust `fn` item (`eofDiagnostic`, `uniml/xml`'s
    // `Doc.scala`'s `scan`) — a Rust `fn` item, unlike a closure, cannot capture ANYTHING from its
    // enclosing scope, including the `let id = "xml.1.0".to_string();` preamble line the OUTER
    // function gets. `liftLocalDefs`'s own capture-analysis `pool` never tracked topvals at all (only
    // locals/params/self-fields), so this reached rustc as `error[E0434]: can't capture dynamic
    // environment in a fn item`. Fixed by INLINING the topval's own init text wherever `Ctx.
    // inLiftedFn` is set, instead of naming the (here, nonexistent) outer binding.
    val src =
      """```scalascript
        |object Dialect:
        |  val id: String = "xml"
        |
        |def useIt(x: Long): String =
        |  def helper(n: Long): String =
        |    Dialect.id + n.toString
        |  helper(x)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("fn helper("), s"the local def should still be lifted to a Rust fn item:\n$g")
    val fnBlock = g.substring(g.indexOf("fn helper("))
    assert(fnBlock.contains("\"xml\".to_string()"),
      s"the lifted fn's body should INLINE the topval's init text:\n$g")
    assert(!fnBlock.take(fnBlock.indexOf('}')).contains(" id"),
      s"the lifted fn's body must not reference an outer `id` binding it cannot capture:\n$g")

  test("`String.valueOf(c)` on a Char lowers to `.to_string()`"):
    // `String.valueOf(code.toChar)` (`uniml/xml`'s `Doc.scala`'s `numericReferenceValue`) — Java's
    // static factory reached through Scala's implicit companion. `String` is a Rust TYPE name, not
    // a value, so the generic Apply path rendered it as a field access on a type:
    // `error[E0423]: expected value, found struct String`. `.toChar` itself renders as `i64` (this
    // lane's SscChar convention, see its own test), so THIS call site is where the code point widens
    // back to a real displayable `char` via `char::from_u32`.
    val src =
      """```scalascript
        |def toStr(code: Long): String = String.valueOf(code.toChar)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("char::from_u32") && g.contains(".to_string()"),
      s"String.valueOf(c.toChar) should widen the code point back to a char, then to_string():\n$g")
    assert(!g.contains("String.valueOf"), s"the Scala spelling must not survive verbatim:\n$g")

  test("`.toChar` renders as `i64` (this lane's Char convention), not a real Rust `char`"):
    // `private def cur: Char = if pos < src.length then src.charAt(pos) else 0.toChar`
    // (`uniml/xml`'s `Doc.scala`'s `Parser`) — `.charAt` yields a genuine `SscChar` newtype (`i64`);
    // `.toChar` used to render `char::from_u32(…).unwrap_or(…)`, a REAL Rust `char` — two different
    // types as sibling `if`/`else` branches of a function declared to return `i64` (`Char` maps to
    // `i64` uniformly on this lane). Both errors this test pins: `.toChar` now matches `i64`
    // directly, and the `.charAt` branch gets its OWN `.0` unwrap to match it (the general
    // "exactly one branch is a bare `.charAt` call" rule in the plain `Term.If` renderer).
    val src =
      """```scalascript
        |class Scanner(src: String):
        |  private var pos = 0
        |  def cur: Long = if pos < src.length then src.charAt(pos) else 0.toChar
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("-> i64"), s"cur should return i64:\n$g")
    assert(!g.contains("char::from_u32"), s".toChar should no longer produce a real char:\n$g")
    assert(g.contains(").0"), s"the .charAt branch should get its own .0 unwrap to unify with .toChar's i64:\n$g")

  test("a self-method call coerces an SscChar argument to i64, same as an ordinary call"):
    // `self.isXmlSpace(self.cur())` (`uniml/xml`'s `Doc.scala`'s `Parser`) — `cur`'s OWN declared
    // Scala return type is `Char` (this lane's SscChar/`i64` convention), and `isXmlSpace(c: Long)`
    // declares a plain `i64` parameter — Scala's own `Char` unifies with nothing extra, but the
    // self-method-call dispatch (added only to inject the `self.` receiver) bypassed the ordinary
    // call path's `_paramTypes`-driven SscChar coercion entirely, so no `.0` unwrap ever reached
    // this call: `error[E0308]: expected i64, found SscChar`.
    val src =
      """```scalascript
        |class Scanner(src: String):
        |  private var pos = 0
        |  def cur: Long = if pos < src.length then src.charAt(pos) else 0L
        |  def isSpace(c: Long): Boolean = c == 32L
        |  def atSpace(): Boolean = isSpace(cur)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("self.isSpace(") && g.contains(").0"),
      s"a self-method call with an SscChar-yielding argument should unwrap it with .0:\n$g")

  test("`throw CustomError(msg, extra)` on a multi-field exception panics with just its `message` field"):
    // `throw ParseError(msg, line, col)` (`uniml/xml`'s `Doc.scala`'s `Parser.err`) — a user-declared
    // MULTI-FIELD exception (`case class ParseError(message: String, line: Int, column: Int)
    // extends RuntimeException(...)`); the single-arg ctor case never matched it and it fell to a
    // verbatim `panic!("{}", ParseError { ... })`, `error[E0277]: ParseError doesn't implement
    // Display` (no generated struct derives one). The `message` field is exactly what `.getMessage`
    // already reads elsewhere for the identical reason.
    val src =
      """```scalascript
        |case class CustomError(message: String, code: Long) extends RuntimeException(message)
        |
        |def fail(msg: String, code: Long): Unit = throw CustomError(msg, code)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("""panic!("{}", msg)"""), s"the throw should panic with just the message field:\n$g")

  test("catching into a multi-field exception TYPE reconstructs the struct, not a bare String"):
    // `try ... catch case e: ParseError => Left(e)` (`uniml/xml`'s `Doc.scala`'s `parse`) — this
    // target's catch mechanism only ever recovers a `String` message from a caught panic; a TYPED
    // bind (`case e: ParseError`) used to discard the type entirely and bind `e` as that bare
    // String, so `Left(e)` (needing a `ParseError`) got `error[E0308]: expected ParseError, found
    // String`. Reconstructs the struct instead: `message` from the caught string, every OTHER field
    // (no way to recover it from a caught panic) from a type-appropriate zero literal.
    val src =
      """```scalascript
        |case class MyError(message: String, line: Long, column: Long) extends RuntimeException(message)
        |
        |def safeRun(f: () => Long): Either[MyError, Long] =
        |  try Right(f())
        |  catch case e: MyError => Left(e)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("MyError { message: __msg, line: 0i64, column: 0i64 }") ||
           g.contains("MyError { message: __msg, column: 0i64, line: 0i64 }"),
      s"the catch should reconstruct the full struct with a zero placeholder for non-message fields:\n$g")

  test("`opt.fold(ifEmpty)(f)` lowers to `.map_or`, cloning a multi-use default"):
    // `prefix.fold(localName)(p => s"$p:$localName")` (`uniml/xml`'s `Doc.scala`'s `QName.toXml`)
    // — Scala's CURRIED `Option.fold`, which Rust's `Option` has no equivalent method for at all
    // (`error[E0599]`). `.map_or(ifEmpty, f)` is the direct equivalent; `localName` appearing as
    // BOTH the default value and again inside `f`'s own closure needed a `.clone()` on the first
    // use — a genuine `error[E0382]: use of moved value` without it.
    val src =
      """```scalascript
        |def describe(prefix: Option[String], localName: String): String =
        |  prefix.fold(localName)(p => s"$p:$localName")
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains(".map_or("), s"Option.fold should lower to .map_or:\n$g")
    assert(g.contains("localName.clone()"), s"the multi-use default should be cloned:\n$g")

  test("a struct-typed (non-variant) parameter needs no let-else destructure"):
    // `parentName: Markup.QName` (`uniml/xml`'s `Doc.scala`'s `readContent`) — `QName` is a plain
    // STRUCT, not an enum variant, so `parentName.localName` already works as ordinary Rust field
    // access. The destructure-preamble mechanism (built for a TRUE variant parameter, `instruction:
    // VmInstruction.Reframe`, where an unchecked `.field` read on the whole enum is illegal) matched
    // ANY qualified type with non-empty fields, missing the `!isStruct` check — `let QName::QName {
    // ... } = ...`, `error[E0223]: ambiguous associated type` (not even valid Rust for a struct).
    val src =
      """```scalascript
        |object Markup:
        |  case class QName(prefix: Option[String], localName: String)
        |
        |def describe(parentName: Markup.QName): String = parentName.localName
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(!g.contains("QName::QName"), s"a struct parameter must not get an enum-variant destructure:\n$g")
    assert(g.contains("parentName.localName") || g.contains("parentName.local_name"),
      s"the struct field should be read via ordinary field access:\n$g")

  test("`.copy` on a `.map` closure param resolves the element type through a `.filter` chain"):
    // `element.attrs.filter(pred).map { attribute => attribute.copy(...) }` (`uniml/xml`'s
    // `Doc.scala`'s `resolveElement`) — the receiver is a CHAIN (a struct field access piped
    // through `.filter`), not a bare name, so the closure param `attribute` reached its body with
    // no known type at all: `error[E0599]: no method named copy found for struct Attr` (blaming the
    // struct for a gap in element-type propagation, not the struct itself).
    val src =
      """```scalascript
        |case class Attr(name: String, value: String)
        |case class Elem(attrs: List[Attr])
        |
        |def clean(e: Elem): List[Attr] =
        |  e.attrs.filter(a => a.name != "").map { attribute => attribute.copy(value = attribute.value.trim) }
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(!g.contains("attribute.copy("), s"a resolved .copy() call should lower to a struct-update literal, not stay verbatim:\n$g")
    assert(g.contains("Attr {"), s".copy should lower to a struct-update literal for the resolved Attr type:\n$g")

  test("`.getMessage` on a closure param typed via a QUALIFIED `Either`-returning call resolves"):
    // `PureMarkupCodec.parse(source).left.map(error => error.getMessage)` (`uniml/xml`'s
    // `Doc.scala`'s `parseMarkup`) — `eitherSideCtorName`'s ORIGINAL case only matched a BARE call
    // (`Term.Name(fn)`); `PureMarkupCodec.parse(...)` is QUALIFIED (`Term.Select(_, Term.Name(fn))`)
    // and never matched at all, so `error`'s type was never recovered and `.getMessage` on it fell
    // through unresolved: `error[E0609]: no field getMessage on type ParseError`. Reads the
    // COLLISION-SAFE `_ownedDefBodies` (keyed by `(owner, member)`), not the bare-name `_defBodies`
    // — this corpus has FOUR distinct `def parse(...)`, and the bare-name table only ever holds one.
    val src =
      """```scalascript
        |case class MyError(message: String)
        |
        |object Codec:
        |  def parse(s: String): Either[MyError, Long] = Right(s.length)
        |
        |def useIt(s: String): Either[String, Long] =
        |  Codec.parse(s).left.map(error => error.getMessage)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains(".message"), s"error.getMessage should resolve to .message via the qualified call's Either type:\n$g")
    assert(!g.contains(".getMessage"), s"the Scala spelling must not survive verbatim:\n$g")

  test("`sb.append(cur)` still pushes a char while `self.isNameStart(self.cur())` needs no `.0`"):
    // Regression check on splitting `yieldsSscChar` in two: `sb.append(cur)` (append a bare
    // self-method's Char-typed result) still needs `char::from_u32` (the BROADER
    // `isConceptuallyChar`), while `self.isNameStart(self.cur())` (an ordinary i64 argument, since
    // `cur`'s own if/else already unifies to plain i64) must NOT get a bogus `.0` unwrap — the
    // FIRST fix (widening `yieldsSscChar` itself) briefly added that bogus `.0`:
    // `error[E0610]: i64 is a primitive type and therefore doesn't have fields`.
    val src =
      """```scalascript
        |class Scanner(src: String):
        |  private var pos = 0
        |  def cur: Char = if pos < src.length then src.charAt(pos) else 0.toChar
        |  def isNameStart(c: Long): Boolean = c > 0
        |  def readName(): Boolean =
        |    val sb = StringBuilder()
        |    sb.append(cur)
        |    isNameStart(cur)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("char::from_u32"), s"sb.append(cur) should still push a char:\n$g")
    assert(!g.contains("self.isNameStart(") || !g.contains(").0)"),
      s"an ordinary i64 argument must not get a bogus .0 unwrap:\n$g")

  test("a boxed recursive enum-variant field derefs to the plain type it was declared as"):
    // `doc.root: Elem` (`uniml/xml`'s `Doc.scala`'s `Doc`) — `Elem` is a SIBLING variant of the same
    // enum `Doc` belongs to, so the struct boxes the field for enum sizing (`ec.boxedFields`).
    // Reading it via the enum-variant field-read match cloned the `Box`, not the value inside it:
    // `error[E0308]: expected Node, found Box<Node>`.
    val src =
      """```scalascript
        |sealed trait Node
        |case class Doc(root: Elem) extends Node
        |case class Elem(name: String, children: List[Node] = Nil) extends Node
        |
        |def describe(node: Node): String = node match
        |  case d: Doc => d.root.name
        |  case e: Elem => e.name
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("*root"), s"a boxed recursive field read should deref the box:\n$g")

  test("`s * n` (String repeat) lowers to `.repeat(n as usize)`"):
    // `opts.indent * depth` (`uniml/xml`'s `Doc.scala`'s `serializeNode`) — Scala's `StringOps.*`
    // repeats the string; reached rustc as literal multiplication, `error[E0369]: cannot multiply
    // String by i64` (`String` has no `Mul` at all).
    val src =
      """```scalascript
        |case class Opts(indent: String)
        |def pad(opts: Opts, depth: Long): String = opts.indent * depth
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains(".repeat("), s"String * Int should lower to .repeat(n as usize):\n$g")

  test("a StringBuilder PARAMETER (not just a local) is emitted `mut`"):
    // `def serializeNode(node: Node, sb: StringBuilder, ...)`, mutated via recursive calls
    // (`uniml/xml`'s `Doc.scala`) — `renderLetBinding`'s own `let mut` only ever covered a LOCAL
    // StringBuilder; a PARAMETER never got `mut` at all: `error[E0596]: cannot borrow sb as
    // mutable, as it is not declared as mutable`.
    val src =
      """```scalascript
        |def write(sb: StringBuilder, s: String): Unit = sb.append(s)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("mut sb: String"), s"a StringBuilder parameter should be emitted mut:\n$g")

  test("a local bound via tuple-destructure from a collection-of-tuples method call knows its ctor"):
    // `val (element, inherited) = stack.remove(stack.size - 1)` where `stack: ArrayBuffer[(Elem,
    // Map[...])]` was built from `ArrayBuffer((root, Map(...)))` (`uniml/xml`'s `Doc.scala`'s
    // `validateNamespaces`) — `element`'s own ctor name (`Elem`, threaded from the parameter `root`
    // through the tuple literal) was invisible everywhere: no def parameter, no field, just a local
    // bound from a collection method call. `element.name` (an enum-variant field, needing the
    // enum-field-read match) fell through to plain field access: `error[E0609]: no field name on
    // type Node`.
    val src =
      """```scalascript
        |sealed trait Node
        |case class Elem(name: String, children: List[Node] = Nil) extends Node
        |
        |import scala.collection.mutable.ArrayBuffer
        |
        |def walk(root: Elem): String =
        |  val stack = ArrayBuffer((root, 0))
        |  val (element, depth) = stack.remove(stack.size - 1)
        |  element.name
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("Node::Elem"), s"element.name should resolve via an enum-variant field-read match:\n$g")

  test("`xs.reverseIterator.foreach(f)` is not shadowed by the ungated generic `.foreach` arm"):
    // `element.children.reverseIterator.foreach(child => …)` (`uniml/xml`'s `Doc.scala`'s
    // `validateNamespaces`) — the generic `xs.foreach(f)` arm has NO receiver-type guard at all (by
    // design, so the method name stays visible before the receiver's type is known) and is
    // positioned textually BEFORE the dedicated `.reverseIterator.foreach` case, so it ALWAYS won
    // first: `qual` rendered as a bare `Select(inner, "reverseIterator")`, which nothing else knows
    // how to render — a LATENT bug, invisible until `isKnownVecReceiver` learned to recognize the
    // receiver at all (before that, the guard on the REFUSAL check for an unhandled no-paren member
    // was ALSO false, so the wrong rendering passed silently instead of being caught).
    val src =
      """```scalascript
        |def walk(xs: List[Long]): Long =
        |  var total = 0L
        |  xs.reverseIterator.foreach(x => total = total + x)
        |  total
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains(".rev()"), s"xs.reverseIterator.foreach should lower via the dedicated .rev() case:\n$g")

  test("a boxed field OVERRIDE in an enum-variant `.copy` gets the same `Box::new` wrap"):
    // `document.copy(root = resolveElement(document.root, …))` (`uniml/xml`'s `Doc.scala`'s
    // `parse`) — `root` is a boxed recursive field (`ec.boxedFields`); the non-overridden branch
    // already re-clones the ORIGINAL `Box<Node>` bare, but an override value is a plain `Node`
    // (whatever the caller's own expression produced) and needs the SAME `Box::new(…)` wrap the
    // ordinary constructor path already applies: `error[E0308]: expected Box<Node>, found Node`
    // without it.
    val src =
      """```scalascript
        |object Markup:
        |  sealed trait Node
        |  case class Doc(root: Elem) extends Node
        |  case class Elem(name: String, children: List[Node] = Nil) extends Node
        |
        |def resolve(e: Markup.Elem): Markup.Elem = e
        |
        |def fix(doc: Markup.Doc): Markup.Doc = doc.copy(root = resolve(doc.root))
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("root: Box::new("), s"an overridden boxed field should get Box::new(...):\n$g")

  test("a default arg is filled for a QUALIFIED call too, not just a bare one"):
    // `PureMarkupCodec.parse(source)` (`uniml/xml`'s `Doc.scala`'s `parseMarkup`) — `parse`'s own
    // `dialect: Dialect = Dialect.Xml1_0` default was never filled for a QUALIFIED call at all (the
    // existing fill logic only ever matched a bare `Term.Name`): `error[E0061]: this function takes
    // 2 arguments but 1 argument was supplied`. Reads the collision-safe `_ownedDefBodies` (this
    // corpus has four `def parse`), not a bare-name table.
    val src =
      """```scalascript
        |case class Dialect(name: String)
        |object Dialect:
        |  val Default: Dialect = Dialect("default")
        |
        |object Codec:
        |  def parse(src: String, dialect: Dialect = Dialect.Default): String = src
        |
        |def useIt(src: String): String = Codec.parse(src)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("parse(src, ") || g.contains("parse(src,"),
      s"the qualified call should get its default argument filled:\n$g")

  test("`opt.orElse(other)` renames to `.or_else(|| other)`"):
    // `name.prefix.flatMap(…).orElse(bindings.get(""))` (`uniml/xml`'s `Doc.scala`'s
    // `resolveElement`) — `Option::orElse` is not Rust's spelling at all: `error[E0599]: no method
    // named orElse found`.
    val src =
      """```scalascript
        |def pick(a: Option[String], b: Option[String]): Option[String] = a.orElse(b)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains(".or_else(|| "), s"Option.orElse should rename to .or_else(|| ...):\n$g")

  test("`s.count(p)` on a String lowers via `.chars().filter(p).count()`"):
    // `lexeme.count(|__p0| ...)` (`uniml/xml`'s `Doc.scala`) — Rust's `Iterator` has no
    // `.count(predicate)`, only `.count()`; `Iterator::filter`'s OWN signature takes `&Item`
    // (unlike `.all`/`.any`), so the predicate's own `__ch` needs an EXTRA deref its
    // `.forall`/`.exists` siblings do not.
    val src =
      """```scalascript
        |def countColons(s: String): Long = s.count(c => c == ':')
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains(".filter(") && g.contains(".count()"), s"String.count(p) should lower via .chars().filter(p).count():\n$g")
    assert(g.contains("(*__ch)") || g.contains("*__ch"), s"the filter closure's own &char param needs a deref:\n$g")

  test("a struct-field STRING LITERAL pattern bubbles an equality guard into the arm"):
    // `case QName(None, "xmlns", _) =>` (`uniml/xml`'s `Doc.scala`'s `namespaceDeclaration`) — a
    // string LITERAL matched against a struct field whose Rust type is an OWNED `String`; only
    // `&str`/`str` support a literal pattern at all: `error[E0308]: expected String, found &str`.
    val src =
      """```scalascript
        |object Markup:
        |  case class QName(prefix: Option[String], localName: String, namespace: Option[String])
        |
        |def isXmlnsDecl(q: Markup.QName): Boolean = q match
        |  case Markup.QName(None, "xmlns", _) => true
        |  case _ => false
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(!g.contains("localName: \"xmlns\""), s"the literal must not stay a struct-field literal pattern:\n$g")
    assert(g.contains("== \"xmlns\""), s"the literal should become an equality guard on the arm:\n$g")

  test("`.map { case x: Variant => x }` (a PartialFunction dispatcher) applies the SAME byRefMut enrichment `renderMatch` gives a standalone match"):
    // `element.children.collect { case child: Markup.Element => child }` (`uniml/xml`'s
    // `Doc.scala`'s `validateNamespaces`) — this shape reaches a SEPARATE, simpler renderer (for a
    // PartialFunction passed directly to `.map`/`.filter`/`.collect`) that never applied
    // `renderMatch`'s own per-arm enrichment (byRefMut, paramTypes, …) at all — a REF-BOUND typed
    // match-arm binder used at a by-value position (returned bare here) needs it the same way a
    // standalone `match` statement's arm does.
    val src =
      """```scalascript
        |object Markup:
        |  sealed trait Node
        |  case class Elem(name: String, children: List[Node] = Nil) extends Node
        |  case class Text(chars: String) extends Node
        |
        |def onlyElems(xs: List[Markup.Node]): List[Markup.Elem] =
        |  xs.collect { case e: Markup.Elem => e }
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("ref e @"), s"the typed bind should still render as a ref-bound pattern:\n$g")

  test("a sibling lifted local def's OWN `val quote = s.charAt(i)` does not pollute another sibling's unrelated `var quote: Char`"):
    // `uniml/xml`'s `Doc.scala`: `scanDoctype`'s own `var quote: Char = ' '` (a plain i64, never
    // `.charAt`) collided with a SIBLING scanner's `val quote = input.charAt(index)` — both were
    // walked from their shared enclosing def's body by the same flat, non-scoped
    // `collectLocalSscChars` `Set[String]`, so `quote` landed in `localSscChars` for BOTH,
    // suppressing the `.0` coercion `quote = char` needs (`lhsIsSscChar` read true for the WRONG
    // reason): `error[E0308]: expected i64, found SscChar`. Fixed by not descending into a nested
    // local def's OWN body when collecting ITS sibling's SscChar-bound names.
    val src =
      """```scalascript
        |def scan(input: String): Char =
        |  def readAttrQuote(): Char =
        |    val quote = input.charAt(0)
        |    quote
        |
        |  def scanDoctype(): Char =
        |    var quote: Char = ' '
        |    val char = input.charAt(1)
        |    quote = char
        |    quote
        |
        |  readAttrQuote()
        |  scanDoctype()
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("quote = (char).0"), s"scanDoctype's own `quote` must still get the `.0` unwrap:\n$g")

  test("`.collect { case p if guard(outer) => … }` does not `move` a name the def reads again afterward"):
    // `Xml.validate` (`uniml/xml`'s `Doc.scala`): `document.docType.toVector.collect { case
    // docType if docType.name != document.root.name.toXml => … }` then `validateNamespaces(
    // document.root)` right after — a `move |__c| …` closure takes OWNERSHIP of `document` even
    // though the guard only ever borrows it, so the later read found it already moved:
    // `error[E0382]: borrow of moved value: document`. Dropping `move` (this closure is consumed
    // synchronously by `.filter_map`, never stored) lets it borrow instead.
    val src =
      """```scalascript
        |case class Item(name: String)
        |case class Doc(tag: String, items: List[Item])
        |
        |def validate(doc: Doc): List[Item] = doc.items
        |
        |def flagged(doc: Doc): List[Item] =
        |  val bad = doc.items.collect { case it if it.name != doc.tag => it }
        |  bad ++ validate(doc)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(!g.contains("move |__c|"), s"a synchronously-consumed filter_map closure must not `move`:\n$g")

  test("`.map { case p if guard(outer) => … }` (bare PartialFunction) does not `move` either"):
    // The general PartialFunction-in-`.map`/`.filter`/… renderer (a few hundred lines above the
    // `.collect`-specific one) has the identical `move |__pf| …` shape and the identical
    // capture-then-reuse-after-move exposure.
    val src =
      """```scalascript
        |case class Item(name: String)
        |case class Doc(tag: String, items: List[Item])
        |
        |def validate(doc: Doc): List[Item] = doc.items
        |
        |def relabelled(doc: Doc): List[Item] =
        |  val out = doc.items.map {
        |    case it if it.name == doc.tag => it
        |    case it => it
        |  }
        |  out ++ validate(doc)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(!g.contains("move |__pf|"), s"a synchronously-consumed map closure must not `move`:\n$g")

  test("an implicit-receiver self-method call clones a multi-use argument"):
    // `readContent(name)` inside another method of the SAME mutable class (`uniml/xml`'s
    // `Doc.scala`'s `Parser`: `readQName()` then `readContent(name)` then `Node::Element { name:
    // name.clone(), … }`) renders as `self.readContent(name)` via a WHOLE SEPARATE rendering path
    // (it exists only to prepend `self.` and fill defaults) that never called `cloneIfMoved` on
    // its own arguments: `error[E0382]: borrow of moved value: name`, `name` read again
    // afterward. This lane needs a genuinely mutable `class` (not `case class`) so the call
    // renders through the self-method path at all.
    val src =
      """```scalascript
        |class Reader(source: String):
        |  private var pos: Int = 0
        |  private def helper(id: String): String = id
        |  def process(id: String): String =
        |    val h = helper(id)
        |    id + h
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("self.helper(id.clone())"), s"the implicit self-method call must clone a multi-use argument:\n$g")

  test("`s.takeWhile(char => …)` on a String does not call a closure literal as an IIFE"):
    // `value.drop(2).takeWhile(char => !isXmlWhitespace(char) && char != '?')` (`uniml/xml`'s
    // `Doc.scala`'s `validatePi`) — the explicit-param lambda argument was rendered generically
    // via `renderTerm` (a `move |char| { … }` closure), then CALLED as an IIFE:
    // `(move |char| { … })(argExpr)` — rustc cannot infer `char`'s type through a closure-literal
    // CALL the way it can through an ordinary function call: `error[E0282]: type annotations
    // needed`. Fixed by rendering the param as a plain `let` binding instead of a closure at all.
    val src =
      """```scalascript
        |def isSpace(c: Long): Boolean = c == 32L
        |
        |def firstWord(value: String): String =
        |  value.takeWhile(char => !isSpace(char))
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(!g.contains("(move |char|"), s"the lambda must not be rendered as a closure literal called via IIFE:\n$g")
    assert(g.contains("let char ="), s"the param should instead be bound via a plain `let`:\n$g")

  test("`Some(child)` clones a `byRefMut`-bound match-arm name used at a by-value position"):
    // `validateNamespaces`-style shape (`uniml/xml`'s `Doc.scala`): a typed with-fields-variant
    // binder (`case child: Markup.Elem => …`) is `byRefMut` (renders bare reads as `(*child)`),
    // but passing it to `Some(...)` is a BY-VALUE position — `(*child)` alone still tries to MOVE
    // out of the borrow: `error[E0507]: cannot move out of *child, which is behind a shared
    // reference`. `cloneIfMoved` must clone at that same rendered text: `(*child).clone()`.
    val src =
      """```scalascript
        |object Markup:
        |  sealed trait Node
        |  case class Elem(name: String, children: List[Node] = Nil) extends Node
        |  case class Text(chars: String) extends Node
        |
        |def firstElem(n: Markup.Node): Option[Markup.Node] = n match
        |  case child: Markup.Elem => Some(child)
        |  case _ => None
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("(*child).clone()"), s"the byRefMut name must be cloned at the by-value position:\n$g")

  test("`s.replace(from, to)` keeps `to` a `&str` even when it's a char literal"):
    // `kind.replace('.', '-')` (`uniml/xml`'s `Doc.scala`) — Rust's `str::replace` requires its
    // SECOND argument to be `&str` specifically (unlike `from`, a genuine `Pattern` where a `char`
    // is fine) — `error[E0308]: expected &str, found char` without the wrap.
    val src =
      """```scalascript
        |def dashIt(kind: String): String = kind.replace('.', '-')
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains(".replace("), s".replace should still lower:\n$g")
    assert(!g.contains("'-')") && !g.contains(", '-'"),
      s"the `to` argument must not stay a bare char literal (needs &str):\n$g")

  test("`.drop(n)`/`.take(n)`/`.takeWhile(p)` on a String use UTF-16-indexed substrings, not `.iter()`"):
    // `value.drop(2).takeWhile(char => …)` (`uniml/xml`'s `Doc.scala`'s `validatePi`) — the
    // Vec-shaped `.drop`/`.take`/`.takeWhile` cases have no receiver-type guard, so a String
    // reached `.into_iter()`/`.iter()`, which it does not have.
    val src =
      """```scalascript
        |def target(value: String): String = value.drop(2).takeWhile(c => c != '?')
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("_str_substring_from"), s".drop on a String should use the UTF-16-indexed substring helper:\n$g")
    assert(g.contains(".chars().take_while("), s".takeWhile on a String should use .chars().take_while(...):\n$g")

  test("`.substring(i)` makes its receiver known as a String for a chained `.forall`"):
    // `inner.substring(1).forall(isEntityNameChar)` (`uniml/xml`'s `Doc.scala`) — `isStringExpr`
    // had no case for `.substring` at all, so `.forall`'s own String-receiver guard never
    // recognized its OWN qualifier: `error[E0599]: no method named forall found for struct String`.
    val src =
      """```scalascript
        |def isAllLetters(inner: String): Boolean = inner.substring(1).forall(c => c != 63L)
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains(".chars().all("), s".forall on a .substring(...) receiver should use .chars().all(...):\n$g")

  test("`s.equalsIgnoreCase(other)` renames to `.eq_ignore_ascii_case`"):
    // `target.equalsIgnoreCase("xml")` (`uniml/xml`'s `Doc.scala`'s `validatePi`) — Rust has no
    // direct equivalent at all: `error[E0599]: no method named equalsIgnoreCase found for String`.
    val src =
      """```scalascript
        |def isXml(target: String): Boolean = target.equalsIgnoreCase("xml")
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains(".eq_ignore_ascii_case("), s".equalsIgnoreCase should rename to .eq_ignore_ascii_case:\n$g")

  test("`.takeWhile`/`.dropWhile` on a String deref the `&char` predicate argument"):
    // Regression check on `.count`'s own fix, applied to the SAME `Iterator::take_while`/
    // `skip_while` shape (`&Item`, not `.forall`/`.exists`'s by-value `Item`) — a bare `(__ch as
    // u32)` on the `&char` these two get would be `error[E0606]: casting &char as u32 is invalid`.
    val src =
      """```scalascript
        |def target(value: String): String = value.takeWhile(c => c != '?')
        |```
        |""".stripMargin
    val g = assets(src)("src/generated/ssc_program.rs")
    assert(g.contains("(*__ch)"), s"the &char predicate argument needs a deref before casting:\n$g")
