package scalascript.codegen.rust

import scalascript.backend.spi.*
import scalascript.parser.Parser
import scalascript.transform.Normalize
import org.scalatest.funsuite.AnyFunSuite

/** Phase R.1 — verbatim `rust` fence-block emit. */
class RustGenRustBlocksTest extends AnyFunSuite:

  private val emptyOpts = BackendOptions(
    baseDir = None, outputDir = None,
    optimizationLevel = 0, emitSourceMaps = false, emitAssertions = false,
    target = None, extra = Map.empty
  )

  private def assets(src: String): Map[String, String] =
    new RustBackend().compile(Normalize(Parser.parse(src)), emptyOpts) match
      case CompileResult.Segmented(segs) =>
        segs.collect { case Segment.Asset(n, b, _) => n -> new String(b, "UTF-8") }.toMap
      case other => fail(s"expected Segmented, got $other")

  test("RustBackend.acceptedSources lists `rust`"):
    val b = new RustBackend()
    assert(b.acceptedSources.contains("rust"),
      s"acceptedSources missing 'rust': ${b.acceptedSources}")

  test("a `rust` fence block is appended verbatim into the generated module"):
    val src =
      """```rust
        |pub fn util() -> i64 { 7 }
        |```
        |""".stripMargin
    val gen = assets(src)("src/generated/ssc_program.rs")
    assert(gen.contains("// ── rust block 1 ──"),
      s"header missing in:\n$gen")
    assert(gen.contains("pub fn util() -> i64 { 7 }"),
      s"rust body missing in:\n$gen")

  test("a mixed module emits the SS defs first, then rust blocks"):
    val src =
      """```scalascript
        |@main def run(): Unit = println("Hello from Rust")
        |```
        |
        |```rust
        |pub fn util() -> i64 { 7 }
        |```
        |""".stripMargin
    val a = assets(src)
    val gen = a("src/generated/ssc_program.rs")
    val ssIdx   = gen.indexOf("pub fn run()")
    val rustIdx = gen.indexOf("pub fn util() -> i64")
    assert(ssIdx >= 0,   s"SS def missing:\n$gen")
    assert(rustIdx >= 0, s"rust block missing:\n$gen")
    assert(ssIdx < rustIdx,
      s"expected SS defs before rust blocks; SS@$ssIdx, rust@$rustIdx\n$gen")
    // Main shim still works.
    assert(a("src/main.rs").contains("generated::ssc_program::run();"))

  test("multiple `rust` blocks are numbered in source order"):
    val src =
      """```rust
        |pub fn one() -> i64 { 1 }
        |```
        |
        |```rust
        |pub fn two() -> i64 { 2 }
        |```
        |""".stripMargin
    val gen = assets(src)("src/generated/ssc_program.rs")
    assert(gen.contains("// ── rust block 1 ──"))
    assert(gen.contains("// ── rust block 2 ──"))
    assert(gen.indexOf("pub fn one") < gen.indexOf("pub fn two"))

  test("a `rust`-only module still produces a usable generated file"):
    val src =
      """```rust
        |pub fn util() -> i64 { 42 }
        |```
        |""".stripMargin
    val gen = assets(src)("src/generated/ssc_program.rs")
    assert(gen.startsWith("//! Generated by RustGen"))
    assert(gen.contains("pub fn util() -> i64 { 42 }"))
