package scalascript.frontend.tui

import scalascript.frontend.*

/** Emits the ratatui Rust crate from a `FrontendModule`.
 *
 *  Slice 0 (scaffold) emits a fixed minimal crate: it renders one empty
 *  frame through ratatui's headless `TestBackend` and prints a readiness
 *  marker, so the crate `cargo build`s and runs without a TTY (the gate).
 *
 *  Slices 1+ replace [[mainRs]]'s body with the real `View → ratatui`
 *  lowering (see the table in `specs/frontend-tui-ratatui.md` §4): the
 *  entry component is resolved (`module.components.find(_.name ==
 *  module.entryPoint)`), its `body(())` lowered via
 *  `NativeElementLowering.lower`, then walked to ratatui widget-building
 *  Rust — mirroring `SwingEmitter.emitBuilder` but emitting Rust source. */
object TuiEmitter:

  /** Cargo manifest for the emitted crate. ratatui ships its own headless
   *  `TestBackend`, so slice 0 needs no extra deps; crossterm (interactive
   *  event loop) is added when slice 2 lands the redraw loop. */
  def cargoToml(manifest: AppManifest): String =
    s"""[package]
       |name = "${crateName(manifest)}"
       |version = "${manifest.version}"
       |edition = "2021"
       |
       |[[bin]]
       |name = "${crateName(manifest)}"
       |path = "src/main.rs"
       |
       |[dependencies]
       |ratatui = "0.29"
       |""".stripMargin

  /** `src/main.rs`. Slice 0: render one empty frame headlessly + a marker. */
  def mainRs(module: FrontendModule, manifest: AppManifest): String =
    // Validate the entry point now so a bad module fails loudly here
    // (slices 1+ lower entry.body(()) — slice 0 only checks it resolves).
    module.components.find(_.name == module.entryPoint).getOrElse(
      throw new IllegalArgumentException(
        s"FrontendModule.entryPoint='${module.entryPoint}' not found among " +
        s"components [${module.components.map(_.name).mkString(", ")}]."
      )
    )
    s"""// Generated by scalascript frontend/tui (ratatui backend) — slice 0 scaffold.
       |// App: ${manifest.displayName}
       |use ratatui::backend::TestBackend;
       |use ratatui::Terminal;
       |
       |fn main() {
       |    // Slice 0: render one empty frame headlessly (no TTY needed).
       |    // The View -> ratatui lowering table lands in slices 1+.
       |    let backend = TestBackend::new(80, 24);
       |    let mut terminal = Terminal::new(backend).expect("terminal init");
       |    terminal.draw(|_frame| { /* empty frame */ }).expect("draw");
       |    println!("ssc-tui: ok");
       |}
       |""".stripMargin

  /** A cargo-safe crate name derived from the bundle id (last segment,
   *  lowercased, non-alphanumerics → '-'), falling back to `ssc-tui-app`. */
  private def crateName(manifest: AppManifest): String =
    val seg = manifest.bundleId.split('.').lastOption.getOrElse("").trim
    val safe = seg.toLowerCase.map(c => if c.isLetterOrDigit then c else '-')
      .dropWhile(!_.isLetter)
    if safe.nonEmpty then safe else "ssc-tui-app"
