package scalascript.frontend.tui

import scalascript.frontend.*

/** Emits the ratatui Rust crate from a `FrontendModule`.
 *
 *  Slice 1 (static layout + text): the entry component's `View` tree is
 *  lowered (`NativeElementLowering.lower`) and walked to a `render_root`
 *  function that builds a ratatui widget tree via `Layout` splits and
 *  `Paragraph` leaves — mirroring `SwingEmitter.emitBuilder` but emitting
 *  Rust source. Rendering is draw-once into a headless `TestBackend`, whose
 *  buffer is printed so the crate runs without a TTY and is snapshot-testable.
 *
 *  Static slice: reactive content (`SignalText`/`Show`/`For`) is read once at
 *  emit time; the live redraw loop + crossterm events arrive in slices 2–3.
 *  Interactive widgets (`Button`/`TextInput`/`Toggle`) render as static text
 *  here; their event wiring lands in slice 3. `Style`/`Theme` mapping is
 *  deferred (slice 4 chrome) — text renders unstyled for now. */
object TuiEmitter:

  /** Cargo manifest. ratatui ships its own headless `TestBackend`, so the
   *  static slice needs no extra deps; crossterm (interactive event loop)
   *  is added when slice 2 lands the redraw loop. */
  def cargoToml(manifest: AppManifest): String =
    s"""[package]
       |name = "${crateName(manifest)}"
       |version = "${manifest.version}"
       |edition = "2021"
       |
       |[[bin]]
       |name = "${crateName(manifest)}"
       |path = "src/main.rs"
       |
       |[dependencies]
       |ratatui = "0.29"
       |""".stripMargin

  /** `src/main.rs` — `render_root` from the lowered `View` tree + a headless
   *  buffer-snapshot harness. */
  def mainRs(module: FrontendModule, manifest: AppManifest): String =
    val entry = module.components.find(_.name == module.entryPoint).getOrElse(
      throw new IllegalArgumentException(
        s"FrontendModule.entryPoint='${module.entryPoint}' not found among " +
        s"components [${module.components.map(_.name).mkString(", ")}]."
      )
    )
    val root = NativeElementLowering.lower(entry.body(()))
    val body = StringBuilder()
    emit(root, "area", body, Iterator.from(0))

    s"""// Generated by scalascript frontend/tui (ratatui backend) — slice 1 (static layout + text).
       |// App: ${manifest.displayName}
       |#![allow(unused_imports, unused_variables)]
       |use ratatui::backend::TestBackend;
       |use ratatui::Terminal;
       |use ratatui::Frame;
       |use ratatui::layout::{Layout, Constraint, Rect};
       |use ratatui::widgets::{Paragraph, Block, Borders};
       |use ratatui::buffer::Buffer;
       |
       |fn render_root(frame: &mut Frame, area: Rect) {
       |${body.toString.stripLineEnd}
       |}
       |
       |fn buffer_to_lines(buf: &Buffer) -> String {
       |    let area = buf.area;
       |    let mut out = String::new();
       |    for y in 0..area.height {
       |        let mut line = String::new();
       |        for x in 0..area.width {
       |            line.push_str(buf[(x, y)].symbol());
       |        }
       |        out.push_str(line.trim_end());
       |        out.push('\\n');
       |    }
       |    out
       |}
       |
       |fn render_to_string(width: u16, height: u16) -> String {
       |    let mut terminal = Terminal::new(TestBackend::new(width, height)).expect("terminal init");
       |    terminal.draw(|f| { let area = f.area(); render_root(f, area); }).expect("draw");
       |    buffer_to_lines(terminal.backend().buffer())
       |}
       |
       |fn main() {
       |    print!("{}", render_to_string(80, 24));
       |}
       |""".stripMargin

  // ── View → ratatui lowering ────────────────────────────────────────────

  private enum Dir { case Vertical, Horizontal }

  /** Emit Rust statements rendering `view` into `area` (a Rust `Rect`
   *  expression). */
  private def emit(view: View[?], area: String, sb: StringBuilder, ids: Iterator[Int]): Unit =
    view match
      case View.Column(children, _, _, _)     => emitStack(children, area, Dir.Vertical, sb, ids)
      case View.Fragment(children)            => emitStack(children, area, Dir.Vertical, sb, ids)
      case View.For(items, render)            => emitStack(items().map(render), area, Dir.Vertical, sb, ids)
      case View.LazyList(items, render, _, _) => emitStack(items().map(render), area, Dir.Vertical, sb, ids)
      case View.Row(children, _, _, _)        => emitStack(children, area, Dir.Horizontal, sb, ids)
      case View.Stack(children, _)            => children.foreach(c => emit(c, area, sb, ids)) // z-overlap
      case View.ScrollView(child, _, _)       => emit(child, area, sb, ids)
      case View.Styled(child, _)              => emit(child, area, sb, ids) // Style mapping deferred
      case View.Show(cond, t, f)              => emit(if cond() then t() else f(), area, sb, ids)
      case View.ShowSignal(cond, t, f)        => emit(if cond() then t else f, area, sb, ids)
      case View.Text(content, _)              => para(rustStr(content()), area, sb)
      case View.TextNode(value)               => para(rustStr(value()), area, sb)
      case View.SignalText(signal, _)         => para(rustStr(String.valueOf(signal())), area, sb)
      case View.Button(label, _, _, _)        => para(rustStr("[" + staticText(label) + "]"), area, sb)
      case View.Toggle(checked, label, _) =>
        val box = if checked() then "[x]" else "[ ]"
        para(rustStr(if label.nonEmpty then s"$box $label" else box), area, sb)
      case View.TextInput(value, placeholder, _, secure, _) =>
        val v = value()
        val shown = if v.isEmpty then placeholder else if secure then "*" * v.length else v
        para(rustStr(shown), area, sb)
      case View.Divider(_, _) =>
        sb ++= s"    frame.render_widget(Block::new().borders(Borders::TOP), $area);\n"
      case View.Spacer(_) => () // empty area
      case _              => () // unhandled cases render nothing (slices 2+ extend)

  /** Split `area` along `dir` and render each child into its sub-rect.
   *  A single child needs no split. Vertical uses measured `Length`
   *  constraints; horizontal splits equally (`Ratio(1, n)`). */
  private def emitStack(children: Seq[View[?]], area: String, dir: Dir, sb: StringBuilder, ids: Iterator[Int]): Unit =
    val kids = children.filterNot(isEmpty)
    if kids.isEmpty then ()
    else if kids.sizeIs == 1 then emit(kids.head, area, sb, ids)
    else
      val chunks = s"chunks${ids.next()}"
      val constraints = dir match
        case Dir.Vertical   => kids.map(k => s"Constraint::Length(${measureHeight(k)})").mkString(", ")
        case Dir.Horizontal => kids.map(_ => s"Constraint::Ratio(1, ${kids.size})").mkString(", ")
      val ctor = dir match { case Dir.Vertical => "vertical"; case Dir.Horizontal => "horizontal" }
      sb ++= s"    let $chunks = Layout::$ctor([$constraints]).split($area);\n"
      kids.zipWithIndex.foreach { case (k, i) => emit(k, s"$chunks[$i]", sb, ids) }

  private def para(rustLiteral: String, area: String, sb: StringBuilder): Unit =
    sb ++= s"    frame.render_widget(Paragraph::new($rustLiteral), $area);\n"

  /** A node that renders nothing — so stacks don't reserve rows for it. */
  private def isEmpty(v: View[?]): Boolean = v match
    case View.Fragment(ch) => ch.forall(isEmpty)
    case _                 => false

  /** Rust rows a vertical child occupies — drives `Constraint::Length`. */
  private def measureHeight(v: View[?]): Int = v match
    case View.Column(ch, _, _, _)           => ch.filterNot(isEmpty).map(measureHeight).sum
    case View.Fragment(ch)                  => ch.filterNot(isEmpty).map(measureHeight).sum
    case View.For(items, render)            => items().map(render).map(measureHeight).sum
    case View.LazyList(items, render, _, _) => items().map(render).map(measureHeight).sum
    case View.Row(ch, _, _, _)              => ch.filterNot(isEmpty).map(measureHeight).maxOption.getOrElse(1)
    case View.Stack(ch, _)                  => ch.map(measureHeight).maxOption.getOrElse(1)
    case View.ScrollView(child, _, _)       => measureHeight(child)
    case View.Styled(child, _)              => measureHeight(child)
    case View.Show(cond, t, f)              => measureHeight(if cond() then t() else f())
    case View.ShowSignal(cond, t, f)        => measureHeight(if cond() then t else f)
    case View.Spacer(size)                  => math.max(0, size.map(_.round.toInt).getOrElse(1))
    case _                                  => 1 // text / divider / interactive leaves = one row

  /** Flatten a `View` to its plain text — for interactive labels. */
  private def staticText(v: View[?]): String = v match
    case View.Text(content, _)       => content()
    case View.TextNode(value)        => value()
    case View.SignalText(signal, _)  => String.valueOf(signal())
    case View.Fragment(ch)           => ch.map(staticText).mkString
    case View.Styled(child, _)       => staticText(child)
    case View.Element(_, _, _, ch)   => ch.map(staticText).mkString
    case View.Button(label, _, _, _) => staticText(label)
    case _                           => ""

  private def rustStr(s: String): String =
    val esc = s.flatMap {
      case '\\' => "\\\\"
      case '"'  => "\\\""
      case '\n' => "\\n"
      case '\r' => "\\r"
      case '\t' => "\\t"
      case ch   => ch.toString
    }
    "\"" + esc + "\""

  /** A cargo-safe crate name derived from the bundle id. */
  private def crateName(manifest: AppManifest): String =
    val seg = manifest.bundleId.split('.').lastOption.getOrElse("").trim
    val safe = seg.toLowerCase.map(c => if c.isLetterOrDigit then c else '-').dropWhile(!_.isLetter)
    if safe.nonEmpty then safe else "ssc-tui-app"
